using System;

namespace Embervale.Combat;

/// <summary>The sound for a blow: which shipped cue, how loud, and at what pitch.</summary>
public readonly record struct CuePlan(string CueId, float PitchScale, float VolumeDb);

/// <summary>How a blow's impact spark looks: its tint, how big it swells, and whether it throws a
/// shock ring as well (the marks of a parry, a guard break and a poise break).</summary>
public readonly record struct SparkPlan(float R, float G, float B, float Scale, bool Ring);

/// <summary>
/// Pure mapping from a hit's flavour to its feedback (Phase 29C, deepened): the sound cue and the
/// impact-spark look for every <see cref="HitOutcome"/>. Godot-free so it's unit-testable; the
/// <see cref="CombatFeedbackDirector"/> consumes it.
///
/// <para><b>Four melee cues, told apart by how they are played.</b> A blow of steel has the swing,
/// hit, crit and block recordings, so the outcomes differ by <em>which</em> cue, at what pitch and
/// loudness: a parry is the block cue rung high and loud, a guard break is the hit cue dropped an
/// octave and driven, a poise break is the crit cue low, a resisted blow is a dull thud. A further
/// melee recording slots into <see cref="Plan"/> without touching a caller.</para>
///
/// <para><b>A spell that lands is not one of them.</b> Spells have recordings of their own, a cast,
/// an impact and a blast per school (<c>Embervale.Audio.SpellAudio</c>, generated by
/// <c>tools/gen_spell_sfx.py</c>), and the audio director plays the impact from the spell's own
/// event. So a landed spell takes no cue from here (<see cref="PlaysHitCue"/>), or the two would
/// stack on every hit. A spell a guard stopped never raises that event and keeps the block cue.</para>
/// </summary>
public static class CombatFx
{
    public const string CritCue = "sfx.combat.crit";
    public const string BlockCue = "sfx.combat.block";
    public const string HitCue = "sfx.combat.hit";
    public const string SwingCue = "sfx.combat.swing";

    /// <summary>The sound-cue id for a resolved hit (crit takes precedence over block over a plain hit).</summary>
    public static string CueId(bool isCrit, bool isBlocked) =>
        isCrit ? CritCue : isBlocked ? BlockCue : HitCue;

    /// <summary>The impact-spark tint (r,g,b 0..1): crit gold, block grey, plain hit white.</summary>
    public static (float R, float G, float B) Tint(bool isCrit, bool isBlocked)
    {
        if (isCrit)
        {
            return (1.0f, 0.82f, 0.35f); // gold
        }

        if (isBlocked)
        {
            return (0.65f, 0.68f, 0.74f); // grey
        }

        return (1.0f, 0.95f, 0.85f); // warm white
    }

    /// <summary>Whether a confirmed blow sounds a melee cue at all. A spell that landed already has
    /// its school's impact from the audio director; one that met a guard, was parried or broke a
    /// guard has no spell impact and keeps the cue for that.</summary>
    public static bool PlaysHitCue(HitOutcome outcome, HitKind kind) =>
        kind != HitKind.Spell ||
        outcome is HitOutcome.Blocked or HitOutcome.Parried or HitOutcome.GuardBroken;

    /// <summary>The sound for an outcome. Heavy kinds sit lower and louder, light ones higher and softer.</summary>
    public static CuePlan Plan(HitOutcome outcome, HitKind kind)
    {
        (string cue, float pitch, float volume) = outcome switch
        {
            HitOutcome.Blocked => (BlockCue, 0.95f, -2f),
            HitOutcome.Parried => (BlockCue, 1.45f, 4f),
            HitOutcome.GuardBroken => (HitCue, 0.6f, 5f),
            HitOutcome.Critical => (CritCue, kind == HitKind.Riposte ? 0.85f : 1f, 2f),
            HitOutcome.PoiseBroken => (CritCue, 0.7f, 0f),
            HitOutcome.Resisted => (BlockCue, 0.75f, -5f),
            _ => (HitCue, 1f, 0f),
        };

        float weight = HitOutcomes.KindWeight(kind);
        pitch *= weight > 1f ? 0.9f : weight < 1f ? 1.12f : 1f;
        volume += weight > 1f ? 2f : weight < 1f ? -3f : 0f;
        return new CuePlan(cue, pitch, volume);
    }

    /// <summary>The spark for an outcome: tinted and sized so the eight things that can happen to a
    /// blow do not all look like a white puff. Damage scales an ordinary hit's swell a little.</summary>
    public static SparkPlan Spark(HitOutcome outcome, float amount)
    {
        float swell = 0.85f + (0.5f * Math.Clamp(amount / HitStop.HeavyDamageRef, 0f, 1f));
        return outcome switch
        {
            HitOutcome.Blocked => new SparkPlan(0.65f, 0.68f, 0.74f, 0.8f, false),
            HitOutcome.Parried => new SparkPlan(1.0f, 0.90f, 0.55f, 1.6f, true),
            HitOutcome.GuardBroken => new SparkPlan(0.82f, 0.35f, 0.30f, 1.8f, true),
            HitOutcome.Critical => new SparkPlan(1.0f, 0.82f, 0.35f, 1.4f * swell, false),
            HitOutcome.PoiseBroken => new SparkPlan(0.95f, 0.62f, 0.30f, 1.5f, true),
            HitOutcome.Resisted => new SparkPlan(0.50f, 0.52f, 0.62f, 0.7f, false),
            _ => new SparkPlan(1.0f, 0.95f, 0.85f, swell, false),
        };
    }
}
