"""Exact .tres writers for quests and dialogues. Deterministic: same model in, same bytes out.

Mirrors the shape of the hand-written and previously generated files (header, ext_resource ids,
sub-resource ids, property order). New fields are written only when set to a non-default value and
are appended after the existing properties. Callers pass already-lowered models (every text field is
a locale key; see locale.lower).
"""

from __future__ import annotations

import re
from typing import List

from .model import Dialogue, Objective, Quest

GENERATED_RE = re.compile(r"^; GENERATED by tools/gen_(campaign|main_story)\.py", re.MULTILINE)
HEADER = "; GENERATED by tools/gen_campaign.py — edit {src}, not this file."
START_VARIANT_SCRIPT = "res://src/Dialogue/DialogueStartVariant.cs"


def q(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def stem(ident: str, prefix: str) -> str:
    """quest.main.the_pass_kept -> MainThePassKept; dialogue.ash_throne -> AshThrone."""
    tail = ident[len(prefix):] if ident.startswith(prefix) else ident
    return "".join(p.capitalize() for p in re.split(r"[._]", tail) if p)


def quest_file(qu: Quest) -> str:
    return (qu.file or stem(qu.id, "quest.")) + ".tres"


def dialogue_file(d: Dialogue) -> str:
    return (d.file or stem(d.id, "dialogue.")) + ".tres"


def is_generated(text: str) -> bool:
    return bool(GENERATED_RE.search(text))


# --- quests --------------------------------------------------------------------------------------

def objective_lines(o: Objective, sub_id: str, ext_id: str = "2_obj") -> List[str]:
    lines = [
        f'[sub_resource type="Resource" id="{sub_id}"]',
        f'script = ExtResource("{ext_id}")',
        f"Type = {o.type}",
        f"TargetId = {q(o.target)}",
        f"RequiredCount = {o.count}",
        f"Description = {q(o.text)}",
    ]
    if o.location:
        lines.append(f"LocationId = {q(o.location)}")
    for prop, value in (("RequiredFlagId", o.req_flag), ("ForbiddenFlagId", o.forbid_flag),
                        ("CompletionFlagId", o.completion_flag), ("ActivatedFlagId", o.activated_flag)):
        if value:
            lines.append(f"{prop} = {q(value)}")
    if o.optional:
        lines.append("IsOptional = true")
    if o.hint:
        lines.append(f"HintKey = {q(o.hint)}")
    if o.journal:
        lines.append(f"JournalEntryKey = {q(o.journal)}")
    return lines


def quest_tres(qu: Quest, src: str) -> str:
    subs: List[str] = []
    refs: List[str] = []
    for i, o in enumerate(qu.objectives):
        sid = o.sub_id or f"Obj_{i}"
        subs.append("\n".join(objective_lines(o, sid)) + "\n")
        refs.append(f'SubResource("{sid}")')
    reward_refs: List[str] = []
    for i, (item, qty) in enumerate(qu.reward_items):
        subs.append(f'[sub_resource type="Resource" id="Reward_{i}"]\nscript = ExtResource("3_reward")\n'
                    f"ItemId = {q(item)}\nQuantity = {qty}\n")
        reward_refs.append(f'SubResource("Reward_{i}")')

    out = ['[gd_resource type="Resource" script_class="QuestResource" format=3]', "",
           '[ext_resource type="Script" path="res://src/Quests/QuestResource.cs" id="1_quest"]',
           '[ext_resource type="Script" path="res://src/Quests/ObjectiveResource.cs" id="2_obj"]']
    if reward_refs:
        out.append('[ext_resource type="Script" path="res://src/Quests/QuestItemReward.cs" id="3_reward"]')
    out += ["", HEADER.format(src=src), ""]
    out.append("\n".join(subs))          # each block ends with "\n"; the join keeps one blank between
    out += ["[resource]", 'script = ExtResource("1_quest")',
            f"Id = {q(qu.id)}", f"Title = {q(qu.title)}", f"Summary = {q(qu.summary)}",
            f"Objectives = Array[Resource]([{', '.join(refs)}])",
            f"XpReward = {qu.xp}", f"GoldReward = {qu.gold}", f"GoldItemId = {q(qu.gold_item)}"]
    if reward_refs:
        out.append(f"RewardItems = Array[Resource]([{', '.join(reward_refs)}])")
    if qu.faction_reward:
        out += [f"FactionRewardId = {q(qu.faction_reward[0])}", f"FactionRewardAmount = {qu.faction_reward[1]}"]
    if qu.time_limit:
        out.append(f"TimeLimitSeconds = {float(qu.time_limit)}")
    out += [f"SequentialObjectives = {'true' if qu.sequential else 'false'}",
            f"CompletionFlagId = {q(qu.completion_flag)}"]
    if qu.prerequisite:
        out.append(f"PrerequisiteQuestId = {q(qu.prerequisite)}")
    out += [f"AutoStartFlagId = {q(qu.auto_start)}", f"IsMainQuest = {'true' if qu.is_main else 'false'}"]
    if qu.one_shot:
        out += ["; One-shot bosses: each one's realm door or brazier is gated on this quest's own AutoStartFlagId,",
                "; so the quest is always active before its target can die.",
                "AllowsOneShotTarget = true"]
    # New fields (W-Core-A), appended after the existing properties, only when set.
    for prop, value in (("ChapterKey", qu.chapter_key), ("OrderInAct", qu.order), ("RegionId", qu.region),
                        ("GiverNameKey", qu.giver_key), ("RecommendedLevel", qu.level),
                        ("DetailKey", qu.detail), ("StartFlagId", qu.start_flag), ("FailFlagId", qu.fail_flag)):
        if value:
            out.append(f"{prop} = {q(value) if isinstance(value, str) else value}")
    if qu.ledger:
        out.append("IsLedger = true")
    return "\n".join(out) + "\n"


# --- dialogues -----------------------------------------------------------------------------------

def _choice_block(c, cid: str) -> str:
    lines = [f'[sub_resource type="Resource" id="{cid}"]', 'script = ExtResource("3_choice")', f"Text = {q(c.text)}"]
    if c.compact:
        if c.goto:
            lines.append(f"Goto = {q(c.goto)}")
        if c.cond[0] or c.cond[1]:
            lines += [f"Condition = {c.cond[0]}", f"ConditionArg = {q(c.cond[1])}"]
        if c.effect[0] or c.effect[1]:
            lines += [f"Effect = {c.effect[0]}", f"EffectArg = {q(c.effect[1])}"]
    else:
        lines += [f"Goto = {q(c.goto)}", f"Condition = {c.cond[0]}", f"ConditionArg = {q(c.cond[1])}",
                  f"Effect = {c.effect[0]}", f"EffectArg = {q(c.effect[1])}"]
    if c.cond2[0] or c.cond2[1]:
        lines += [f"Condition2 = {c.cond2[0]}", f"Condition2Arg = {q(c.cond2[1])}"]
    if c.effect2[0] or c.effect2[1]:
        lines += [f"Effect2 = {c.effect2[0]}", f"Effect2Arg = {q(c.effect2[1])}"]
    return "\n".join(lines) + "\n"


def _node_block(n, crefs: List[str]) -> str:
    # Id must stay directly above Text and Text directly above Choices: DialogueContentTests
    # recognises nodes by that shape. Optional fields therefore go after Choices.
    lines = [f'[sub_resource type="Resource" id="node_{n.id}"]', 'script = ExtResource("2_node")',
             f"Id = {q(n.id)}", f"Text = {q(n.text)}",
             f"Choices = Array[Resource]([{', '.join(crefs)}])"]
    if n.speaker:
        lines.append(f"Speaker = {q(n.speaker)}")
    if n.on_enter[0] or n.on_enter[1]:
        lines += [f"OnEnterEffect = {n.on_enter[0]}", f"OnEnterEffectArg = {q(n.on_enter[1])}"]
    return "\n".join(lines) + "\n"


def dialogue_tres(d: Dialogue, src: str) -> str:
    lead_choices: List[str] = []
    lead_nodes: List[str] = []
    subs: List[str] = []
    node_refs: List[str] = []
    for n in d.nodes:
        crefs: List[str] = []
        for j, c in enumerate(n.choices):
            cid = c.sub_id or f"ch_{n.id}_{j}"
            (lead_choices if c.early else subs).append(_choice_block(c, cid))
            crefs.append(f'SubResource("{cid}")')
        (lead_nodes if n.early else subs).append(_node_block(n, crefs))
        node_refs.append(f'SubResource("node_{n.id}")')
    subs = lead_choices + lead_nodes + subs
    variant_refs: List[str] = []
    for i, v in enumerate(d.start_variants):
        subs.append(f'[sub_resource type="Resource" id="start_{i}"]\nscript = ExtResource("4_variant")\n'
                    f"Condition = {v.cond[0]}\nConditionArg = {q(v.cond[1])}\nNodeId = {q(v.node)}\n")
        variant_refs.append(f'SubResource("start_{i}")')

    out = ['[gd_resource type="Resource" script_class="DialogueResource" format=3]', "",
           '[ext_resource type="Script" path="res://src/Dialogue/DialogueResource.cs" id="1_dlg"]',
           '[ext_resource type="Script" path="res://src/Dialogue/DialogueNode.cs" id="2_node"]',
           '[ext_resource type="Script" path="res://src/Dialogue/DialogueChoice.cs" id="3_choice"]']
    if variant_refs:
        out.append(f'[ext_resource type="Script" path="{START_VARIANT_SCRIPT}" id="4_variant"]')
    out += ["", HEADER.format(src=src), ""]
    if d.comment:
        out.append(f"; {d.comment}")
    out.append("\n".join(subs))
    out += ["[resource]", 'script = ExtResource("1_dlg")',
            f"Id = {q(d.id)}", f"SpeakerName = {q(d.speaker)}", f"StartNodeId = {q(d.start)}",
            f"Nodes = Array[Resource]([{', '.join(node_refs)}])"]
    if variant_refs:
        out.append(f"StartVariants = Array[Resource]([{', '.join(variant_refs)}])")
    return "\n".join(out) + "\n"
