#!/usr/bin/env python3
"""Self-test for the campaign generator. No framework: plain asserts.

    python tools/campaign/selftest.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from tools import gen_campaign  # noqa: E402
from tools.campaign import emit, graph, locale, tres, validate  # noqa: E402
from tools.campaign.model import (  # noqa: E402
    C, E, K, OT, Dialogue, Node, Patch, Quest, StartVariant, collect, corruption_at_least, defend, go,
    has_flag, interact, kill, leave, milestone, reach, say, set_flag, start_quest, talk)

CHECKS = []


def check(fn):
    CHECKS.append(fn)
    return fn


def read(rel: str) -> str:
    with open(ROOT / rel, encoding="utf-8", newline="") as f:
        return f.read()


def pristine(name: str) -> str:
    """A hand-authored quest or dialogue as it was before the campaign touched it (tools/campaign/fixtures/<name>.orig). The
    tests that exercise the patcher need a file no spec has touched yet."""
    with open(ROOT / "tools" / "campaign" / "fixtures" / f"{name}.orig", encoding="utf-8", newline="") as f:
        return f.read()


# --- model and lowering ---------------------------------------------------------------------------

def sample_quest() -> Quest:
    return Quest(
        id="quest.main.sample", title="Sample", summary="A sample quest.", detail="Long detail.",
        objectives=[
            talk("dialogue.elder", "Talk to the Elder", tag="elder", hint="Ask around"),
            reach("location.ember_crown.square", "Reach the square", tag="square", journal="You arrived."),
            interact("interact.bell", "Ring the bell", tag="bell", completion_flag="flag.beat.bell"),
            defend("location.ember_crown.square", 45, "Hold the square", tag="hold", req_flag="flag.beat.bell"),
            collect("item.material.iron_ore", 2, K("quest.warband.forge.obj"), tag="ore", optional=True),
            milestone("flag.beat.bell", "The bell has rung", tag="ms"),
            kill("enemy.goblin", 3, "Kill goblins", tag="gob", forbid_flag="flag.fork.spared"),
        ],
        completion_flag="flag.main.sample_done", auto_start="flag.main.before_done",
        chapter_key="chapter.act1", order=3, level=4, ledger=False)


@check
def lowering_and_keys():
    lq, lp, ld, rows = locale.lower([sample_quest()], [], [])
    q = lq[0]
    keys = dict(rows)
    assert q.title == "quest.main.sample.title" and keys[q.title] == "Sample"
    assert q.detail == "quest.main.sample.detail"
    assert q.objectives[0].text == "quest.main.sample.obj_elder"
    assert q.objectives[0].hint == "quest.main.sample.hint_elder"
    assert q.objectives[1].journal == "quest.main.sample.log_square"
    assert q.objectives[4].text == "quest.warband.forge.obj" and "quest.warband.forge.obj" not in keys, "K emits no row"
    assert len(keys) == len(rows), "no duplicate keys"
    secret = Quest(id="quest.main.pale_door", title="T", summary="S", secret="pale",
                   objectives=[talk("dialogue.x", "Go", tag="a")])
    lq, _, _, rows = locale.lower([secret], [], [])
    assert all(k.startswith("pale.quest.pale_door.") for k, _ in rows), rows
    d = Dialogue(id="dialogue.pale_queen", speaker="Queen", secret="pale",
                 nodes=[Node("root", "Hello", [say("Bye", tag="bye")])])
    _, _, ld, rows = locale.lower([], [], [d])
    assert [k for k, _ in rows] == ["pale.dlg.pale_queen.speaker", "pale.dlg.pale_queen.root",
                                    "pale.dlg.pale_queen.root.c_bye"], rows
    try:
        locale.lower([Quest(id="quest.main.nl", title="a\nb", summary="s")], [], [])
        raise AssertionError("newline accepted")
    except ValueError:
        pass


@check
def quest_emit_parse_roundtrip():
    lq, _, _, _ = locale.lower([sample_quest()], [], [])
    text = emit.quest_tres(lq[0], "tools/campaign/specs/x.py")
    assert text.startswith('[gd_resource type="Resource" script_class="QuestResource" format=3]')
    assert "; GENERATED by tools/gen_campaign.py" in text and emit.is_generated(text)
    p = graph.parse_quest(text, "data/quests/MainSample.tres", "generated")
    assert p["id"] == "quest.main.sample" and p["autoStart"] == "flag.main.before_done"
    assert p["chapter"] == "chapter.act1" and p["order"] == 3 and p["level"] == 4
    assert [o["type"] for o in p["objectives"]] == [OT.TALK, OT.REACH, OT.INTERACT, OT.DEFEND, OT.COLLECT, OT.MILESTONE, OT.KILL]
    assert p["objectives"][3]["count"] == 45 and p["objectives"][3]["reqFlag"] == "flag.beat.bell"
    assert p["objectives"][4]["optional"] and not p["objectives"][0]["optional"]
    assert p["objectives"][2]["completionFlag"] == "flag.beat.bell"
    assert ("flag.beat.bell", "objective[5].milestone") in {(r["flag"], r["via"]) for r in p["reads"]}
    assert emit.quest_tres(lq[0], "tools/campaign/specs/x.py") == text, "deterministic"
    # new fields are absent when default
    plain = emit.quest_tres(locale.lower([Quest(id="quest.x.y", title="t", summary="s",
                                                 objectives=[kill("enemy.goblin", 1, "k", tag="k")])], [], [])[0][0], "s")
    for prop in ("ChapterKey", "OrderInAct", "IsLedger", "IsOptional", "DetailKey"):
        assert prop not in plain, prop
    assert not re.search(r"^StartFlagId", plain, re.M)
    assert emit.stem("quest.main.the_pass_kept", "quest.") == "MainThePassKept"


def sample_dialogue() -> Dialogue:
    return Dialogue(
        id="dialogue.sample", speaker="Sam", start="root",
        start_variants=[StartVariant(has_flag("flag.beat.a"), "again")],
        nodes=[
            Node("root", "Well met.", [
                go("Tell me more", "more", tag="more"),
                set_flag("I choose A", "flag.fork.a", "more", when=corruption_at_least(40), tag="a",
                         do2=(E.ADD_CORRUPTION, "5"), when2=(C.HAS_ITEM, "item.x:1")),
                start_quest("Take the job", "quest.main.sample", "more", tag="job"),
                leave("Bye", tag="bye"),
            ]),
            Node("more", "More.", [say("Back", "root", tag="back")], on_enter=(E.SET_FLAG, "flag.beat.a"), speaker="Narrator"),
            Node("again", "Again.", [leave("Bye", tag="bye")]),
        ])


@check
def dialogue_emit_and_dialoguecontenttests_shape():
    _, _, ld, rows = locale.lower([], [], [sample_dialogue()])
    text = emit.dialogue_tres(ld[0], "tools/campaign/specs/x.py")
    # The regex shapes tests/Embervale.Tests/DialogueContentTests.cs depends on.
    nodes = re.findall(r'^Id = "([^"]+)"\nText = ', text, re.M)
    assert nodes == ["root", "more", "again"], nodes
    for m in re.finditer(r'^Id = "([^"]+)"\nText = [^\n]+\n(Choices = [^\n]*)', text, re.M):
        assert "([])" not in m.group(2)
    assert re.search(r'^Condition2 = 17|^Condition2 = 19', text, re.M)
    assert 'Effect2 = 4\nEffect2Arg = "5"' in text and 'OnEnterEffect = 2\nOnEnterEffectArg = "flag.beat.a"' in text
    assert 'Condition = 7\nConditionArg = "40"' in text
    assert re.search(r'^Effect = (\d+)\nEffectArg = "([^"]*)"', text, re.M)
    assert 'NodeId = "again"' in text and "StartVariants = Array[Resource]" in text
    d = graph.parse_dialogue(text, "data/dialogue/Sample.tres", "generated")
    assert d["flagsSet"] == ["flag.beat.a", "flag.fork.a"] and d["flagsRead"] == ["flag.beat.a"]
    assert d["questsStarted"] == ["quest.main.sample"]
    errors = []
    validate.check_dialogue_graph(d, errors)
    assert errors == [], errors
    # break it: unreachable node, dead end, bad goto
    broken = dict(d, nodes=d["nodes"] + [{"id": "orphan", "choices": 0, "gotos": ["nowhere"]}])
    errors = []
    validate.check_dialogue_graph(broken, errors)
    assert any("unreachable" in e for e in errors) and any("dead end" in e for e in errors) \
        and any("unknown node" in e for e in errors), errors


@check
def legacy_round_trip_matches_disk():
    r = gen_campaign.compute(ROOT)   # every spec: the quests the other specs add read flags only they write
    assert r.errors == [], r.errors
    for rel in ("data/quests/MainGathering.tres", "data/quests/MainHidden.tres", "data/quests/MainTruth.tres",
                "data/quests/MainCelestial.tres", "data/dialogue/SunspireArchivist.tres", "data/dialogue/AshThrone.tres"):
        assert gen_campaign._norm(r.files[rel]) == gen_campaign._norm(read(rel)), f"{rel} drifted from legacy.py"
    assert r.files[gen_campaign.LOCALE] == read(gen_campaign.LOCALE), "legacy emits no locale rows"
    # the generator is idempotent: the graph is a pure function of the files
    assert gen_campaign._norm(r.files[gen_campaign.GRAPH]) == gen_campaign._norm(read(gen_campaign.GRAPH))


# --- locale ---------------------------------------------------------------------------------------

BASE_CSV = ("keys,en\r\n# comment\r\na.b,Hello\r\n# --- BEGIN campaign:one ---\r\n# --- END campaign:one ---\r\n"
            "c.d,\"Quoted, text\"\r\n# --- BEGIN campaign:two ---\r\nold.row,stale\r\n# --- END campaign:two ---\r\n")


@check
def locale_block_rewrite():
    rows = [("x.one", "plain"), ("x.two", 'has, comma and "quotes"'), ("x.three", " padded ")]
    t1 = locale.rewrite_block(BASE_CSV, "one", rows)
    assert locale.rewrite_block(t1, "one", rows) == t1, "idempotent"
    assert "\r\n" in t1 and "\n" not in t1.replace("\r\n", ""), "CRLF preserved"
    assert 'x.two,"has, comma and ""quotes"""' in t1 and 'x.three," padded "' in t1 and "x.one,plain" in t1
    # only the one block changed
    assert t1.replace("x.one,plain\r\n", "").split("# --- END campaign:one ---")[1] == BASE_CSV.split("# --- END campaign:one ---")[1]
    t2 = locale.rewrite_block(t1, "two", [])
    assert "old.row" not in t2 and "x.one,plain" in t2
    assert locale.rewrite_block(t2, "one", []) != t2 and "x.one" not in locale.rewrite_block(t2, "one", [])
    # a missing block is appended only when it has rows, and the LF style is kept
    lf = "keys,en\na,b\n"
    assert locale.rewrite_block(lf, "new", []) == lf
    added = locale.rewrite_block(lf, "new", [("k.v", "w")])
    assert added == "keys,en\na,b\n# --- BEGIN campaign:new ---\nk.v,w\n# --- END campaign:new ---\n", repr(added)
    # round trip through the csv reader
    assert dict((r[0], r[1]) for r in locale.parse_rows(t1))["x.two"] == 'has, comma and "quotes"'
    assert locale.fmt_row("k", "Truth") == "k,Truth"


@check
def locale_audit_rules():
    clean = "keys,en\na.b,Hello\npale.x,The Pale Concord waits\n"
    assert locale.audit(clean) == []
    dup = locale.audit("keys,en\na.b,1\n# c\na.b,2\n")
    assert len(dup) == 1 and "duplicate key 'a.b'" in dup[0]
    leak = locale.audit("keys,en\nquest.main.x.summary,\"Beyond the door lies the pale concord, they say\"\n")
    assert len(leak) == 1 and "secret leak" in leak[0]
    assert locale.audit(read(gen_campaign.LOCALE)) == [], "the real catalogue is clean"


# --- patcher --------------------------------------------------------------------------------------

@check
def patcher_on_a_copy():
    original = pristine("WarbandHeart")
    patch = Patch("quest.warband.heart",
                  append=[interact("interact.arena_gate", K("quest.warband.heart.obj_arena"), tag="arena",
                                   location="location.frostfang.arena"),
                          reach("location.frostfang.arena", K("quest.warband.heart.obj_reach"), tag="reach", optional=True)],
                  auto_start="flag.main.bounty_done", start_flag="flag.main.heart_started",
                  fields={"ChapterKey": "chapter.act1"})
    out = tres.apply_patch(original, patch)
    assert tres.apply_patch(out, patch) == out, "idempotent"
    # every original line survives; the only edited line is the Objectives array
    import difflib
    removed = [ln[2:] for ln in difflib.ndiff(original.splitlines(), out.splitlines()) if ln.startswith("- ")]
    assert removed == ['Objectives = Array[Resource]([SubResource("Obj_kill")])'], removed
    for needle in ('CompletionFlagId = "flag.frostfang.passage_open"', 'Description = "quest.warband.heart.obj"'):
        assert out.count(needle) == 1, needle
    secs = tres.parse(out)
    res = tres.resource_of(secs)
    assert res.props["Objectives"] == ["Obj_kill", "Obj_arena", "Obj_reach"], res.props["Objectives"]
    assert res.props["AutoStartFlagId"] == "flag.main.bounty_done" and res.props["StartFlagId"] == "flag.main.heart_started"
    assert res.props["ChapterKey"] == "chapter.act1" and res.props["CompletionFlagId"] == "flag.frostfang.passage_open"
    assert tres.sub_index(secs)["Obj_reach"].props["IsOptional"] is True
    assert tres.sub_index(secs)["Obj_kill"].props["TargetId"] == "enemy.goblin"
    # a flag that is already set to something else is never overwritten
    try:
        tres.apply_patch(original, Patch("quest.warband.heart", completion_flag="flag.other"))
        raise AssertionError("overwrote a set field")
    except tres.PatchError:
        pass
    try:
        tres.apply_patch(original, Patch("quest.warband.bounty"))
        raise AssertionError("patched the wrong quest")
    except tres.PatchError:
        pass
    # an empty field is filled in place; load_steps follows added sub-resources; CRLF is preserved
    synthetic = ('[gd_resource type="Resource" script_class="QuestResource" load_steps=4 format=3]\r\n\r\n'
                 '[ext_resource type="Script" path="res://src/Quests/ObjectiveResource.cs" id="2_obj"]\r\n\r\n'
                 '[sub_resource type="Resource" id="Obj_a"]\r\nscript = ExtResource("2_obj")\r\nType = 0\r\n\r\n'
                 '[resource]\r\nId = "quest.t.t"\r\nObjectives = Array[Resource]([SubResource("Obj_a")])\r\n'
                 'AutoStartFlagId = ""\r\n')
    out2 = tres.apply_patch(synthetic, Patch("quest.t.t", append=[talk("dialogue.d", K("a.b"), tag="x")],
                                             auto_start="flag.go"))
    assert "load_steps=5" in out2 and 'AutoStartFlagId = "flag.go"' in out2 and out2.count("AutoStartFlagId") == 1
    assert "\r\n" in out2 and re.search(r"(?<!\r)\n", out2) is None
    # lowering: appended objectives need a tag unless their text is a K
    try:
        locale.lower([], [Patch("quest.t.t", append=[talk("dialogue.d", "prose")])], [])
        raise AssertionError("untagged prose accepted")
    except ValueError:
        pass
    _, lp, _, rows = locale.lower([], [Patch("quest.warband.heart", append=[interact("i.x", "Open it", tag="gate")])], [])
    assert rows == [("quest.warband.heart.obj_gate", "Open it")] and lp[0].append[0].text == "quest.warband.heart.obj_gate"


# --- graph analyses -------------------------------------------------------------------------------

def mini_graph() -> dict:
    def quest(qid, auto="", done="", prereq="", main=True, reads=(), writes=(), objectives=()):
        return {"id": qid, "autoStart": auto, "completionFlag": done, "prerequisite": prereq, "isMain": main,
                "objectives": list(objectives),
                "reads": [{"flag": f, "via": v} for f, v in ([(auto, "autoStart")] if auto else []) + list(reads)],
                "writes": ([{"flag": done, "via": "completion"}] if done else []) + [{"flag": f, "via": v} for f, v in writes],
                "source": "generated"}
    quests = [
        quest("quest.a", auto="flag.boss", done="flag.a_done", writes=[("flag.fork.x", "objective[0].completion")]),
        quest("quest.b", auto="flag.a_done", done="flag.b_done", reads=[("flag.fork.x", "objective[1].required")]),
        quest("quest.c", auto="flag.b_done", done="flag.c_done", reads=[("flag.later", "objective[0].required")]),
        quest("quest.d", auto="flag.nobody_sets"),
        quest("quest.e", auto="flag.c_done", done="flag.e_done", writes=[("flag.later", "objective[0].completion")]),
    ]
    flags = {}
    for q in quests:
        for w in q["writes"]:
            flags.setdefault(w["flag"], {"writers": [], "readers": [], "externalRefs": []})["writers"].append(
                {"kind": "quest", "id": q["id"], "via": w["via"]})
        for r in q["reads"]:
            flags.setdefault(r["flag"], {"writers": [], "readers": [], "externalRefs": []})["readers"].append(
                {"kind": "quest", "id": q["id"], "via": r["via"]})
    return {"codeFlags": ["flag.boss"], "terminalFlags": [], "entryQuests": [], "quests": quests,
            "dialogues": [], "flags": flags, "forks": []}


@check
def graph_analyses():
    g = mini_graph()
    assert graph.reachable(g) == {"quest.a", "quest.b", "quest.c", "quest.e"}, graph.reachable(g)
    anc = graph.ancestors(g)
    assert anc["quest.c"] == {"quest.a", "quest.b"} and anc["quest.a"] == set()
    scope = {q["id"] for q in g["quests"]}
    bad = graph.unordered_reads(g, scope)
    assert len(bad) == 2 and "quest.c reads flag.later" in bad[0] and "quest.d reads flag.nobody_sets" in bad[1], bad
    # flag.later is written by quest.e, which runs AFTER c; flag.nobody_sets has no writer at all
    assert graph.dead_end_flags(g, scope) == ["quest.e sets flag.e_done but nothing reads it (chain gap; add the next link or list it in TERMINAL_FLAGS)"]
    g["terminalFlags"] = ["flag.e_done"]
    assert graph.dead_end_flags(g, scope) == []


@check
def validator_rules():
    errors, warnings = [], []
    bad = Quest(id="quest.main.bad", title="T", summary="S", completion_flag="oops", objectives=[
        reach("location.a.b", "r", tag="r", location="location.a.b"),
        milestone("not_a_flag", "m", tag="m"),
        interact("interact.x", "i", tag="i", req_flag="flag.a", forbid_flag="flag.a"),
        defend("location.a.b", 0, "d", tag="d")])
    validate.check_quest(bad, errors, warnings, set(), set())
    text = "\n".join(errors)
    for needle in ("must start with 'flag.'", "Reach takes its destination", "Milestone target", "both required and forbidden",
                   "Defend needs"):
        assert needle in text, needle
    errors = []
    d = Dialogue(id="dialogue.q", nodes=[Node("root", "x", [say("y", do=(E.SET_FLAG, "nope"), when=(99, "")),
                                                          say("z", do=(E.ADD_CORRUPTION, "lots"))])])
    validate.check_dialogue(d, errors, [], set(), set())
    assert any("out of range" in e for e in errors) and any("must start with 'flag.'" in e for e in errors) \
        and any("not an integer" in e for e in errors), errors


@check
def end_to_end_in_a_scratch_root():
    """Whole pipeline on new content (example spec + a secret spec + a patch + a deliberate leak) in a
    scratch copy of the data, so the real tree is never touched."""
    import copy
    import shutil
    import tempfile
    import types
    from tools.campaign.specs import _example

    tmp = Path(tempfile.mkdtemp(prefix="campaign_selftest_"))
    try:
        # A scratch tree holding only what the legacy spec owns: the campaign specs' quests, dialogues, patches and
        # locale blocks are left out (and the warband quests are restored to their pristine fixtures), so the checks
        # below keep meaning "new content on top of the legacy four" however much real content the tree gains.
        for sub in ("bosses", "locale"):
            shutil.copytree(ROOT / "data" / sub, tmp / "data" / sub)
        (tmp / "data" / "quests").mkdir(parents=True)
        for n in ("MainGathering", "MainHidden", "MainTruth", "MainCelestial"):
            shutil.copy(ROOT / "data" / "quests" / f"{n}.tres", tmp / "data" / "quests" / f"{n}.tres")
        (tmp / "data" / "dialogue").mkdir(parents=True)
        for path in (ROOT / "data" / "dialogue").glob("*.tres"):
            text = read_path(path)
            # legacy output, and the hand-authored files no campaign spec has extended (an extension adds StartVariants)
            if path.stem in ("SunspireArchivist", "AshThrone") or (not emit.is_generated(text) and "StartVariants" not in text):
                shutil.copy(path, tmp / "data" / "dialogue" / path.name)
        for n in ("Elder", "Smith", "Apothecary"):   # the givers of the warband quests, before the campaign extended them
            gen_campaign._write(tmp / "data" / "dialogue" / f"{n}.tres", pristine(n))
        for n in ("WarbandBounty", "WarbandForge", "WarbandRemedies", "WarbandHeart"):
            gen_campaign._write(tmp / "data" / "quests" / f"{n}.tres", pristine(n))
        csv_path = tmp / gen_campaign.LOCALE
        csv_text = read_path(csv_path)
        for tag in re.findall(r"^# --- BEGIN campaign:(\w+) ---", csv_text, re.M):
            csv_text = locale.rewrite_block(csv_text, tag, [])
        gen_campaign._write(csv_path, csv_text)
        (tmp / "data" / "story").mkdir()

        def modules(broken: bool):
            def ex_build():
                items, dialogues, rows, tag = _example.build()
                items, dialogues = copy.deepcopy(items), copy.deepcopy(dialogues)
                if not broken:   # give the "sold" fork nothing to be a fork of
                    dialogues[0].nodes[0].choices[2].effect2 = (E.NONE, "")
                return items, dialogues, rows, tag

            ex = types.SimpleNamespace(
                __name__="spec_example", build=ex_build, CODE_FLAGS={"flag.main.opening_done": "story rule"},
                TERMINAL_FLAGS={"flag.frostfang.passage_open": "its reader (quest.main.iron_king) is not in the scratch tree"})

            def pale_build():
                q = Quest(id="quest.main.pale_door_test", title="The Door", summary="Behind it waits the Pale Concord.",
                          completion_flag="flag.main.pale_door_test_done", auto_start="flag.main.example_square_done",
                          objectives=[talk("dialogue.pale_test", "Speak to the voice", tag="speak")])
                d = Dialogue(id="dialogue.pale_test", speaker="Voice",
                             nodes=[Node("root", "The Pale Concord hears you.", [leave("Go", tag="go")])])
                return [q], [d], [], "pale"

            pale = types.SimpleNamespace(__name__="spec_pale", build=pale_build, SECRET="pale",
                                         TERMINAL_FLAGS={} if broken else {"flag.main.pale_door_test_done": "end of the test"})

            def leak_build():
                q = Quest(id="quest.main.leaky", title="Leaky", summary="Ask about the Pale Concord.",
                          objectives=[kill("enemy.goblin", 1, "Kill one", tag="k")])
                return ([q] if broken else []), [], [], "leak"

            patchmod = types.SimpleNamespace(__name__="spec_patch", build=lambda: (
                [Patch("quest.warband.heart", append=[interact("interact.arena_gate", "Open the arena gate", tag="arena")],
                       start_flag="flag.main.heart_started")], [], [], "patchtag"))
            return [ex, pale, types.SimpleNamespace(__name__="spec_leak", build=leak_build), patchmod]

        bad = gen_campaign.compute(tmp, ["legacy"], modules(broken=True))
        text = "\n".join(bad.errors)
        assert "flag.fork.example_sold has no consequence" in text, text
        assert "quest.main.pale_door_test sets flag.main.pale_door_test_done but nothing reads it" in text, text
        assert "secret leak: 'quest.main.leaky.summary'" in text, text
        assert "pale.quest.pale_door_test" not in text, "pale keys may name the Pale Concord"

        good = gen_campaign.compute(tmp, ["legacy"], modules(broken=False))
        assert good.errors == [], good.errors
        assert any("location.ember_crown.square" in w for w in good.warnings), "unknown ids are warnings, not errors"
        for rel, content in good.files.items():
            gen_campaign._write(tmp / rel, content)
        again = gen_campaign.compute(tmp, ["legacy"], modules(broken=False))
        assert again.errors == [] and gen_campaign.drift(again, tmp) == [], gen_campaign.drift(again, tmp)

        csv_text = read_path(tmp / gen_campaign.LOCALE)
        assert "# --- BEGIN campaign:example ---" in csv_text and "pale.quest.pale_door_test.title,The Door" in csv_text
        assert "quest.warband.heart.obj_arena,Open the arena gate" in csv_text
        assert "quest.main.example_square.obj_hold,Hold the square" in csv_text
        assert "chapter.act1,Act I: Embers at the Crown" in csv_text
        assert "Pale Concord" not in "".join(ln for ln in csv_text.split("\r\n") if not ln.startswith("pale."))
        heart = read_path(tmp / "data/quests/WarbandHeart.tres")
        assert 'StartFlagId = "flag.main.heart_started"' in heart and 'Description = "quest.warband.heart.obj"' in heart
        assert read("data/quests/WarbandHeart.tres").count("heart_started") == 0, "real tree untouched"
        assert pristine("WarbandHeart").count("heart_started") == 0, "fixture untouched"
        g = __import__("json").loads(read_path(tmp / gen_campaign.GRAPH))
        ids = {q["id"]: q for q in g["quests"]}
        assert ids["quest.main.example_square"]["source"] == "generated" and ids["quest.warband.heart"]["source"] == "patched"
        assert [f["flag"] for f in g["forks"]] == ["flag.fork.example_parley"], g["forks"]
        assert "quest.main.example_square" in graph.reachable(g)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def read_path(path: Path) -> str:
    with open(path, encoding="utf-8", newline="") as f:
        return f.read()


@check
def real_tree_validates_clean():
    r = gen_campaign.compute(ROOT)
    assert r.errors == [], r.errors


def main() -> int:
    failed = 0
    for fn in CHECKS:
        try:
            fn()
            print(f"ok    {fn.__name__}")
        except Exception as exc:   # noqa: BLE001
            failed += 1
            print(f"FAIL  {fn.__name__}: {type(exc).__name__}: {exc}")
    print(f"selftest: {len(CHECKS) - failed}/{len(CHECKS)} passed")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
