#!/usr/bin/env python3
"""Engine-free questions about authored content. No Godot, no build; about a second or two.

    python tools/content.py refs item.material.scrap        who defines and who uses this id
    python tools/content.py refs enm_bandit                 ... or a model stem / res:// path
    python tools/content.py refs --prefix item.material.    list defined ids
    python tools/content.py refs --unused --kind items      defined ids nothing refers to
    python tools/content.py refs --dangling                 ids and res:// paths used but not defined
    python tools/content.py census                          what exists, per data folder
    python tools/content.py diff main                       what content changed since a commit
    python tools/content.py diff v1 v2 --kind items --fields
    python tools/content.py balance enemies|loot|recipes|xp   estimate tables with outlier flags
    python tools/content.py balance enemies --save a.json   then, after a retune:
    python tools/content.py balance enemies --baseline a.json --threshold 0.15

Every command takes --json (one object on stdout). Through the SDK:
    python tools/embervale.py tool content -- refs item.material.scrap

These are reports, never gates: ContentValidator (--validate) stays the authority on what is valid.
An "id" here is any quoted string shaped like `word.word`; a string counts as a reference only when
it equals a defined id (or, under --dangling, shares a prefix with defined ids and is not a locale
key). `balance` mirrors three formulas from src/Combat/CombatMath.cs and refuses to run when their
constants change; it ignores perks, hit zones, blocking, status effects, spells and per-attack
multipliers, so it finds outliers and does not prove a fight is winnable.
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import re
import statistics
import subprocess
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path

from quality_common import ROOT, write_json
import tres_reader
from tres_reader import Ref

ID = re.compile(r"[a-z][a-z0-9_]*(?:\.[a-z0-9_{}]+)+")
CODE_STRING = re.compile(r'"([a-z][a-z0-9_]*(?:\.[a-z0-9_]+)+)"')
GENERATED = re.compile(r"(?im)^[;#] *generated by (tools/[\w/.]+\.py)")
LOCALE = "data/locale/strings.csv"
ARTIFACTS = ROOT / "artifacts" / "content"
CONTENT_PATHS = ("data", "scenes")
CACHE = ARTIFACTS / "index.json"
CACHE_SCHEMA = 1
#: prepared world artifacts are binary build output; tools/world_bake.py --plan reports on them.
BAKED = ":(exclude)data/world_bake"


# ------------------------------------------------------------------------------------- index

@dataclass
class Definition:
    id: str
    kind: str
    path: str
    script_class: str
    generated: str
    section: str = ""


@dataclass
class Index:
    defs: dict[str, list[Definition]] = field(default_factory=lambda: defaultdict(list))
    uses: dict[str, list[tuple[str, str, str]]] = field(default_factory=lambda: defaultdict(list))
    files: dict[str, dict] = field(default_factory=dict)
    locale: set[str] = field(default_factory=set)
    root: Path = ROOT


def kind_of(rel: str) -> str:
    parts = rel.split("/")
    if rel.endswith(".json"):
        return "json"
    if parts[0] == "data" and len(parts) > 2:
        return parts[1]
    if parts[0] == "scenes":
        return "scenes"
    if parts[0] == "src":
        return "code"
    if parts[0] == "tools":
        return "tools"
    if parts[0] == "tests":
        return "tests"
    return parts[0]


def generated_by(text: str) -> str:
    match = GENERATED.search(text[:4000])
    return match.group(1) if match else ""


def document_record(rel: str, text: str) -> dict:
    """What one .tres/.tscn defines and every id or res:// path it mentions, as plain JSON."""
    doc = tres_reader.parse(text)
    kind = kind_of(rel)
    generator = generated_by(text)
    root = doc.root
    root_id = root.get("Id") if root is not None else None
    record = {"info": {"kind": kind, "generated": generator,
                       "id": root_id if isinstance(root_id, str) else ""},
              "defs": [], "uses": []}
    if isinstance(root_id, str) and root_id:
        record["defs"].append([root_id, kind, doc.script_class, generator, ""])
    for section in doc.sections:
        if section.kind == "ext_resource":
            path = section.attrs.get("path")
            if isinstance(path, str) and path.startswith("res://"):
                record["uses"].append([path, "ext_resource"])
            continue
        own_id = section.get("Id")
        if section.kind == "sub_resource" and isinstance(own_id, str) and ID.fullmatch(own_id):
            sub_kind = "cells" if kind == "regions" and "ScenePath" in section.props else f"{kind}.sub"
            record["defs"].append([own_id, sub_kind, doc.script_class, generator, section.label])
        for key, value in section.props.items():
            if key == "Id" and (section is root or section.kind == "sub_resource"):
                continue
            for string in tres_reader.strings_in(value):
                if string.startswith("res://") or ID.fullmatch(string):
                    record["uses"].append([string, f"{section.label}.{key}"])
    return record


def code_record(rel: str, text: str) -> dict:
    uses = []
    for number, line in enumerate(text.splitlines(), 1):
        if '"' not in line:
            continue
        for match in CODE_STRING.finditer(line):
            uses.append([match.group(1), f"line {number}"])
    return {"info": None, "defs": [], "uses": uses}


def locale_keys(text: str) -> set[str]:
    keys: set[str] = set()
    for line in text.splitlines():
        if not line or line.startswith("#"):
            continue
        keys.add(line.split(",", 1)[0])
    return keys


def source_files(root: Path, code: bool) -> list[tuple[str, Path]]:
    found: list[tuple[str, Path]] = []
    for folder in CONTENT_PATHS:
        for path in sorted((root / folder).rglob("*")):
            rel = path.relative_to(root).as_posix()
            if path.suffix in (".tres", ".tscn") and path.is_file() and not rel.startswith("data/_templates/"):
                found.append((rel, path))
    if code:
        # tests and GDScript probes name ids too: a rename that misses them breaks the build or a gate.
        # So does authored JSON under data/ (the campaign graph and its specs name enemies and items).
        for folder, pattern in (("src", "*.cs"), ("tools", "*.py"), ("tools", "*.gd"), ("tests", "*.cs"),
                                ("data", "*.json")):
            for path in sorted((root / folder).rglob(pattern)):
                rel = path.relative_to(root).as_posix()
                # data/world_bake is a manifest of hashes, not content.
                if "/obj/" in rel or "/bin/" in rel or rel.startswith("data/world_bake/"):
                    continue
                if "/test_" not in rel and not rel.endswith(("tools/content.py", "tools/tres_reader.py")):
                    found.append((rel, path))
    return found


def build_index(root: Path = ROOT, code: bool = True, cache: Path | None = None) -> Index:
    """Index the tree. With `cache`, a file whose size and mtime are unchanged is not re-read."""
    cached: dict = {}
    if cache is not None and cache.is_file():
        try:
            loaded = json.loads(cache.read_text(encoding="utf-8"))
            cached = loaded["files"] if loaded.get("schema") == CACHE_SCHEMA else {}
        except (OSError, ValueError, KeyError):
            cached = {}
    index = Index(root=root)
    records: dict[str, dict] = {}
    dirty = False
    for rel, path in source_files(root, code):
        stat = path.stat()
        signature = [stat.st_size, stat.st_mtime_ns]
        record = cached.get(rel)
        if record is None or record.get("sig") != signature:
            text = path.read_text(encoding="utf-8", errors="replace")
            record = document_record(rel, text) if path.suffix in (".tres", ".tscn") else code_record(rel, text)
            record["sig"] = signature
            dirty = True
        records[rel] = record
        kind = kind_of(rel)
        if record["info"] is not None:
            index.files[rel] = record["info"]
        for token, def_kind, script_class, generator, section in record["defs"]:
            index.defs[token].append(Definition(token, def_kind, rel, script_class, generator, section))
        for token, where in record["uses"]:
            index.uses[token].append((kind, rel, where))
    locale = root / LOCALE
    if locale.is_file():
        index.locale = locale_keys(locale.read_text(encoding="utf-8", errors="replace"))
    if cache is not None:
        # A content-only build leaves the cached code records alone rather than dropping them.
        gone = [rel for rel in cached if rel not in records
                and (code or not rel.startswith(("src/", "tools/")))]
        if dirty or gone:
            cached.update(records)
            for rel in gone:
                del cached[rel]
            cache.parent.mkdir(parents=True, exist_ok=True)
            temporary = cache.with_suffix(".tmp")
            temporary.write_text(json.dumps({"schema": CACHE_SCHEMA, "files": cached}), encoding="utf-8")
            temporary.replace(cache)
    return index


# ------------------------------------------------------------------------------------- refs

def resolve_query(index: Index, query: str) -> list[str]:
    """The index tokens a query stands for: the id itself, its defining files' res:// paths, and
    for a bare stem or partial path every res:// token that ends with it."""
    tokens = [query] if query in index.defs or query in index.uses else []
    for definition in index.defs.get(query, ()):
        if not definition.section:
            tokens.append("res://" + definition.path)
    if not query.startswith("res://") and not tokens:
        stem = query.rsplit("/", 1)[-1]
        for token in index.uses:
            if not token.startswith("res://"):
                continue
            name = token.rsplit("/", 1)[-1]
            if token.endswith("/" + query) or name == stem or name.rsplit(".", 1)[0] == stem:
                tokens.append(token)
    return list(dict.fromkeys(tokens))


def refs(index: Index, query: str) -> dict:
    tokens = resolve_query(index, query)
    definitions = [vars(d) for d in index.defs.get(query, ())]
    uses: list[dict] = []
    seen: set[tuple] = set()
    for token in tokens:
        for kind, path, where in index.uses.get(token, ()):
            key = (kind, path, where)
            if key in seen:
                continue
            seen.add(key)
            uses.append({"kind": kind, "path": path, "where": where,
                         **({"via": token} if token != query else {})})
    uses.sort(key=lambda use: (use["kind"], use["path"], use["where"]))
    locale = sorted(key for key in index.locale if key == query or key.startswith(query + "."))
    return {"query": query, "defs": definitions, "uses": uses, "locale_keys": locale,
            "by_kind": dict(Counter(use["kind"] for use in uses))}


def unused(index: Index, kind: str | None) -> list[Definition]:
    out = []
    for token, definitions in sorted(index.defs.items()):
        for definition in definitions:
            if kind and definition.kind != kind:
                continue
            path_token = "res://" + definition.path
            used = any(path != definition.path for _, path, _ in index.uses.get(token, ()))
            used = used or (not definition.section and any(
                path != definition.path for _, path, _ in index.uses.get(path_token, ())))
            if not used:
                out.append(definition)
    return out


def dangling(index: Index) -> list[dict]:
    prefixes = {token.split(".", 1)[0] for token, definitions in index.defs.items()
                if any(not definition.section for definition in definitions)}
    out = []
    for token, uses in sorted(index.uses.items()):
        content_uses = [use for use in uses if use[0] not in ("code", "tools", "tests", "json")]
        if not content_uses or "{" in token:
            continue
        if token.startswith("res://"):
            target = index.root / token[len("res://"):]
            if not target.exists():
                out.append({"token": token, "why": "missing file", "uses": content_uses})
        elif (token not in index.defs and token not in index.locale
              and token.split(".", 1)[0] in prefixes):
            out.append({"token": token, "why": "undefined id", "uses": content_uses})
    return out


def cmd_refs(args) -> int:
    index = build_index(cache=CACHE)
    if args.unused:
        rows = unused(index, args.kind)
        if args.json:
            print(json.dumps({"unused": [vars(d) for d in rows]}))
        else:
            for definition in rows:
                print(f"unused  {definition.id}  {definition.kind}  {definition.path}")
            print(f"summary unused {len(rows)}" + (f" kind {args.kind}" if args.kind else ""))
        return 0
    if args.dangling:
        rows = dangling(index)
        if args.json:
            print(json.dumps({"dangling": rows}))
        else:
            for row in rows:
                kind, path, where = row["uses"][0]
                more = f"  (+{len(row['uses']) - 1} more)" if len(row["uses"]) > 1 else ""
                print(f"dangling  {row['token']}  {row['why']}  {path}  {where}{more}")
            print(f"summary dangling {len(rows)}")
        return 0
    if args.prefix is not None:
        rows = [d for token, ds in sorted(index.defs.items()) if token.startswith(args.prefix)
                for d in ds if not args.kind or d.kind == args.kind]
        if args.json:
            print(json.dumps({"defs": [vars(d) for d in rows]}))
        else:
            shown_rows = rows if args.limit is None else rows[:args.limit]
            for definition in shown_rows:
                print(f"def  {definition.id}  {definition.kind}  {definition.path}")
            if len(shown_rows) < len(rows):
                print(f"def  ... {len(rows) - len(shown_rows)} more (raise --limit)")
            print(f"summary defs {len(rows)}")
        return 0
    if not args.id:
        print("refs: give an id, a res:// path or a model stem, or --unused/--dangling/--prefix",
              file=sys.stderr)
        return 2
    result = refs(index, args.id)
    limit = 25 if args.limit is None else args.limit
    if args.json:
        print(json.dumps(result))
    else:
        for definition in result["defs"]:
            where = f"#{definition['section']}" if definition["section"] else ""
            generated = f"  generated:{definition['generated']}" if definition["generated"] else ""
            print(f"def  {definition['id']}  {definition['kind']}  {definition['path']}{where}"
                  f"  {definition['script_class']}{generated}")
        shown: Counter = Counter()
        for use in result["uses"]:
            shown[use["kind"]] += 1
            if shown[use["kind"]] > limit:
                continue
            via = f"  via {use['via']}" if "via" in use else ""
            print(f"use  {use['kind']}  {use['path']}  {use['where']}{via}")
        for kind, count in sorted(shown.items()):
            if count > limit:
                print(f"use  {kind}  ... {count - limit} more (raise --limit)")
        if result["locale_keys"]:
            keys = result["locale_keys"]
            print(f"locale  {len(keys)} key(s): {', '.join(keys[:4])}{' ...' if len(keys) > 4 else ''}")
        kinds = ", ".join(f"{kind} {count}" for kind, count in sorted(result["by_kind"].items()))
        print(f"summary {args.id}  defs {len(result['defs'])}  uses {len(result['uses'])}"
              + (f"  ({kinds})" if kinds else ""))
    return 0 if result["defs"] or result["uses"] else 1


# ------------------------------------------------------------------------------------- census

def census(root: Path = ROOT, cache: Path | None = None) -> dict:
    index = build_index(root, code=False, cache=cache)
    kinds: dict[str, dict] = {}
    for rel, info in sorted(index.files.items()):
        if not rel.startswith("data/"):
            continue
        row = kinds.setdefault(info["kind"], {"files": 0, "generated": 0, "hand": 0})
        row["files"] += 1
        row["generated" if info["generated"] else "hand"] += 1
    cells: Counter = Counter()
    for definitions in index.defs.values():
        for definition in definitions:
            if definition.kind == "cells":
                cells[definition.path.rsplit("/", 1)[-1].removesuffix(".tres")] += 1
    bosses = 0
    for rel in index.files:
        if rel.startswith("data/enemies/"):
            doc = tres_reader.load(root / rel)
            bosses += 1 if doc.root is not None and doc.root.get("IsBoss") is True else 0
    return {
        "kinds": kinds,
        "cells": dict(sorted(cells.items())),
        "cells_total": sum(cells.values()),
        "scenes": sum(1 for rel in index.files if rel.startswith("scenes/")),
        "locale_rows": len(index.locale),
        "bosses": bosses,
        "main_quests": sum(1 for token in index.defs if token.startswith("quest.main.")),
        "ids": sum(len(v) for v in index.defs.values()),
    }


def cmd_census(args) -> int:
    result = census(cache=CACHE)
    if args.json:
        print(json.dumps(result))
        return 0
    for kind, row in result["kinds"].items():
        extra = ""
        if kind == "enemies":
            extra = f", bosses {result['bosses']}"
        elif kind == "quests":
            extra = f", main {result['main_quests']}"
        print(f"{kind:<16} {row['files']:>4}  (generated {row['generated']}, hand {row['hand']}{extra})")
    regions = ", ".join(f"{name} {count}" for name, count in result["cells"].items())
    print(f"{'cells':<16} {result['cells_total']:>4}  ({regions})")
    print(f"{'scenes':<16} {result['scenes']:>4}")
    print(f"{'locale rows':<16} {result['locale_rows']:>4}")
    print(f"summary ids {result['ids']}  data files {sum(r['files'] for r in result['kinds'].values())}")
    return 0


# ------------------------------------------------------------------------------------- diff

def git(*arguments: str, data: bytes | None = None) -> bytes:
    return subprocess.run(["git", *arguments], cwd=ROOT, input=data, capture_output=True, check=True).stdout


def git_blobs(revision: str, paths: list[str]) -> dict[str, str | None]:
    """Many files at one revision through a single `git cat-file --batch` process."""
    if not paths:
        return {}
    request = "".join(f"{revision}:{path}\n" for path in paths).encode("utf-8")
    stream = io.BytesIO(git("cat-file", "--batch", data=request))
    out: dict[str, str | None] = {}
    for path in paths:
        header = stream.readline().decode("utf-8", "replace").strip()
        if header.endswith("missing") or not header:
            out[path] = None
            continue
        size = int(header.rsplit(" ", 1)[-1])
        out[path] = stream.read(size).decode("utf-8", "replace")
        stream.read(1)
    return out


def changed_paths(rev_a: str, rev_b: str | None) -> list[tuple[str, str]]:
    arguments = ["diff", "--name-status", "--no-renames", "-z", rev_a]
    if rev_b:
        arguments.append(rev_b)
    names = git(*arguments, "--", *CONTENT_PATHS, BAKED).decode("utf-8", "replace").split("\0")
    changes = [(names[i], names[i + 1]) for i in range(0, len(names) - 1, 2)]
    if not rev_b:
        untracked = git("ls-files", "--others", "--exclude-standard", "-z", "--", *CONTENT_PATHS)
        changes += [("A", name) for name in untracked.decode("utf-8", "replace").split("\0") if name]
    return changes


def flatten(doc: tres_reader.Doc) -> dict[str, object]:
    flat: dict[str, object] = {}
    for section in doc.sections:
        if section.kind == "resource":
            prefix = ""
        elif section.kind in ("sub_resource", "node"):
            prefix = section.label + "."
        else:
            continue
        for key, value in section.props.items():
            if key != "script":
                flat[prefix + key] = value
    return flat


def short(value) -> str:
    if isinstance(value, Ref):
        return f"{value.kind}:{value.id}"
    if isinstance(value, float):
        return f"{value:g}"
    if isinstance(value, list):
        return f"[{len(value)}]" if len(value) > 3 else "[" + ", ".join(short(v) for v in value) + "]"
    text = str(value)
    return text if len(text) <= 40 else text[:37] + "..."


def diff_documents(old: str | None, new: str | None) -> dict:
    """Field-level difference of two versions of one .tres/.tscn (either side may be absent)."""
    old_flat = flatten(tres_reader.parse(old)) if old is not None else {}
    new_flat = flatten(tres_reader.parse(new)) if new is not None else {}
    fields = []
    for key in sorted(set(old_flat) | set(new_flat)):
        before, after = old_flat.get(key), new_flat.get(key)
        if before != after:
            fields.append({"field": key,
                           "old": None if key not in old_flat else short(before),
                           "new": None if key not in new_flat else short(after)})
    return {"fields": fields}


def diff_locale(old: str | None, new: str | None) -> dict:
    def rows(text):
        out = {}
        for line in (text or "").splitlines():
            if line and not line.startswith("#"):
                key, _, rest = line.partition(",")
                out[key] = rest
        return out
    before, after = rows(old), rows(new)
    return {"added": len(set(after) - set(before)), "removed": len(set(before) - set(after)),
            "changed": sum(1 for key in set(before) & set(after) if before[key] != after[key])}


def root_id(text: str | None) -> str:
    if text is None:
        return ""
    doc = tres_reader.parse(text)
    value = doc.root.get("Id") if doc.root is not None else None
    return value if isinstance(value, str) else ""


def content_diff(rev_a: str, rev_b: str | None, kind_filter: str | None = None) -> dict:
    changes = changed_paths(rev_a, rev_b)
    paths = [path for _, path in changes]
    old = git_blobs(rev_a, paths)
    if rev_b:
        new = git_blobs(rev_b, paths)
    else:
        new = {}
        for path in paths:
            target = ROOT / path
            new[path] = target.read_text(encoding="utf-8", errors="replace") if target.is_file() else None
    facts = []
    for status, path in changes:
        kind = kind_of(path)
        if kind_filter and kind != kind_filter:
            continue
        before, after = old.get(path), new.get(path)
        fact = {"status": {"A": "+", "D": "-"}.get(status, "~"), "kind": kind, "path": path}
        if path == LOCALE:
            fact.update(kind="locale", locale=diff_locale(before, after))
        elif path.endswith((".tres", ".tscn")):
            fact["id"] = root_id(after) or root_id(before)
            if fact["status"] == "~":
                fact.update(diff_documents(before, after))
                if not fact["fields"]:
                    continue  # comments, ordering or line endings only
        facts.append(fact)
    summary: dict[str, Counter] = defaultdict(Counter)
    for fact in facts:
        summary[fact["kind"]][fact["status"]] += 1
    return {"a": rev_a, "b": rev_b or "worktree", "facts": facts,
            "summary": {kind: dict(counts) for kind, counts in sorted(summary.items())}}


def fact_line(fact: dict, fields: bool) -> str:
    name = fact.get("id") or fact["path"]
    line = f"{fact['status']} {name} ({fact['kind']})"
    if "locale" in fact:
        counts = fact["locale"]
        return f"~ locale keys +{counts['added']} -{counts['removed']} ~{counts['changed']}"
    changed = fact.get("fields") or []
    if not changed:
        return line
    sections = sorted({f["field"].rsplit(".", 1)[0] for f in changed if "." in f["field"]})
    if len(changed) > 6 and not fields:
        tail = f" in {len(sections)} section(s): {', '.join(sections[:3])}" if sections else ""
        return f"{line} {len(changed)} fields{tail}{' ...' if len(sections) > 3 else ''}"
    parts = [f"{f['field']} {f['old'] if f['old'] is not None else '(unset)'} -> "
             f"{f['new'] if f['new'] is not None else '(unset)'}" for f in changed]
    return f"{line} " + "; ".join(parts)


def summary_line(summary: dict) -> str:
    parts = []
    for kind, counts in summary.items():
        parts.append(kind + " " + " ".join(f"{sign}{counts[sign]}" for sign in "+~-" if counts.get(sign)))
    return "summary " + (" | ".join(parts) if parts else "no content changes")


def cmd_diff(args) -> int:
    try:
        result = content_diff(args.rev_a, args.rev_b, args.kind)
    except subprocess.CalledProcessError as error:
        print(f"diff: git failed: {error.stderr.decode('utf-8', 'replace').strip()}", file=sys.stderr)
        return 2
    safe = lambda rev: re.sub(r"[^A-Za-z0-9_.-]", "_", rev)[:40]
    report = ARTIFACTS / f"diff-{safe(result['a'])}-{safe(result['b'])}.json"
    write_json(report, result)
    if args.json:
        print(json.dumps({**result, "report": report.relative_to(ROOT).as_posix()}))
        return 0
    lines = [fact_line(fact, args.fields) for fact in result["facts"]]
    if len(lines) > args.max_lines and not args.fields:
        print(f"{len(lines)} changes; showing counts (use --kind K, --fields or --max-lines N for lines)")
    else:
        for line in lines:
            print(line)
    print(summary_line(result["summary"]))
    print(f"report {report.relative_to(ROOT).as_posix()}")
    return 0


# ------------------------------------------------------------------------------------- balance

COMBAT_MATH = "src/Combat/CombatMath.cs"
POWER_SCALING = 0.5
#: source text that must still be present in CombatMath.cs for the mirror below to be trusted.
COMBAT_MATH_ANCHORS = (
    "private const float PowerScaling = 0.5f;",
    "return baseDamage + (power * scaling);",
    "return 100f / (100f + clamped);",
)
ARMOUR_SLOTS = (3, 4, 5, 6, 7)  # EquipmentSlot Head, Chest, Hands, Legs, Feet
MAIN_HAND = 1


def combat_math_drift(root: Path = ROOT) -> list[str]:
    text = (root / COMBAT_MATH).read_text(encoding="utf-8", errors="replace")
    return [anchor for anchor in COMBAT_MATH_ANCHORS if anchor not in text]


def armor_multiplier(armor: float) -> float:
    return 100.0 / (100.0 + max(0.0, armor))


def scale_damage(base: float, power: float, scaling: float = POWER_SCALING) -> float:
    return base + power * scaling


def hits_to_kill(health: float, base: float, power: float, armor: float) -> float:
    hit = max(1.0, scale_damage(base, power) * armor_multiplier(armor))
    return health / hit


def xp_to_leave(level: int, base_xp: float, exponent: float, max_level: int) -> int:
    return 0 if level >= max_level else int(round(base_xp * level ** exponent))


def number(section, key: str, default: float = 0.0) -> float:
    value = section.get(key, default) if section is not None else default
    return float(value) if isinstance(value, (int, float)) and not isinstance(value, bool) else default


def res_path(root: Path, value) -> Path | None:
    return root / value[len("res://"):] if isinstance(value, str) and value.startswith("res://") else None


def load_root(path: Path | None):
    if path is None or not path.is_file():
        return None
    return tres_reader.load(path).root


def tier_tables() -> tuple[dict, dict]:
    sys.path.insert(0, str(ROOT / "tools" / "items"))
    try:
        import catalogue  # the generators' own source of truth for tier -> realm and level band
    finally:
        sys.path.pop(0)
    return dict(catalogue.TIER_LEVELS), dict(catalogue.TIER_REGION)


def median(values: list[float]) -> float:
    return statistics.median(values) if values else 0.0


def tier_kits(root: Path = ROOT) -> dict[int, dict]:
    """A typical on-tier kit: the median main-hand weapon and the median armour piece per slot."""
    weapons: dict[int, list[tuple[float, float]]] = defaultdict(list)
    armour: dict[int, dict[int, list[tuple[float, float]]]] = defaultdict(lambda: defaultdict(list))
    for path in sorted((root / "data" / "items").glob("*.tres")):
        doc = tres_reader.load(path)
        item = doc.root
        if item is None or not isinstance(item.get("Tier"), int) or not item.get("Slot"):
            continue
        tier, slot = item.get("Tier"), item.get("Slot")
        if slot == MAIN_HAND:
            weapon = load_root(res_path(root, doc.resolve(item.get("Weapon"))))
            if weapon is not None:
                weapons[tier].append((number(weapon, "BaseDamage"), number(item, "BonusPhysicalPower")))
        elif slot in ARMOUR_SLOTS:
            armour[tier][slot].append((number(item, "BonusArmor"), number(item, "BonusMaxHealth")))
    kits = {}
    for tier in sorted(set(weapons) | set(armour)):
        kits[tier] = {
            "weapon_damage": median([w[0] for w in weapons[tier]]),
            "power": median([w[1] for w in weapons[tier]]),
            "armor": sum(median([a[0] for a in armour[tier][slot]]) for slot in ARMOUR_SLOTS),
            "health": sum(median([a[1] for a in armour[tier][slot]]) for slot in ARMOUR_SLOTS),
        }
    return kits


def player_at(level: int, kit: dict, base, progression) -> dict:
    grown = level - 1
    return {
        "health": number(base, "Health") + number(progression, "HealthPerLevel") * grown + kit["health"],
        "power": number(base, "PhysicalPower") + number(progression, "PhysicalPowerPerLevel") * grown + kit["power"],
        "armor": number(base, "Armor") + number(progression, "ArmorPerLevel") * grown + kit["armor"],
        "weapon_damage": kit["weapon_damage"],
    }


def enemy_regions(index: Index, enemy_id: str, folders: dict[str, str]) -> tuple[set[str], bool]:
    """(regions an enemy is tied to, whether an encounter can also bring it anywhere).

    Sources: an encounter's RegionIds, and any region scene that names the enemy or names a
    resource (boss, encounter) that names it."""
    regions: set[str] = set()
    anywhere = False
    tokens = [enemy_id]
    for kind, path, _ in index.uses.get(enemy_id, ()):
        if kind == "encounters":
            root = tres_reader.load(index.root / path).root
            listed = [r for r in (root.get("RegionIds") or []) if isinstance(r, str)] if root else []
            regions.update(listed)
            anywhere = anywhere or not listed
        owner = index.files.get(path, {}).get("id")
        if owner and kind in ("bosses", "encounters"):
            tokens.append(owner)
    for token in tokens:
        for kind, path, _ in index.uses.get(token, ()):
            parts = path.split("/")
            if kind == "scenes" and len(parts) > 3 and parts[1] == "regions" and parts[2] in folders:
                regions.add(folders[parts[2]])
    return regions, anywhere


def region_folders(root: Path = ROOT) -> dict[str, str]:
    """scenes/regions/<folder> -> region id, read from each region resource's cell scene paths."""
    folders: dict[str, str] = {}
    for path in sorted((root / "data" / "regions").glob("*.tres")):
        text = path.read_text(encoding="utf-8", errors="replace")
        region = re.search(r'^Id = "(region\.[^"]+)"', text, re.MULTILINE)
        if region:
            for folder in set(re.findall(r'res://scenes/regions/([^/"]+)/', text)):
                folders[folder] = region.group(1)
    return folders


def balance_enemies(root: Path = ROOT, index: Index | None = None) -> list[dict]:
    index = index or build_index(root, code=False, cache=CACHE if root == ROOT else None)
    tier_levels, tier_region = tier_tables()
    region_tier = {region: tier for tier, region in tier_region.items()}
    folders = region_folders(root)
    kits = tier_kits(root)
    base = load_root(root / "data" / "attributes" / "PlayerAttributes.tres")
    progression = load_root(root / "data" / "progression" / "PlayerProgression.tres")
    empty_kit = {"weapon_damage": 0.0, "power": 0.0, "armor": 0.0, "health": 0.0}
    rows = []
    for path in sorted((root / "data" / "enemies").glob("*.tres")):
        enemy = tres_reader.load(path).root
        if enemy is None or not isinstance(enemy.get("Id"), str):
            continue
        attributes = load_root(res_path(root, enemy.get("AttributesPath")))
        weapon = load_root(res_path(root, enemy.get("WeaponPath")))
        regions, anywhere = enemy_regions(index, enemy.get("Id"), folders)
        tiers = sorted(region_tier[r] for r in regions if r in region_tier)
        known = bool(tiers) or anywhere
        if anywhere or not tiers:
            tiers = sorted(set(tiers) | {min(tier_levels)}) if anywhere else sorted(tier_levels)
        low_tier, high_tier = tiers[0], tiers[-1]
        low_level, high_level = tier_levels[low_tier][0], tier_levels[high_tier][1]
        health, armor = number(attributes, "Health"), number(attributes, "Armor")
        enemy_base, enemy_power = number(weapon, "BaseDamage"), number(attributes, "PhysicalPower")
        row = {"id": enemy.get("Id"), "boss": enemy.get("IsBoss") is True,
               "tiers": tiers, "band_known": known, "levels": [low_level, high_level],
               "hp": health, "armor": armor, "xp": number(enemy, "XpValue"),
               "xp_per_hp": round(number(enemy, "XpValue") / health, 3) if health else 0.0}
        for edge, tier, level in (("lo", low_tier, low_level), ("hi", high_tier, high_level)):
            player = player_at(level, kits.get(tier, empty_kit), base, progression)
            row[f"ttk_{edge}"] = round(hits_to_kill(health, player["weapon_damage"], player["power"], armor), 1)
            row[f"ttd_{edge}"] = round(hits_to_kill(player["health"], enemy_base, enemy_power, player["armor"]), 1)
        rows.append(row)
    flag_enemies(rows)
    return rows


def flag_enemies(rows: list[dict]) -> None:
    """Outlier flags, each relative to the ordinary enemies that share the row's lowest tier."""
    by_tier: dict[int, list[dict]] = defaultdict(list)
    for row in rows:
        if not row["boss"] and row["band_known"]:
            by_tier[row["tiers"][0]].append(row)
    for row in rows:
        flags = []
        peers = by_tier.get(row["tiers"][0], [])
        if not row["band_known"]:
            flags.append("band-unknown")
        if row["ttd_lo"] < 2.0:
            flags.append("one-shots-at-entry")
        if peers and not row["boss"]:
            typical = median([peer["ttk_lo"] for peer in peers])
            if typical and row["ttk_lo"] > 3 * typical:
                flags.append("tanky")
            if typical and row["ttk_lo"] < typical / 3:
                flags.append("fragile")
            typical_xp = median([peer["xp_per_hp"] for peer in peers])
            if typical_xp and not typical_xp / 3 <= row["xp_per_hp"] <= typical_xp * 3:
                flags.append("xp-outlier")
        if peers and row["boss"] and row["hp"] < max(peer["hp"] for peer in peers):
            flags.append("boss-weaker-than-trash")
        row["flags"] = flags


def item_values(root: Path = ROOT) -> dict[str, float]:
    values = {}
    for path in sorted((root / "data" / "items").glob("*.tres")):
        item = tres_reader.load(path).root
        if item is not None and isinstance(item.get("Id"), str):
            values[item.get("Id")] = number(item, "Value")
    return values


def table_value(root: Path, path: Path | None, values: dict[str, float], tier: int, depth: int = 0) -> float:
    """Expected sale value of one roll of a loot table. Ungrouped entries roll independently; the
    entries of one Group are treated as one weighted pick. An estimate: level and rarity gates,
    affixes and once-per-save rows are ignored."""
    if path is None or not path.is_file() or depth > 3:
        return 0.0
    doc = tres_reader.load(path)
    table = doc.root
    if table is None:
        return 0.0
    total = number(table, "GoldChance") * (number(table, "GoldMin") + number(table, "GoldMax")) / 2
    groups: dict[str, list[tuple[float, float]]] = defaultdict(list)
    for entry in doc.resolve(table.get("Entries") or []):
        if not isinstance(entry, tres_reader.Section):
            continue
        quantity = (number(entry, "MinQuantity", 1) + number(entry, "MaxQuantity", 1)) / 2
        nested = entry.get("TablePath")
        if isinstance(nested, str) and nested:
            worth = table_value(root, res_path(root, nested.replace("{tier}", str(tier))), values, tier, depth + 1)
        else:
            worth = values.get(entry.get("ItemId"), 0.0) * quantity
        expected = number(entry, "DropChance", 1.0) * worth
        group = entry.get("Group")
        if isinstance(group, str) and group:
            groups[group].append((number(entry, "Weight", 1.0), expected))
        else:
            total += expected
    for picks in groups.values():
        weight = sum(w for w, _ in picks)
        total += sum(w * v for w, v in picks) / weight if weight else 0.0
    return total


def balance_loot(root: Path = ROOT, enemies: list[dict] | None = None) -> list[dict]:
    enemies = enemies if enemies is not None else balance_enemies(root)
    tiers = {row["id"]: row for row in enemies}
    values = item_values(root)
    rows = []
    for path in sorted((root / "data" / "enemies").glob("*.tres")):
        enemy = tres_reader.load(path).root
        if enemy is None or enemy.get("Id") not in tiers:
            continue
        info = tiers[enemy.get("Id")]
        tier = info["tiers"][0]
        value = table_value(root, res_path(root, enemy.get("LootTablePath")), values, tier)
        xp = info["xp"]
        rows.append({"id": info["id"], "tier": tier, "boss": info["boss"], "value_per_kill": round(value, 1),
                     "xp": xp, "value_per_100xp": round(100 * value / xp, 1) if xp else 0.0, "flags": []})
    by_tier: dict[int, list[float]] = defaultdict(list)
    for row in rows:
        if not row["boss"]:
            by_tier[row["tier"]].append(row["value_per_100xp"])
    for row in rows:
        typical = median(by_tier.get(row["tier"], []))
        if row["value_per_kill"] == 0:
            row["flags"].append("drops-nothing")
        elif typical and not row["boss"] and not typical / 3 <= row["value_per_100xp"] <= typical * 3:
            row["flags"].append("value-outlier")
    return rows


def balance_recipes(root: Path = ROOT) -> list[dict]:
    """Ingredient cost against output worth at base item Value (no shop spread, no standing).
    tools/gen_recipes.py --report is the shop-priced commission table."""
    values = item_values(root)
    rows = []
    for path in sorted((root / "data" / "recipes").glob("*.tres")):
        doc = tres_reader.load(path)
        recipe = doc.root
        if recipe is None or not isinstance(recipe.get("Id"), str):
            continue
        cost, missing = 0.0, []
        for ingredient in doc.resolve(recipe.get("Ingredients") or []):
            if not isinstance(ingredient, tres_reader.Section):
                continue
            item = ingredient.get("ItemId")
            if item not in values:
                missing.append(str(item))
            cost += values.get(item, 0.0) * number(ingredient, "Quantity", 1)
        output = recipe.get("OutputItemId")
        worth = values.get(output, 0.0) * number(recipe, "OutputQuantity", 1)
        flags = []
        if missing or output not in values:
            flags.append("missing-item")
        if cost and worth / cost > 3:
            flags.append("output-worth-3x-cost")
        if cost and worth and worth / cost < 1 / 3:
            flags.append("output-under-third-of-cost")
        rows.append({"id": recipe.get("Id"), "tier": recipe.get("Tier", 0), "cost": round(cost, 1),
                     "worth": round(worth, 1), "ratio": round(worth / cost, 2) if cost else 0.0,
                     "flags": flags})
    return rows


def balance_xp(root: Path = ROOT, enemies: list[dict] | None = None) -> list[dict]:
    enemies = enemies if enemies is not None else balance_enemies(root)
    tier_levels, _ = tier_tables()
    progression = load_root(root / "data" / "progression" / "PlayerProgression.tres")
    base_xp, exponent = number(progression, "BaseXpToLevel", 100), number(progression, "XpCurveExponent", 1.5)
    max_level = int(number(progression, "MaxLevel", 50))
    rows = []
    for tier, (low, high) in sorted(tier_levels.items()):
        needed = sum(xp_to_leave(level, base_xp, exponent, max_level) for level in range(low, high))
        ordinary = [row["xp"] for row in enemies
                    if not row["boss"] and row["band_known"] and tier in row["tiers"] and row["xp"]]
        typical = median(ordinary)
        kills = round(needed / typical) if typical else 0
        flags = [] if ordinary else ["no-enemies"]
        rows.append({"id": f"tier{tier}", "tier": tier, "levels": [low, high], "xp_needed": needed,
                     "enemies": len(ordinary), "median_xp": typical, "kills_to_clear_band": kills,
                     "flags": flags})
    return rows


BALANCE = {
    "enemies": (balance_enemies, ("id", "tiers", "levels", "hp", "armor", "ttk_lo", "ttk_hi", "ttd_lo",
                                  "ttd_hi", "xp", "xp_per_hp")),
    "loot": (balance_loot, ("id", "tier", "value_per_kill", "xp", "value_per_100xp")),
    "recipes": (balance_recipes, ("id", "tier", "cost", "worth", "ratio")),
    "xp": (balance_xp, ("id", "levels", "xp_needed", "enemies", "median_xp", "kills_to_clear_band")),
}


def moved(rows: list[dict], baseline: list[dict], threshold: float) -> list[dict]:
    """Rows that are new, gone, or have a number that moved by more than `threshold` (a fraction)."""
    before = {row["id"]: row for row in baseline}
    out = []
    for row in rows:
        old = before.pop(row["id"], None)
        if old is None:
            out.append({**row, "change": "new"})
            continue
        changes = []
        for key, value in row.items():
            previous = old.get(key)
            if isinstance(value, bool) or not isinstance(value, (int, float)) or not isinstance(previous, (int, float)):
                continue
            scale = max(abs(previous), 1e-9)
            if abs(value - previous) / scale > threshold:
                changes.append(f"{key} {previous:g} -> {value:g}")
        if changes:
            out.append({**row, "change": "; ".join(changes)})
    out.extend({**row, "change": "removed"} for row in before.values())
    return out


def cell(value, column: str = "") -> str:
    if isinstance(value, list):
        return ("T" + ",".join(str(v) for v in value)) if column == "tiers" else "-".join(str(v) for v in value)
    if isinstance(value, float):
        return f"{value:g}"
    return str(value)


def cmd_balance(args) -> int:
    drift = combat_math_drift()
    if drift:
        print(f"balance: {COMBAT_MATH} changed; update the mirror in tools/content.py. Missing: "
              + " | ".join(drift), file=sys.stderr)
        return 2
    build, columns = BALANCE[args.table]
    rows = build()
    if args.save:
        write_json(Path(args.save), rows)
    if args.baseline:
        try:
            baseline = json.loads(Path(args.baseline).read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            print(f"balance: cannot read baseline: {error}", file=sys.stderr)
            return 2
        rows = moved(rows, baseline, args.threshold)
        columns = ("id", "change")
    elif args.flagged:
        rows = [row for row in rows if row["flags"]]
    if args.json:
        print(json.dumps({"table": args.table, "rows": rows}))
        return 0
    print("# " + "  ".join(columns) + ("" if args.baseline else "  flags"))
    for row in rows:
        line = "  ".join(cell(row.get(column, ""), column) for column in columns)
        if not args.baseline:
            line += "  " + (",".join(row["flags"]) or "-")
        print(line)
    flagged = sum(1 for row in rows if row.get("flags"))
    print(f"summary {args.table} rows {len(rows)}"
          + (f" moved over {args.threshold:g}" if args.baseline else f" flagged {flagged}")
          + "  (estimate; see --help for what it leaves out)")
    return 0


# ------------------------------------------------------------------------------------- cli

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    commands = parser.add_subparsers(dest="command", required=True)

    p = commands.add_parser("refs", help="who defines and uses an id, path or model")
    p.add_argument("id", nargs="?")
    p.add_argument("--unused", action="store_true")
    p.add_argument("--dangling", action="store_true")
    p.add_argument("--prefix")
    p.add_argument("--kind", help="data folder name, e.g. items, recipes, quests")
    p.add_argument("--limit", type=int, default=None,
                   help="use lines printed per kind (default 25); with --prefix, def lines printed (default all)")
    p.add_argument("--json", action="store_true")
    p.set_defaults(run=cmd_refs)

    p = commands.add_parser("census", help="what content exists")
    p.add_argument("--json", action="store_true")
    p.set_defaults(run=cmd_census)

    p = commands.add_parser("diff", help="content changes between two commits, or a commit and the worktree")
    p.add_argument("rev_a")
    p.add_argument("rev_b", nargs="?", help="default: the working tree, including untracked files")
    p.add_argument("--kind")
    p.add_argument("--fields", action="store_true", help="print every changed field")
    p.add_argument("--max-lines", type=int, default=60)
    p.add_argument("--json", action="store_true")
    p.set_defaults(run=cmd_diff)

    p = commands.add_parser(
        "balance", help="estimate tables with outlier flags",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=(
            "Estimates from authored data, mirroring three CombatMath formulas. Left out: perks, hit zones,\n"
            "blocking, status effects, spells, per-attack multipliers and quest XP.\n"
            "  enemies  ttk_* = player HITS to kill it, ttd_* = its HITS to kill the player (not seconds);\n"
            "           lo/hi = at the first level of its lowest tier / last level of its highest, in that\n"
            "           tier's kit. tiers come from the regions whose encounters or scenes name it.\n"
            "  loot     value_per_kill = expected gold value of one kill's drops.\n"
            "  recipes  cost = ingredient value, worth = output value, ratio = worth / cost.\n"
            "  xp       kills_to_clear_band = XP to leave the band / median non-boss XP (quest XP ignored)."))
    p.add_argument("table", choices=sorted(BALANCE))
    p.add_argument("--flagged", action="store_true", help="only rows with a flag")
    p.add_argument("--save", help="write the rows to this JSON file")
    p.add_argument("--baseline", help="print only rows that moved against this saved file")
    p.add_argument("--threshold", type=float, default=0.15)
    p.add_argument("--json", action="store_true")
    p.set_defaults(run=cmd_balance)

    args = parser.parse_args(argv)
    return args.run(args)


if __name__ == "__main__":
    raise SystemExit(main())
