#!/usr/bin/env python3
"""DEPRECATED: the main story is now generated by tools/gen_campaign.py from tools/campaign/specs/*.py.

This wrapper only forwards to it. The four legacy quests and the Archivist / Ash Throne conversations
live in tools/campaign/specs/legacy.py.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import gen_campaign  # noqa: E402

if __name__ == "__main__":
    print("note: gen_main_story.py is deprecated; run tools/gen_campaign.py (edit tools/campaign/specs/*.py)")
    raise SystemExit(gen_campaign.main(sys.argv[1:]))
