#!/usr/bin/env python3
"""The main story's quests and its two story conversations (finish run, 2026-09-27).

    python tools/gen_main_story.py

Writes data/quests/Main*.tres, data/dialogue/ArchivistTruth.tres and data/dialogue/AshThrone.tres.
The acts chain through QuestResource.AutoStartFlagId (docs/playbook/finish.md): a boss's defeat flag
or the previous act's flag starts the next quest with no quest giver. Text lives in strings.csv.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# DialogueCondition / DialogueEffect ordinals (src/Dialogue/DialogueEnums.cs).
ALWAYS, HAS_FLAG, MISSING_FLAG, CORRUPTION_AT_LEAST, CORRUPTION_BELOW = 0, 5, 6, 7, 8
SET_FLAG = 2

# (file, id, auto-start flag, completion flag, [(target enemy, location, description key)])
QUESTS = [
    ("MainGathering", "quest.main.gathering", "flag.iron_king_defeated", "", [
        ("enemy.storm_tyrant", "location.frostfang.stormcrown", "quest.main.gathering.obj_storm"),
        ("enemy.beast_lord", "location.ashen.beast_lair", "quest.main.gathering.obj_beast"),
        ("enemy.crimson_prophet", "location.sunspire.mission", "quest.main.gathering.obj_prophet"),
    ]),
    ("MainHidden", "quest.main.hidden", "flag.pale_concord_revealed", "", [
        ("enemy.hollow_queen", "location.pale.palace", "quest.main.hidden.obj"),
    ]),
    ("MainCelestial", "quest.main.celestial", "flag.celestial_gate_open", "", [
        ("enemy.ashen_knight", "location.celestial.knight_gate", "quest.main.celestial.obj_knight"),
        ("enemy.morthul", "location.celestial.ash_throne", "quest.main.celestial.obj_morthul"),
    ]),
]

# Act III is a conversation, not a kill: a Talk objective on the Archivist's dialogue.
TRUTH = ("MainTruth", "quest.main.truth", "flag.hollow_queen_defeated", "dialogue.sunspire_archivist")


def quest(file, qid, auto, completion, objectives, talk=None, sequential=False) -> str:
    subs, refs = [], []
    for i, (target, location, desc) in enumerate(objectives):
        subs.append(f'''[sub_resource type="Resource" id="Obj_{i}"]
script = ExtResource("2_obj")
Type = 0
TargetId = "{target}"
RequiredCount = 1
Description = "{desc}"
LocationId = "{location}"
''')
        refs.append(f'SubResource("Obj_{i}")')
    if talk:
        subs.append(f'''[sub_resource type="Resource" id="Obj_talk"]
script = ExtResource("2_obj")
Type = 3
TargetId = "{talk}"
RequiredCount = 1
Description = "{qid}.obj"
LocationId = "location.sunspire.library"
''')
        refs.append('SubResource("Obj_talk")')
    return f'''[gd_resource type="Resource" script_class="QuestResource" format=3]

[ext_resource type="Script" path="res://src/Quests/QuestResource.cs" id="1_quest"]
[ext_resource type="Script" path="res://src/Quests/ObjectiveResource.cs" id="2_obj"]

; GENERATED by tools/gen_main_story.py — edit the generator, not this file.

{chr(10).join(subs)}
[resource]
script = ExtResource("1_quest")
Id = "{qid}"
Title = "{qid}.title"
Summary = "{qid}.summary"
Objectives = Array[Resource]([{", ".join(refs)}])
XpReward = 600
GoldReward = 200
GoldItemId = "item.currency.gold"
SequentialObjectives = {"true" if sequential else "false"}
CompletionFlagId = "{completion}"
AutoStartFlagId = "{auto}"
IsMainQuest = true
; One-shot bosses: each one's realm door or brazier is gated on this quest's own AutoStartFlagId,
; so the quest is always active before its target can die.
AllowsOneShotTarget = true
'''


def dialogue(did, speaker, start, nodes) -> str:
    """nodes: [(node id, text key, [(text key, goto, condition, cond arg, effect, effect arg)])]"""
    subs, node_refs = [], []
    for nid, text, choices in nodes:
        crefs = []
        for j, (ctext, goto, cond, carg, eff, earg) in enumerate(choices):
            cid = f"ch_{nid}_{j}"
            subs.append(f'''[sub_resource type="Resource" id="{cid}"]
script = ExtResource("3_choice")
Text = "{ctext}"
Goto = "{goto}"
Condition = {cond}
ConditionArg = "{carg}"
Effect = {eff}
EffectArg = "{earg}"
''')
            crefs.append(f'SubResource("{cid}")')
        subs.append(f'''[sub_resource type="Resource" id="node_{nid}"]
script = ExtResource("2_node")
Id = "{nid}"
Text = "{text}"
Choices = Array[Resource]([{", ".join(crefs)}])
''')
        node_refs.append(f'SubResource("node_{nid}")')
    return f'''[gd_resource type="Resource" script_class="DialogueResource" format=3]

[ext_resource type="Script" path="res://src/Dialogue/DialogueResource.cs" id="1_dlg"]
[ext_resource type="Script" path="res://src/Dialogue/DialogueNode.cs" id="2_node"]
[ext_resource type="Script" path="res://src/Dialogue/DialogueChoice.cs" id="3_choice"]

; GENERATED by tools/gen_main_story.py — edit the generator, not this file.

{chr(10).join(subs)}
[resource]
script = ExtResource("1_dlg")
Id = "{did}"
SpeakerName = "{speaker}"
StartNodeId = "{start}"
Nodes = Array[Resource]([{", ".join(node_refs)}])
'''


def c(text, goto="", cond=ALWAYS, carg="", eff=0, earg=""):
    return (text, goto, cond, carg, eff, earg)


# The Archivist is Sunspire's (Seren Adaru, 2026-09 Sunspire build); her library and Prophet topics are
# kept and the Act II/III story branches hang off the same root.
ARCHIVIST = dialogue("dialogue.sunspire_archivist", "dlg.sunspire_archivist.speaker", "root", [
    ("root", "dlg.sunspire_archivist.root", [
        c("dlg.archivist.c_truth", "cataclysm", HAS_FLAG, "flag.hollow_queen_defeated"),
        c("dlg.archivist.c_gate", "gate", HAS_FLAG, "flag.celestial_gate_open"),
        c("dlg.archivist.c_hidden", "hidden", MISSING_FLAG, "flag.hollow_queen_defeated"),
        c("dlg.sunspire_archivist.c_library", "library"),
        c("dlg.sunspire_archivist.c_prophet", "prophet", MISSING_FLAG, "flag.crimson_prophet_defeated"),
        c("dlg.sunspire_archivist.c_bye"),
    ]),
    ("library", "dlg.sunspire_archivist.library", [c("dlg.sunspire_archivist.c_library_bye")]),
    ("prophet", "dlg.sunspire_archivist.prophet", [c("dlg.sunspire_archivist.c_prophet_bye")]),
    ("hidden", "dlg.archivist.hidden", [c("dlg.archivist.c_back", "root")]),
    ("cataclysm", "dlg.archivist.cataclysm", [c("dlg.archivist.c_more", "morthul")]),
    ("morthul", "dlg.archivist.morthul", [c("dlg.archivist.c_more", "throne")]),
    ("throne", "dlg.archivist.throne", [c("dlg.archivist.c_open", "opened", MISSING_FLAG,
                                          "flag.celestial_gate_open", SET_FLAG, "flag.celestial_gate_open"),
                                        c("dlg.archivist.c_back", "root")]),
    ("opened", "dlg.archivist.opened", [c("dlg.sunspire_archivist.c_bye")]),
    ("gate", "dlg.archivist.gate", [c("dlg.archivist.c_back", "root")]),
])

# The ending choice. Corruption decides which doors are open: under 40 only Dawnfire, 60 and over
# only the throne, and the band between may choose (CorruptionTiers). Both paths confirm first.
THRONE = dialogue("dialogue.ash_throne", "dlg.throne.speaker", "gate", [
    # The throne is also a placed talkable (celestial/ash_throne.tscn), so the choice can be re-opened
    # by a player who walked away; this first node holds it shut while Morthul still sits.
    ("gate", "dlg.throne.gate", [
        c("dlg.throne.c_approach", "throne", HAS_FLAG, "flag.morthul_defeated"),
        c("dlg.throne.c_leave", "", MISSING_FLAG, "flag.morthul_defeated"),
    ]),
    ("throne", "dlg.throne.intro", [
        c("dlg.throne.c_refuse", "dawn", CORRUPTION_BELOW, "60"),
        c("dlg.throne.c_sit", "embers", CORRUPTION_AT_LEAST, "40"),
        c("dlg.throne.c_later"),
    ]),
    ("dawn", "dlg.throne.dawn", [
        c("dlg.throne.c_dawn_yes", "", MISSING_FLAG, "flag.ending_embers", SET_FLAG, "flag.ending_dawnfire"),
        c("dlg.throne.c_wait", "throne"),
    ]),
    ("embers", "dlg.throne.embers", [
        c("dlg.throne.c_embers_yes", "", MISSING_FLAG, "flag.ending_dawnfire", SET_FLAG, "flag.ending_embers"),
        c("dlg.throne.c_wait", "throne"),
    ]),
])


def main() -> None:
    for file, qid, auto, completion, objectives in QUESTS:
        (ROOT / "data/quests" / f"{file}.tres").write_text(
            quest(file, qid, auto, completion, objectives, sequential=qid.endswith("celestial")),
            encoding="utf-8", newline="\n")
    file, qid, auto, talk = TRUTH
    (ROOT / "data/quests" / f"{file}.tres").write_text(
        quest(file, qid, auto, "", [], talk=talk), encoding="utf-8", newline="\n")
    (ROOT / "data/dialogue/SunspireArchivist.tres").write_text(ARCHIVIST, encoding="utf-8", newline="\n")
    (ROOT / "data/dialogue/AshThrone.tres").write_text(THRONE, encoding="utf-8", newline="\n")
    print("wrote 4 main quests, dialogue.sunspire_archivist, dialogue.ash_throne")


if __name__ == "__main__":
    main()
