#!/usr/bin/env python3
"""Author the item catalogue (ics, content lane).

tools/items/catalogue.py decides WHAT exists (ids, slots, tiers, sources). This file decides the
numbers and the words, and writes everything that must agree with them, so none of it can drift:

  1. data/items/*.tres            one resource per NEW catalogue item (marked "; Generated by ...")
  2. data/weapons/Player*.tres    the WeaponResource each new main-hand item swaps in
  3. data/unique_effects/*.tres   one UniqueEffectResource per catalogue unique effect
  4. data/item_sets/*.tres        one ItemSetResource per catalogue set
  5. data/loot/*LeveledGear.tres, EmbermarketCaravanGear.tres   the three shop gear pools (tiered)
  6. data/shops/*.tres            the stock rows named in SHOP_STOCK (ids "Stock_ics_*")
  7. the 12 EXISTING_RETROFIT items: tier / level / class fields stamped onto their .tres
  8. data/locale/strings.csv      set and unique-effect text, inside the ics:content block
  9. src/Debugging/ItemValidator.Content.cs   the id lists between the "generated" markers

Hand-authored files are never rewritten wholesale: (5)-(7) splice marked rows into them and leave
every other byte alone. Generated item files carry a marker comment; a marked file the catalogue no
longer names is deleted, an unmarked one is never touched.

THE NUMBERS LIVE IN FOUR FUNCTIONS, mirrored in C# by ItemBudget (ItemValidator.Content.cs), which
--validate and tests/Embervale.Tests/ItemCatalogueTests.cs recompute against the written files:

  budget_points(item_level, slot, two_handed, rarity)   the stat points an equippable may spend
  weapon_damage(item_level, weapon_class, rarity)       WeaponResource.BaseDamage
  item_value(item_level, rarity, slot)                  ItemResource.Value (gold)
  STAT_WEIGHT                                           what one unit of each stat costs in points

Enum ordinals are read from the C# sources (a .tres stores an enum as its index).

Idempotent. Usage:  python tools/gen_items.py [--check]
        --check exits 1 if anything would change, without writing (a gate, not a generator).
"""

import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools", "items"))
import catalogue as C  # noqa: E402  (pure data, no I/O on import)

ITEM_DIR = os.path.join(ROOT, "data", "items")
WEAPON_DIR = os.path.join(ROOT, "data", "weapons")
UNIQUE_DIR = os.path.join(ROOT, "data", "unique_effects")
SET_DIR = os.path.join(ROOT, "data", "item_sets")
LOOT_DIR = os.path.join(ROOT, "data", "loot")
SHOP_DIR = os.path.join(ROOT, "data", "shops")
CSV = os.path.join(ROOT, "data", "locale", "strings.csv")
VALIDATOR = os.path.join(ROOT, "src", "Debugging", "ItemValidator.Content.cs")

MARK_BEGIN = "# --- BEGIN ics:content ---"
MARK_END = "# --- END ics:content ---"
CS_BEGIN = "    // --- BEGIN generated by tools/gen_items.py (do not edit by hand) ---"
CS_END = "    // --- END generated ---"
GENERATED = "; Generated by tools/gen_items.py from tools/items/catalogue.py. Edit those, not this file."
ICS = "ics_"  # sub-resource id infix of every row this generator splices into a hand-authored file


def enum_members(rel_path, name):
    """Member names of `enum <name>` in a C# file, in declaration order (= the stored ordinal)."""
    text = io.open(os.path.join(ROOT, rel_path), encoding="utf-8").read()
    body = re.search(r"enum\s+" + name + r"\s*\{(.*?)\n\}", text, re.S).group(1)
    body = re.sub(r"//[^\n]*", "", body)
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    return [m.strip().split("=")[0].strip() for m in body.split(",") if m.strip()]


SLOTS = enum_members("src/Items/EquipmentSlot.cs", "EquipmentSlot")
TYPES = enum_members("src/Items/ItemType.cs", "ItemType")
RARITIES = enum_members("src/Items/ItemType.cs", "ItemRarity")
CLASSES = enum_members("src/Items/WeaponClass.cs", "WeaponClass")
WEIGHTS = enum_members("src/Items/ArmorWeight.cs", "ArmorWeight")
EFFECTS = enum_members("src/Items/ConsumableEffectKind.cs", "ConsumableEffectKind")
UNIQUE_KINDS = enum_members("src/Items/UniqueEffectKind.cs", "UniqueEffectKind")
STATS = enum_members("src/Stats/StatType.cs", "StatType")
MODS = enum_members("src/Stats/StatModifier.cs", "ModifierType")
REPUTATION = enum_members("src/Factions/ReputationTier.cs", "ReputationTier")

# ---------------------------------------------------------------------------------------------
# THE STAT BUDGET. One equippable may spend budget_points() on stats, each priced by STAT_WEIGHT.
# A "point" is one point of Armor. Everything else is priced against that.
# ---------------------------------------------------------------------------------------------

#: Points one unit of a stat costs. CritChance and MoveSpeed are per 1.0, the regens per 1/second.
STAT_WEIGHT = {
    "Armor": 1.0, "Health": 0.4, "Stamina": 0.5, "Mana": 0.5,
    "PhysicalPower": 3.0, "SpellPower": 3.0, "CritChance": 500.0, "MoveSpeed": 25.0,
    "FireResist": 0.5, "FrostResist": 0.5, "LightningResist": 0.5,
    "ArcaneResist": 0.5, "NatureResist": 0.5, "NecroticResist": 0.5,
    "ManaRegen": 8.0, "StaminaRegen": 6.0,
}
#: The grain a stat is authored in (everything else is whole numbers).
STAT_STEP = {"CritChance": 0.005, "MoveSpeed": 0.05, "ManaRegen": 0.1, "StaminaRegen": 0.1}
#: StatType name -> the EquippableItemResource export that carries it.
BONUS_FIELD = {
    "Armor": "BonusArmor", "PhysicalPower": "BonusPhysicalPower", "SpellPower": "BonusSpellPower",
    "Health": "BonusMaxHealth", "Stamina": "BonusMaxStamina", "CritChance": "BonusCritChance",
    "MoveSpeed": "BonusMoveSpeed", "FrostResist": "BonusFrostResist", "FireResist": "BonusFireResist",
    "LightningResist": "BonusLightningResist", "ArcaneResist": "BonusArcaneResist",
    "NatureResist": "BonusNatureResist", "NecroticResist": "BonusNecroticResist", "Mana": "BonusMana",
    "ManaRegen": "BonusManaRegen", "StaminaRegen": "BonusStaminaRegen",
}
#: How much of a chest piece's budget each slot gets. A full five-piece suit is 3.25 chests.
SLOT_SHARE = {
    "Chest": 1.0, "Legs": 0.75, "Head": 0.6, "Hands": 0.45, "Feet": 0.45,
    "OffHand": 0.6, "MainHand": 0.5, "Ring": 0.5, "Amulet": 0.6, "Ammo": 0.2,
}
#: A two-hander fills both hands, so it gets a main hand and most of an off hand.
TWO_HANDED_SHARE = 1.6
RARITY_FACTOR = {"Common": 1.0, "Uncommon": 1.1, "Rare": 1.25, "Epic": 1.4, "Legendary": 1.6}
#: How far a written item may sit from its budget: a quarter, or one rounding grain on a tiny budget.
BUDGET_TOLERANCE = 0.25
BUDGET_GRAIN = 1.6


def budget_points(item_level, slot, two_handed, rarity):
    """The stat points an equippable of this level, slot and rarity spends.

    A chest piece gets 6 + 0.9 per item level (10.5 at level 5, 48.3 at level 47); every other slot
    a share of that; rarity scales it. With the armour allocations below, a full heavy suit and
    shield reaches about 185 Armor at item level 47, a medium suit about 120 and a light one about
    70, on the 100 / (100 + armour) curve the damage pipeline already uses.
    """
    share = SLOT_SHARE[slot] * (TWO_HANDED_SHARE if two_handed else 1.0)
    return (6.0 + 0.9 * item_level) * share * RARITY_FACTOR[rarity]


#: Sword-equivalent damage multiplier per weapon class (WeaponResource.BaseDamage).
CLASS_DAMAGE = {
    "Sword": 1.0, "Dagger": 0.72, "Axe": 1.12, "Mace": 1.08, "Spear": 0.95,
    "Staff": 0.8, "Greatsword": 1.6, "Bow": 1.12,
}


def weapon_damage(item_level, weapon_class, rarity):
    """WeaponResource.BaseDamage: 12 + 0.62 per item level for a sword (the Steel Sword's 20 at
    level 14), times the class multiplier, plus 4% per rarity step above Common."""
    return (12.0 + 0.62 * item_level) * CLASS_DAMAGE[weapon_class] * (1.0 + 0.04 * RARITIES.index(rarity))


VALUE_RARITY = {"Common": 1.0, "Uncommon": 1.25, "Rare": 1.8, "Epic": 2.6, "Legendary": 4.0}
VALUE_SLOT = {
    "Chest": 1.0, "Legs": 0.8, "Head": 0.7, "Hands": 0.55, "Feet": 0.55,
    "MainHand": 1.0, "OffHand": 0.8, "Ring": 0.9, "Amulet": 1.0, "Ammo": 0.04,
}


def item_value(item_level, rarity, slot):
    """ItemResource.Value of an equippable, in gold, from item level, rarity and slot alone.

    18 + 3.2 L + 0.06 L^2 is fitted to what main already sells (Iron Dagger 35 at level 5, Steel
    Sword 85 at 14, Drakescale Mail 420 at 28 Epic) and tops out near 1,300 for a level-50
    legendary: dear beside a 500-gold mercenary, never beyond what a late purse can reach. Above
    100 it rounds to the nearest 5.
    """
    raw = (18.0 + 3.2 * item_level + 0.06 * item_level * item_level) * VALUE_RARITY[rarity] * VALUE_SLOT[slot]
    if raw >= 100.0:
        return int(round(raw / 5.0)) * 5
    return max(1, int(round(raw)))


#: The school each realm's gear turns aside (tier -> StatType name). Storm-callers' cloth in the
#: Reach answers lightning instead of frost, so all six schools are worn somewhere.
REALM_RESIST = {1: "FireResist", 2: "FrostResist", 3: "NatureResist", 4: "FireResist", 5: "NecroticResist", 6: "ArcaneResist"}


def realm_resist(tier, armor_weight="None"):
    return "LightningResist" if tier == 2 and armor_weight == "Light" else REALM_RESIST[tier]


# Allocations: (stat, fraction of the budget). The FIRST stat is the primary: it takes whatever the
# rounding of the others leaves, so a written item always lands on its budget. "R" = realm resist.
ARMOR_ALLOC = {
    "Heavy": (("Armor", 0.70), ("Health", 0.15), ("R", 0.15)),
    "Medium": (("Armor", 0.50), ("Stamina", 0.20), ("CritChance", 0.15), ("R", 0.15)),
    "Light": (("Armor", 0.30), ("Mana", 0.30), ("SpellPower", 0.25), ("R", 0.15)),
}
WEAPON_ALLOC = {
    "Sword": (("PhysicalPower", 1.0),),
    "Dagger": (("PhysicalPower", 0.5), ("CritChance", 0.5)),
    "Axe": (("PhysicalPower", 1.0),),
    "Mace": (("PhysicalPower", 0.8), ("Health", 0.2)),
    "Spear": (("PhysicalPower", 0.7), ("Stamina", 0.3)),
    "Staff": (("SpellPower", 0.7), ("Mana", 0.3)),
    "Greatsword": (("PhysicalPower", 0.85), ("Health", 0.15)),
    "Bow": (("PhysicalPower", 0.6), ("CritChance", 0.4)),
    "Shield": (("Armor", 0.8), ("Health", 0.2)),
}
RING_ALLOC = {
    1: (("Stamina", 1.0),),
    2: (("Mana", 0.5), ("SpellPower", 0.5)),
    3: (("PhysicalPower", 0.6), ("CritChance", 0.4)),
    4: (("Armor", 0.5), ("Health", 0.5)),
    5: (("SpellPower", 0.6), ("ManaRegen", 0.4)),
    6: (("PhysicalPower", 0.4), ("SpellPower", 0.4), ("CritChance", 0.2)),
}
AMULET_SECOND = {1: "Health", 2: "Stamina", 3: "Health", 4: "Mana", 5: "Health", 6: "Mana"}
#: Items whose stats are their own idea rather than their slot's.
ALLOC_OVERRIDE = {
    "item.amulet.wildheart_totem": (("NatureResist", 0.6), ("Health", 0.4)),
    "item.ring.wildheart_band": (("Health", 0.5), ("Stamina", 0.5)),
    "item.ring.unmakers_signet": (("PhysicalPower", 0.5), ("CritChance", 0.3), ("NecroticResist", 0.2)),
    "item.ring.last_ember": (("PhysicalPower", 0.5), ("Health", 0.3), ("FireResist", 0.2)),
    "item.amulet.sages_reservoir": (("Mana", 0.5), ("SpellPower", 0.3), ("ManaRegen", 0.2)),
    "item.amulet.magpies_charm": (("Stamina", 0.4), ("CritChance", 0.4), ("MoveSpeed", 0.2)),
    "item.armor.windrunner_treads": (("Armor", 0.45), ("Stamina", 0.2), ("MoveSpeed", 0.2), ("R", 0.15)),
    "item.armor.hollow_diadem": (("Mana", 0.4), ("Armor", 0.2), ("SpellPower", 0.25), ("ManaRegen", 0.15)),
}


def allocation(e):
    if e["id"] in ALLOC_OVERRIDE:
        alloc = ALLOC_OVERRIDE[e["id"]]
    elif e["slot"] == "Ammo":
        alloc = (("PhysicalPower", 1.0),)
    elif e["slot"] == "Ring":
        alloc = RING_ALLOC[e["tier"]]
    elif e["slot"] == "Amulet":
        alloc = (("R", 0.6), (AMULET_SECOND[e["tier"]], 0.4))
    elif e["weapon_class"] != "None":
        alloc = WEAPON_ALLOC[e["weapon_class"]]
    else:
        alloc = ARMOR_ALLOC[e["armor_weight"]]
    return tuple((realm_resist(e["tier"], e["armor_weight"]) if s == "R" else s, f) for s, f in alloc)


def snap(stat, value):
    step = STAT_STEP.get(stat, 1.0)
    return round(round(value / step) * step, 4)


def score(stats):
    return sum(STAT_WEIGHT[s] * v for s, v in stats.items())


def stat_block(e):
    """The stats an equippable carries: every secondary stat rounded to its grain, then the primary
    given whatever is left of the budget (at least one grain), so the total lands on the budget."""
    budget = budget_points(e["item_level"], e["slot"], e["two_handed"], e["rarity_floor"])
    alloc = allocation(e)
    stats = {}
    for stat, fraction in alloc[1:]:
        value = snap(stat, budget * fraction / STAT_WEIGHT[stat])
        if value > 0:
            stats[stat] = value
    primary = alloc[0][0]
    left = budget - score(stats)
    stats[primary] = max(STAT_STEP.get(primary, 1.0), snap(primary, left / STAT_WEIGHT[primary]))
    off = abs(score(stats) - budget)
    assert off <= max(BUDGET_TOLERANCE * budget, BUDGET_GRAIN), (e["id"], stats, budget)
    return stats


# ---------------------------------------------------------------------------------------------
# Weapons. Timings are copied from the closest existing weapon (SteelSword, IronDagger, HuntingBow)
# and bent per class: two-handers wind up longer, cost more and hit harder; daggers the opposite.
# ---------------------------------------------------------------------------------------------

#: class -> ordered WeaponResource fields after BaseDamage. PoiseDamage is the tier-1 figure.
WEAPON_PROFILE = {
    "Sword": dict(PoiseDamage=28.0, StaminaCost=15.0, WindupTime=0.18, ActiveTime=0.12, RecoveryTime=0.3,
                  AttackSpeed=0.95, ComboLength=3, FinisherMultiplier=1.7, HeavyDamageScale=2.1,
                  MaxChargeSeconds=1.0, PlungeDamageScale=1.6),
    "Dagger": dict(PoiseDamage=9.0, StaminaCost=8.0, WindupTime=0.1, ActiveTime=0.09, RecoveryTime=0.18,
                   AttackSpeed=1.35, ComboLength=3, FinisherMultiplier=1.5, RecoveryCommit=0.2,
                   FinisherRecoveryCommit=0.45, HeavyDamageScale=1.6, HeavyPoiseScale=1.8,
                   HeavyStaminaMultiplier=2.0, MaxChargeSeconds=0.7, ChargeDamageBonus=0.6),
    "Axe": dict(PoiseDamage=36.0, StaminaCost=17.0, WindupTime=0.22, ActiveTime=0.13, RecoveryTime=0.34,
                AttackSpeed=0.9, ComboLength=3, FinisherMultiplier=1.8, HeavyDamageScale=2.2,
                MaxChargeSeconds=1.0, PlungeDamageScale=1.7),
    "Mace": dict(PoiseDamage=46.0, StaminaCost=18.0, WindupTime=0.24, ActiveTime=0.13, RecoveryTime=0.36,
                 AttackSpeed=0.85, ComboLength=2, FinisherMultiplier=1.8, HeavyDamageScale=2.0,
                 HeavyPoiseScale=2.8, MaxChargeSeconds=1.1, PlungeDamageScale=1.7),
    "Spear": dict(PoiseDamage=22.0, StaminaCost=13.0, WindupTime=0.2, ActiveTime=0.14, RecoveryTime=0.28,
                  AttackSpeed=1.0, ComboLength=3, FinisherMultiplier=1.6, HeavyDamageScale=2.0,
                  MaxChargeSeconds=0.9, PlungeDamageScale=1.8),
    "Staff": dict(PoiseDamage=24.0, StaminaCost=14.0, WindupTime=0.22, ActiveTime=0.14, RecoveryTime=0.34,
                  AttackSpeed=0.9, ComboLength=2, FinisherMultiplier=1.6, HeavyDamageScale=1.9,
                  MaxChargeSeconds=1.0, PlungeDamageScale=1.5),
    "Greatsword": dict(PoiseDamage=60.0, StaminaCost=24.0, WindupTime=0.34, ActiveTime=0.16, RecoveryTime=0.48,
                       AttackSpeed=0.75, ComboLength=2, FinisherMultiplier=1.8, FinisherRecoveryCommit=0.8,
                       HeavyDamageScale=2.2, HeavyPoiseScale=2.6, MaxChargeSeconds=1.3, PlungeDamageScale=1.8),
}
#: The Hunting Bow's single link, verbatim: a bow does not combo and never warps.
BOW_ACTION = [
    'Id = "bow.loose"', "Kind = 6", 'AnimationSlot = "attack"', "Duration = 1.35", "FallbackDuration = 1.35",
    "ActiveFrom = 0.64", "ActiveTo = 0.7", "CancelFrom = 0.78", "ComboFrom = 1.0", "ComboTo = 1.0",
    'NextActionId = ""', "Interruptible = true", "MoveScale = 0.45", "TurnDegreesPerSecond = -1.0",
    "StaminaCost = 4.0", "DamageScale = 1.0", "PoiseScale = 1.0", "RootMotion = 0", "HitStopScale = 0.6",
    "CameraImpulse = 0.15", 'SwingCueId = "sfx.combat.swing"', "AiWeight = 1.0", "AiMinRange = 4.0",
    "AiMaxRange = 26.0", "AiRecoverySeconds = 0.9",
]

# ---------------------------------------------------------------------------------------------
# Words. Grid gear is "<what the piece is> <what it is made of>"; named gear has its own line.
# No em-dashes in player text, and the fifth realm is never named.
# ---------------------------------------------------------------------------------------------

MATERIAL_TEXT = {
    "Iron": "Plain bloomery iron from the Ember Crown's forges, dark with oil.",
    "Steel": "Reach steel, quenched in meltwater and ground to a hard grey shine.",
    "Blacksteel": "Blacksteel folded with grave dust in the Ashen Wilds. It gives back no light.",
    "Sunsteel": "Sunsteel the colour of late afternoon, still warm long after dusk.",
    "Moonsilver": "Moonsilver, cold and bright, worked where no forge-light shows.",
    "Starmetal": "Starmetal beaten from fallen sky-iron. It hums faintly when struck.",
    "Oak": "Seasoned Ember Crown oak, cut straight along the grain.",
    "Frostpine": "Frostpine from the high Reach, slow-grown and springy with cold.",
    "Cinderwood": "Cinderwood that outlived the burning of the Wilds, black-barked and iron-hard.",
    "Goldenpalm": "Goldenpalm heartwood, supple and bright, oiled against the desert air.",
    "Gloamwood": "Gloamwood cut at dusk, grey as old smoke and nearly weightless.",
    "Starwood": "Starwood from the high places, silver-veined and faintly warm in the hand.",
    "Homespun": "Undyed homespun, mended more than once.",
    "Frostwool": "Thick Reach frostwool, felted against the wind.",
    "Ashweave": "Ashweave, grey thread spun with cinder so that sparks die on it.",
    "Sunsilk": "Sunsilk from the Dominion's looms, light as breath and bright as brass.",
    "Gloamweave": "Gloamweave, dyed at twilight so the eye slides off it.",
    "Starweave": "Starweave, cool to the touch, with a faint glimmer in the weft.",
    "Rawhide": "Stiff rawhide, cured over a smoky fire.",
    "Frosthide": "Frosthide from the Reach's white herds, thick-furred at the seams.",
    "Ashhide": "Ashhide, scorched grey and tougher for it.",
    "Dunehide": "Dunehide, sand-scoured and supple, the colour of a dry riverbed.",
    "Duskhide": "Duskhide, soft and dark, that makes no sound when it folds.",
    "Skyhide": "Skyhide, blue-grey and strangely light on the shoulders.",
}
PIECE_TEXT = {
    "Sword": "A straight, even blade that forgives a tired arm.",
    "Dagger": "Short, quick and easy to hide. It asks you to stand very close.",
    "Axe": "A bearded head on a stout haft, made to bite deep and pull free.",
    "Mace": "A flanged head that cares little for armour and less for finesse.",
    "Spear": "A leaf-bladed spear with a long reach and an honest point.",
    "Staff": "A walking staff shod at both ends, made to carry a spell as well as a traveller.",
    "Greatsword": "A two-handed blade as long as its bearer is tall. Every swing is a decision.",
    "Bow": "A long bow with a heavy draw and a clean release.",
    "Shield": "A broad shield with a domed boss, strapped for the forearm.",
    "Hood": "A deep hood that keeps weather and attention off the face.",
    "Robe": "A long robe with wide sleeves, cut to leave the hands free.",
    "Wraps": "Hand wraps wound tight from knuckle to elbow.",
    "Trousers": "Loose trousers gathered at the ankle.",
    "Shoes": "Soft-soled shoes that find quiet footing.",
    "Coif": "A fitted coif laced under the chin.",
    "Jerkin": "A sleeveless jerkin, close-fitted and easy to move in.",
    "Gloves": "Gloves with the fingertips worn thin for the bowstring.",
    "Breeches": "Breeches reinforced at knee and seat.",
    "Boots": "Tall boots with a good heel for bad ground.",
    "Helm": "An open-faced helm with a ridge down the crown.",
    "Cuirass": "A breast and back plate, buckled at the sides.",
    "Gauntlets": "Articulated gauntlets, lined with soft leather.",
    "Greaves": "Greaves shaped to the shin and strapped behind.",
    "Sabatons": "Plated sabatons that announce every step.",
    "Totem": "A carved totem on a braided cord.",
    "Band": "A ring of twisted root, still green at the core.",
}
NAMED_TEXT = {
    "item.ring.copper": "A plain copper band that turns the finger green and steadies the breath.",
    "item.ring.silver": "A silver band etched with a single unbroken line.",
    "item.ring.obsidian": "A ring cut whole from black glass, sharp at the inner edge.",
    "item.ring.gold": "A heavy gold ring, soft enough to take a tooth mark.",
    "item.ring.moonsilver": "A moonsilver band that is cold at noon and colder at night.",
    "item.ring.starmetal": "A starmetal ring that hums faintly against the knuckle.",
    "item.amulet.copper_charm": "A stamped copper disc on a thong, worn against embers and bad luck.",
    "item.amulet.silver_pendant": "A silver drop on a fine chain, cold against the breastbone.",
    "item.amulet.obsidian_talisman": "A thumb of black glass bound in wire, carried by those who walk the Wilds.",
    "item.amulet.gold_medallion": "A sun-faced medallion, worn smooth by generations of thumbs.",
    "item.amulet.moonsilver_locket": "A locket that will not open. Something inside shifts when you run.",
    "item.amulet.starmetal_torc": "An open collar of starmetal that rests as lightly as a hand on the neck.",
    "item.weapon.crownbreaker": "The maul-head that cracked the Iron King's crown, set on a new haft. It still rings like a bell.",
    "item.weapon.stormcleaver": "The Storm Tyrant's axe, cut down to mortal size. The edge crackles before rain.",
    "item.weapon.packlords_talon": "A claw from the Beast Lord's own hand, bound to a grip of his hide. It wants to be used.",
    "item.weapon.prophets_pyre": "The Crimson Prophet's staff. The ember at its head has never gone out.",
    "item.armor.hollow_diadem": "A circlet of grey silver from the Hollow Queen's brow. It weighs nothing and it is always cold.",
    "item.weapon.ashen_oath": "The Ashen Knight's blade, surrendered and not taken. It is heaviest when you are winning.",
    "item.ring.unmakers_signet": "A ring found where Morthul fell. The stone is a hole in the shape of a stone.",
    "item.armor.mirrorguard": "The Dawnwardens' honour shield, polished until a blow can see itself coming.",
    "item.weapon.farsight": "The Ash Hunters' master bow. They say its string was drawn from one patient thought.",
    "item.amulet.sages_reservoir": "A sealed vial from the Veiled Archive, worn at the throat. What is inside is not water.",
    "item.amulet.magpies_charm": "A holed coin on a cord, on loan from the Iron Syndicate. The luck is on loan too.",
    "item.weapon.emberpike": "A spear of the Emberbound whose point is held at forge heat by will alone.",
    "item.armor.windrunner_treads": "Boots so light that the grass stands back up behind you.",
    "item.armor.briarheart_cuirass": "A breastplate grown through with living thorn. It is kinder to the wearer than to anyone else.",
    "item.armor.gravetenders_grips": "The gloves of a keeper of the dead. What they close on gives a little of itself back.",
    "item.weapon.winters_bite": "A blade of Reach steel that never warms. Frost creeps down the fuller when it is drawn.",
    "item.ring.last_ember": "A ring holding one coal from the first fire. It burns brightest when everything else is going out.",
    "item.material.blacksteel_ingot": "Steel folded with charcoal and grave dust until it gives back no light.",
    "item.material.sunsteel_ingot": "Steel alloyed with emberbloom. It holds the warmth of the day.",
    "item.material.moonsilver_ingot": "Steel drawn through moonstone until it runs white and cold.",
    "item.material.starmetal_ingot": "Moonsilver remade with dust from the high places. It hums faintly.",
    "item.material.celestial_dust": "Fine bright dust swept from where the sky broke. It drifts upward if left alone.",
    "item.potion.health_greater": "A thick crimson draught that closes a wound while you watch.",
    "item.potion.health_superior": "A dark crimson draught that mends what should not mend this fast.",
    "item.potion.cure_lesser": "A bitter tonic that draws out burn and chill.",
    "item.potion.cure_greater": "A grey tonic that clears fire, frost, rot, stings and binding roots.",
    "item.potion.cure_superior": "A clear draught that ends every affliction at once.",
    "item.food.grilled_catch": "Lake fish split and charred over coals. Eaten hot, with fingers.",
    "item.food.hearth_stew": "Barley, herbs and whatever the pot was owed. It mends you slowly and thoroughly.",
    "item.food.oatcake": "A dense oatcake glazed with honey. A second wind you can carry in a pocket.",
    "item.food.eel_pie": "Salted eel under a thick crust. Tarn folk swear by it and are rarely wrong.",
    "item.food.spiced_roast": "Fish roasted in far-road spice. You feel sturdier for hours afterwards.",
    "item.food.frostfang_broth": "A fatty broth the Reach drinks before going out. The cold bites less.",
    "item.food.ember_tea": "Emberbloom steeped until the water glows. It clears the head and fills the well.",
    "item.food.roe_toast": "Tarn roe on toasted bread. Rich enough to keep your legs under you all day.",
}
SET_TEXT = {
    "set.emberguard": "Worn by the wall-watch of the Ember Crown, blackened by a hundred night fires.",
    "set.frostfang_hunter": "Kit of the Reach's lone hunters, stitched with wolf sinew.",
    "set.stormcaller": "Marked with the forked sign of those who call the storm down and live.",
    "set.ashen_reaver": "Taken up by the raiders of the burnt country. The scorch marks are a tally.",
    "set.wildheart": "Grown as much as made. Green things lean toward it.",
    "set.sunspire_templar": "Gilded plate of the Dominion's temple guard, polished to a blinding edge.",
    "set.gloamwarden": "Gear of the wardens who keep the dusk roads. It casts no clear shadow.",
    "set.starfall": "Woven from threads that fell with the stars. It remembers the sky.",
}
STRENGTH_TEXT = {"lesser": "A small measure.", "greater": "A full measure.", "superior": "A master's distillation."}
FAMILY_TEXT = {
    "stamina": "A sharp, salty draught that puts breath back in the lungs.",
    "mana": "A blue tincture that fills the well behind the eyes.",
    "might": "An iron-tasting elixir that puts weight behind every blow for a short while.",
    "insight": "A chalky elixir that sharpens the mind's edge for a short while.",
    "stoneskin": "A gritty elixir that toughens the skin like fired clay for a short while.",
}
SCHOOL_TEXT = {
    "fire": "flame", "frost": "cold", "lightning": "the storm", "arcane": "raw magic",
    "nature": "venom and thorn", "necrotic": "the grave's touch",
}


def description(e):
    if e["id"] in NAMED_TEXT:
        return NAMED_TEXT[e["id"]]
    leaf = e["id"].rsplit(".", 1)[1]
    if e["kind"] == "scroll":
        return "A craftsman's pattern for %s. Study it to learn the recipe." % e["name"][len("Recipe: "):]
    if e["kind"] == "consumable":
        family, strength = leaf.rsplit("_", 1)
        if family.startswith("resist_"):
            return "An elixir that hardens the body against %s for a few minutes. %s" % (
                SCHOOL_TEXT[family[len("resist_"):]], STRENGTH_TEXT[strength])
        return "%s %s" % (FAMILY_TEXT[family], STRENGTH_TEXT[strength])
    if e["slot"] == "Ammo":
        metal = e["name"].split(" ")[0]
        return "A wrap of arrows with %s heads. They fly truer and bite deeper than plain shafts." % metal.lower()
    noun = e["name"].rsplit(" ", 1)[1]
    if e["set_id"]:
        return "%s %s" % (PIECE_TEXT[noun], SET_TEXT[e["set_id"]])
    return "%s %s" % (PIECE_TEXT[noun], MATERIAL_TEXT[e["name"].split(" ")[0]])


# ---------------------------------------------------------------------------------------------
# Non-equippable prices. A crafted consumable never sells for more than 1.8x its ingredients' base
# value, so buying the makings at a counter and selling the result is always a loss.
# ---------------------------------------------------------------------------------------------

CONSUMABLE_VALUE = {
    "health_greater": 48, "health_superior": 110,
    "stamina_lesser": 12, "stamina_greater": 32, "stamina_superior": 120,
    "mana_lesser": 16, "mana_greater": 60, "mana_superior": 150,
    "cure_lesser": 18, "cure_greater": 36, "cure_superior": 95,
    "might_lesser": 14, "might_greater": 55, "might_superior": 120,
    "insight_lesser": 22, "insight_greater": 55, "insight_superior": 120,
    "stoneskin_lesser": 14, "stoneskin_greater": 55, "stoneskin_superior": 120,
    "grilled_catch": 10, "hearth_stew": 22, "oatcake": 9, "eel_pie": 26,
    "spiced_roast": 60, "frostfang_broth": 28, "ember_tea": 40, "roe_toast": 32,
}
RESIST_VALUE = {"lesser": 20, "greater": 50, "superior": 110}
MATERIAL_VALUE = {
    "item.material.blacksteel_ingot": 60, "item.material.sunsteel_ingot": 85,
    "item.material.moonsilver_ingot": 150, "item.material.starmetal_ingot": 420,
    "item.material.celestial_dust": 70,
}
SCROLL_VALUE = {2: 45, 3: 120, 4: 200, 5: 300, 6: 420}
POTION_MODEL = "res://assets/models/props/prp_item_potion.glb"
MODEL = {
    "Sword": "res://assets/models/weapons/wpn_sword_iron.glb",
    "Greatsword": "res://assets/models/weapons/wpn_greatsword_iron.glb",
    "Axe": "res://assets/models/weapons/wpn_axe_iron.glb",
    "Mace": "res://assets/models/weapons/wpn_mace_iron.glb",
    "Spear": "res://assets/models/weapons/wpn_spear_iron.glb",
    "Staff": "res://assets/models/weapons/wpn_staff_oak.glb",
    "Dagger": "res://assets/models/weapons/wpn_dagger_iron.glb",
    "Bow": "res://assets/models/weapons/wpn_bow_hunting.glb",
    "Shield": "res://assets/models/equipment/eqp_shield_round.glb",
}
WEAPON_WEIGHT = {"Sword": 3.5, "Dagger": 1.0, "Axe": 4.0, "Mace": 4.5, "Spear": 3.0, "Staff": 2.5,
                 "Greatsword": 6.0, "Bow": 2.0, "Shield": 4.5}
ARMOR_WEIGHT = {"Light": 2.0, "Medium": 5.0, "Heavy": 12.0}
FISH_DISHES = ("grilled_catch", "eel_pie", "spiced_roast", "frostfang_broth", "roe_toast")

# ---------------------------------------------------------------------------------------------
# .tres emit helpers
# ---------------------------------------------------------------------------------------------


def fnum(v):
    return repr(round(float(v), 6))


def num(v):
    v = round(v, 6)
    return str(int(v)) if v == int(v) else ("%g" % v)


def quote(text):
    return '"%s"' % text.replace("\\", "\\\\").replace('"', '\\"')


def strings(values):
    return "Array[String]([%s])" % ", ".join('"%s"' % v for v in values)


def pascal(leaf):
    return "".join(part.capitalize() for part in leaf.split("_"))


GRID_RINGS = ("copper", "silver", "obsidian", "gold", "moonsilver", "starmetal")


def file_stem(item_id):
    _, subcat, leaf = item_id.split(".")
    if subcat == "potion":
        return "Potion" + pascal(leaf)
    if subcat == "food":
        return "Food" + pascal(leaf)
    if subcat == "recipe_scroll":
        return "RecipeScroll" + pascal(leaf)
    if subcat == "ring" and leaf in GRID_RINGS:
        return pascal(leaf) + "Ring"
    return pascal(leaf)


def trade_tags(e):
    if e["kind"] == "scroll":
        return ["tome"]
    if e["kind"] == "material":
        return ["reagent", "arcane"] if e["id"].endswith("celestial_dust") else ["metal"]
    if e["kind"] == "consumable":
        leaf = e["id"].rsplit(".", 1)[1]
        if e["cooldown_group"] == "food":
            return ["food", "fish"] if leaf in FISH_DISHES else ["food"]
        return ["potion"]
    legendary = ["relic"] if e["rarity_floor"] == "Legendary" else []
    if e["slot"] in ("Ring", "Amulet"):
        return ["jewelry"] + legendary
    if e["slot"] == "Ammo":
        return ["weapon"]
    if e["weapon_class"] == "Shield":
        return ["armor", "metal"] + legendary
    if e["weapon_class"] in ("Staff", "Bow"):
        return (["weapon", "arcane"] if e["weapon_class"] == "Staff" else ["weapon"]) + legendary
    if e["weapon_class"] != "None":
        return ["weapon", "metal"] + legendary
    return ["armor", {"Heavy": "metal", "Medium": "leather", "Light": "textile"}[e["armor_weight"]]] + legendary


def world_model(e):
    if e["kind"] == "scroll":
        return "res://assets/models/props/prp_item_book.glb"
    if e["kind"] == "material":
        return "res://assets/models/props/prp_item_ingot.glb" if e["id"].endswith("_ingot") else ""
    if e["kind"] == "consumable":
        return "" if e["cooldown_group"] == "food" else POTION_MODEL
    if e["slot"] == "Ammo":
        return "res://assets/models/weapons/wpn_arrow.glb"
    if e["weapon_class"] in MODEL:
        return MODEL[e["weapon_class"]]
    if e["slot"] == "Chest" and e["armor_weight"] == "Heavy":
        return "res://assets/models/equipment/eqp_armor_mail.glb"
    if e["slot"] == "Chest" and e["armor_weight"] == "Medium":
        return "res://assets/models/equipment/eqp_armor_leather.glb"
    return ""


def base_fields(e, item_type, max_stack, weight, value):
    lines = [
        "Id = %s" % quote(e["id"]),
        "DisplayName = %s" % quote(e["name"]),
        "Description = %s" % quote(description(e)),
        "Type = %d" % TYPES.index(item_type),
        "Rarity = %d" % RARITIES.index(e["rarity_floor"]),
        "MaxStack = %d" % max_stack,
        "Weight = %s" % fnum(weight),
        "Value = %d" % value,
    ]
    model = world_model(e)
    if model:
        lines.append("WorldModelPath = %s" % quote(model))
    lines.append("TradeTags = %s" % strings(trade_tags(e)))
    if e["kind"] in ("equippable", "consumable"):
        lines.append("ItemLevel = %d" % e["item_level"])
    lines.append("Tier = %d" % e["tier"])
    if e["required_level"]:
        lines.append("RequiredLevel = %d" % e["required_level"])
    if e["set_id"]:
        lines.append("SetId = %s" % quote(e["set_id"]))
    if e["unique_effect_id"]:
        lines.append("UniqueEffectId = %s" % quote(e["unique_effect_id"]))
    return lines


def resource_text(script_class, script_path, ext, subs, lines):
    """One generated .tres: header, ext resources, the marker comment, sub resources, [resource]."""
    out = ['[gd_resource type="Resource" script_class="%s" format=3]' % script_class, "",
           '[ext_resource type="Script" path="%s" id="1_script"]' % script_path]
    out += ext
    out += ["", GENERATED, ""]
    for sid, body in subs:
        out.append('[sub_resource type="Resource" id="%s"]' % sid)
        out += body
        out.append("")
    out += ["[resource]", 'script = ExtResource("1_script")']
    out += lines
    return "\n".join(out) + "\n"


def weapon_tres(e):
    cls = e["weapon_class"]
    damage = float(int(round(weapon_damage(e["item_level"], cls, e["rarity_floor"]))))
    tier_scale = 1.0 + 0.04 * (e["tier"] - 1)
    lines = ["DisplayName = %s" % quote(e["name"]), "DamageType = 0", "BaseDamage = %s" % fnum(damage)]
    if cls == "Bow":
        lines += [
            "PoiseDamage = %s" % fnum(round(12.0 * tier_scale, 1)), "StaminaCost = 4.0",
            'Attacks = Array[ExtResource("2_action")]([SubResource("Loose")])',
            "WindupTime = 0.86", "ActiveTime = 0.08", "RecoveryTime = 0.41", "AttackSpeed = 1.0", "IsRanged = true",
            "ProjectileSpeed = %s" % fnum(42.0 + 2.0 * (e["tier"] - 1)), "ProjectileRange = 65.0",
            'ProjectileModelPath = "res://assets/models/weapons/wpn_arrow.glb"',
            "ComboLength = 1", "FinisherMultiplier = 1.0",
        ]
        ext = ['[ext_resource type="Script" path="res://src/Combat/Actions/ActionDefinitionResource.cs" id="2_action"]']
        subs = [("Loose", ['script = ExtResource("2_action")'] + BOW_ACTION)]
        return resource_text("WeaponResource", "res://src/Combat/WeaponResource.cs", ext, subs, lines)
    for field, value in WEAPON_PROFILE[cls].items():
        if field == "PoiseDamage":
            value = round(value * tier_scale, 1)
        lines.append("%s = %s" % (field, value if isinstance(value, int) else fnum(value)))
    return resource_text("WeaponResource", "res://src/Combat/WeaponResource.cs", [], [], lines)


def equippable_tres(e, stats):
    slot = e["slot"]
    value = item_value(e["item_level"], e["rarity_floor"], slot)
    if slot == "Ammo":
        item_type, stack, weight = "Weapon", 60, 0.05
    elif slot == "MainHand":
        item_type, stack, weight = "Weapon", 1, WEAPON_WEIGHT[e["weapon_class"]]
    elif slot == "OffHand":
        item_type, stack, weight = "Armor", 1, WEAPON_WEIGHT["Shield"]
    elif slot in ("Ring", "Amulet"):
        item_type, stack, weight = "Misc", 1, 0.1 if slot == "Ring" else 0.2
    else:
        item_type, stack, weight = "Armor", 1, round(ARMOR_WEIGHT[e["armor_weight"]] * SLOT_SHARE[slot], 1)
    lines = base_fields(e, item_type, stack, weight, value)
    lines.append("Slot = %d" % SLOTS.index(slot))
    ext = []
    if slot == "MainHand":
        ext.append('[ext_resource type="Resource" path="res://data/weapons/Player%s.tres" id="2_wpn"]' % file_stem(e["id"]))
        lines.append('Weapon = ExtResource("2_wpn")')
    for stat in BONUS_FIELD:  # fixed order, so a retune never reshuffles a file
        if stat in stats:
            lines.append("%s = %s" % (BONUS_FIELD[stat], fnum(stats[stat])))
    if e["two_handed"]:
        lines.append("TwoHanded = true")
    if e["weapon_class"] != "None":
        lines.append("WeaponClass = %d" % CLASSES.index(e["weapon_class"]))
    if e["armor_weight"] != "None":
        lines.append("ArmorWeight = %d" % WEIGHTS.index(e["armor_weight"]))
    return resource_text("EquippableItemResource", "res://src/Items/EquippableItemResource.cs", ext, [], lines)


def consumable_value(e):
    leaf = e["id"].rsplit(".", 1)[1]
    if leaf.startswith("resist_"):
        return RESIST_VALUE[leaf.rsplit("_", 1)[1]]
    return CONSUMABLE_VALUE[leaf]


def consumable_tres(e):
    food = e["cooldown_group"] == "food"
    lines = base_fields(e, "Consumable", 20 if food else 10, 0.4 if food else 0.5, consumable_value(e))
    lines.append("Effect = %d" % EFFECTS.index(e["effect"]))
    if e["magnitude"]:
        lines.append("Magnitude = %s" % fnum(e["magnitude"]))
    if e["duration"]:
        lines.append("DurationSeconds = %s" % fnum(e["duration"]))
    if e["effect"] == "Buff":
        lines.append("BuffStat = %d" % STATS.index(e["buff_stat"]))
        lines.append("BuffKind = %d" % MODS.index(e["buff_kind"]))
    if e["cure_status_ids"]:
        lines.append("CureStatusIds = %s" % strings(e["cure_status_ids"]))
    if e["cooldown"]:
        lines.append("CooldownSeconds = %s" % fnum(e["cooldown"]))
    if e["cooldown_group"]:
        lines.append("CooldownGroup = %s" % quote(e["cooldown_group"]))
    return resource_text("ConsumableItemResource", "res://src/Items/ConsumableItemResource.cs", [], [], lines)


def plain_tres(e):
    if e["kind"] == "material":
        lines = base_fields(e, "Material", 50, 0.1 if e["id"].endswith("dust") else 1.5, MATERIAL_VALUE[e["id"]])
    else:
        lines = base_fields(e, "Misc", 1, 0.2, SCROLL_VALUE[e["tier"]])
    return resource_text("ItemResource", "res://src/Items/ItemResource.cs", [], [], lines)


def unique_tres(fx):
    lines = ["Id = %s" % quote(fx["id"]), "NameKey = %s" % quote(fx["name_key"]),
             "DescriptionKey = %s" % quote(fx["description_key"]), "Kind = %d" % UNIQUE_KINDS.index(fx["kind"])]
    for field, key in (("Magnitude", "magnitude"), ("Chance", "chance"), ("Threshold", "threshold"),
                       ("DurationSeconds", "duration"), ("CooldownSeconds", "cooldown")):
        if fx[key] != (1.0 if key == "chance" else 0.0):
            lines.append("%s = %s" % (field, fnum(fx[key])))
    if fx["status_id"]:
        lines.append("StatusId = %s" % quote(fx["status_id"]))
    return resource_text("UniqueEffectResource", "res://src/Items/UniqueEffectResource.cs", [], [], lines)


def set_tres(s):
    subs = []
    for pieces, stat, value, mod, effect in s["bonuses"]:
        body = ['script = ExtResource("2_bonus")', "PiecesRequired = %d" % pieces]
        if stat:
            body += ["Stat = %d" % STATS.index(stat), "Value = %s" % fnum(value), "ModifierType = %d" % MODS.index(mod)]
        if effect:
            body.append("EffectId = %s" % quote(effect))
        subs.append(("Bonus_%d" % (len(subs) + 1), body))
    ext = ['[ext_resource type="Script" path="res://src/Items/ItemSetBonusResource.cs" id="2_bonus"]']
    lines = ["Id = %s" % quote(s["id"]), "DisplayNameKey = %s" % quote(s["display_name_key"]),
             "PieceIds = %s" % strings(s["pieces"]),
             'Bonuses = Array[ExtResource("2_bonus")]([%s])' % ", ".join('SubResource("%s")' % sid for sid, _ in subs)]
    return resource_text("ItemSetResource", "res://src/Items/ItemSetResource.cs", ext, subs, lines)


def unique_description(fx):
    """The tooltip line with the effect's own numbers baked in, so a retune cannot leave a stale one."""
    flat = fx["kind"] in ("DodgeRefund", "ThornsFlat")
    magnitude = num(fx["magnitude"]) if flat else num(fx["magnitude"] * 100) + "%"
    return fx["desc"].format(magnitude, num(fx["chance"] * 100) + "%", num(fx["threshold"] * 100) + "%",
                             num(fx["duration"]), num(fx["cooldown"]))


# ---------------------------------------------------------------------------------------------
# Where it is sold. Rows are (item id, quantity, gate) spliced into the named shop's Stock; a gate
# is {"flag": ...}, {"tier": ReputationTier name} or {"invest": n}. Every shop in the game stands
# in the Ember Crown or the Ashen Wilds, so later tiers open behind the Flamebearer who guards the
# road to them, never behind a price alone. No row authors a price: Value x the shop's markup is
# the one price authority.
# ---------------------------------------------------------------------------------------------

AFTER = {  # tier -> the flag that opens that tier's wares
    2: "flag.iron_king_defeated", 3: "flag.storm_tyrant_defeated", 4: "flag.beast_lord_defeated",
    5: "flag.crimson_prophet_defeated", 6: "flag.hollow_queen_defeated",
}


def gate(tier):
    return {"flag": AFTER[tier]} if tier in AFTER else {}


def scroll(leaf):
    return "item.recipe_scroll." + leaf


SCHOOLS = [s.lower() for s in C.RESIST_SCHOOLS]
SHOP_STOCK = {
    "EmberCrownSmith": (
        [("item.weapon.iron_sword", 1, {}), ("item.weapon.iron_axe", 1, {}), ("item.weapon.iron_mace", 1, {}),
         ("item.weapon.iron_greatsword", 1, {}), ("item.armor.iron_helm", 1, {}), ("item.armor.iron_cuirass", 1, {}),
         ("item.armor.iron_gauntlets", 1, {}), ("item.armor.iron_greaves", 1, {}), ("item.armor.iron_sabatons", 1, {}),
         ("item.weapon.steel_axe", 1, gate(2)), ("item.weapon.steel_greatsword", 1, gate(2)),
         ("item.armor.steel_cuirass", 1, gate(2)), ("item.armor.steel_shield", 1, gate(2)),
         ("item.ammo.steel_arrows", 40, gate(2)), ("item.ammo.blacksteel_arrows", 40, gate(3)),
         ("item.ammo.sunsteel_arrows", 40, gate(4)), ("item.ammo.moonsilver_arrows", 40, gate(5)),
         ("item.ammo.starmetal_arrows", 40, gate(6)),
         ("item.armor.mirrorguard", 1, {"flag": "flag.dawnwardens.finale_service"})]),
    "EmbermarketIronmonger": (
        [("item.weapon.iron_spear", 1, {}), ("item.weapon.steel_dagger", 1, gate(2)),
         ("item.weapon.steel_mace", 1, gate(2)), ("item.weapon.steel_spear", 1, gate(2)),
         ("item.ammo.steel_arrows", 30, gate(2)),
         ("item.material.sunsteel_ingot", 2, gate(4)), ("item.material.moonsilver_ingot", 2, gate(5)),
         ("item.material.starmetal_ingot", 1, gate(6)),
         ("item.armor.mirrorguard", 1, {"flag": "flag.dawnwardens.finale_authority"})]),
    "EmbermarketTannery": (
        [("item.armor.rawhide_coif", 1, {}), ("item.armor.rawhide_jerkin", 1, {}), ("item.armor.rawhide_gloves", 1, {}),
         ("item.armor.rawhide_breeches", 1, {}), ("item.armor.rawhide_boots", 1, {}),
         ("item.armor.frosthide_jerkin", 1, gate(2)),
         (scroll("ashhide_jerkin"), 1, gate(3)), (scroll("dunehide_jerkin"), 1, gate(4)),
         (scroll("duskhide_jerkin"), 1, gate(5)), (scroll("skyhide_jerkin"), 1, gate(6)),
         ("item.weapon.farsight", 1, {"flag": "flag.ash_hunters.verdict_given"})]),
    "EmbermarketWeaver": (
        [("item.armor.homespun_hood", 1, {}), ("item.armor.homespun_robe", 1, {}), ("item.armor.homespun_wraps", 1, {}),
         ("item.armor.homespun_trousers", 1, {}), ("item.armor.homespun_shoes", 1, {}),
         ("item.armor.frostwool_robe", 1, gate(2)),
         (scroll("ashweave_robe"), 1, gate(3)), (scroll("sunsilk_robe"), 1, gate(4)),
         (scroll("gloamweave_robe"), 1, gate(5)), (scroll("starweave_robe"), 1, gate(6))]),
    "EmbermarketJoiner": (
        [("item.weapon.oak_staff", 1, {}), ("item.weapon.frostpine_bow", 1, gate(2)),
         ("item.weapon.frostpine_staff", 1, gate(2)),
         (scroll("cinderwood_bow"), 1, gate(3)), (scroll("cinderwood_staff"), 1, gate(3)),
         (scroll("goldenpalm_bow"), 1, gate(4)), (scroll("goldenpalm_staff"), 1, gate(4)),
         (scroll("gloamwood_bow"), 1, gate(5)), (scroll("gloamwood_staff"), 1, gate(5)),
         (scroll("starwood_bow"), 1, gate(6)), (scroll("starwood_staff"), 1, gate(6))]),
    "EmbermarketJeweller": (
        [("item.ring.copper", 1, {}), ("item.amulet.copper_charm", 1, {}),
         ("item.ring.silver", 1, gate(2)), ("item.amulet.silver_pendant", 1, gate(2)),
         ("item.ring.obsidian", 1, gate(3)), ("item.amulet.obsidian_talisman", 1, gate(3)),
         ("item.ring.gold", 1, gate(4)), ("item.amulet.gold_medallion", 1, gate(4))]),
    "EmbermarketScriptorium": (
        [(scroll("blacksteel_ingot"), 1, gate(3)), (scroll("blacksteel_sword"), 1, gate(3)),
         (scroll("blacksteel_cuirass"), 1, gate(3)), (scroll("blacksteel_arrows"), 1, gate(3)),
         (scroll("sunsteel_ingot"), 1, gate(4)), (scroll("sunsteel_sword"), 1, gate(4)),
         (scroll("sunsteel_cuirass"), 1, gate(4)),
         (scroll("moonsilver_ingot"), 1, gate(5)), (scroll("moonsilver_sword"), 1, gate(5)),
         (scroll("moonsilver_cuirass"), 1, gate(5)),
         (scroll("starmetal_ingot"), 1, gate(6)), (scroll("starmetal_sword"), 1, gate(6)),
         (scroll("starmetal_cuirass"), 1, gate(6)),
         ("item.amulet.sages_reservoir", 1, {"flag": "flag.veiled_archive.verdict_given"})]),
    "EmberCrownApothecary": (
        [("item.potion.stamina_lesser", 4, {}), ("item.potion.mana_lesser", 4, {}), ("item.potion.cure_lesser", 3, {}),
         ("item.potion.health_greater", 3, gate(3)),
         (scroll("health_greater"), 1, gate(3)), (scroll("stamina_greater"), 1, gate(3)),
         (scroll("mana_greater"), 1, gate(3)), (scroll("cure_greater"), 1, gate(3)),
         ("item.potion.health_superior", 2, gate(5)), ("item.potion.stamina_superior", 2, gate(5)),
         ("item.potion.mana_superior", 2, gate(5)), ("item.potion.cure_superior", 1, gate(5))]),
    "EmbermarketHerbalist": (
        [("item.potion.might_lesser", 2, {}), ("item.potion.insight_lesser", 2, {}),
         ("item.potion.stoneskin_lesser", 2, {}), ("item.food.ember_tea", 3, {})]
        + [("item.potion.resist_%s_lesser" % s, 2, {}) for s in SCHOOLS]
        + [("item.potion.might_superior", 1, gate(5)), ("item.potion.insight_superior", 1, gate(5)),
           ("item.potion.stoneskin_superior", 1, gate(5))]
        # A travelling stall may not be the only seller of a consumable (--validate), so the
        # resident herbalist carries the superior wards too.
        + [("item.potion.resist_%s_superior" % s, 1, gate(5)) for s in SCHOOLS]),
    "EmbermarketCurios": (
        [("item.potion.resist_%s_superior" % s, 1, gate(5)) for s in SCHOOLS]
        + [(scroll("health_superior"), 1, gate(5)), (scroll("stamina_superior"), 1, gate(5)),
           (scroll("mana_superior"), 1, gate(5)), (scroll("cure_superior"), 1, gate(5)),
           ("item.material.celestial_dust", 2, gate(6)),
           ("item.armor.gravetenders_grips", 1, gate(4)),
           ("item.weapon.emberpike", 1, {"flag": "flag.emberbound.verdict_given"})]),
    "LastHearthScavenger": (
        [("item.potion.health_greater", 3, {}), ("item.potion.stamina_greater", 2, {}),
         ("item.potion.mana_greater", 2, {}), ("item.potion.cure_greater", 2, {}),
         ("item.potion.might_greater", 1, {}), ("item.potion.insight_greater", 1, {}),
         ("item.potion.stoneskin_greater", 1, {})]
        + [("item.potion.resist_%s_greater" % s, 1, {}) for s in SCHOOLS]
        + [("item.ammo.steel_arrows", 30, {}), ("item.ammo.blacksteel_arrows", 30, {}),
           ("item.material.blacksteel_ingot", 2, {}),
           ("item.weapon.blacksteel_sword", 1, {}), ("item.armor.ashhide_jerkin", 1, {}),
           ("item.armor.briarheart_cuirass", 1, gate(4))]),
    "EmbermarketProvisions": (
        [("item.food.hearth_stew", 4, {}), ("item.food.oatcake", 6, {}),
         (scroll("frostfang_broth"), 1, gate(2)), (scroll("spiced_roast"), 1, gate(3)), (scroll("ember_tea"), 1, gate(3))]),
    "EmberdeepQuartermaster": ([("item.food.hearth_stew", 6, {}), ("item.food.oatcake", 8, {})]),
    "EmbermarketFishmonger": ([("item.food.grilled_catch", 5, {})]),
    "TarnCurer": ([("item.food.grilled_catch", 6, {}), ("item.food.eel_pie", 4, {}), ("item.food.roe_toast", 3, {}),
                   ("item.food.spiced_roast", 2, {}), ("item.food.frostfang_broth", 2, {})]),
    "EmbermarketCaravan": ([("item.food.spiced_roast", 2, {}), ("item.food.frostfang_broth", 2, {})]),
    "EmberCrownTraveller": (
        [("item.armor.windrunner_treads", 1, gate(2)),
         ("item.amulet.wildheart_totem", 1, gate(4)), ("item.ring.wildheart_band", 1, gate(4)),
         ("item.armor.wildheart_gloves", 1, gate(4))]),
    "HollowreachHull": (
        [("item.ring.moonsilver", 1, gate(5)), ("item.amulet.moonsilver_locket", 1, gate(5)),
         ("item.ring.starmetal", 1, gate(6)), ("item.amulet.starmetal_torc", 1, gate(6)),
         ("item.amulet.magpies_charm", 1, {"flag": "flag.iron_syndicate.verdict_given"}),
         ("item.ring.last_ember", 1, gate(6))]),
}

# The three shop gear pools, rolled at each restock (ShopStockService). Each grid item of the named
# tiers gets an entry at GRID_CHANCE; drop-sourced set pieces and the one drop legendary ride along
# as rare finds, unrolled (RollAffixes false keeps the template's own rarity).
POOLS = {
    "ShopLeveledGear": {"tiers": (1,), "grid": 0.07, "sets": 0.0},
    "TravellerLeveledGear": {"tiers": (2, 3), "grid": 0.045, "sets": 0.012},
    "EmbermarketCaravanGear": {"tiers": (4, 5, 6), "grid": 0.025, "sets": 0.012},
}
POOL_HEADER = """; Hesk's rolled shelf (ics): the wares of the two realms a wayfarer actually walks, the Reach and the
; Ashen Wilds. Entries are generated by tools/gen_items.py from tools/items/catalogue.py; the pool is
; non-stackable gear only, with no gold, for the reasons ShopLeveledGear.tres gives."""


def pool_entries(name):
    spec = POOLS[name]
    rows = []
    for e in C.EQUIPPABLES:
        if e["tier"] not in spec["tiers"] or e["slot"] == "Ammo":
            continue
        named = bool(e["set_id"] or e["unique_effect_id"])
        if not named:
            rows.append((e["id"], spec["grid"], True))
        elif e["source"] == "drop" and spec["sets"] > 0:
            rows.append((e["id"], spec["sets"], False))
    if name == "TravellerLeveledGear":  # tier-1 set pieces have no tier-1 pool that carries rare finds
        rows += [(e["id"], spec["sets"], False) for e in C.EQUIPPABLES if e["set_id"] == "set.emberguard"]
    return rows


# ---------------------------------------------------------------------------------------------
# Splicing rows into a hand-authored .tres
# ---------------------------------------------------------------------------------------------


def splice(text, script_file, array_prop, blocks):
    """Replaces every '<prefix>ics_*' sub resource of `text` with `blocks` ((id, body lines), ...)
    and rewrites the `array_prop` list to match. Everything else is left byte-for-byte alone."""
    ext = re.search(r'\[ext_resource type="Script" path="res://[^"]*/%s" id="([^"]+)"\]' % re.escape(script_file), text)
    if not ext and blocks:
        # A shop that stocked nothing has no entry script declared yet: declare it after the last ext.
        ids = re.findall(r'^\[ext_resource [^\]]*\]$', text, re.M)
        new_ext = '[ext_resource type="Script" path="res://src/Economy/%s" id="ics_entry"]' % script_file
        text = text.replace(ids[-1], ids[-1] + "\n" + new_ext, 1)
        ext = re.search(r'id="(ics_entry)"', text)
    text = re.sub(r'\[sub_resource type="Resource" id="[A-Za-z]+_%s[^"]*"\]\n(?:(?!\[)[^\n]+\n)*\n' % ICS, "", text)
    rendered = ""
    for sid, body in blocks:
        rendered += '[sub_resource type="Resource" id="%s"]\n' % sid
        rendered += 'script = ExtResource("%s")\n' % ext.group(1)
        rendered += "\n".join(body) + "\n\n"
    lines = text.split("\n")
    at = lines.index("[resource]")
    while at > 0 and lines[at - 1].startswith(";"):
        at -= 1
    text = "\n".join(lines[:at]) + ("\n" if at else "") + rendered + "\n".join(lines[at:])

    def relist(match):
        kept = [x for x in match.group(2).split(", ") if x and ("_" + ICS) not in x]
        kept += ['SubResource("%s")' % sid for sid, _ in blocks]
        return match.group(1) + ", ".join(kept) + match.group(3)

    text, count = re.subn(r"^(%s = Array\[Resource\]\(\[)(.*)(\]\))$" % array_prop, relist, text, flags=re.M)
    assert count == 1, "no %s list to splice into" % array_prop
    steps = len(re.findall(r"^\[(?:ext|sub)_resource ", text, re.M)) + 1
    return re.sub(r"load_steps=\d+", "load_steps=%d" % steps, text, count=1)


def shop_blocks(rows):
    blocks = []
    for item_id, quantity, lock in rows:
        assert item_id in C.ITEMS_BY_ID, "SHOP_STOCK names %s, which the catalogue does not plan" % item_id
        body = ["ItemId = %s" % quote(item_id), "Quantity = %d" % quantity]
        if "tier" in lock:
            body.append("RequiredTier = %d" % REPUTATION.index(lock["tier"]))
        if "flag" in lock:
            body.append("RequiredFlagId = %s" % quote(lock["flag"]))
        if "invest" in lock:
            body.append("RequiredInvestment = %d" % lock["invest"])
        blocks.append(("Stock_%s%d" % (ICS, len(blocks) + 1), body))
    return blocks


def pool_blocks(rows):
    return [("Entry_%s%d" % (ICS, i + 1),
             ["ItemId = %s" % quote(item_id), "DropChance = %s" % fnum(chance), "MinQuantity = 1", "MaxQuantity = 1",
              "RollAffixes = %s" % ("true" if roll else "false")])
            for i, (item_id, chance, roll) in enumerate(rows)]


def new_pool_text():
    return "\n".join([
        '[gd_resource type="Resource" script_class="LootTable" format=3]', "",
        '[ext_resource type="Script" path="res://src/Loot/LootTable.cs" id="1_table"]',
        '[ext_resource type="Script" path="res://src/Loot/LootEntry.cs" id="2_entry"]', "",
        POOL_HEADER, "", "[resource]", 'script = ExtResource("1_table")', "Entries = Array[Resource]([])",
        'GoldItemId = "item.currency.gold"', "GoldChance = 0.0", "GoldMin = 0", "GoldMax = 0", "QualityBonus = 0.0", ""])


RETROFIT_KEYS = ("ItemLevel", "Tier", "TwoHanded", "WeaponClass", "ArmorWeight")


def retrofit(text, fields):
    """Stamps the classification fields onto an existing item, appended to its [resource] section."""
    lines = [l for l in text.rstrip("\n").split("\n") if l.split(" = ")[0] not in RETROFIT_KEYS]
    lines += ["ItemLevel = %d" % fields["item_level"], "Tier = %d" % fields["tier"]]
    if fields["two_handed"]:
        lines.append("TwoHanded = true")
    if fields["weapon_class"] != "None":
        lines.append("WeaponClass = %d" % CLASSES.index(fields["weapon_class"]))
    if fields["armor_weight"] != "None":
        lines.append("ArmorWeight = %d" % WEIGHTS.index(fields["armor_weight"]))
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------------------------
# Locale and the C# id lists
# ---------------------------------------------------------------------------------------------


def csv_cell(text):
    return '"%s"' % text.replace('"', '""') if any(c in text for c in ',"\n') else text


def build_locale(existing):
    lines = [MARK_BEGIN,
             "# Item sets and unique effects. Generated by tools/gen_items.py from tools/items/catalogue.py."]
    for s in C.SETS:
        lines.append("%s,%s" % (s["display_name_key"], csv_cell(s["name"][:-2] if s["name"].endswith("'s") else s["name"])))
    for fx in C.UNIQUE_EFFECTS:
        lines.append("%s,%s" % (fx["name_key"], csv_cell(fx["name"])))
        lines.append("%s,%s" % (fx["description_key"], csv_cell(unique_description(fx))))
    lines.append(MARK_END)
    sep = "\r\n" if "\r\n" in existing else "\n"  # strings.csv is CRLF; an LF block would never settle
    assert MARK_BEGIN in existing, "strings.csv has no ics:content block"
    return re.sub(re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END), lambda _: sep.join(lines), existing, flags=re.S)


def cs_list(name, summary, values):
    out = ["    /// <summary>%s</summary>" % summary,
           "    public static readonly IReadOnlyList<string> %s = new[]" % name, "    {"]
    out += ['        "%s",' % v for v in values]
    out.append("    };")
    return out


def build_validator(existing):
    lines = [CS_BEGIN]
    lines += cs_list("ItemIds", "Every item tools/items/catalogue.py plans, in catalogue order.", [e["id"] for e in C.ITEMS])
    lines.append("")
    lines += cs_list("SetIds", "Every planned item set.", C.SET_IDS)
    lines.append("")
    lines += cs_list("UniqueEffectIds", "Every planned unique effect.", C.UNIQUE_EFFECT_IDS)
    lines.append("")
    lines += cs_list("BossSignatureIds", "The legendary each Flamebearer drops; boss-owned, so nothing sells them.",
                     sorted(C.BOSS_SIGNATURE.values()))
    lines.append(CS_END)
    assert CS_BEGIN in existing, "ItemValidator.Content.cs has no generated block"
    # C# is checked out with the platform's endings (autocrlf), so the block follows the file's.
    sep = "\r\n" if "\r\n" in existing else "\n"
    return re.sub(re.escape(CS_BEGIN) + r".*?" + re.escape(CS_END), lambda _: sep.join(lines), existing, flags=re.S)


# ---------------------------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------------------------


def read(path):
    return io.open(path, encoding="utf-8", newline="").read() if os.path.exists(path) else None


def existing_item_files():
    """id -> path of every hand-authored item (anything in data/items without the marker)."""
    found = {}
    for name in sorted(os.listdir(ITEM_DIR)):
        if name.endswith(".tres"):
            text = read(os.path.join(ITEM_DIR, name))
            if GENERATED not in text:
                found[re.search(r'^Id = "([^"]+)"', text, re.M).group(1)] = os.path.join(ITEM_DIR, name)
    return found


def build():
    problems = C.validate()
    assert not problems, problems
    wanted = {}   # path -> full text of a file this generator owns outright
    edited = {}   # path -> new text of a hand-authored file it splices into
    hand = existing_item_files()

    for e in C.ITEMS:
        path = os.path.join(ITEM_DIR, file_stem(e["id"]) + ".tres")
        assert path not in hand.values() and path not in wanted, "file name collision: " + path
        if e["kind"] == "equippable":
            wanted[path] = equippable_tres(e, stat_block(e))
            if e["slot"] == "MainHand":
                wanted[os.path.join(WEAPON_DIR, "Player%s.tres" % file_stem(e["id"]))] = weapon_tres(e)
        elif e["kind"] == "consumable":
            wanted[path] = consumable_tres(e)
        else:
            wanted[path] = plain_tres(e)

    for fx in C.UNIQUE_EFFECTS:
        wanted[os.path.join(UNIQUE_DIR, pascal(fx["id"].split(".", 1)[1]) + ".tres")] = unique_tres(fx)
    for s in C.SETS:
        wanted[os.path.join(SET_DIR, pascal(s["id"].split(".", 1)[1]) + ".tres")] = set_tres(s)

    for item_id, fields in C.EXISTING_RETROFIT.items():
        edited[hand[item_id]] = retrofit(read(hand[item_id]), fields)

    for name, rows in SHOP_STOCK.items():
        path = os.path.join(SHOP_DIR, name + ".tres")
        edited[path] = splice(read(path), "ShopStockEntry.cs", "Stock", shop_blocks(rows))
    for name in POOLS:
        path = os.path.join(LOOT_DIR, name + ".tres")
        edited[path] = splice(read(path) or new_pool_text(), "LootEntry.cs", "Entries", pool_blocks(pool_entries(name)))

    edited[CSV] = build_locale(read(CSV))
    edited[VALIDATOR] = build_validator(read(VALIDATOR))
    return wanted, edited


def stale_files(wanted):
    """Marked files the catalogue no longer names. Unmarked (hand-authored) files are never listed."""
    stale = []
    for folder in (ITEM_DIR, WEAPON_DIR, UNIQUE_DIR, SET_DIR):
        if not os.path.isdir(folder):
            continue
        for name in sorted(os.listdir(folder)):
            full = os.path.join(folder, name)
            if name.endswith(".tres") and full not in wanted and GENERATED in read(full):
                stale.append(full)
    return stale


def main():
    check = "--check" in sys.argv
    wanted, edited = build()
    changed = []
    for path, text in list(wanted.items()) + list(edited.items()):
        if read(path) != text:
            changed.append(path)
            if not check:
                if not os.path.isdir(os.path.dirname(path)):
                    os.makedirs(os.path.dirname(path))
                io.open(path, "w", encoding="utf-8", newline="").write(text)
    for path in stale_files(wanted):
        changed.append(path)
        if not check:
            os.remove(path)

    summary = "%d items (%d equippable, %d consumable, %d material, %d scroll), %d sets, %d unique effects" % (
        len(C.ITEMS), len(C.EQUIPPABLES), len(C.CONSUMABLES), len(C.NEW_MATERIALS), len(C.RECIPE_SCROLLS),
        len(C.SETS), len(C.UNIQUE_EFFECTS))
    if check:
        for c in changed:
            print("WOULD CHANGE", os.path.relpath(c, ROOT))
        print("%s; %d file(s) out of date" % (summary, len(changed)))
        return 1 if changed else 0
    print("%s; wrote %d file(s)" % (summary, len(changed)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
