#!/usr/bin/env python3
"""Author the planned recipes (ics crafting lane) from tools/items/catalogue.py.

One table, catalogue.PLANNED_RECIPES, generates four things that MUST agree, so they cannot drift:

  1. data/recipes/<Name>.tres            one CraftingRecipeResource per planned recipe
  2. data/locale/strings.csv             <recipe id>.name for EVERY recipe (the 15 hand-authored ones
                                         included), inside '# --- BEGIN ics:crafting:recipes ---'
  3. data/services/EmberCrownTrainer.tres   its TaughtRecipeIds line
  4. (checked, not written) src/Core/GameIds.cs   Recipes.Starting must seed exactly the old list
                                         plus every recipe whose discovery is "known"

The 15 recipes main already ships are hand-authored and are NEVER written: the generator reads them
(for their names, and for the commission check) and leaves the files alone.

Discovery, as the game can express it today
-------------------------------------------
ContentValidator.ValidateRecipeReachability accepts two routes only: GameIds.Recipes.Starting, or a
ServiceKind.Trainer that lists the recipe (never both). So:
  "known"    -> Recipes.Starting
  "trainer"  -> the Ember Crown trainer's list
  "scroll"   -> the Ember Crown trainer's list AS WELL, and the recipe's ScrollItemId names the
                item.recipe_scroll.* that also teaches it (CraftingComponent.StudyScroll)
A recipe above tier 1 additionally needs a crafting rank before the player's own hands can make it
(CraftingSkill.RequiredRank), so knowing a recipe and being able to craft it are separate gates.

The commission check
--------------------
ContentValidator.ValidateCommission fails --validate when "buy every material from the master, have
him make the piece, sell it" pays for itself. No lane can run --validate, so --check restates that
inequality here from the same data: the service's labour at Allied standing with the best perk, each
ingredient at the master's cheapest counter price, the output at the keenest buyer's best day. Item
values come from data/items/*.tres; an item the content lane has not generated yet is priced from
PRICE_GUIDE (and listed as such), so the check stays meaningful before and after the merge.

Enum ordinals are read from the C# sources (a .tres stores an enum as its index).

Idempotent. Usage:  python tools/gen_recipes.py [--check] [--report]
        --check   exits 1 if anything would change or any rule fails, without writing
        --report  also prints the commission table (cost, best sale, the highest safe output value)
"""

import io
import math
import os
import re
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools", "items"))
import catalogue  # noqa: E402  (pure data; importing it reads and writes nothing)

RECIPE_DIR = os.path.join(ROOT, "data", "recipes")
ITEM_DIR = os.path.join(ROOT, "data", "items")
SHOP_DIR = os.path.join(ROOT, "data", "shops")
SERVICE_DIR = os.path.join(ROOT, "data", "services")
REGION_DIR = os.path.join(ROOT, "data", "regions")
CSV = os.path.join(ROOT, "data", "locale", "strings.csv")
TRAINER = os.path.join(SERVICE_DIR, "EmberCrownTrainer.tres")
GAME_IDS = os.path.join(ROOT, "src", "Core", "GameIds.cs")

LANE_END = "# --- END ics:crafting ---"
MARK_BEGIN = "# --- BEGIN ics:crafting:recipes (generated by tools/gen_recipes.py; do not edit by hand) ---"
MARK_END = "# --- END ics:crafting:recipes ---"

#: The trainer recipes main already taught before this generator existed; they stay first in its list.
TRAINER_EXISTING = ("recipe.drakescale_mail",)

#: What GameIds.Recipes.Starting seeded before this generator existed.
STARTING_EXISTING = (
    "recipe.iron_ingot", "recipe.leather_strips", "recipe.health_potion", "recipe.leather_cap",
    "recipe.steel_sword", "recipe.leather_vest", "recipe.iron_ring",
    "recipe.kit.forge", "recipe.kit.workbench", "recipe.kit.alchemy", "recipe.kit.brazier",
    "recipe.kit.crate", "recipe.kit.banner", "recipe.kit.display_stand",
)


def read(path):
    return io.open(path, encoding="utf-8", newline="").read()


def enum_members(rel_path, name):
    """Member names of `enum <name>` in a C# file, in declaration order (= the stored ordinal)."""
    text = read(os.path.join(ROOT, rel_path))
    body = re.search(r"enum\s+" + name + r"\s*\{(.*?)\n\}", text, re.S).group(1)
    body = re.sub(r"//[^\n]*", "", body)
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    return [m.strip().split("=")[0].strip() for m in body.split(",") if m.strip()]


STATIONS = enum_members("src/Crafting/CraftingStationType.cs", "CraftingStationType")
RARITIES = enum_members("src/Items/ItemType.cs", "ItemRarity")
SERVICE_KINDS = enum_members("src/Economy/ServiceKind.cs", "ServiceKind")

# ---- reading authored .tres ---------------------------------------------------------------------


def tres_fields(text):
    """key -> raw value of the [resource] section of a .tres."""
    body = text.split("[resource]", 1)[1] if "[resource]" in text else ""
    out = {}
    for line in body.splitlines():
        m = re.match(r"^(\w+) = (.*)$", line)
        if m:
            out[m.group(1)] = m.group(2).strip()
    return out


def unquote(raw, default=""):
    m = re.match(r'^"(.*)"$', raw or "")
    return m.group(1) if m else default


def string_list(raw):
    return re.findall(r'"([^"]*)"', raw or "")


def load_items():
    """id -> {name, value, tags, rarity (ordinal), stackable} for every data/items/*.tres."""
    items = {}
    for name in sorted(os.listdir(ITEM_DIR)):
        if not name.endswith(".tres"):
            continue
        f = tres_fields(read(os.path.join(ITEM_DIR, name)))
        item_id = unquote(f.get("Id", ""))
        if item_id:
            items[item_id] = {
                "name": unquote(f.get("DisplayName", ""), item_id),
                "value": int(f.get("Value", "1")),
                "tags": string_list(f.get("TradeTags", "")),
                "rarity": int(f.get("Rarity", "0")),
                "guide": False,
            }
    return items


def load_cells():
    """cell id -> (surplus, demand, shock tags), from every generated region."""
    cells = {}
    for name in sorted(os.listdir(REGION_DIR)):
        if not name.endswith(".tres"):
            continue
        for block in read(os.path.join(REGION_DIR, name)).split("[sub_resource")[1:]:
            ident = re.search(r'^Id = "([^"]+)"', block, re.M)
            if not ident or "ScenePath" not in block:
                continue

            def tags(key, block=block):
                m = re.search(r"^" + key + r" = (.*)$", block, re.M)
                return string_list(m.group(1)) if m else []

            cells[ident.group(1)] = (tags("Surplus"), tags("Demand"), tags("ShockTags"))
    return cells


def load_shops():
    shops = []
    for name in sorted(os.listdir(SHOP_DIR)):
        if not name.endswith(".tres"):
            continue
        f = tres_fields(read(os.path.join(SHOP_DIR, name)))
        shops.append({
            "id": unquote(f.get("Id", "")),
            "cell": unquote(f.get("CellId", "")),
            "accepted": string_list(f.get("AcceptedTags", "")),
            "specialties": string_list(f.get("Specialties", "")),
            "markup": float(f.get("BuyMarkup", "1.5")),
            "fraction": float(f.get("SellFraction", "0.4")),
            "haggle": int(f.get("HaggleChance", "0")),
            "consign": float(f.get("ConsignFraction", "0")) > 0,
        })
    return shops


def load_existing_recipes():
    """The hand-authored recipes: the same dict shape as a planned one, read from their .tres."""
    out = []
    for name in sorted(os.listdir(RECIPE_DIR)):
        if not name.endswith(".tres"):
            continue
        text = read(os.path.join(RECIPE_DIR, name))
        f = tres_fields(text)
        rid = unquote(f.get("Id", ""))
        if rid not in catalogue.EXISTING_RECIPE_IDS:
            continue
        ingredients = tuple(
            (m.group(1), int(m.group(2)))
            for m in re.finditer(r'ItemId = "([^"]+)"\s*\nQuantity = (\d+)', text.replace("\r\n", "\n")))
        out.append({
            "id": rid, "file": name, "display": unquote(f.get("DisplayName", ""), rid),
            "output": unquote(f.get("OutputItemId", "")), "quantity": int(f.get("OutputQuantity", "1")),
            "station": STATIONS[int(f.get("Station", "0"))], "ingredients": ingredients,
            "rarity": RARITIES[int(f.get("OutputRarity", "0"))], "tier": 0,
        })
    return out


# ---- the planned recipes ------------------------------------------------------------------------

ITEMS = load_items()

#: Suggested values for items the content lane has not generated yet. Only used until the real
#: data/items/<x>.tres exists; the content lane's numbers win the moment they land.
PRICE_GUIDE = {
    "item.material.celestial_dust": (160, ["reagent", "arcane"]),
}

#: Value a crafted output is suggested to carry, as a multiple of what went into it.
GUIDE_MARKUP = {"material": 1.15, "consumable": 1.4, "equippable": 1.25}


def guide_tags(entry):
    item_id, kind = entry["id"], entry["kind"]
    if kind == "material":
        return ["metal"] if entry["id"].endswith("_ingot") else ["reagent"]
    if kind == "consumable":
        return ["food"] if ".food." in item_id else ["potion"]
    if entry["slot"] in ("Ring", "Amulet"):
        return ["jewelry"]
    if entry["slot"] == "Ammo":
        return ["weapon"]
    if entry["slot"] == "MainHand":
        return ["weapon"] if entry["weapon_class"] in ("Bow", "Staff") else ["weapon", "metal"]
    weight = {"Heavy": "metal", "Medium": "leather", "Light": "textile"}.get(entry["armor_weight"], "metal")
    return ["armor", weight]


def item(item_id, _seen=()):
    """The item's facts: real when its .tres exists, otherwise a guide price (marked 'guide')."""
    if item_id in ITEMS:
        return ITEMS[item_id]
    entry = catalogue.ITEMS_BY_ID.get(item_id)
    assert entry is not None, "unknown item " + item_id
    if item_id in PRICE_GUIDE:
        value, tags = PRICE_GUIDE[item_id]
    else:
        recipe = next((r for r in catalogue.PLANNED_RECIPES if r["output"] == item_id), None)
        assert recipe is not None and item_id not in _seen, "no guide price for " + item_id
        spent = sum(item(i, _seen + (item_id,))["value"] * q for i, q in recipe["ingredients"])
        value = max(1, int(round(GUIDE_MARKUP[entry["kind"]] * spent / recipe["quantity"])))
        tags = guide_tags(entry)
    ITEMS[item_id] = {
        "name": entry["name"], "value": value, "tags": tags,
        "rarity": RARITIES.index(entry["rarity_floor"]), "guide": True,
    }
    return ITEMS[item_id]


def output_rarity(recipe):
    """What a crafted piece rolls at: gear is Uncommon through tier 3 and Rare above (never below
    the item's own floor); arrows, materials and consumables are plain."""
    entry = catalogue.ITEMS_BY_ID.get(recipe["output"])
    slot = entry["slot"] if entry else {"item.weapon.hunting_bow": "MainHand", "item.ammo.arrows": "Ammo"}.get(recipe["output"], "None")
    if slot in ("None", "Ammo"):
        return "Common"
    wanted = "Uncommon" if recipe["tier"] <= 3 else "Rare"
    floor = entry["rarity_floor"] if entry else "Common"
    return max(wanted, floor, key=RARITIES.index)


def verb_and_blurb(recipe, name):
    out, station = recipe["output"], recipe["station"]
    if station == "Hand":
        return "Cook", "Prepare %s by hand; no station is needed." % name
    if station == "Alchemy":
        return "Brew", "Brew %s at an alchemy table." % article(name)
    if out.endswith("_ingot"):
        return "Smelt", "Smelt lesser metal and a catalyst into %s." % article(name)
    if ".ammo." in out:
        return "Fletch", "Fletch a sheaf of %s." % name
    if station == "Forge":
        return "Forge", "Forge %s at the anvil." % article(name)
    if ".weapon." in out:
        return "Carve", "Shape seasoned wood into %s." % article(name)
    return "Stitch", "Cut and stitch %s at the workbench." % article(name)


def article(name):
    return ("an " if name[0].lower() in "aeiou" else "a ") + name


def file_name(recipe_id):
    return "".join(part.capitalize() for part in recipe_id.split(".", 1)[1].replace(".", "_").split("_")) + ".tres"


def planned():
    out = []
    for r in catalogue.PLANNED_RECIPES:
        name = item(r["output"])["name"]
        verb, blurb = verb_and_blurb(r, name)
        out.append(dict(r, file=file_name(r["id"]), display="%s %s" % (verb, name), blurb=blurb,
                        rarity=output_rarity(r)))
    return out


def render(recipe):
    lines = [
        '[gd_resource type="Resource" script_class="CraftingRecipeResource" load_steps=%d format=3]' % (3 + len(recipe["ingredients"])),
        "",
        '[ext_resource type="Script" path="res://src/Crafting/CraftingRecipeResource.cs" id="1_recipe"]',
        '[ext_resource type="Script" path="res://src/Crafting/RecipeIngredient.cs" id="2_ing"]',
        "",
        "; GENERATED by tools/gen_recipes.py from tools/items/catalogue.py. Edit the catalogue, not this file.",
        "; Discovery: %s." % {
            "known": "every character starts with it (GameIds.Recipes.Starting)",
            "trainer": "taught by the Ember Crown trainer",
            "scroll": "taught by the Ember Crown trainer, or by using %s" % recipe["scroll_id"],
        }[recipe["discovery"]],
        "",
    ]
    for i, (item_id, quantity) in enumerate(recipe["ingredients"]):
        lines += [
            '[sub_resource type="Resource" id="Ing_%d"]' % i,
            'script = ExtResource("2_ing")',
            'ItemId = "%s"' % item_id,
            "Quantity = %d" % quantity,
            "",
        ]
    subs = ", ".join('SubResource("Ing_%d")' % i for i in range(len(recipe["ingredients"])))
    lines += [
        "[resource]",
        'script = ExtResource("1_recipe")',
        'Id = "%s"' % recipe["id"],
        'DisplayName = "%s"' % recipe["display"],
        'Description = "%s"' % recipe["blurb"],
        "Station = %d" % STATIONS.index(recipe["station"]),
        "Ingredients = Array[Resource]([%s])" % subs,
        'OutputItemId = "%s"' % recipe["output"],
        "OutputQuantity = %d" % recipe["quantity"],
        "OutputRarity = %d" % RARITIES.index(recipe["rarity"]),
        "Tier = %d" % recipe["tier"],
        'ScrollItemId = "%s"' % recipe["scroll_id"],
        "",
    ]
    return "\n".join(lines)


# ---- locale and trainer -------------------------------------------------------------------------


def csv_cell(text):
    return '"%s"' % text.replace('"', '""') if any(c in text for c in ',"\n') else text


def build_locale(existing, recipes):
    sep = "\r\n" if "\r\n" in existing else "\n"
    lines = [MARK_BEGIN]
    lines += ["%s.name,%s" % (r["id"], csv_cell(r["display"])) for r in recipes]
    lines.append(MARK_END)
    block = sep.join(lines)
    if MARK_BEGIN in existing:
        return re.sub(re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END), lambda _: block, existing, flags=re.S)
    assert LANE_END in existing, "strings.csv has no ics:crafting block"
    return existing.replace(LANE_END, block + sep + LANE_END, 1)


def taught_ids(recipes):
    return list(TRAINER_EXISTING) + [r["id"] for r in recipes if r.get("discovery") in ("trainer", "scroll")]


def build_trainer(existing, recipes):
    line = "TaughtRecipeIds = Array[String]([%s])" % ", ".join('"%s"' % i for i in taught_ids(recipes))
    assert re.search(r"^TaughtRecipeIds = .*$", existing, re.M), "trainer has no TaughtRecipeIds line"
    return re.sub(r"^TaughtRecipeIds = [^\r\n]*", lambda _: line, existing, count=1, flags=re.M)


def starting_ids():
    """The recipe ids GameIds.Recipes.Starting seeds, resolved through the block's constants."""
    text = read(GAME_IDS)
    block = re.search(r"public static class Recipes\b(.*?)\n    \}", text, re.S).group(1)
    consts = dict(re.findall(r'const string (\w+) = "(recipe\.[^"]+)"', block))
    body = re.search(r"Starting\s*=\s*\{(.*?)\};", block, re.S).group(1)
    body = re.sub(r"//[^\n]*", "", body)
    return [consts[name] for name in re.findall(r"\b([A-Z]\w+)\b", body) if name in consts]


# ---- the commission inequality (ContentValidator.ValidateCommission, restated) ------------------


def f32(x):
    return struct.unpack("f", struct.pack("f", x))[0]


def fmul(*factors):
    """A chain of C# float multiplications: each product is rounded to single precision."""
    out = f32(factors[0])
    for factor in factors[1:]:
        out = f32(out * f32(factor))
    return out


def value_at(base, tags, surplus, demand):
    """RegionDemand.ValueAt."""
    if base <= 0 or not tags:
        return max(0, base)
    if any(t in surplus for t in tags):
        factor = 0.62
    elif any(t in demand for t in tags):
        factor = 1.5
    else:
        return base
    return max(1, int(math.floor(fmul(base, factor) + 0.5)))


def local_value(shop, cells, base, tags, peak):
    """ShopResource.LocalValue at PriceView.Peak / Trough (SupplyShockRules.Extremes)."""
    if not shop["cell"] or shop["cell"] not in cells:
        return base
    surplus, demand, shock = cells[shop["cell"]]
    if peak:
        surplus, demand = [t for t in surplus if t not in shock], demand + [t for t in shock if t not in demand]
    else:
        demand, surplus = [t for t in demand if t not in shock], surplus + [t for t in shock if t not in surplus]
    return value_at(base, tags, surplus, demand)


def accepts(tags, accepted):
    """TradeTags.Accepts."""
    if "contraband" in tags:
        return "contraband" in accepted
    return not accepted or not tags or any(t in accepted for t in tags)


def specialty(tags, specialties):
    return bool(specialties) and bool(tags) and any(t in specialties for t in tags)


ALLIED = 0.85          # ShopPricing.PriceMultiplierFor(ReputationTier.Allied)
BEST_SERVICE = 0.95    # PerkEffectMath.BestServiceFactor
BEST_SELL = 1.05       # PerkEffectMath.BestSellFactor
HAGGLE_BUY = 0.90      # HaggleRules.BuyDiscount
SPECIALTY_BUY = 0.95   # ShopPricing.SpecialtyBuyDiscount
SPECIALTY_SELL = 1.25  # ShopPricing.SpecialtySellBonus


def commission_cost(recipe, shop, cells, labour):
    """EconomyReport.CommissionCost at Allied standing, haggled where the shop haggles, PriceView.Trough."""
    total = labour
    for item_id, quantity in recipe["ingredients"]:
        it = item(item_id)
        unit = local_value(shop, cells, it["value"], it["tags"], peak=False)
        markup = fmul(shop["markup"], ALLIED, SPECIALTY_BUY if specialty(it["tags"], shop["specialties"]) else 1.0,
                      HAGGLE_BUY if shop["haggle"] > 0 else 1.0, 1.0)
        total += max(1, int(math.ceil(fmul(max(0, unit), max(1.0, markup))))) * quantity
    return total


def best_sale(value, tags, shops, cells):
    """EconomyReport.BestBuyers at PriceView.Peak with the best sell perk. Standing is ignored
    (a hostile shop is counted as a buyer), which can only make this check stricter."""
    best, who = 0, ""
    for shop in shops:
        if shop["consign"] or not accepts(tags, shop["accepted"]):
            continue
        fraction = fmul(shop["fraction"], SPECIALTY_SELL if specialty(tags, shop["specialties"]) else 1.0, 1.0, BEST_SELL)
        price = max(0, int(math.floor(fmul(max(0, local_value(shop, cells, value, tags, peak=True)),
                                           min(1.0, max(0.0, fraction))))))
        if price > best:
            best, who = price, shop["id"]
    return best, who


def commission_rows(recipes):
    """One row per (commission service, recipe it can make): the validator's own two numbers."""
    shops, cells = load_shops(), load_cells()
    by_id = {s["id"]: s for s in shops}
    rows, problems = [], []
    for name in sorted(os.listdir(SERVICE_DIR)):
        if not name.endswith(".tres"):
            continue
        f = tres_fields(read(os.path.join(SERVICE_DIR, name)))
        if int(f.get("Kind", "0")) != SERVICE_KINDS.index("Commission"):
            continue
        service, station = unquote(f.get("Id", "")), STATIONS[int(f.get("CommissionStation", "0"))]
        shop = by_id.get(unquote(f.get("MaterialsShopId", "")))
        if shop is None:
            problems.append("%s: unknown materials shop" % service)
            continue
        labour = max(1, int(math.ceil(fmul(int(f.get("PriceGold", "0")), ALLIED, BEST_SERVICE))))
        for r in recipes:
            if r["station"] not in ("Hand", station):
                continue
            out = item(r["output"])
            cost = commission_cost(r, shop, cells, labour)
            sale, who = best_sale(out["value"], out["tags"], shops, cells)
            quantity = max(1, r["quantity"])
            # The highest output value that still loses money, for the content lane to price under.
            ceiling = out["value"]
            while best_sale(ceiling + 1, out["tags"], shops, cells)[0] * quantity < cost and ceiling < 100000:
                ceiling += max(1, ceiling // 50)
            while ceiling > 0 and best_sale(ceiling, out["tags"], shops, cells)[0] * quantity >= cost:
                ceiling -= 1
            rows.append((service, r, out, cost, sale, who, ceiling))
            if sale * quantity >= cost:   # CommissionRules.Exploitable
                problems.append(
                    "%s commissions %s for %d gold and %s pays %d x%d for %s (value %d%s): keep its value at or under %d" % (
                        service, r["id"], cost, who, sale, quantity, r["output"], out["value"],
                        ", guide" if out["guide"] else "", ceiling))
    return rows, problems


# ---- rules the generator itself can check --------------------------------------------------------


def check_rules(recipes, new):
    problems = list(catalogue.validate())
    known = [r["id"] for r in new if r["discovery"] == "known"]
    taught = taught_ids(new)
    try:
        starting = starting_ids()
    except (AttributeError, KeyError) as error:
        starting = []
        problems.append("GameIds.Recipes could not be read: %r" % (error,))

    wanted_start = list(STARTING_EXISTING) + known
    for rid in wanted_start:
        if rid not in starting:
            problems.append("GameIds.Recipes.Starting does not seed %s" % rid)
    for rid in starting:
        if rid not in wanted_start:
            problems.append("GameIds.Recipes.Starting seeds %s, which the catalogue does not mark 'known'" % rid)
        if rid in taught:
            problems.append("%s is both seeded and taught" % rid)
    for r in recipes:
        if r["id"] not in starting and r["id"] not in taught:
            problems.append("%s is neither seeded nor taught" % r["id"])
        if r["quantity"] <= 0 or any(q <= 0 for _, q in r["ingredients"]):
            problems.append("%s has a non-positive quantity" % r["id"])

    files = [r["file"] for r in recipes]
    for name in set(files):
        if files.count(name) > 1:
            problems.append("two recipes share the file name %s" % name)

    used = {i for r in recipes for i, _ in r["ingredients"]}
    for material in catalogue.MATERIAL_TIERS:
        if material["id"] not in used:
            problems.append("material %s is used by no recipe" % material["id"])
    return problems


def main():
    check = "--check" in sys.argv
    existing = load_existing_recipes()
    new = planned()
    recipes = existing + new
    changed = []

    wanted = {os.path.join(RECIPE_DIR, r["file"]): render(r) for r in new}
    for path, text in wanted.items():
        old = read(path) if os.path.exists(path) else None
        if old != text:
            changed.append(path)
            if not check:
                io.open(path, "w", encoding="utf-8", newline="").write(text)

    # A recipe file that is neither hand-authored nor in the catalogue is stale.
    kept = {os.path.join(RECIPE_DIR, r["file"]) for r in existing}
    for name in sorted(os.listdir(RECIPE_DIR)):
        full = os.path.join(RECIPE_DIR, name)
        if name.endswith(".tres") and full not in wanted and full not in kept:
            changed.append(full)
            if not check:
                os.remove(full)

    for path, build in ((CSV, lambda t: build_locale(t, recipes)), (TRAINER, lambda t: build_trainer(t, new))):
        old = read(path)
        text = build(old)
        if text != old:
            changed.append(path)
            if not check:
                io.open(path, "w", encoding="utf-8", newline="").write(text)

    problems = check_rules(recipes, new)
    rows, commission_problems = commission_rows(recipes)
    problems += commission_problems

    if "--report" in sys.argv:
        print("%-34s %-26s %5s %5s  %s" % ("recipe", "output value", "cost", "sale", "highest safe value"))
        for _service, r, out, cost, sale, _who, ceiling in rows:
            print("%-34s %-26s %5d %5d  %d" % (
                r["id"], "%d%s x%d" % (out["value"], " (guide)" if out["guide"] else "", r["quantity"]),
                cost, sale * max(1, r["quantity"]), ceiling))

    guided = sorted(i for i, it in ITEMS.items() if it["guide"])
    for problem in problems:
        print("PROBLEM: " + problem)
    summary = "%d recipes (%d generated, %d hand-authored); %d commission pairs checked; %d item(s) priced from the guide" % (
        len(recipes), len(new), len(existing), len(rows), len(guided))
    if check:
        for c in changed:
            print("WOULD CHANGE", os.path.relpath(c, ROOT))
        print("%s; %d file(s) out of date; %d problem(s)" % (summary, len(changed), len(problems)))
        return 1 if changed or problems else 0
    print("%s; wrote %d file(s); %d problem(s)" % (summary, len(changed), len(problems)))
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
