#!/usr/bin/env python3
"""Create the empty scene for every region cell that does not have one yet.

    python tools/new_cell_scenes.py [--check]

A transitional cell's scene is a root, a `Nav` region and its baker — nothing else. Its ground,
collision, ecology and roads all come from the region resource at bake time. The navigation voxel
grid is the wilderness one (0.4/0.3) with agent dims quantised to it (NOW.md invariant 20).
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

TEMPLATE = """[gd_scene format=3]

[ext_resource type="Script" path="res://src/World/CellNavBaker.cs" id="1_navbaker"]

; {title} — a transitional cell (2026-09 world rebuild). Generated by tools/new_cell_scenes.py.
;
; ⚠️ IT IS EMPTY AND THAT IS THE POINT. Ground, elevation, collision, vegetation and any road across it
; are authored in data/regions/*.tres (via tools/region_spec_*.py) and prepared by the world bake.
; Do not fill this in without asking whether the realm needs another beat here.
[sub_resource type="NavigationMesh" id="NavMesh_{key}"]
geometry_parsed_geometry_type = 1
cell_size = 0.4
cell_height = 0.3
agent_height = 1.8
agent_radius = 0.8
agent_max_climb = 0.3
agent_max_slope = 40.0

[node name="{node}" type="Node3D"]

[node name="Nav" type="NavigationRegion3D" parent="."]
navigation_mesh = SubResource("NavMesh_{key}")

[node name="NavBaker" type="Node" parent="Nav"]
script = ExtResource("1_navbaker")
"""


def main(argv: list[str]) -> int:
    from region_spec_ember import cells as ember
    from region_spec_frostfang import cells as frost
    missing = 0
    for cell in list(ember()) + list(frost()):
        path = ROOT / cell.scene.replace("res://", "")
        if path.exists():
            continue
        missing += 1
        if "--check" in argv:
            print(f"missing scene: {path.relative_to(ROOT)}")
            continue
        node = "".join(part.capitalize() for part in cell.key.split("_")) + "Cell"
        path.write_text(TEMPLATE.format(title=cell.key.replace("_", " ").upper(), key=cell.key, node=node),
                        encoding="utf-8")
        print(f"created {path.relative_to(ROOT)}")
    return 1 if ("--check" in argv and missing) else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
