#!/usr/bin/env python3
"""Frostfang Reach's macro layout, geography and approaches. Consumed by tools/gen_regions.py."""

from __future__ import annotations

from gen_regions import (Cell, Mound, Ridge, Route, Seam, Yard, check_envelopes, check_seams,
                         check_tiling, emit, local)

EXTENT_X = (260.0, 600.0)
ROWS = [(-300.0, -190.0), (-190.0, -100.0), (-100.0, -10.0), (-10.0, 70.0)]

HEADER = '''[gd_resource type="Resource" script_class="RegionResource" load_steps=12 format=3 uid="uid://crgnfrostfng0"]

[ext_resource type="Script" path="res://src/World/RegionResource.cs" id="1_region"]
[ext_resource type="Script" path="res://src/World/RegionCellResource.cs" id="2_cell"]
[ext_resource type="Script" path="res://src/World/WorldEnvironmentProfileResource.cs" id="3_environment"]
[ext_resource type="Script" path="res://src/World/WorldCellPresentationResource.cs" id="4_presentation"]
[ext_resource type="Script" path="res://src/World/WorldPerformanceBudgetResource.cs" id="5_budget"]
[ext_resource type="Script" path="res://src/World/WorldPathSegmentResource.cs" id="6_path"]
[ext_resource type="Script" path="res://src/World/WorldGroundAreaResource.cs" id="7_area"]
[ext_resource type="Script" path="res://src/World/WorldLandformResource.cs" id="8_landform"]
[ext_resource type="Script" path="res://src/World/WorldBiomeScatterResource.cs" id="9_scatter"]
[ext_resource type="Script" path="res://src/World/BiomeScatterLayerResource.cs" id="10_layer"]
[ext_resource type="Script" path="res://src/World/BiomeScatterExclusionResource.cs" id="11_exclusion"]
[ext_resource type="Script" path="res://src/World/WorldWaterResource.cs" id="12_water"]
[ext_resource type="Resource" path="res://data/world_gen/FrostfangReach.tres" id="13_generation"]

; ⚠️ GENERATED BY tools/gen_regions.py FROM tools/region_spec_frostfang.py. Edit the spec.
;
; ====================================================================================================
; FROSTFANG REACH AFTER THE 2026-08-29 GEOGRAPHY OVERHAUL
; ====================================================================================================
;
; ⚠️ THE REACH MOVED OUT OF THE EMBER CROWN'S COORDINATE SPACE, AND THAT WAS A LATENT BUG, NOT A
; DESIGN. dragon_roost sat at (25, 0, -20) and ancient_aerie at (25, 0, -110), which is inside the
; Ember Crown's arena and northern wilds; RegionStreamer's header carried "both regions cannot be
; resident at once" as a documented limitation for that reason alone. The Reach now occupies
; x 260..600, z -320..70 — nothing overlaps anything, and the constraint went with the overlap.
;
; WHAT CHANGED. Five cells packed into 250 x 200 metres became ten across 340 x 380, and the Clan
; Hold no longer has two dragon territories starting at its property line: the Wild roost is 115 m
; west of the hold's centre and the Ash roost 115 m east, with the hold's own shoulders of mountain
; in between, and the Ancient's aerie is 220 metres and three cells north of the hold up a glacier
; pass and a mountain traverse. Five new cells carry that distance: two southern marches (the
; arrival), a snowfield, a high ascent and an unroaded approach behind the ash crater.
;
; WHAT DID NOT CHANGE. The moot ring, the work terrace and the beast runs; the Splintered Shelf; the
; long exposed causeway into the ash crater; the bent procession, the standing-stone crescent and the
; hidden hoard. Every one of them is now cut into real elevation instead of drawn on a 90 m platform.
;
;   ROW z -300..-190   ancient_aerie (x 260..400)      aerie_ascent (400..600)
;   ROW z -190..-100   north_snowfield (260..380)  glacier (380..500)  ash_approach (500..600)
;   ROW z -100..-10    dragon_roost (260..370)     clan_hold (370..490)  ash_roost (490..600)
;   ROW z  -10..70     frost_march_w (260..430)    frost_march_e (430..600)
;
; ⚠️ THE PLAYER NOW ARRIVES 110 METRES SOUTH OF THE HOLD. SpawnPoint is (415, 1.2, 55), in the
; southern march, and the road climbs north to the gate. Arriving inside a settlement is what made
; the Reach read as one room; arriving in weather with the hold's smoke on the skyline is the region
; introducing itself.
'''

ENVIRONMENT = '''[sub_resource type="Resource" id="Environment_frostfang"]
script = ExtResource("3_environment")
SurfaceColor = Color(0.49, 0.55, 0.60, 1)
SecondaryColor = Color(0.70, 0.75, 0.78, 1)
DetailColor = Color(0.26, 0.31, 0.36, 1)
RoadColor = Color(0.33, 0.37, 0.42, 1)
BackdropColor = Color(0.25, 0.29, 0.34, 1)
Relief = 2.2
DetailScale = 3.5
BackdropCenter = Vector3(430, 0, -120)
BackdropRadius = 330.0
BackdropHeight = 128.0
BackdropCount = 28
TerrainSeed = 3800
SurfaceRoughness = 0.93
DetailRoughness = 0.84
RoadRoughness = 0.78
SlopeBlendStart = 0.22
SlopeBlendEnd = 0.58
HeightBlendStart = 10.0
HeightBlendEnd = 34.0

; ⚠️ THE LIGHT IS THE REGION, NOT JUST THE PALETTE. Every terrain colour here is cold and the Clan
; Hold still rendered as warm tan sand, because a neutral-grey bedrock under the Ember Crown's
; golden-hour sun IS tan. SunTint pulls the key toward ART_STYLE §2.1's "hard white-blue"; the sun
; is also weaker and the air much thicker, which is what puts the aerial depth into a shot of a
; massif and what makes the Reach feel like altitude rather than like a repainted lowland.
SunTint = Color(0.74, 0.82, 0.96, 1)
SunEnergyScale = 0.86
HazeColor = Color(0.72, 0.79, 0.87, 1)
HazeScale = 1.55

'''

BUDGET = '''[sub_resource type="Resource" id="Budget_frostfang"]
script = ExtResource("5_budget")
MaxAuthoredNodesPerCell = 260
MaxResidentAuthoredNodes = 900
MaxResidentRuntimeNodes = 1800
MaxScatterInstancesPerCell = 2400
MaxResidentScatterInstances = 20000
MaxTerrainVerticesPerCell = 7000
MaxResidentTerrainVertices = 45000
MaxDrawCalls = 1800
MaxNodeCount = 14000
MaxStaticMemoryMb = 2048.0
MaxFrameMilliseconds = 16.67
ConsecutiveSamplesBeforeWarning = 5
BiomeCullDistance = 340.0
VisibilityUpdateInterval = 0.25
MaxConcurrentLoadRequests = 2
MaxCellInstantiationsPerFrame = 1

'''

SCATTER = '''[sub_resource type="Resource" id="Layer_dead_pine"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_pine_dead.glb"
Count = 85
MinimumScale = 0.68
MaximumScale = 1.08
MinimumSpacing = 6.5
Saturation = 0.42
Clumping = 0.72
ClumpScale = 44.0
MaxSlope = 0.4
HeightRange = Vector2(-9999, 34)
Tint = Color(0.78, 0.84, 0.90, 1)
TintVariation = 0.10
VisibilityRangeEnd = 155.0
VisibilityFadeMargin = 20.0
HlodShape = 1
HlodReduction = 4
HlodRangeBegin = 130.0
HlodRangeEnd = 320.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

; ⚠️ `prp_rock_cluster` IS ONE 244-TRIANGLE ROCK UNDER A PLURAL NAME, and both of Frostfang's stone
; layers scattered it — 120 and 95 instances per 100 x 100 m of the same silhouette. The name is why
; nobody looked: a layer called "cluster" reads as though it already carries variety.
;
; ⚠️ THE DENSITY IS SPLIT, NOT ADDED TO. 70 + 40 here against the 120 it replaces, and the ice tier
; below is genuinely new cover rather than a substitution — Frostfang is a glacial realm whose only
; ice was twelve hand-placed copies of one prop, so the ground between them had nothing frozen on it
; at all.
[sub_resource type="Resource" id="Layer_frost_rock"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_rock_cluster.glb"
Count = 70
MinimumScale = 0.55
MaximumScale = 1.15
MinimumSpacing = 3.2
Saturation = 0.3
Clumping = 0.52
ClumpScale = 28.0
MaxSlope = 1.0
Tint = Color(0.72, 0.79, 0.86, 1)
TintVariation = 0.12
VisibilityRangeEnd = 135.0
VisibilityFadeMargin = 18.0
HlodShape = 2
HlodReduction = 5
HlodRangeBegin = 112.0
HlodRangeEnd = 280.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

[sub_resource type="Resource" id="Layer_snow_tuft"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_grass_short.glb"
Count = 420
MinimumScale = 0.6
MaximumScale = 1.1
MinimumSpacing = 2.6
Saturation = 0.35
Clumping = 0.4
ClumpScale = 20.0
MaxSlope = 0.55
Tint = Color(0.80, 0.86, 0.92, 1)
TintVariation = 0.14
VisibilityRangeEnd = 52.0
VisibilityFadeMargin = 10.0

[sub_resource type="Resource" id="Layer_frost_rock_b"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_rock_cluster_a.glb"
Count = 40
MinimumScale = 0.34
MaximumScale = 0.72
MinimumSpacing = 7.0
Saturation = 0.3
Clumping = 0.55
ClumpScale = 30.0
MaxSlope = 0.95
Tint = Color(0.73, 0.79, 0.86, 1)
TintVariation = 0.13
VisibilityRangeEnd = 135.0
VisibilityFadeMargin = 18.0
CastShadows = true

; Shed ice. Small, common and low, so it dresses the ground a glacier has ground over rather than
; competing with the authored ice masses. No HLOD: at 1.3 m it is gone well before the range where
; a proxy would earn its draw call.
[sub_resource type="Resource" id="Layer_ice_chunk"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_ice_chunk.glb"
Count = 55
MinimumScale = 0.55
MaximumScale = 1.5
MinimumSpacing = 5.2
Clumping = 0.62
ClumpScale = 26.0
MaxSlope = 0.7
Tint = Color(0.88, 0.93, 0.98, 1)
TintVariation = 0.09
VisibilityRangeEnd = 78.0
VisibilityFadeMargin = 14.0

; ⚠️ THE SHARD STANDS 2.5 m AND IT IS THE ONE THAT NEEDS A SLOPE GATE. Ice that has been shoved
; upright belongs on the flat of a snowfield, not canted out of a 40-degree corrie wall — which is
; exactly the failure the terrain gate was added for (see WorldBiomeScatter's MaxSlope comment).
[sub_resource type="Resource" id="Layer_ice_shard"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_ice_shard.glb"
Count = 12
MinimumScale = 0.6
MaximumScale = 1.35
MinimumSpacing = 13.0
Clumping = 0.66
ClumpScale = 40.0
MaxSlope = 0.32
Tint = Color(0.88, 0.93, 0.98, 1)
TintVariation = 0.07
VisibilityRangeEnd = 130.0
VisibilityFadeMargin = 18.0
CastShadows = true

; ⚠️ AN EXCLUSION FOLLOWS ITS NEST AND THE NESTS DID NOT MOVE WITHIN THEIR CELLS. Each roost names
; its own, centred on where its Nest node actually sits in cell-local metres.
[sub_resource type="Resource" id="Exclusion_dragon_roost"]
script = ExtResource("11_exclusion")
Center = Vector2(-14, -20)
Radius = 15.0

[sub_resource type="Resource" id="Exclusion_ash_roost"]
script = ExtResource("11_exclusion")
Center = Vector2(10, 6)
Radius = 15.0

; The ash roost causeway: a 34 m exposed approach, and a line of trees across it would hand the
; player cover the fight is designed not to offer.
[sub_resource type="Resource" id="Exclusion_ash_causeway"]
script = ExtResource("11_exclusion")
Center = Vector2(-32, 1)
Radius = 12.0

[sub_resource type="Resource" id="Exclusion_aerie"]
script = ExtResource("11_exclusion")
Center = Vector2(-6, -18)
Radius = 18.0

[sub_resource type="Resource" id="Exclusion_aerie_hoard"]
script = ExtResource("11_exclusion")
Center = Vector2(12, -12)
Radius = 7.0

[sub_resource type="Resource" id="Scatter_glacier"]
script = ExtResource("9_scatter")
Seed = 5205
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_frost_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_chunk"), SubResource("Layer_ice_shard"), SubResource("Layer_snow_tuft")])

[sub_resource type="Resource" id="Scatter_dragon_roost"]
script = ExtResource("9_scatter")
Seed = 5202
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_dead_pine"), SubResource("Layer_frost_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_chunk"), SubResource("Layer_snow_tuft")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_dragon_roost")])

[sub_resource type="Resource" id="Scatter_ash_roost"]
script = ExtResource("9_scatter")
Seed = 5203
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_dead_pine"), SubResource("Layer_frost_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_chunk")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_ash_roost"), SubResource("Exclusion_ash_causeway")])

[sub_resource type="Resource" id="Scatter_aerie"]
script = ExtResource("9_scatter")
Seed = 5204
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_dead_pine"), SubResource("Layer_frost_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_chunk")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_aerie"), SubResource("Exclusion_aerie_hoard")])

[sub_resource type="Resource" id="Layer_high_rock"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_rock_cluster.glb"
Count = 55
MinimumScale = 0.5
MaximumScale = 1.45
MinimumSpacing = 4.0
Saturation = 0.28
Clumping = 0.58
ClumpScale = 32.0
MaxSlope = 1.15
Tint = Color(0.76, 0.81, 0.87, 1)
TintVariation = 0.14
VisibilityRangeEnd = 145.0
VisibilityFadeMargin = 20.0
HlodShape = 2
HlodReduction = 5
HlodRangeBegin = 120.0
HlodRangeEnd = 290.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

[sub_resource type="Resource" id="Layer_high_pine"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_pine_dead.glb"
Count = 16
MinimumScale = 0.55
MaximumScale = 0.9
MinimumSpacing = 14.0
Saturation = 0.4
Clumping = 0.6
ClumpScale = 50.0
MaxSlope = 0.38
Tint = Color(0.80, 0.86, 0.92, 1)
TintVariation = 0.08
VisibilityRangeEnd = 150.0
VisibilityFadeMargin = 20.0

; ⚠️ ABOVE THE TREE LINE, AND THAT IS THE POINT. The shared roost profile put 230 dead pines on the
; Ancient's massif and buried the summit court, the crescent and three precipices in a forest — the
; one cell in the realm whose whole job is a reveal. Sixteen wind-killed trunks and bare rock.
[sub_resource type="Resource" id="Scatter_heights"]
script = ExtResource("9_scatter")
Seed = 5209
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_high_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_shard"), SubResource("Layer_high_pine")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_aerie"), SubResource("Exclusion_aerie_hoard")])

[sub_resource type="Resource" id="Scatter_snowfield"]
script = ExtResource("9_scatter")
Seed = 5206
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_snow_tuft"), SubResource("Layer_frost_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_chunk"), SubResource("Layer_dead_pine")])

[sub_resource type="Resource" id="Scatter_march"]
script = ExtResource("9_scatter")
Seed = 5207
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_snow_tuft"), SubResource("Layer_dead_pine"), SubResource("Layer_frost_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_chunk")])

[sub_resource type="Resource" id="Scatter_hold"]
script = ExtResource("9_scatter")
Seed = 5208
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_snow_tuft"), SubResource("Layer_frost_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_chunk")])

'''

RESOURCE = '''[resource]
script = ExtResource("1_region")
Id = "region.frostfang_reach"
DisplayName = "Frostfang Reach"
Realm = 1

; ⚠️ THE ARRIVAL IS 110 METRES SOUTH OF THE CLAN HOLD NOW. It used to be (100, 1.2, 0), which is
; twenty metres from the moot ring — a region that began inside its own capital. The portal stands at
; SpawnPoint + (0, -1.2, -4) because Frostfang authors no PortalPoint, so both are in the southern
; march and the hold is a walk up a road.
SpawnPoint = Vector3(415, 1.2, 55)

; ⚠️ FROSTFANG IS NOT QUEST-GATED (maintainer direction, 2026-08-28). UnlockFlagId held
; "flag.frostfang.passage_open" — written by quest.warband.heart — and RegionSetup fed it to the
; portal's RequiredFlagId, so the door was hidden until that quest closed. It is EMPTY, and the
; portal is visible and usable from the first minute. The Crossway toll below is a separate thing
; and still fails closed: removing the quest gate made the crossing a price, not a prerequisite.
UnlockFlagId = ""
Cells = Array[ExtResource("2_cell")]([@CELLS@])
EnvironmentProfile = SubResource("Environment_frostfang")
GenerationProfile = ExtResource("13_generation")
PerformanceBudget = SubResource("Budget_frostfang")

; The lattice is x 260..600, z -300..70, disjoint from the Ember Crown's x -190..140. The Y range
; carries the aerie summit at +24 and the ash crater floor at -4.
Bounds = AABB(240, -80, -320, 380, 220, 440)
SafeZoneCenter = Vector3(430, 0, -55)
SafeZoneRadius = 30.0
WeavePotency = 0.5
DefaultWeatherId = "weather.clear"
DayPhaseBias = 2
Neighbours = Array[String](["region.ember_crown"])

; The Crossway toll, northbound (Phase 38M). The twin of the block in EmberCrown.tres — same gate,
; same road, same permit — because the toll is declared on the destination and a crossing has two.
TollGold = 25
TollPermitFlagId = "flag.crossway.permit"
TollPassFlagId = "flag.crossway.pass"
'''


def cells() -> list[Cell]:
    return [
        # ------------------------------------------------------------------ row z -10..70 (arrival)
        Cell(
            key="frost_march_w", cell_id="frostfang_reach.frost_march_w",
            scene="res://scenes/regions/frostfang_reach/frost_march_w.tscn",
            center=(345.0, 30.0), size=(170.0, 80.0), resolution=40, seed=206,
            scatter="Scatter_march",
            note="""
            THE WESTERN MARCH — where the road from the Ember Crown comes out of the pass, and where
            the player now arrives. A hundred and ten metres of open snow-country between the portal
            and the Clan Hold's gate, under a scarp that runs most of the cell's width. Nothing here
            but the road and the weather.
            """,
            landforms=(
                Ridge(a=(-85, -24), b=(30, -30), half=19, h=14.0, fall=0.85),
                Mound(at=(-40, 20), ext=(42, 27), h=6.0, fall=0.9),
                Mound(at=(20, 18), ext=(35, 23), h=-3.0, fall=0.9),
                Mound(at=(78, -10), ext=(23, 29), h=3.0, fall=0.95),
            ),
            routes=(Route((70, 25), (75, -10), 5.5, 2.5),),
        ),
        Cell(
            key="frost_march_e", cell_id="frostfang_reach.frost_march_e",
            scene="res://scenes/regions/frostfang_reach/frost_march_e.tscn",
            center=(515.0, 30.0), size=(170.0, 80.0), resolution=40, seed=207,
            scatter="Scatter_march",
            note="""
            THE EASTERN MARCH — a second hundred and seventy metres of nothing, with a herders' track
            off the road that stops in the middle of it. It exists so that the ground south of the
            ash roost is somewhere rather than an edge.
            """,
            landforms=(
                Ridge(a=(-85, -26), b=(85, -22), half=21, h=16.0, fall=0.8),
                Mound(at=(0, 22), ext=(52, 25), h=5.0, fall=0.9),
                Mound(at=(55, -4), ext=(31, 25), h=-4.0, fall=0.9),
            ),
            routes=(Route((-60, 4), (-20, 10), 3.0, 2.0),),
        ),

        # ------------------------------------------------------------------ row z -100..-10 (the holds)
        Cell(
            key="dragon_roost", cell_id="frostfang_reach.dragon_roost",
            scene="res://scenes/regions/frostfang_reach/dragon_roost.tscn",
            center=(315.0, -55.0), size=(110.0, 90.0), resolution=52, seed=202,
            scatter="Scatter_dragon_roost",
            biome="Snowfield",
            note="""
            THE WILD DRAGON'S ROOST — the Splintered Shelf, and it is a shelf. A twelve-metre
            flat-topped platform with 51-degree sides sits in the north-west of the cell and the nest
            is on top of it; the only way up is the shelf path, which climbs twelve metres over
            eighteen and is the steepest walkable ground in the realm on purpose. The splinter field
            east of the narrows is two rock ridges standing out of the ground rather than a scattering
            of boulders, the narrows squeeze between two more, and there is a twenty-metre ice wall
            closing the north. The land drops five metres south of the shelf, so the nest looks down
            on its own approach.
            """,
            # Path_dragon_aerie is gone. It ran north out of this cell to the Ancient's aerie back
            # when the aerie abutted the roost; the aerie is now three cells away up the glacier
            # pass, so that segment pointed at a snowfield seam nothing opened onto — exactly the
            # "a road that points at a wall says nothing" defect of NOW.md invariant 11. The roost
            # is a dead-end shelf reached from the hold, which is what a lair should be.
            legacy_paths=("Path_dragon_approach", "Path_dragon_narrows", "Path_dragon_shelf"),
            legacy_areas=("Area_dragon_bowl", "Area_dragon_splinter"),
            area_elevation={"Area_dragon_bowl": 0.0, "Area_dragon_splinter": -5.16},
            landforms=(
                Ridge(a=(-50, -40), b=(20, -42), half=15, h=20.0, fall=0.35),
                Mound(at=(-44, 0), ext=(21, 35), h=8.0, fall=0.9),
                Mound(at=(-18, 10), ext=(25, 19), h=-5.0, fall=0.5),
                Ridge(a=(14, -24), b=(30, 20), half=7, h=5.0, fall=0.45),
                Ridge(a=(34, -18), b=(44, 16), half=6, h=6.0, fall=0.45),
                Ridge(a=(14, -18), b=(18, -4), half=6, h=9.0, fall=0.4),
                Ridge(a=(2, 6), b=(8, 20), half=6, h=9.0, fall=0.4),
                Mound(at=(-14, -16), ext=(22, 19), h=10.0, fall=0.45, flat=1.0),
            ),
        ),
        Cell(
            key="clan_hold", cell_id="frostfang_reach.clan_hold",
            scene="res://scenes/regions/frostfang_reach/clan_hold.tscn",
            center=(430.0, -55.0), size=(120.0, 90.0), resolution=56, seed=201,
            safe_radius=30.0, scatter="Scatter_hold",
            biome="Alpine",
            note="""
            THE CLAN HOLD — the moot ring, the work terrace and the beast runs survive; what changed
            is that they are no longer three functional zones distributed across a flat 60 m
            platform. A twenty-two-metre mountain wall stands across the whole north of the cell and
            two shoulders of it come down either side, so the hold sits in the shelter the clan chose
            it for. The moot is level ground at zero, the work terrace is genuinely a terrace 2.2 m
            up, and the beast runs are dug 1.6 m down — a settlement that follows its own ground. The
            land falls four metres south into the march, so the hold is above its own road.
            """,
            legacy_paths=("Path_hold_west", "Path_hold_east", "Path_hold_north", "Path_hold_ring",
                          "Path_hold_moot_access", "Path_hold_south"),
            # The east longhouse sits across 0.66 m of the hold's own slope.
            yards=(Yard(at=(-15.0, 10.1), ext=(4.5, 5.6), feather=3.0, blend=0.9),),
            legacy_areas=("Area_hold_moot", "Area_hold_craft", "Area_hold_runs"),
            area_elevation={"Area_hold_moot": 0.0, "Area_hold_craft": 0.0, "Area_hold_runs": 0.0},
            landforms=(
                # THE WALL HAS A PASS IN IT, AND THE PASS IS WHERE THE ROAD IS. Drawn as one
                # 120 m ridge it buried the glacier road under twenty-two metres of mountain and
                # ValidateRouteGrades called it at 63 degrees. It is two ridges with a gap at local
                # x -16..26, which is the only way north out of the hold - the geography making the
                # same argument the toll does at the Crossway.
                Ridge(a=(-60, -30), b=(-16, -33), half=13, h=22.0, fall=0.55),
                Ridge(a=(26, -34), b=(60, -36), half=13, h=22.0, fall=0.55),
                Mound(at=(-46, 14), ext=(21, 27), h=7.0, fall=0.85),
                Mound(at=(48, 10), ext=(23, 29), h=9.0, fall=0.85),
                Mound(at=(0, 40), ext=(48, 19), h=-4.0, fall=0.9),
                Mound(at=(0, 0), ext=(32, 26), h=0.0, fall=0.5, flat=0.85),
                Mound(at=(15, -1), ext=(9, 8), h=2.2, fall=0.35, flat=1.0),
                Mound(at=(-23, 2), ext=(8, 10), h=-1.6, fall=0.4, flat=1.0),
            ),
        ),
        Cell(
            key="ash_roost", cell_id="frostfang_reach.ash_roost",
            scene="res://scenes/regions/frostfang_reach/ash_roost.tscn",
            center=(545.0, -55.0), size=(110.0, 90.0), resolution=52, seed=203,
            tint=(0.20, 0.13, 0.11), tint_strength=0.68, scatter="Scatter_ash_roost",
            biome="AshWaste",
            note="""
            THE ASH ROOST — a real crater and a real causeway. The rim is an eight-metre ring of
            raised ground and the floor inside it is four metres down, so the fight happens twelve
            metres below its own skyline; the only graded way in is the bowl path, which ramps
            through the rim at a walkable angle. The approach is a raised natural causeway with the
            ground dropped six metres on BOTH sides of it — thirty-four metres with nowhere to stand
            except the road, which is what the encounter was always asking the props to do.
            """,
            legacy_paths=("Path_ash_causeway", "Path_ash_bowl", "Path_ash_vent"),
            legacy_areas=("Area_ash_bowl",),
            area_elevation={"Area_ash_bowl": 0.0},
            landforms=(
                Ridge(a=(30, -40), b=(52, 10), half=13, h=16.0, fall=0.5),
                Mound(at=(-34, -24), ext=(25, 19), h=-6.0, fall=0.6),
                Mound(at=(-34, 26), ext=(25, 19), h=-6.0, fall=0.6),
                Ridge(a=(-58, 0), b=(-14, 3), half=8, h=4.0, fall=0.5),
                Mound(at=(12, 5), ext=(35, 31), h=8.0, fall=0.45),
                Ridge(a=(24, -10), b=(40, -22), half=5, h=-3.0, fall=0.4),
                Mound(at=(12, 5), ext=(21, 18), h=-4.0, fall=0.3, flat=1.0),
            ),
        ),

        # ------------------------------------------------------------------ row z -190..-100
        Cell(
            key="north_snowfield", cell_id="frostfang_reach.north_snowfield",
            scene="res://scenes/regions/frostfang_reach/north_snowfield.tscn",
            center=(320.0, -145.0), size=(120.0, 90.0), resolution=36, seed=209,
            scatter="Scatter_snowfield",
            biome="Snowfield",
            note="""
            THE NORTH SNOWFIELD — the shoulder between the glacier pass and the aerie road. A
            fourteen-metre swell, a hollow, a long low ridge and a track across it. Nothing else.
            """,
            landforms=(
                Mound(at=(-30, -10), ext=(42, 35), h=14.0, fall=0.9),
                Mound(at=(30, 20), ext=(35, 27), h=-5.0, fall=0.9),
                Ridge(a=(-60, 32), b=(60, 26), half=15, h=8.0, fall=0.85),
            ),
            routes=(Route((30, -6), (0, -20), 4.0, 2.5),),
        ),
        Cell(
            key="glacier", cell_id="frostfang_reach.glacier",
            scene="res://scenes/regions/frostfang_reach/glacier.tscn",
            center=(440.0, -145.0), size=(120.0, 90.0), resolution=72, seed=205,
            tint=(0.70, 0.84, 0.92), tint_strength=0.30, scatter="Scatter_glacier",
            biome="Glacier",
            note="""
            GLACIER PASS — completely re-thought, purpose intact. It was a 60 x 20 corridor with six
            ice props alternated left and right: a slalom course, and the player could read the
            authoring from the first one. It is a pass now. Two twenty-six-metre walls close the
            north and south of the cell and the route is the ground between them; three spurs of
            differing size and reach come off those walls and none of them alternates regularly; two
            narrow crevasses cut across at 25-degree falloff, which is a slot you go around rather
            than a prop you walk past; and the floor rises eight metres from the southern entry
            before dropping into the saddle. The two pockets are still pockets and still go nowhere,
            but they are wider hollows in the ice rather than gaps between models. Movement weaves
            because the land weaves.
            """,
            legacy_paths=("Path_glacier_entry", "Path_glacier_chicane", "Path_glacier_west",
                          "Path_glacier_east"),
            legacy_areas=("Area_glacier_saddle",),
            area_elevation={"Area_glacier_saddle": -0.9},
            landforms=(
                # The two walls are gapped where the pass enters and leaves. A pass whose mouths
                # are buried under its own walls is a wall.
                Ridge(a=(-60, 40), b=(-14, 42), half=16, h=26.0, fall=0.5),
                Ridge(a=(16, 43), b=(60, 44), half=16, h=26.0, fall=0.5),
                Ridge(a=(-60, -40), b=(-14, -42), half=16, h=26.0, fall=0.5),
                Ridge(a=(16, -43), b=(60, -44), half=16, h=26.0, fall=0.5),
                Mound(at=(0, -20), ext=(70, 42), h=6.0, fall=0.95),
                Mound(at=(-18, -18), ext=(25, 21), h=16.0, fall=0.45),
                Mound(at=(15, 25), ext=(28, 16), h=15.0, fall=0.6),
                Mound(at=(34, -20), ext=(21, 19), h=13.0, fall=0.45),
                Ridge(a=(-46, 10), b=(-30, 22), half=5.0, h=-7.0, fall=0.32, flat=1.0),
                Ridge(a=(14, -28), b=(26, -16), half=4.5, h=-8.0, fall=0.32, flat=1.0),
                Mound(at=(-34, -2), ext=(17, 15), h=-5.0, fall=0.55, flat=0.7),
                Mound(at=(32, 4), ext=(19, 16), h=-4.0, fall=0.55, flat=0.7),
                Mound(at=(0, 0), ext=(13, 11), h=-1.5, fall=0.8, flat=0.8),
            ),
            routes=(Route((0, 0), (-40, -12), 4.0, 2.5),
                    Route((0, 0), (6, -20), 4.0, 2.5)),
        ),
        Cell(
            key="ash_approach", cell_id="frostfang_reach.ash_approach",
            scene="res://scenes/regions/frostfang_reach/ash_approach.tscn",
            center=(550.0, -145.0), size=(100.0, 90.0), resolution=36, seed=210,
            scatter="Scatter_snowfield",
            biome="AshWaste",
            note="""
            THE ASH APPROACH — the unroaded ground behind the crater's northern crags. There is no
            path into it and it needs none: it is the landscape the player sees over the rim from
            inside the fight, and it can be walked to if anyone insists. Deliberately empty.
            """,
            landforms=(
                Ridge(a=(-45, -20), b=(45, -28), half=19, h=20.0, fall=0.7),
                Mound(at=(0, 20), ext=(42, 27), h=-4.0, fall=0.9),
                Mound(at=(-30, 0), ext=(23, 25), h=9.0, fall=0.85),
            ),
        ),

        # ------------------------------------------------------------------ row z -300..-190 (the heights)
        Cell(
            key="ancient_aerie", cell_id="frostfang_reach.ancient_aerie",
            scene="res://scenes/regions/frostfang_reach/ancient_aerie.tscn",
            center=(330.0, -245.0), size=(140.0, 110.0), resolution=60, seed=204,
            tint=(0.67, 0.72, 0.82), tint_strength=0.16, scatter="Scatter_heights",
            biome="Snowfield",
            note="""
            THE ANCIENT AERIE — an aerie that is finally high. The cell is a massif: the ground rises
            eighteen metres from its southern edge to a levelled summit court at twenty, and
            the crescent of standing stones and the nest are up there. Three precipices are cut into
            it — fourteen metres west, sixteen east and eighteen off the north face directly behind
            the crescent — so the court stands on the edge of nothing on three sides and the vista is
            the reveal. The bent procession is now genuinely bent: it switchbacks west and then back
            east up the last eleven metres, because a straight line up that face would be a
            thirty-nine-degree ramp. The hidden hoard is a notch stepped a metre below the court
            behind the east horn, out of sight from the procession.
            """,
            legacy_paths=("Path_aerie_crescent", "Path_aerie_hoard"),
            legacy_areas=("Area_aerie_court", "Area_aerie_hoard"),
            area_elevation={"Area_aerie_court": 0.0, "Area_aerie_hoard": 0.0},
            landforms=(
                Mound(at=(0, -10), ext=(58, 54), h=18.0, fall=0.95),
                Mound(at=(-46, 40), ext=(27, 23), h=4.0, fall=0.9),
                Mound(at=(-6, -18), ext=(23, 19), h=20.0, fall=0.3, flat=1.0),
                Mound(at=(16, -10), ext=(9, 8), h=19.0, fall=0.3, flat=1.0),
                Mound(at=(-54, -30), ext=(23, 27), h=-14.0, fall=0.35),
                Mound(at=(56, -34), ext=(23, 27), h=-16.0, fall=0.35),
                Mound(at=(0, -50), ext=(62, 21), h=-18.0, fall=0.3),
            ),
            # The bent procession, re-cut as a switchback. The legacy straight run (0,20)->(0,6)
            # would be a 39-degree ramp against the new massif; these two are 20 degrees.
            routes=(Route((0, 55), (18, 42), 5.5, 3.0),
                    Route((18, 42), (8, 30), 5.5, 3.0),
                    Route((8, 30), (0, 20), 5.5, 3.0),
                    Route((0, 20), (10, 13), 4.5, 2.0),
                    Route((10, 13), (0, 6), 4.5, 2.0)),
        ),
        Cell(
            key="aerie_ascent", cell_id="frostfang_reach.aerie_ascent",
            scene="res://scenes/regions/frostfang_reach/aerie_ascent.tscn",
            center=(500.0, -245.0), size=(200.0, 110.0), resolution=44, seed=208,
            scatter="Scatter_heights",
            biome="Alpine",
            note="""
            THE AERIE ASCENT — two hundred metres of high traverse between the glacier pass and the
            massif, under a thirty-metre range. A hundred metres of road with a corrie below it and
            nothing on it. This is the cell that makes the aerie feel remote rather than adjacent.
            """,
            landforms=(
                Ridge(a=(-100, -20), b=(100, -30), half=27, h=30.0, fall=0.7),
                Mound(at=(-70, 10), ext=(42, 35), h=16.0, fall=0.85),
                Mound(at=(20, 20), ext=(52, 31), h=8.0, fall=0.9),
                Mound(at=(75, 4), ext=(35, 31), h=12.0, fall=0.9),
                Mound(at=(-40, -40), ext=(31, 23), h=-10.0, fall=0.45),
            ),
            routes=(Route((-40, 30), (-70, 6), 5.0, 3.0),),
        ),
    ]


def seams() -> list[Seam]:
    return [
        Seam("frost_march_w", "frost_march_e", (430, 30), (75, -10), (-60, 4), 4.0, 2.0),
        Seam("frost_march_w", "clan_hold", (420, -10), (75, -10), (0, 20), 5.5, 2.5),
        Seam("clan_hold", "dragon_roost", (370, -55), (-30, 0), (45, 0), 5.5, 2.5),
        Seam("clan_hold", "ash_roost", (490, -55), (30, 0), (-40, 1), 6.0, 3.0),
        Seam("clan_hold", "glacier", (440, -100), (0, -30), (0, 10), 6.0, 2.5),
        Seam("glacier", "north_snowfield", (380, -145), (-40, -12), (30, -6), 4.0, 2.5),
        Seam("glacier", "aerie_ascent", (440, -190), (6, -20), (-40, 30), 5.0, 3.0),
        Seam("north_snowfield", "ancient_aerie", (330, -190), (0, -20), (0, 55), 5.0, 3.0),
        Seam("aerie_ascent", "ancient_aerie", (400, -245), (-70, 6), (40, 4), 5.0, 3.0),
    ]


def build_frostfang(legacy: dict[str, str]) -> tuple[str, list[str]]:
    spec = cells()
    by_key = {c.key: c for c in spec}
    link = seams()

    issues = check_tiling("FrostfangReach", spec, ROWS, EXTENT_X)
    issues += check_seams("FrostfangReach", by_key, link)

    routed = {c.key: list(c.routes) for c in spec}
    for seam in link:
        routed[seam.a].append(Route(seam.reach_a, local(by_key[seam.a], seam.at)))
        routed[seam.b].append(Route(local(by_key[seam.b], seam.at), seam.reach_b))
    issues += check_envelopes("FrostfangReach", spec, routed)

    return emit("frostfang_reach", HEADER, spec, link, legacy,
                ENVIRONMENT, BUDGET, RESOURCE, SCATTER, "Alpine"), issues
