#!/usr/bin/env python3
"""The Celestial Realm's macro layout, geography and assault road. Consumed by tools/gen_regions.py.

Started from tools/region_spec_template.py (the finish run, Act IV). The ruined realm of the dead
gods: shattered terraces hanging over a void rift under an ember sky, broken divine architecture, and
one ascending road from the arrival landing to the Ash Throne. It is reached only by the story portal
in the Sunspire library once flag.celestial_gate_open is set, has no ordinary neighbour and no fast
travel in, and is COMPACT on purpose (nine cells): an assault, not a country.

    1. macro geography    a raised spine of terraces between two void flanks, cut by one rift
    2. POI placement      the landing (where the gate lets out), the Knight's gate (the only bridge
                          over the rift), the Ash Throne (the highest dais in the realm)
    3. route network      one road that climbs terrace to terrace, crosses the rift on the Knight's
                          bridge and ends at the dais
    4. negative space     six of nine cells carry nothing but broken ground and the view down
    6. biome + materials  CelestialRuin (worked stone under ash), and a light no other realm has
"""

from __future__ import annotations

from gen_regions import (Cell, Mound, Ridge, Road, check_envelopes, check_tiling, emit,
                         place_world, realize_roads)

# --------------------------------------------------------------------------------------------------
# 1. MACRO GEOGRAPHY — the lattice. The atlas band is x 2400..3200, z -2400..-1600
# (docs/WORLD_ATLAS.md, tools/world_atlas.py); the lattice sits inside it with a margin.
# --------------------------------------------------------------------------------------------------
EXTENT_X = (2480.0, 3120.0)
_ROW_BREAKS = [-2340.0, -2110.0, -1880.0, -1660.0]
ROWS = list(zip(_ROW_BREAKS, _ROW_BREAKS[1:]))
# Irregular, and chosen after the three places (see check_world_composition.py).
COLUMNS = {
    0: [2700.0, 2910.0],
    1: [2690.0, 2920.0],
    2: [2710.0, 2900.0],
}

# The three places, in world space.
LANDING = (2632.0, -1712.0)   # where the story gate lets the player out
GATE = (2842.0, -2032.0)      # the Ashen Knight's gate, at the far end of the only bridge
THRONE = (2776.0, -2262.0)    # the Ash Throne's dais

HEADER = '''[gd_resource type="Resource" script_class="RegionResource" load_steps=13 format=3 uid="uid://crgncelestial0"]

[ext_resource type="Script" path="res://src/World/RegionResource.cs" id="1_region"]
[ext_resource type="Script" path="res://src/World/RegionCellResource.cs" id="2_cell"]
[ext_resource type="Script" path="res://src/World/WorldEnvironmentProfileResource.cs" id="3_environment"]
[ext_resource type="Script" path="res://src/World/WorldCellPresentationResource.cs" id="4_presentation"]
[ext_resource type="Script" path="res://src/World/WorldPerformanceBudgetResource.cs" id="5_budget"]
[ext_resource type="Script" path="res://src/World/WorldPathSegmentResource.cs" id="6_path"]
[ext_resource type="Script" path="res://src/World/WorldGroundAreaResource.cs" id="7_area"]
[ext_resource type="Script" path="res://src/World/WorldLandformResource.cs" id="8_landform"]
[ext_resource type="Script" path="res://src/World/WorldBiomeScatterResource.cs" id="9_scatter"]
[ext_resource type="Script" path="res://src/World/BiomeScatterLayerResource.cs" id="10_layer"]
[ext_resource type="Script" path="res://src/World/BiomeScatterExclusionResource.cs" id="11_exclusion"]
[ext_resource type="Script" path="res://src/World/WorldWaterResource.cs" id="12_water"]
[ext_resource type="Resource" path="res://data/world_gen/CelestialRealm.tres" id="13_generation"]

; ⚠️ GENERATED BY tools/gen_regions.py FROM tools/region_spec_celestial.py. Edit the spec.
;
; ====================================================================================================
; THE CELESTIAL REALM (the finish run, Act IV)
; ====================================================================================================
;
; The ruined realm of the dead gods. The story gate in the Sunspire library lets out on a raised
; landing at the south-west; the road climbs two broken concourse terraces north-east, crosses the
; void rift on the one bridge left standing and meets the Ashen Knight at the gate beyond it. The
; Ash Throne stands on the highest dais at the north of the realm. East and west, the terraces
; fall away into void. Nine cells, six of them nothing but broken ground and the view down.
;
; NO NEIGHBOUR IN, NO FAST TRAVEL IN. Nothing lists this region as a neighbour; the Sunspire library's
; story portal (owned by the main line) is the only way here. UnlockFlagId is still set, so any
; future door into the realm is gated on the same flag without a code change.
'''

# --------------------------------------------------------------------------------------------------
# 6. ATMOSPHERE — the light IS the realm. Every other realm is lit by a sun; this one is lit by the
# fire the gods died in: a low ember key light, a weak sun and a thick violet-ash haze that turns
# the far terraces into silhouettes. No other region's SunTint is this red or its haze this dark.
# --------------------------------------------------------------------------------------------------
ENVIRONMENT = '''[sub_resource type="Resource" id="Environment_celestial"]
script = ExtResource("3_environment")
SurfaceColor = Color(0.36, 0.33, 0.34, 1)
SecondaryColor = Color(0.24, 0.21, 0.22, 1)
DetailColor = Color(0.14, 0.12, 0.13, 1)
RoadColor = Color(0.52, 0.47, 0.44, 1)
BackdropColor = Color(0.10, 0.07, 0.10, 1)
Relief = 1.0
DetailScale = 3.0
BackdropRadius = 360.0
BackdropHeight = 108.0
TerrainSeed = 4700
SurfaceRoughness = 0.9
DetailRoughness = 0.86
RoadRoughness = 0.7
SlopeBlendStart = 0.24
SlopeBlendEnd = 0.6
HeightBlendStart = 24.0
HeightBlendEnd = 44.0
SunTint = Color(1.0, 0.56, 0.40, 1)
SunEnergyScale = 0.7
HazeColor = Color(0.27, 0.17, 0.25, 1)
HazeScale = 1.25

'''

BUDGET = '''[sub_resource type="Resource" id="Budget_celestial"]
script = ExtResource("5_budget")
MaxAuthoredNodesPerCell = 400
MaxResidentAuthoredNodes = 3000
MaxResidentRuntimeNodes = 9000
MaxScatterInstancesPerCell = 4000
MaxResidentScatterInstances = 40000
MaxTerrainVerticesPerCell = 7000
MaxResidentTerrainVertices = 70000
MaxDrawCalls = 1800
MaxNodeCount = 20000
MaxStaticMemoryMb = 2048.0
MaxFrameMilliseconds = 16.67
ConsecutiveSamplesBeforeWarning = 5
BiomeCullDistance = 340.0
VisibilityUpdateInterval = 0.25
MaxConcurrentLoadRequests = 2
MaxCellInstantiationsPerFrame = 1

; A compact realm: Backdrop covers the lattice diagonal, so the throne's dais reads from the landing.
NearDistance = 95.0
MidDistance = 190.0
FarDistance = 420.0
BackdropDistance = 1100.0

'''

# 8. SCATTER — broken stone and the shards of heaven. No trees and no grass: nothing grows here.
SCATTER = '''[sub_resource type="Resource" id="Layer_rubble"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_rock_cluster.glb"
Count = 60
MinimumScale = 0.5
MaximumScale = 1.3
MinimumSpacing = 4.0
Saturation = 0.2
Clumping = 0.6
ClumpScale = 30.0
MaxSlope = 1.0
Tint = Color(0.62, 0.56, 0.58, 1)
TintVariation = 0.12
VisibilityRangeEnd = 140.0
VisibilityFadeMargin = 20.0
HlodShape = 2
HlodReduction = 5
HlodRangeBegin = 118.0
HlodRangeEnd = 290.0
HlodColor = Color(0.7, 0.66, 0.68, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

[sub_resource type="Resource" id="Layer_rubble_b"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_rock_cluster_a.glb"
Count = 36
MinimumScale = 0.3
MaximumScale = 0.7
MinimumSpacing = 7.0
Saturation = 0.2
Clumping = 0.55
ClumpScale = 26.0
MaxSlope = 0.95
Tint = Color(0.6, 0.55, 0.56, 1)
TintVariation = 0.12
VisibilityRangeEnd = 130.0
VisibilityFadeMargin = 18.0
CastShadows = true

[sub_resource type="Resource" id="Layer_ember_shard"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_ice_shard.glb"
Count = 10
MinimumScale = 0.5
MaximumScale = 1.2
MinimumSpacing = 14.0
Saturation = 0.3
Clumping = 0.7
ClumpScale = 36.0
MaxSlope = 0.4
Tint = Color(1.0, 0.62, 0.36, 1)
TintVariation = 0.08
VisibilityRangeEnd = 130.0
VisibilityFadeMargin = 18.0
CastShadows = true

[sub_resource type="Resource" id="Layer_ash_tuft"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_grass_short.glb"
Count = 120
MinimumScale = 0.5
MaximumScale = 0.9
MinimumSpacing = 3.0
Saturation = 0.05
Clumping = 0.5
ClumpScale = 18.0
MaxSlope = 0.5
Tint = Color(0.42, 0.38, 0.38, 1)
TintVariation = 0.1
VisibilityRangeEnd = 48.0
VisibilityFadeMargin = 10.0
CastShadows = false

[sub_resource type="Resource" id="Exclusion_landing"]
script = ExtResource("11_exclusion")
Center = Vector2(37, 58)
Radius = 16.0

[sub_resource type="Resource" id="Exclusion_gate"]
script = ExtResource("11_exclusion")
Center = Vector2(37, -37)
Radius = 26.0

[sub_resource type="Resource" id="Exclusion_throne"]
script = ExtResource("11_exclusion")
Center = Vector2(-29, -37)
Radius = 24.0

[sub_resource type="Resource" id="Scatter_celestial"]
script = ExtResource("9_scatter")
Seed = 4711
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_rubble"), SubResource("Layer_rubble_b"), SubResource("Layer_ember_shard"), SubResource("Layer_ash_tuft")])

[sub_resource type="Resource" id="Scatter_landing"]
script = ExtResource("9_scatter")
Seed = 4712
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_rubble"), SubResource("Layer_rubble_b"), SubResource("Layer_ash_tuft")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_landing")])

[sub_resource type="Resource" id="Scatter_gate"]
script = ExtResource("9_scatter")
Seed = 4713
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_rubble"), SubResource("Layer_rubble_b"), SubResource("Layer_ember_shard")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_gate")])

[sub_resource type="Resource" id="Scatter_throne"]
script = ExtResource("9_scatter")
Seed = 4714
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_rubble"), SubResource("Layer_rubble_b"), SubResource("Layer_ember_shard")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_throne")])

'''

RESOURCE = '''[resource]
script = ExtResource("1_region")
Id = "region.celestial"
DisplayName = "The Celestial Realm"
Realm = 4

; The arrival is the landing the Sunspire library's story gate lets out on. The return portal stands
; on the same landing, a few metres behind the player.
; ⚠️ TEMPORARY: it returns to the Ember Crown, because region.sunspire does not exist on the branch
; this realm was built on and --validate fails an unknown neighbour. When Sunspire lands, change the
; one id below to "region.sunspire" (the portal takes the player to that region's SpawnPoint).
SpawnPoint = @WORLD(2632, 1.2, -1708)@
PortalPoint = @WORLD(2632, 0, -1697)@
; ⚠️ UnlockFlagId IS EMPTY UNTIL THE MAIN LINE SETS flag.celestial_gate_open. --validate fails a region
; that unlocks on a flag nothing sets, and the setter (the Veiled Archive reading) is the main line's.
; When it lands, set UnlockFlagId = "flag.celestial_gate_open" here: a neighbour portal into this
; region then hides until the flag is set (RegionSetup.RebuildPortals), with no code change.
UnlockFlagId = "flag.celestial_gate_open"
Cells = Array[ExtResource("2_cell")]([@CELLS@])
EnvironmentProfile = SubResource("Environment_celestial")
GenerationProfile = ExtResource("13_generation")
PerformanceBudget = SubResource("Budget_celestial")

; The lattice is x 2480..3120, z -2340..-1660, inside its atlas band (x 2400..3200, z -2400..-1600).
Bounds = @BOUNDS(20, -60, 200)@
SafeZoneCenter = @WORLD(2632, 0, -1712)@
SafeZoneRadius = 22.0
WeavePotency = 0.3
DefaultWeatherId = "weather.fog"
DayPhaseBias = 3
; Sealed like the Pale Concord: only the assault encounters that name this realm roll here.
ScopedContentOnly = true
Neighbours = Array[String](["region.sunspire"])
'''

CEL = "res://scenes/regions/celestial/"


def lattice():
    out = {}
    for r, (top, bottom) in enumerate(ROWS):
        xs = [EXTENT_X[0], *COLUMNS[r], EXTENT_X[1]]
        for c in range(len(xs) - 1):
            out[(r, c)] = (((xs[c] + xs[c + 1]) / 2, (top + bottom) / 2), (xs[c + 1] - xs[c], bottom - top))
    return out


def cells() -> list[Cell]:
    L = lattice()

    def cell(key, r, c, seed, scatter="Scatter_celestial", resolution=44, note="", **kw):
        return Cell(key=key, cell_id=f"celestial.{key}", scene=f"{CEL}{key}.tscn",
                    center=L[(r, c)][0], size=L[(r, c)][1], resolution=resolution, seed=seed,
                    scatter=scatter, note=note, **kw)

    return [
        # ================================================================== row 0 — the throne
        cell("shattered_rim", 0, 0, 4701, note="""THE SHATTERED RIM — the west edge of the throne
            terrace, broken off into void. Empty."""),
        cell("ash_throne", 0, 1, 4702, scatter="Scatter_throne", resolution=72, note="""
            THE ASH THRONE — the highest dais in the realm, at its northern end, where Morthul sits. It
            is here because it is the top: every terrace below it climbs toward it, and it is visible
            from the landing across the whole realm. The fight is on the dais; the throne stands at its
            back."""),
        cell("godfall", 0, 2, 4703, note="""GODFALL — broken terraces east of the throne, where a god's
            hall came down. Empty; it is the view from the dais."""),

        # ================================================================== row 1 — the gate
        cell("fallen_choir", 1, 0, 4704, note="""THE FALLEN CHOIR — the west terraces beyond the rift.
            Empty."""),
        cell("knight_gate", 1, 1, 4705, scatter="Scatter_gate", resolution=72, note="""
            THE KNIGHT'S GATE — the last gate before the throne, at the far end of the only bridge left
            over the void rift. The Ashen Knight holds it because there is no other way across: whoever
            reaches the throne crosses this bridge and passes through him."""),
        cell("sundered_stair", 1, 2, 4706, note="""THE SUNDERED STAIR — the east flank of the gate
            terrace, stairs to nowhere. Empty."""),

        # ================================================================== row 2 — the arrival
        cell("landing", 2, 0, 4707, scatter="Scatter_landing", resolution=56, safe_radius=18.0, note="""
            THE LANDING — where the Sunspire library's story gate lets the player out, on the one
            terrace at the realm's south-west edge that still holds a whole floor. The return portal
            stands behind the arrival point."""),
        cell("broken_concourse", 2, 1, 4708, resolution=56, note="""
            THE BROKEN CONCOURSE — two shattered processional terraces the road climbs between the
            landing and the rift. The assault's first resistance meets the player here."""),
        cell("void_edge", 2, 2, 4709, note="""THE VOID EDGE — the south-east, where the terraces end.
            Empty."""),
    ]


def roads() -> list[Road]:
    return [
        # The assault road: landing -> concourse terraces -> the Knight's bridge -> the gate.
        Road((LANDING, (2668.0, -1760.0), (2700.0, -1800.0), (2750.0, -1846.0), (2790.0, -1872.0),
              (2816.0, -1930.0), (2832.0, -1990.0), (GATE[0], GATE[1] + 22.0)), width=6.0, shoulder=2.5),
        # Through the gate and up to the dais.
        Road(((GATE[0], GATE[1] - 22.0), (2820.0, -2120.0), (2796.0, -2192.0), (THRONE[0], THRONE[1] + 20.0)),
             width=6.0, shoulder=2.5),
    ]


def geography() -> list:
    return [
        # The void flanks: the terraces fall away east and west of the spine.
        Ridge(a=(2500, -2330), b=(2530, -1680), half=40, h=-30.0, fall=0.55),
        Ridge(a=(3100, -2330), b=(3080, -1680), half=40, h=-30.0, fall=0.55),
        # The void rift between the concourse and the gate, broken by one natural stone bridge — the
        # Knight's bridge — where the road crosses at x ~2818. The two halves stop short of it.
        Ridge(a=(2560, -1938), b=(2786, -1934), half=16, h=-24.0, fall=0.35),
        Ridge(a=(2850, -1932), b=(3060, -1928), half=16, h=-24.0, fall=0.35),
        # The landing: a raised whole floor.
        Mound(at=LANDING, ext=(40.0, 34.0), h=3.0, fall=0.5, flat=1.0),
        # The concourse terraces, stepping up toward the rift.
        Mound(at=(2700.0, -1800.0), ext=(34.0, 26.0), h=4.0, fall=0.5, flat=1.0),
        Mound(at=(2790.0, -1868.0), ext=(36.0, 24.0), h=6.0, fall=0.5, flat=1.0),
        # The gate terrace: the arena floor, level across the whole ring.
        Mound(at=GATE, ext=(52.0, 48.0), h=8.0, fall=0.45, flat=1.0),
        # The throne dais: the highest ground in the realm.
        Mound(at=THRONE, ext=(48.0, 46.0), h=12.0, fall=0.5, flat=1.0),
        # Broken terraces in the empty country, so the view down is of ruin rather than a slope.
        Mound(at=(2600.0, -2200.0), ext=(40.0, 30.0), h=12.0, fall=0.3, flat=1.0),
        Mound(at=(3000.0, -2230.0), ext=(46.0, 32.0), h=16.0, fall=0.3, flat=1.0),
        Mound(at=(2600.0, -2030.0), ext=(36.0, 28.0), h=8.0, fall=0.3, flat=1.0),
        Mound(at=(3010.0, -2010.0), ext=(34.0, 30.0), h=10.0, fall=0.3, flat=1.0),
        Mound(at=(3000.0, -1760.0), ext=(40.0, 30.0), h=6.0, fall=0.3, flat=1.0),
    ]


def build_celestial() -> tuple[str, list[str]]:
    spec = cells()
    issues = check_tiling("CelestialRealm", spec, ROWS, EXTENT_X)
    spec = place_world(spec, geography())
    spec, road_issues = realize_roads(spec, roads())
    issues += [f"CelestialRealm: {issue}" for issue in road_issues]
    issues += check_envelopes("CelestialRealm", spec, {c.key: list(c.routes) for c in spec})
    return emit("celestial", HEADER, spec, [], ENVIRONMENT, BUDGET, RESOURCE, SCATTER, "CelestialRuin"), issues


if __name__ == "__main__":
    _text, _issues = build_celestial()
    for _issue in _issues:
        print(f"LATTICE ERROR: {_issue}")
    print("self-check: FAILED" if _issues else f"self-check: builds ({len(_text)} bytes), lattice sound")
    raise SystemExit(1 if _issues else 0)
