#!/usr/bin/env python3
"""The Sunspire Dominion's macro layout, geography and approaches. Consumed by tools/gen_regions.py.

Started from tools/region_spec_template.py (not from another realm's spec). The workflow order in
that file's docstring is the order this one was written in.
"""

from __future__ import annotations

import re

from gen_regions import (Cell, Mound, Ridge, Road, Route, Water, Yard, apply_origins,
                         check_envelopes, check_tiling, emit, place_world, realize_roads)

# --------------------------------------------------------------------------------------------------
# 1. MACRO GEOGRAPHY — the lattice
# --------------------------------------------------------------------------------------------------
# The Dominion's band in the atlas (docs/WORLD_ATLAS.md) is x -800..800, z 900..2300: south of the
# Ember Crown beyond the Southmarch Gate. The realm is COMPACT (docs/playbook/finish.md): twenty cells
# across 780 x 900 m in the north-west corner of that band, which leaves the rest of the band for
# anything later that wants it. Columns are irregular and were chosen after the places.
EXTENT_X = (-380.0, 400.0)
_ROW_BREAKS = [900.0, 1070.0, 1250.0, 1430.0, 1610.0, 1790.0]
ROWS = list(zip(_ROW_BREAKS, _ROW_BREAKS[1:]))
COLUMNS = {
    0: [-150.0, 90.0, 250.0],
    1: [-190.0, -10.0, 220.0],
    2: [-130.0, 90.0, 250.0],
    3: [-210.0, -10.0, 180.0],
    4: [-160.0, 60.0, 230.0],
}

HEADER = '''[gd_resource type="Resource" script_class="RegionResource" load_steps=12 format=3 uid="uid://crgnsunspire0"]

[ext_resource type="Script" path="res://src/World/RegionResource.cs" id="1_region"]
[ext_resource type="Script" path="res://src/World/RegionCellResource.cs" id="2_cell"]
[ext_resource type="Script" path="res://src/World/WorldEnvironmentProfileResource.cs" id="3_environment"]
[ext_resource type="Script" path="res://src/World/WorldCellPresentationResource.cs" id="4_presentation"]
[ext_resource type="Script" path="res://src/World/WorldPerformanceBudgetResource.cs" id="5_budget"]
[ext_resource type="Script" path="res://src/World/WorldPathSegmentResource.cs" id="6_path"]
[ext_resource type="Script" path="res://src/World/WorldGroundAreaResource.cs" id="7_area"]
[ext_resource type="Script" path="res://src/World/WorldLandformResource.cs" id="8_landform"]
[ext_resource type="Script" path="res://src/World/WorldBiomeScatterResource.cs" id="9_scatter"]
[ext_resource type="Script" path="res://src/World/BiomeScatterLayerResource.cs" id="10_layer"]
[ext_resource type="Script" path="res://src/World/BiomeScatterExclusionResource.cs" id="11_exclusion"]
[ext_resource type="Script" path="res://src/World/WorldWaterResource.cs" id="12_water"]
[ext_resource type="Resource" path="res://data/world_gen/Sunspire.tres" id="13_generation"]

; ⚠️ GENERATED BY tools/gen_regions.py FROM tools/region_spec_sunspire.py. Edit the spec.
;
; ====================================================================================================
; THE SUNSPIRE DOMINION
; ====================================================================================================
;
; South beyond the Southmarch Gate. The caravan road comes through a gap in the northern escarpment
; into the dry basins, crosses them between two mesas and drops into the water-fed jungle belt, where
; Saffra Wells keeps the oasis and the caravans. West of the wells, at the foot of the library mesa,
; the Veiled Archive's great library stands half-buried in the sand of an older civilisation. South of
; the belt the country dries and reddens again up to the Crimson Mission, the Prophet's seat, whose
; walled sanctum is where the fifth Flamebearer is fought.
;
; Fourteen of the twenty cells carry ground, weather, ecology and at most a road. Do not fill them in.
'''

# --------------------------------------------------------------------------------------------------
# 6. BIOME, MATERIALS AND ATMOSPHERE
# --------------------------------------------------------------------------------------------------
# Desert (data/biomes/Desert.tres) is new: loose sand is the one ground identity none of the ten
# shipped biomes had. The jungle belt reuses Woodland and Wetland. The LIGHT does most of the work:
# a hot white-gold key and thick pale haze, the opposite of Frostfang's cold blue air.
ENVIRONMENT = '''[sub_resource type="Resource" id="Environment_sunspire"]
script = ExtResource("3_environment")
SurfaceColor = Color(0.62, 0.52, 0.36, 1)
SecondaryColor = Color(0.55, 0.46, 0.33, 1)
DetailColor = Color(0.30, 0.24, 0.17, 1)
RoadColor = Color(0.52, 0.44, 0.32, 1)
BackdropColor = Color(0.46, 0.36, 0.26, 1)
Relief = 1.8
DetailScale = 2.5
BackdropRadius = 340.0
BackdropHeight = 135.0
TerrainSeed = 4400
SurfaceRoughness = 0.95
DetailRoughness = 0.88
RoadRoughness = 0.84
SlopeBlendStart = 0.26
SlopeBlendEnd = 0.64
HeightBlendStart = 14.0
HeightBlendEnd = 34.0
SunTint = Color(1.0, 0.9, 0.74, 1)
SunEnergyScale = 1.12
HazeColor = Color(0.86, 0.75, 0.58, 1)
HazeScale = 1.2

'''

BUDGET = '''[sub_resource type="Resource" id="Budget_sunspire"]
script = ExtResource("5_budget")
MaxAuthoredNodesPerCell = 400
MaxResidentAuthoredNodes = 4000
MaxResidentRuntimeNodes = 9000
MaxScatterInstancesPerCell = 7000
MaxResidentScatterInstances = 160000
MaxTerrainVerticesPerCell = 7000
MaxResidentTerrainVertices = 260000
MaxDrawCalls = 1800
MaxNodeCount = 30000
MaxStaticMemoryMb = 2048.0
MaxFrameMilliseconds = 16.67
ConsecutiveSamplesBeforeWarning = 5
BiomeCullDistance = 340.0
VisibilityUpdateInterval = 0.25
MaxConcurrentLoadRequests = 2
MaxCellInstantiationsPerFrame = 1

; A compact realm: Backdrop covers the whole lattice diagonal (~1.2 km), so the mesas and the
; mission read from the arrival.
NearDistance = 95.0
MidDistance = 190.0
FarDistance = 420.0
BackdropDistance = 1300.0

'''

# --------------------------------------------------------------------------------------------------
# 8. SCATTER — the region's ecology
# --------------------------------------------------------------------------------------------------
SCATTER = '''[sub_resource type="Resource" id="Layer_desert_rock"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_rock_rubble_a.glb"
Count = 32
MinimumScale = 0.45
MaximumScale = 1.2
MinimumSpacing = 6.0
Saturation = 0.55
Clumping = 0.55
ClumpScale = 30.0
MaxSlope = 1.0
Tint = Color(0.92, 0.78, 0.6, 1)
TintVariation = 0.12
VisibilityRangeEnd = 140.0
VisibilityFadeMargin = 18.0
CastShadows = true
HlodShape = 2
HlodReduction = 5
HlodRangeBegin = 120.0
HlodRangeEnd = 290.0
HlodColor = Color(0.88, 0.8, 0.7, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

[sub_resource type="Resource" id="Layer_dry_grass"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_grass_clump_a.glb"
Count = 150
MinimumScale = 0.55
MaximumScale = 1.0
MinimumSpacing = 3.0
Saturation = 0.35
Clumping = 0.6
ClumpScale = 26.0
MaxSlope = 0.55
Tint = Color(0.98, 0.84, 0.58, 1)
TintVariation = 0.16
VisibilityRangeEnd = 55.0
VisibilityFadeMargin = 10.0
CastShadows = false

; Wind-killed trunks in the open basins: few, far apart and bleached.
[sub_resource type="Resource" id="Layer_dead_tree"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_tree_dead_a.glb"
Count = 6
MinimumScale = 0.7
MaximumScale = 1.3
MinimumSpacing = 18.0
Saturation = 0.3
Clumping = 0.5
ClumpScale = 60.0
MaxSlope = 0.35
Tint = Color(0.95, 0.85, 0.72, 1)
TintVariation = 0.08
VisibilityRangeEnd = 150.0
VisibilityFadeMargin = 20.0

; Sandstone spires: the jagged rock at 1.0-2.2 (6-13 m), three per 100 x 100 m of open desert.
; The desert had nothing taller than a man in it. No collision, like every scatter layer.
[sub_resource type="Resource" id="Layer_desert_crag"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_rock_crag_a.glb"
Count = 3
MinimumScale = 1.0
MaximumScale = 2.2
MinimumSpacing = 26.0
Saturation = 0.45
Clumping = 0.6
ClumpScale = 80.0
MaxSlope = 0.6
Tint = Color(1.5, 1.2, 0.86, 1)
TintVariation = 0.1
VisibilityRangeEnd = 190.0
VisibilityFadeMargin = 24.0
CastShadows = true
HlodShape = 1
HlodReduction = 2
HlodRangeBegin = 170.0
HlodRangeEnd = 380.0
HlodColor = Color(1.5, 1.2, 0.86, 1)
HlodScale = Vector3(1.1, 1.1, 1.1)

; The tor: the boulder at 2.5-4, a 10-16 m sandstone mass, one per 100 x 100 m of open desert.
[sub_resource type="Resource" id="Layer_desert_tor"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_rock_boulder_a.glb"
Count = 1
MinimumScale = 2.5
MaximumScale = 4.0
MinimumSpacing = 60.0
Saturation = 0.55
Clumping = 0.6
ClumpScale = 90.0
MaxSlope = 0.5
Tint = Color(1.2, 1.0, 0.76, 1)
TintVariation = 0.08
VisibilityRangeEnd = 220.0
VisibilityFadeMargin = 26.0
CastShadows = true
HlodShape = 1
HlodReduction = 2
HlodRangeBegin = 200.0
HlodRangeEnd = 420.0
HlodColor = Color(1.2, 1.0, 0.76, 1)
HlodScale = Vector3(1.1, 1.1, 1.1)

; The jungle belt is the Ember Crown's oak under a warm yellow-green tint: there is no palm in the
; set. 10-18 m with an 8.5 m crown at scale 1, so 90 where the old 3 m-wide tree needed 150.
[sub_resource type="Resource" id="Layer_jungle_tree"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_tree_oak_a.glb"
Count = 90
MinimumScale = 0.8
MaximumScale = 1.5
MinimumSpacing = 8.5
Saturation = 1.0
Clumping = 0.7
ClumpScale = 40.0
MaxSlope = 0.42
Tint = Color(1.05, 1.0, 0.72, 1)
TintVariation = 0.18
VisibilityRangeEnd = 150.0
VisibilityFadeMargin = 22.0
CastShadows = true
HlodShape = 1
HlodReduction = 3
HlodRangeBegin = 130.0
HlodRangeEnd = 320.0
HlodColor = Color(1.05, 1.0, 0.72, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

; Elder trees of the jungle belt: the oak at 1.8-2.4 (22-29 m), three per 100 x 100 m, held to the
; interior of a stand by a Clumping above Layer_jungle_tree's on the same ClumpScale. Not in the
; Wells profile: a town does not get a walk-through trunk.
[sub_resource type="Resource" id="Layer_jungle_elder"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_tree_oak_a.glb"
Count = 3
MinimumScale = 1.8
MaximumScale = 2.4
MinimumSpacing = 28.0
Clumping = 0.9
ClumpScale = 40.0
MaxSlope = 0.36
Tint = Color(1.0, 0.96, 0.7, 1)
TintVariation = 0.1
VisibilityRangeEnd = 220.0
VisibilityFadeMargin = 26.0
CastShadows = true
HlodShape = 1
HlodReduction = 2
HlodRangeBegin = 200.0
HlodRangeEnd = 420.0
HlodColor = Color(0.8, 0.9, 0.75, 1)
HlodScale = Vector3(1.1, 1.1, 1.1)

[sub_resource type="Resource" id="Layer_fern"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_fern_clump_a.glb"
Count = 260
MinimumScale = 1.0
MaximumScale = 1.8
MinimumSpacing = 2.2
Clumping = 0.55
ClumpScale = 22.0
MaxSlope = 0.6
Tint = Color(0.8, 0.95, 0.62, 1)
TintVariation = 0.2
VisibilityRangeEnd = 60.0
VisibilityFadeMargin = 12.0
CastShadows = false

[sub_resource type="Resource" id="Layer_jungle_grass"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_grass_clump_a.glb"
Count = 520
MinimumScale = 1.0
MaximumScale = 1.7
MinimumSpacing = 1.6
Clumping = 0.35
ClumpScale = 20.0
MaxSlope = 0.55
Tint = Color(0.82, 0.92, 0.6, 1)
TintVariation = 0.2
VisibilityRangeEnd = 60.0
VisibilityFadeMargin = 12.0
CastShadows = false

[sub_resource type="Resource" id="Layer_bush"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_fern_clump_a.glb"
Count = 36
MinimumScale = 1.3
MaximumScale = 1.8
MinimumSpacing = 4.0
Clumping = 0.6
ClumpScale = 28.0
MaxSlope = 0.6
Tint = Color(0.5, 0.6, 0.36, 1)
TintVariation = 0.16
VisibilityRangeEnd = 90.0
VisibilityFadeMargin = 14.0
CastShadows = false

; The mission's sanctum and the library forecourt stay bare: a fight floor and a place two story
; portals will stand. Centres are in each cell's CONTENT frame and move with it (see EXCLUSION_OWNERS).
[sub_resource type="Resource" id="Exclusion_temple_court"]
script = ExtResource("11_exclusion")
Center = Vector2(0, 0)
Radius = 30.0

[sub_resource type="Resource" id="Exclusion_library_court"]
script = ExtResource("11_exclusion")
Center = Vector2(0, 2)
Radius = 22.0

[sub_resource type="Resource" id="Exclusion_wells_plaza"]
script = ExtResource("11_exclusion")
Center = Vector2(4, -4)
Radius = 20.0

[sub_resource type="Resource" id="Scatter_desert"]
script = ExtResource("9_scatter")
Seed = 6401
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_desert_rock"), SubResource("Layer_dry_grass"), SubResource("Layer_dead_tree"), SubResource("Layer_desert_crag"), SubResource("Layer_desert_tor")])

[sub_resource type="Resource" id="Scatter_jungle"]
script = ExtResource("9_scatter")
Seed = 6402
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_jungle_tree"), SubResource("Layer_jungle_elder"), SubResource("Layer_fern"), SubResource("Layer_jungle_grass"), SubResource("Layer_bush")])

[sub_resource type="Resource" id="Scatter_wells"]
script = ExtResource("9_scatter")
Seed = 6403
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_jungle_tree"), SubResource("Layer_fern"), SubResource("Layer_jungle_grass")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_wells_plaza")])

[sub_resource type="Resource" id="Scatter_library"]
script = ExtResource("9_scatter")
Seed = 6404
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_desert_rock"), SubResource("Layer_dry_grass")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_library_court")])

[sub_resource type="Resource" id="Scatter_temple"]
script = ExtResource("9_scatter")
Seed = 6405
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_desert_rock"), SubResource("Layer_dry_grass")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_temple_court")])

'''

RESOURCE = '''[resource]
script = ExtResource("1_region")
Id = "region.sunspire"
DisplayName = "The Sunspire Dominion"
Realm = 3

; The arrival is the caravan road's gap in the northern escarpment; the portal back to the Ember
; Crown's Southmarch Gate stands in the gap behind the player.
SpawnPoint = @WORLD(60, 1.2, 936)@
PortalPoint = @WORLD(60, 0, 916)@

; ⚠️ EARNED, NOT OPEN (docs/playbook/finish.md). The Southmarch Gate's portal into this realm hides
; until the Iron King falls; RegionSetup feeds this to the portal's RequiredFlagId. The return door
; reads the Ember Crown's UnlockFlagId, which is empty, so nobody is ever shut in here.
UnlockFlagId = "flag.iron_king_defeated"
Cells = Array[ExtResource("2_cell")]([@CELLS@])
EnvironmentProfile = SubResource("Environment_sunspire")
GenerationProfile = ExtResource("13_generation")
PerformanceBudget = SubResource("Budget_sunspire")

; The lattice is x -380..400, z 900..1790, inside the atlas band and disjoint from every other realm.
Bounds = @BOUNDS(20, -80, 220)@
SafeZoneCenter = @ORIGIN(wells, 0, 0, 0)@
SafeZoneRadius = 45.0
WeavePotency = 0.8
DefaultWeatherId = "weather.clear"
DayPhaseBias = 2
Neighbours = Array[String](["region.ember_crown", "region.pale_concord", "region.celestial"])

; The two story doors stand in the library forecourt, on library.tscn's PaleConcordPortalAnchor and
; CelestialPortalAnchor (cell centre (-295, 1520) + local (37|53, -42)). Each hides until its realm's
; UnlockFlagId is set, and a traveller coming back through one lands in the forecourt beside it.
NeighbourPortalPoints = Array[Vector3]([Vector3(0, 0, 0), @WORLD(-258, 0, 1478)@, @WORLD(-242, 0, 1478)@])
NeighbourArrivalPoints = Array[Vector3]([Vector3(0, 0, 0), @WORLD(-258, 1.2, 1486)@, @WORLD(-242, 1.2, 1486)@])
'''


SUN = "res://scenes/regions/sunspire/"


def empty(key, center, size, seed, scatter, biome=None, note="", resolution=None):
    """Open country: ground, weather, ecology and at most a road — no gameplay beat."""
    if resolution is None:
        resolution = min(80, max(36, int(max(size) / 2.8)))
    return Cell(key=key, cell_id=f"sunspire.{key}", scene=f"{SUN}{key}.tscn",
                center=center, size=size, resolution=resolution, seed=seed, scatter=scatter,
                biome=biome, note=note)


def lattice():
    out = {}
    for r, (top, bottom) in enumerate(ROWS):
        xs = [EXTENT_X[0], *COLUMNS[r], EXTENT_X[1]]
        for c in range(len(xs) - 1):
            out[(r, c)] = (((xs[c] + xs[c + 1]) / 2, (top + bottom) / 2), (xs[c + 1] - xs[c], bottom - top))
    return out


# Where each scatter clearing sits in its OWN content frame; shifted with the content.
EXCLUSION_OWNERS = {
    "Exclusion_temple_court": "temple",
    "Exclusion_library_court": "library",
    "Exclusion_wells_plaza": "wells",
}

WELLS = (10.0, 1290.0)
LIBRARY = (-250.0, 1470.0)
TEMPLE = (190.0, 1680.0)


def cells() -> list[Cell]:
    L = lattice()

    def at(r, c):
        return {"center": L[(r, c)][0], "size": L[(r, c)][1]}

    return [
        # ================================================================== row 0 — the escarpment
        empty("north_dunes_w", **at(0, 0), seed=701, scatter="Scatter_desert", biome="Desert"),
        empty("caravan_gap", **at(0, 1), seed=702, scatter="Scatter_desert", biome="Desert", note="""
            THE CARAVAN GAP — the caravan road from the Southmarch Gate comes through the one gap in
            the northern escarpment here, and the portal home stands in it. Nothing else."""),
        empty("north_dunes_e", **at(0, 2), seed=703, scatter="Scatter_desert", biome="Desert"),
        empty("northeast_scarp", **at(0, 3), seed=704, scatter="Scatter_desert", biome="Desert"),

        # ================================================================== row 1 — the dry basins
        empty("west_mesa", **at(1, 0), seed=711, scatter="Scatter_desert", biome="Desert", note="""
            THE WEST MESA — a flat-topped upland west of the caravan road; the road runs between it
            and the east mesa so the basin reads as a corridor with a view south."""),
        empty("salt_basin", **at(1, 1), seed=712, scatter="Scatter_desert", biome="Desert"),
        empty("caravan_road", **at(1, 2), seed=713, scatter="Scatter_desert", biome="Desert", note="""
            THE CARAVAN ROAD — the road's long descent across the dry basin towards the green line
            of the jungle belt."""),
        empty("east_mesa", **at(1, 3), seed=714, scatter="Scatter_desert", biome="Desert"),

        # ================================================================== row 2 — the jungle belt
        empty("belt_west", **at(2, 0), seed=721, scatter="Scatter_jungle", biome="Woodland"),
        Cell(
            key="wells", cell_id="sunspire.wells", scene=f"{SUN}wells.tscn", **at(2, 1),
            origin=WELLS, resolution=80, seed=731, safe_radius=32.0, scatter="Scatter_wells",
            biome="Woodland",
            note="""
            SAFFRA WELLS — the caravan town at the oasis, where the road off the basins meets the
            water of the jungle belt. It is here because it is the only reliable water between the
            Southmarch Gate and the south; roads leave it west for the library and south for the
            Crimson Mission.
            """,
            yards=(
                Yard((2, -3), (14, 11), 3.0, 0.85, elevation=0.0, name="Area_wells_plaza"),
                Yard((18, -12), (7, 6), 2.0, 0.9, elevation=0.0, name="Area_wells_caravanserai"),
            ),
            routes=(
                Route((0, -24), (0, -8), 5.0, 2.0, name="Path_wells_north"),
                Route((-26, -2), (-8, -2), 4.5, 2.0, name="Path_wells_west"),
                Route((0, 4), (0, 24), 4.5, 2.0, name="Path_wells_south"),
            ),
            landforms=(
                # The oasis pool: a wadeable basin under WadeDepth, so the water is a place to stand
                # in rather than a hazard.
                Mound(at=(-17, 17), ext=(12, 9), h=-0.9, fall=0.6, flat=0.9),
            ),
            waters=(Water(at=(-17, 17), ext=(17, 13), ident="SaffraOasis",
                          shallow=(0.2, 0.36, 0.34), deep=(0.06, 0.18, 0.2), opaque=1.8),),
        ),
        empty("belt_east", **at(2, 2), seed=723, scatter="Scatter_jungle", biome="Wetland"),
        empty("belt_far_east", **at(2, 3), seed=724, scatter="Scatter_jungle", biome="Woodland"),

        # ================================================================== row 3 — the old country
        Cell(
            key="library", cell_id="sunspire.library", scene=f"{SUN}library.tscn", **at(3, 0),
            origin=LIBRARY, resolution=70, seed=741, safe_radius=26.0, scatter="Scatter_library",
            biome="Desert",
            note="""
            THE GREAT LIBRARY — the Veiled Archive's great library, the last of the old civilisation's
            reading halls, half-buried at the foot of the library mesa west of Saffra Wells. It is
            here because the mesa sheltered it from the sand that took the rest of the city. Its
            forecourt is kept clear: two story portals are placed there later (Acts III and IV).
            """,
            yards=(Yard((0, 2), (18, 16), 3.0, 0.92, elevation=0.0, name="Area_library_court"),),
            routes=(Route((0, 20), (0, 3), 4.0, 2.0, name="Path_library_forecourt"),),
        ),
        empty("sand_sea", **at(3, 1), seed=742, scatter="Scatter_desert", biome="Desert"),
        empty("red_flats", **at(3, 2), seed=743, scatter="Scatter_desert", biome="Desert"),
        empty("east_waste", **at(3, 3), seed=744, scatter="Scatter_desert", biome="Desert"),

        # ================================================================== row 4 — the Prophet's country
        empty("south_dunes_w", **at(4, 0), seed=751, scatter="Scatter_desert", biome="Desert"),
        empty("pilgrim_track", **at(4, 1), seed=752, scatter="Scatter_desert", biome="Desert", note="""
            THE PILGRIM TRACK — the worshippers' path from the library to the mission, across open
            sand. It pays for its walk with the mission's tower ahead of it all the way."""),
        Cell(
            key="temple", cell_id="sunspire.temple", scene=f"{SUN}temple.tscn", **at(4, 2),
            origin=TEMPLE, resolution=72, seed=761, scatter="Scatter_temple", biome="Desert",
            note="""
            THE CRIMSON MISSION — the Crimson Prophet's seat, on a low red rise at the south end of the
            realm. His worshippers' chapel and tower stand beside a walled sanctum; the sanctum is the
            arena. It is here because it is the far end of the pilgrims' road, four hundred metres of
            open country from the wells.
            """,
            yards=(
                Yard((0, 0), (22, 22), 3.0, 0.94, elevation=0.0, name="Area_temple_sanctum"),
                Yard((-31, -9), (7, 8), 2.0, 0.92, elevation=0.0, name="Area_temple_chapel"),
            ),
            routes=(Route((0, -30), (0, -12), 5.0, 2.0, name="Path_temple_gate"),),
        ),
        empty("south_waste", **at(4, 3), seed=754, scatter="Scatter_desert", biome="Desert"),
    ]


def roads() -> list[Road]:
    W, Lb, T = WELLS, LIBRARY, TEMPLE

    def o(origin, local):
        return (origin[0] + local[0], origin[1] + local[1])

    return [
        # ---- primary: the caravan road, the gap -> the basins -> Saffra Wells
        Road(((60, 904), (54, 1000), (38, 1110), (22, 1200), o(W, (0, -24))), width=5.0, shoulder=2.0),
        # ---- primary: the library road, the wells' west end -> the great library's forecourt
        Road((o(W, (-26, -2)), (-80, 1330), (-150, 1392), (-205, 1450), (-235, 1482), o(Lb, (0, 20))),
             width=4.5, shoulder=2.0),
        # ---- primary: the mission road, the wells' south end -> the Crimson Mission's gate
        Road((o(W, (0, 24)), (30, 1400), (80, 1480), (130, 1560), (170, 1622), o(T, (0, -30))),
             width=4.5, shoulder=2.0),
        # ---- secondary: the pilgrim track, library -> mission (the realm's loop)
        Road(((-235, 1482), (-200, 1560), (-110, 1630), (20, 1672), (110, 1660), (170, 1622)),
             width=3.0, shoulder=1.5),
    ]


def geography() -> list:
    return [
        # The northern escarpment, gapped where the caravan road comes in.
        Ridge(a=(-390, 918), b=(18, 926), half=26, h=18.0, fall=0.8),
        Ridge(a=(112, 926), b=(410, 916), half=26, h=18.0, fall=0.8),
        # The realm's east and west walls.
        Ridge(a=(-372, 960), b=(-372, 1760), half=30, h=16.0, fall=0.85),
        Ridge(a=(392, 960), b=(392, 1760), half=30, h=16.0, fall=0.85),
        # The southern wall behind the mission.
        Ridge(a=(-390, 1782), b=(410, 1778), half=28, h=20.0, fall=0.85),
        # The two basin mesas either side of the caravan road: flat tops, steep sides.
        Mound(at=(-240, 1150), ext=(55, 42), h=22.0, fall=0.35, flat=0.9),
        Mound(at=(262, 1210), ext=(46, 58), h=26.0, fall=0.35, flat=0.9),
        # The library mesa, whose lee kept the library out of the sand.
        Mound(at=(-335, 1505), ext=(34, 58), h=24.0, fall=0.35, flat=0.9),
        # A lone butte in the sand sea the pilgrim track bends around.
        Mound(at=(-40, 1555), ext=(34, 30), h=18.0, fall=0.4, flat=0.9),
        # The jungle belt: a long shallow trough the water gathers in.
        Ridge(a=(-390, 1335), b=(410, 1355), half=55, h=-4.0, fall=0.9),
        # Dunes.
        Mound(at=(250, 1000), ext=(70, 40), h=5.0, fall=0.95),
        Mound(at=(-250, 1010), ext=(80, 45), h=4.0, fall=0.95),
        Mound(at=(300, 1490), ext=(60, 50), h=6.0, fall=0.95),
        Mound(at=(-120, 1735), ext=(90, 34), h=5.0, fall=0.95),
        # The mission's low red rise.
        Mound(at=(195, 1690), ext=(62, 50), h=5.0, fall=0.95),
    ]


def build_sunspire() -> tuple[str, list[str]]:
    spec = cells()
    issues = check_tiling("Sunspire", spec, ROWS, EXTENT_X)
    by_key = {c.key: c for c in spec}
    spec, _ = apply_origins(spec, [])
    spec = place_world(spec, geography())
    spec, road_issues = realize_roads(spec, roads())
    issues += [f"Sunspire: {issue}" for issue in road_issues]
    issues += check_envelopes("Sunspire", spec, {c.key: list(c.routes) for c in spec})

    def shift_exclusion(match):
        ident, x, z = match.group(1), float(match.group(2)), float(match.group(3))
        dx, dz = by_key[EXCLUSION_OWNERS[ident]].offset if ident in EXCLUSION_OWNERS else (0.0, 0.0)
        return (f'[sub_resource type="Resource" id="{ident}"]\nscript = ExtResource("11_exclusion")\n'
                f"Center = Vector2({round(x + dx, 3)}, {round(z + dz, 3)})")
    scatter = re.sub(r'\[sub_resource type="Resource" id="(Exclusion_[a-z_]+)"\]\n'
                     r'script = ExtResource\("11_exclusion"\)\nCenter = Vector2\(([-\d.]+), ([-\d.]+)\)',
                     shift_exclusion, SCATTER)
    # Trees and rocks stay out from under the monuments and the boss rings (gen_regions.py).
    from gen_regions import monument_exclusions
    spec, scatter = monument_exclusions(spec, scatter)
    return emit("sunspire", HEADER, spec, [], ENVIRONMENT, BUDGET, RESOURCE, scatter, "Desert"), issues


if __name__ == "__main__":
    _text, _issues = build_sunspire()
    for _issue in _issues:
        print(f"LATTICE ERROR: {_issue}")
    print("self-check: FAILED" if _issues else f"self-check: sound ({len(_text)} bytes)")
    raise SystemExit(1 if _issues else 0)
