#!/usr/bin/env python3
"""The Ashen Wilds' macro layout, geography and approaches. Consumed by tools/gen_regions.py.

Started from tools/region_spec_template.py (not a copy of a shipped realm). Compact on purpose
(docs/playbook/finish.md): sixteen cells, one survivor settlement, the Ash Hunters' field station and
the Beast Lord's plateau, with dead country between them.
"""

from __future__ import annotations

from gen_regions import (Cell, Mound, Ridge, Road, Route, Yard, apply_origins, check_envelopes,
                         check_tiling, emit, place_world, realize_roads)

# 1. MACRO GEOGRAPHY — the atlas band is x 900..2100, z -1100..300 (docs/WORLD_ATLAS.md). The lattice
# uses the western part of it, nearest the Ashen Breach, and the rest stays unbuilt Cataclysm scar.
EXTENT_X = (900.0, 1500.0)
_ROW_BREAKS = [-640.0, -500.0, -370.0, -230.0, -80.0]
ROWS = list(zip(_ROW_BREAKS, _ROW_BREAKS[1:]))
# Irregular and chosen after the places, so nothing sits on a cell centre or a seam midpoint.
COLUMNS = {
    0: [1050.0, 1200.0, 1350.0],
    1: [1060.0, 1230.0, 1370.0],
    2: [1040.0, 1190.0, 1340.0],
    3: [1070.0, 1220.0, 1360.0],
}

HEARTH = (1095.0, -275.0)    # Last Hearth, the survivor settlement
STATION = (1180.0, -430.0)   # the Ash Hunters' field station (location.ashen.station)
LAIR = (1440.0, -585.0)      # the Beast Lord's plateau

HEADER = '''[gd_resource type="Resource" script_class="RegionResource" load_steps=13 format=3 uid="uid://crgnashenwld0"]

[ext_resource type="Script" path="res://src/World/RegionResource.cs" id="1_region"]
[ext_resource type="Script" path="res://src/World/RegionCellResource.cs" id="2_cell"]
[ext_resource type="Script" path="res://src/World/WorldEnvironmentProfileResource.cs" id="3_environment"]
[ext_resource type="Script" path="res://src/World/WorldCellPresentationResource.cs" id="4_presentation"]
[ext_resource type="Script" path="res://src/World/WorldPerformanceBudgetResource.cs" id="5_budget"]
[ext_resource type="Script" path="res://src/World/WorldPathSegmentResource.cs" id="6_path"]
[ext_resource type="Script" path="res://src/World/WorldGroundAreaResource.cs" id="7_area"]
[ext_resource type="Script" path="res://src/World/WorldLandformResource.cs" id="8_landform"]
[ext_resource type="Script" path="res://src/World/WorldBiomeScatterResource.cs" id="9_scatter"]
[ext_resource type="Script" path="res://src/World/BiomeScatterLayerResource.cs" id="10_layer"]
[ext_resource type="Script" path="res://src/World/BiomeScatterExclusionResource.cs" id="11_exclusion"]
[ext_resource type="Script" path="res://src/World/WorldWaterResource.cs" id="12_water"]
[ext_resource type="Resource" path="res://data/world_gen/AshenWilds.tres" id="13_generation"]

; ⚠️ GENERATED BY tools/gen_regions.py FROM tools/region_spec_ashen.py. Edit the spec.
;
; THE ASHEN WILDS — the Cataclysm scar east of the Ashen Breach. Warped plateaus, deep ravines, a
; crater field, two pockets of corrupted forest and dead ash country between them. The road comes
; through the Breach into the scar, reaches Last Hearth (the survivors) a hundred and seventy metres
; later, climbs north-east past the Ash Hunters' field station, and ends on the Beast Lord's plateau
; under the northern wall. Twelve of sixteen cells carry nothing but the weather. Do not fill them in.
'''

ENVIRONMENT = '''[sub_resource type="Resource" id="Environment_ashen"]
script = ExtResource("3_environment")
SurfaceColor = Color(0.26, 0.23, 0.21, 1)
SecondaryColor = Color(0.36, 0.32, 0.29, 1)
DetailColor = Color(0.13, 0.11, 0.10, 1)
RoadColor = Color(0.40, 0.35, 0.30, 1)
BackdropColor = Color(0.20, 0.17, 0.16, 1)
Relief = 1.8
DetailScale = 3.0
BackdropRadius = 330.0
BackdropHeight = 96.0
TerrainSeed = 4400
SurfaceRoughness = 0.95
DetailRoughness = 0.86
RoadRoughness = 0.80
SlopeBlendStart = 0.22
SlopeBlendEnd = 0.58
HeightBlendStart = 9.0
HeightBlendEnd = 30.0

; The air is ash. A low, rust-orange key through a thick grey-brown haze is what makes the Wilds
; read as the scar rather than as the Ember Crown's burnt frontier with the colour turned down.
SunTint = Color(0.96, 0.78, 0.62, 1)
SunEnergyScale = 0.78
HazeColor = Color(0.52, 0.47, 0.44, 1)
HazeScale = 1.9

'''

BUDGET = '''[sub_resource type="Resource" id="Budget_ashen"]
script = ExtResource("5_budget")
MaxAuthoredNodesPerCell = 400
MaxResidentAuthoredNodes = 4000
MaxResidentRuntimeNodes = 9000
MaxScatterInstancesPerCell = 7000
MaxResidentScatterInstances = 120000
MaxTerrainVerticesPerCell = 7000
MaxResidentTerrainVertices = 160000
MaxDrawCalls = 1800
MaxNodeCount = 30000
MaxStaticMemoryMb = 2048.0
MaxFrameMilliseconds = 16.67
ConsecutiveSamplesBeforeWarning = 5
BiomeCullDistance = 340.0
VisibilityUpdateInterval = 0.25
MaxConcurrentLoadRequests = 2
MaxCellInstantiationsPerFrame = 1
NearDistance = 95.0
MidDistance = 190.0
FarDistance = 420.0
BackdropDistance = 900.0

'''

SCATTER = '''[sub_resource type="Resource" id="Layer_ash_grass"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_grass_wispy.glb"
Count = 180
MinimumScale = 0.6
MaximumScale = 1.1
MinimumSpacing = 2.6
Saturation = 0.25
Clumping = 0.55
ClumpScale = 22.0
MaxSlope = 0.55
Tint = Color(0.62, 0.56, 0.48, 1)
TintVariation = 0.14
VisibilityRangeEnd = 55.0
VisibilityFadeMargin = 10.0

[sub_resource type="Resource" id="Layer_ash_stone"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_rock_cluster.glb"
Count = 60
MinimumScale = 0.5
MaximumScale = 1.3
MinimumSpacing = 3.6
Saturation = 0.2
Clumping = 0.5
ClumpScale = 28.0
MaxSlope = 1.05
Tint = Color(0.52, 0.47, 0.44, 1)
TintVariation = 0.12
VisibilityRangeEnd = 135.0
VisibilityFadeMargin = 18.0
HlodShape = 2
HlodReduction = 5
HlodRangeBegin = 112.0
HlodRangeEnd = 280.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

[sub_resource type="Resource" id="Layer_ash_stone_b"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_rock_cluster_a.glb"
Count = 35
MinimumScale = 0.34
MaximumScale = 0.8
MinimumSpacing = 7.0
Saturation = 0.2
Clumping = 0.55
ClumpScale = 30.0
MaxSlope = 0.95
Tint = Color(0.48, 0.43, 0.40, 1)
TintVariation = 0.12
VisibilityRangeEnd = 135.0
VisibilityFadeMargin = 18.0
CastShadows = true

[sub_resource type="Resource" id="Layer_ash_pebble"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_pebble_a.glb"
Count = 70
MinimumScale = 0.8
MaximumScale = 1.8
MinimumSpacing = 3.2
Clumping = 0.4
ClumpScale = 24.0
MaxSlope = 1.1
Tint = Color(0.50, 0.46, 0.43, 1)
TintVariation = 0.16
VisibilityRangeEnd = 55.0
VisibilityFadeMargin = 12.0

[sub_resource type="Resource" id="Layer_dead_trunk"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_pine_dead.glb"
Count = 40
MinimumScale = 0.6
MaximumScale = 1.1
MinimumSpacing = 8.0
Saturation = 0.2
Clumping = 0.7
ClumpScale = 44.0
MaxSlope = 0.4
Tint = Color(0.40, 0.35, 0.32, 1)
TintVariation = 0.10
VisibilityRangeEnd = 155.0
VisibilityFadeMargin = 20.0
HlodShape = 1
HlodReduction = 4
HlodRangeBegin = 130.0
HlodRangeEnd = 320.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

; ⚠️ THE CORRUPTED FOREST IS THE SAME BROADLEAF THE EMBER CROWN PLANTS, DRAINED AND DARKENED. Saturation
; strips its green and the tint pushes it to a bruised purple-brown: one shared asset reads as a second
; ecology, which is what Saturation is for. Dense and clumped, so a pocket is a thicket, not a scatter.
[sub_resource type="Resource" id="Layer_blight_tree"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_tree_broadleaf.glb"
Count = 200
MinimumScale = 0.7
MaximumScale = 1.45
MinimumSpacing = 6.0
Saturation = 0.18
Clumping = 0.85
ClumpScale = 40.0
MaxSlope = 0.42
Tint = Color(0.46, 0.34, 0.40, 1)
TintVariation = 0.16
VisibilityRangeEnd = 150.0
VisibilityFadeMargin = 22.0
CastShadows = true
HlodShape = 1
HlodReduction = 3
HlodRangeBegin = 130.0
HlodRangeEnd = 320.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

[sub_resource type="Resource" id="Layer_blight_fungus"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_mushrooms.glb"
Count = 90
MinimumScale = 0.7
MaximumScale = 1.4
MinimumSpacing = 3.0
Saturation = 0.5
Clumping = 0.7
ClumpScale = 18.0
MaxSlope = 0.5
Tint = Color(0.62, 0.44, 0.58, 1)
TintVariation = 0.2
VisibilityRangeEnd = 50.0
VisibilityFadeMargin = 10.0

; The Beast Lord's floor stays bare: nothing on the plateau top that reads as cover.
[sub_resource type="Resource" id="Exclusion_lair"]
script = ExtResource("11_exclusion")
Center = Vector2(15, -15)
Radius = 26.0

[sub_resource type="Resource" id="Exclusion_hearth"]
script = ExtResource("11_exclusion")
Center = Vector2(-20, 25)
Radius = 30.0

[sub_resource type="Resource" id="Exclusion_station"]
script = ExtResource("11_exclusion")
Center = Vector2(35, 5)
Radius = 18.0

[sub_resource type="Resource" id="Scatter_ash"]
script = ExtResource("9_scatter")
Seed = 6401
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_ash_grass"), SubResource("Layer_ash_stone"), SubResource("Layer_ash_stone_b"), SubResource("Layer_ash_pebble"), SubResource("Layer_dead_trunk")])

[sub_resource type="Resource" id="Scatter_blight"]
script = ExtResource("9_scatter")
Seed = 6402
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_blight_tree"), SubResource("Layer_blight_fungus"), SubResource("Layer_ash_grass"), SubResource("Layer_ash_stone_b")])

[sub_resource type="Resource" id="Scatter_hearth"]
script = ExtResource("9_scatter")
Seed = 6403
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_ash_grass"), SubResource("Layer_ash_pebble"), SubResource("Layer_ash_stone_b")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_hearth")])

[sub_resource type="Resource" id="Scatter_station"]
script = ExtResource("9_scatter")
Seed = 6404
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_ash_grass"), SubResource("Layer_ash_stone"), SubResource("Layer_ash_pebble"), SubResource("Layer_dead_trunk")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_station")])

[sub_resource type="Resource" id="Scatter_lair"]
script = ExtResource("9_scatter")
Seed = 6405
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_ash_stone"), SubResource("Layer_ash_stone_b"), SubResource("Layer_dead_trunk")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_lair")])

'''

RESOURCE = '''[resource]
script = ExtResource("1_region")
Id = "region.ashen_wilds"
DisplayName = "The Ashen Wilds"
Realm = 2

; The arrival is the scar's western mouth, where the road from the Ashen Breach comes out; the
; portal back to the Ember Crown stands on the road behind the player.
SpawnPoint = @WORLD(950, 1.2, -300)@
PortalPoint = @WORLD(928, 0, -298)@

; Earned (docs/playbook/finish.md): the Breach portal in the Ember Crown stays hidden and inert until
; the Iron King is dead. RegionSetup feeds this to that portal's RequiredFlagId.
UnlockFlagId = "flag.iron_king_defeated"
Cells = Array[ExtResource("2_cell")]([@CELLS@])
EnvironmentProfile = SubResource("Environment_ashen")
GenerationProfile = ExtResource("13_generation")
PerformanceBudget = SubResource("Budget_ashen")
Bounds = @BOUNDS(20, -80, 200)@
SafeZoneCenter = @ORIGIN(last_hearth, 0, 0, 0)@
SafeZoneRadius = 36.0
WeavePotency = 0.4
DefaultWeatherId = "weather.fog"
DayPhaseBias = 3
Neighbours = Array[String](["region.ember_crown"])
'''

ASHEN = "res://scenes/regions/ashen_wilds/"


def lattice():
    out = {}
    for r, (top, bottom) in enumerate(ROWS):
        xs = [EXTENT_X[0], *COLUMNS[r], EXTENT_X[1]]
        for c in range(len(xs) - 1):
            out[(r, c)] = (((xs[c] + xs[c + 1]) / 2, (top + bottom) / 2), (xs[c + 1] - xs[c], bottom - top))
    return out


def empty(key, center, size, seed, scatter="Scatter_ash", biome=None, note="", tint=None, tint_strength=0.0):
    """Dead country: ground, weather, ecology and at most a road — no gameplay beat."""
    resolution = min(80, max(36, int(max(size) / 2.8)))
    return Cell(key=key, cell_id=f"ashen_wilds.{key}", scene=f"{ASHEN}{key}.tscn", center=center,
                size=size, resolution=resolution, seed=seed, scatter=scatter, biome=biome, note=note,
                tint=tint, tint_strength=tint_strength)


def cells() -> list[Cell]:
    L = lattice()

    def at(r, c):
        return {"center": L[(r, c)][0], "size": L[(r, c)][1]}

    return [
        # ================================================================== row 0 — the northern wall
        empty("north_scar", **at(0, 0), seed=701),
        empty("ash_plateau", **at(0, 1), seed=702, biome="BurnedHeath", note="""
            THE ASH PLATEAU — a warped table of ground the Cataclysm lifted and left. Nothing on it."""),
        empty("cinder_ravine", **at(0, 2), seed=703, note="""
            THE CINDER RAVINE — a deep cut under the northern wall. A hazard, not a route."""),
        Cell(
            key="beast_lair", cell_id="ashen_wilds.beast_lair", scene=f"{ASHEN}beast_lair.tscn",
            **at(0, 3), origin=LAIR, resolution=72, seed=704, scatter="Scatter_lair",
            tint=(0.24, 0.16, 0.14), tint_strength=0.35,
            note="""
            THE BEAST LORD'S PLATEAU — a levelled shelf under the northern wall at the end of the scar
            road, three hundred metres past the Hunters' station. The Fourth Flamebearer holds it; the
            challenge brazier stands at the head of the ramp and the floor is bare on purpose.
            """,
            yards=(Yard((0, 0), (22, 20), 4.0, 0.8, elevation=0.0, name="Area_lair_floor"),),
            routes=(Route((0, 25), (0, 12), 5.0, 2.5, name="Path_lair_gate"),),
            landforms=(Mound(at=(0, 0), ext=(30, 28), h=5.0, fall=0.45, flat=1.0),),
        ),

        # ================================================================== row 1 — the hunters' rise
        empty("dead_wood", **at(1, 0), seed=711, scatter="Scatter_blight", biome="Woodland",
              tint=(0.30, 0.22, 0.26), tint_strength=0.3, note="""
            THE DEAD WOOD — a corrupted forest pocket north of the arrival. Trees that should have died
            and did not."""),
        Cell(
            key="hunters_rise", cell_id="ashen_wilds.hunters_rise", scene=f"{ASHEN}hunters_rise.tscn",
            **at(1, 1), origin=STATION, resolution=64, seed=712, scatter="Scatter_station", biome="BurnedHeath",
            note="""
            THE HUNTERS' RISE — the Ash Hunters' field station, on a low rise above the scar road where
            they can see both the Hearth and the plateau. A tent line, a watch tower and a fire.
            """,
            yards=(Yard((0, 0), (14, 12), 3.0, 0.8, elevation=0.0, name="Area_station"),),
            routes=(Route((0, 20), (4, 2), 4.5, 2.0, name="Path_station_south"),
                    Route((4, 2), (20, 0), 4.5, 2.0, name="Path_station_east")),
            landforms=(Mound(at=(0, 0), ext=(20, 18), h=0.0, fall=0.5, flat=0.85),),
        ),
        empty("crater_field", **at(1, 2), seed=713, note="""
            THE CRATER FIELD — where something came down in the Cataclysm. One crater, deep enough that
            the player who walks in is meant to know they fell."""),
        empty("lair_approach", **at(1, 3), seed=714, tint=(0.24, 0.16, 0.14), tint_strength=0.2),

        # ================================================================== row 2 — the scar road
        empty("breach_scar", **at(2, 0), seed=721, biome="BurnedHeath", note="""
            THE BREACH SCAR — the western mouth of the Wilds, where the road from the Ashen Breach comes
            out and the player arrives. The portal home stands on the road."""),
        Cell(
            key="last_hearth", cell_id="ashen_wilds.last_hearth", scene=f"{ASHEN}last_hearth.tscn",
            **at(2, 1), origin=HEARTH, resolution=64, seed=722, safe_radius=32.0, scatter="Scatter_hearth",
            biome="BurnedHeath",
            note="""
            LAST HEARTH — the survivors: people who came through the Breach before it closed and could
            not go back. On the one piece of level ground by the scar road, the first shelter a traveller
            reaches and the last one before the Hunters' station.
            """,
            # ⚠️ BLEND 0.95, NOT 0.8: at 0.8 the work shelter at (16, -14) stood on 1.10 m of ground range.
            # One strong pad rather than a second pad inside it, because two pads over one footprint
            # each level to the ground under their own centre and meet in a step.
            yards=(Yard((0, 0), (26, 22), 3.0, 0.95, elevation=0.0, name="Area_hearth_ground"),),
            routes=(Route((-30, 0), (0, 0), 5.5, 2.5, name="Path_hearth_west"),
                    Route((0, 0), (0, -30), 5.5, 2.5, name="Path_hearth_north")),
            landforms=(Mound(at=(0, 0), ext=(32, 28), h=0.0, fall=0.5, flat=0.85),),
        ),
        empty("ashen_flats", **at(2, 2), seed=723),
        empty("east_rim", **at(2, 3), seed=724),

        # ================================================================== row 3 — the southern ravines
        empty("south_ravines", **at(3, 0), seed=731, note="""
            THE SOUTH RAVINES — two cuts through the ash south of the arrival. Deep, and unroaded."""),
        empty("blight_wood", **at(3, 1), seed=732, scatter="Scatter_blight", biome="Woodland",
              tint=(0.30, 0.22, 0.26), tint_strength=0.3, note="""
            THE BLIGHT WOOD — the second corrupted pocket, south of the Hearth. The survivors do not
            cut here."""),
        empty("scorched_hollow", **at(3, 2), seed=733),
        empty("far_rim", **at(3, 3), seed=734),
    ]


def roads() -> list[Road]:
    def o(origin, local):
        return (origin[0] + local[0], origin[1] + local[1])

    return [
        # ---- the scar road: arrival -> Last Hearth
        Road(((922, -298), (980, -306), (1030, -290), o(HEARTH, (-30, 0))), width=5.5, shoulder=2.5),
        # ---- Last Hearth north gate -> the Hunters' station
        Road((o(HEARTH, (0, -30)), (1105, -340), (1150, -380), o(STATION, (0, 20))), width=5.0, shoulder=2.5),
        # ---- the station -> the Beast Lord's plateau
        Road((o(STATION, (20, 0)), (1270, -465), (1330, -520), (1400, -560), o(LAIR, (0, 25))),
             width=4.5, shoulder=2.5),
    ]


def geography() -> list:
    return [
        # The border hills the Breach cuts through, gapped where the road comes in.
        Ridge(a=(905, -620), b=(915, -360), half=24, h=22.0, fall=0.85),
        Ridge(a=(915, -240), b=(905, -100), half=24, h=20.0, fall=0.85),
        # The northern wall, the eastern rim and the southern edge that close the scar.
        Ridge(a=(900, -640), b=(1500, -640), half=20, h=24.0, fall=0.85),
        Ridge(a=(1497, -600), b=(1497, -100), half=22, h=26.0, fall=0.85),
        Ridge(a=(900, -84), b=(1500, -86), half=22, h=18.0, fall=0.85),
        # The ash plateau: a warped table, levelled by the Cataclysm rather than by anyone's hand.
        Mound(at=(1125, -570), ext=(60, 42), h=12.0, fall=0.4, flat=0.9, irr=0.3),
        # The Cinder Ravine, deep enough to be a hazard the player falls into rather than a trap.
        Ridge(a=(1210, -560), b=(1330, -598), half=10, h=-9.0, fall=0.3, flat=1.0, irr=0.3),
        # The crater: a raised rim and a deep floor.
        Mound(at=(1310, -410), ext=(30, 26), h=4.0, fall=0.8),
        Mound(at=(1310, -410), ext=(18, 15), h=-7.0, fall=0.35),
        # The southern ravines.
        Ridge(a=(930, -140), b=(1050, -190), half=9, h=-10.0, fall=0.3, flat=1.0, irr=0.3),
        # Swells that give the dead country something to crest.
        Mound(at=(975, -450), ext=(50, 40), h=8.0, fall=0.9),
        Mound(at=(1450, -300), ext=(50, 60), h=12.0, fall=0.9),
        Mound(at=(1420, -150), ext=(60, 40), h=9.0, fall=0.9),
        Mound(at=(1290, -160), ext=(60, 50), h=-4.0, fall=0.9),
    ]


def build_ashen() -> tuple[str, list[str]]:
    spec = cells()
    issues = check_tiling("AshenWilds", spec, ROWS, EXTENT_X)
    by_key = {c.key: c for c in spec}
    spec, _ = apply_origins(spec, [])
    spec = place_world(spec, geography())
    spec, road_issues = realize_roads(spec, roads())
    issues += [f"AshenWilds: {issue}" for issue in road_issues]
    issues += check_envelopes("AshenWilds", spec, {c.key: list(c.routes) for c in spec})

    # Scatter clearings are authored cell-local, at the content origin's offset (see the exclusions'
    # Centre values, which equal each owner's Cell.offset); assert they still do.
    for ident, owner in (("Exclusion_lair", "beast_lair"), ("Exclusion_hearth", "last_hearth"),
                         ("Exclusion_station", "hunters_rise")):
        dx, dz = by_key[owner].offset
        needle = 'id="%s"]\nscript = ExtResource("11_exclusion")\nCenter = Vector2(%g, %g)' % (ident, dx, dz)
        if needle not in SCATTER:
            issues.append(f"AshenWilds: {ident} is not at {owner}'s content offset ({dx:g}, {dz:g})")
    scatter = SCATTER
    return emit("ashen_wilds", HEADER, spec, [], ENVIRONMENT, BUDGET, RESOURCE, scatter, "AshWaste"), issues
