#!/usr/bin/env python3
"""Frostfang Reach's macro layout, geography and approaches. Consumed by tools/gen_regions.py."""

from __future__ import annotations

import re

from gen_regions import (Cell, Mound, Ridge, Road, Route, Water, Yard, apply_origins,
                         check_envelopes, check_tiling, emit, place_world, realize_roads)

# The Reach's band in the atlas (docs/WORLD_ATLAS.md): north of the Ember Crown, across the Crown Pass.
EXTENT_X = (-460.0, 500.0)
_ROW_BREAKS = [-2320.0, -2150.0, -2010.0, -1880.0, -1740.0, -1600.0, -1450.0, -1300.0]
ROWS = list(zip(_ROW_BREAKS, _ROW_BREAKS[1:]))
# Irregular on purpose and chosen after the places (see region_spec_ember.py's COLUMNS).
COLUMNS = {
    0: [-250.0, -10.0, 200.0, 330.0],
    1: [-230.0, -40.0, 170.0, 330.0],
    2: [-270.0, -60.0, 140.0, 300.0],
    3: [-230.0, -10.0, 160.0, 280.0],
    4: [-300.0, -150.0, 40.0, 250.0],
    5: [-330.0, -140.0, 30.0, 240.0, 380.0],
    6: [-230.0, -20.0, 210.0, 360.0],
}

HEADER = '''[gd_resource type="Resource" script_class="RegionResource" load_steps=12 format=3 uid="uid://crgnfrostfng0"]

[ext_resource type="Script" path="res://src/World/RegionResource.cs" id="1_region"]
[ext_resource type="Script" path="res://src/World/RegionCellResource.cs" id="2_cell"]
[ext_resource type="Script" path="res://src/World/WorldEnvironmentProfileResource.cs" id="3_environment"]
[ext_resource type="Script" path="res://src/World/WorldCellPresentationResource.cs" id="4_presentation"]
[ext_resource type="Script" path="res://src/World/WorldPerformanceBudgetResource.cs" id="5_budget"]
[ext_resource type="Script" path="res://src/World/WorldPathSegmentResource.cs" id="6_path"]
[ext_resource type="Script" path="res://src/World/WorldGroundAreaResource.cs" id="7_area"]
[ext_resource type="Script" path="res://src/World/WorldLandformResource.cs" id="8_landform"]
[ext_resource type="Script" path="res://src/World/WorldBiomeScatterResource.cs" id="9_scatter"]
[ext_resource type="Script" path="res://src/World/BiomeScatterLayerResource.cs" id="10_layer"]
[ext_resource type="Script" path="res://src/World/BiomeScatterExclusionResource.cs" id="11_exclusion"]
[ext_resource type="Script" path="res://src/World/WorldWaterResource.cs" id="12_water"]
[ext_resource type="Resource" path="res://data/world_gen/FrostfangReach.tres" id="13_generation"]

; ⚠️ GENERATED BY tools/gen_regions.py FROM tools/region_spec_frostfang.py. Edit the spec.
;
; ====================================================================================================
; FROSTFANG REACH AFTER THE 2026-09 WORLD REBUILD
; ====================================================================================================
;
; WHAT CHANGED. The Reach was 340 x 380 m and read as a boss-selection hub: the Clan Hold with a dragon
; lair a hundred and twenty metres either side of it and the aerie two cells north. It is now 960 x
; 1020 m in its own atlas band north of the Ember Crown. The road comes in from the south into the
; Stormbound Vale, passes the clan's Stonewatch waystation and reaches the hold on its bench under the
; mountain wall three hundred and fifty metres later. The dragons live in their own country: the Wild
; roost up a side valley over the roost ridge to the west, the Ash roost past the burnt col to the
; east where the snow turns to ash, and the Ancient's aerie against the northern wall nine hundred
; metres from the arrival, reached through Glacier Pass or by the hunters' ridge route.
;
; SCATTERED, NOT DENSE. The clan's presence outside the hold is traces, not buildings: the waystation,
; an abandoned hunting lodge, the broken Ravenspur watch, cairns on the roads. Twenty-seven of the
; thirty-six cells are empty high country, and that emptiness — distance, exposure, altitude — is the
; realm's identity. Do not fill it in.
;
; Stormcrown, the blasted spire in the north-east high passes, is reserved for the Storm Tyrant
; (Phase 44E / 47E): a track reaches its foot and nothing else exists there.
'''

ENVIRONMENT = '''[sub_resource type="Resource" id="Environment_frostfang"]
script = ExtResource("3_environment")
SurfaceColor = Color(0.49, 0.55, 0.60, 1)
SecondaryColor = Color(0.70, 0.75, 0.78, 1)
DetailColor = Color(0.26, 0.31, 0.36, 1)
RoadColor = Color(0.33, 0.37, 0.42, 1)
BackdropColor = Color(0.25, 0.29, 0.34, 1)
Relief = 2.2
DetailScale = 3.5
BackdropCenter = Vector3(430, 0, -120)
BackdropRadius = 330.0
BackdropHeight = 180.0
BackdropCount = 28
TerrainSeed = 3800
SurfaceRoughness = 0.93
DetailRoughness = 0.84
RoadRoughness = 0.78
SlopeBlendStart = 0.22
SlopeBlendEnd = 0.58
HeightBlendStart = 10.0
HeightBlendEnd = 34.0

; ⚠️ THE LIGHT IS THE REGION, NOT JUST THE PALETTE. Every terrain colour here is cold and the Clan
; Hold still rendered as warm tan sand, because a neutral-grey bedrock under the Ember Crown's
; golden-hour sun IS tan. SunTint pulls the key toward ART_STYLE §2.1's "hard white-blue"; the sun
; is also weaker and the air much thicker, which is what puts the aerial depth into a shot of a
; massif and what makes the Reach feel like altitude rather than like a repainted lowland.
SunTint = Color(0.74, 0.82, 0.96, 1)
SunEnergyScale = 0.86
HazeColor = Color(0.72, 0.79, 0.87, 1)
HazeScale = 1.15

'''

BUDGET = '''[sub_resource type="Resource" id="Budget_frostfang"]
script = ExtResource("5_budget")
MaxAuthoredNodesPerCell = 400
MaxResidentAuthoredNodes = 4000
MaxResidentRuntimeNodes = 9000
MaxScatterInstancesPerCell = 7000
MaxResidentScatterInstances = 160000
MaxTerrainVerticesPerCell = 7000
MaxResidentTerrainVertices = 260000
MaxDrawCalls = 1800
MaxNodeCount = 30000
MaxStaticMemoryMb = 2048.0
MaxFrameMilliseconds = 16.67
ConsecutiveSamplesBeforeWarning = 5
BiomeCullDistance = 340.0
VisibilityUpdateInterval = 0.25
MaxConcurrentLoadRequests = 2
MaxCellInstantiationsPerFrame = 1

; Streaming radii for a kilometre realm: see the Ember Crown's budget for why Backdrop covers the
; diagonal (an unloaded cell is a hole in the backdrop; the aerie and Stormcrown must read from the vale).
NearDistance = 95.0
MidDistance = 190.0
FarDistance = 420.0
BackdropDistance = 1500.0

'''

SCATTER = '''[sub_resource type="Resource" id="Layer_dead_pine"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_tree_dead_a.glb"
Count = 85
MinimumScale = 0.8
MaximumScale = 1.5
MinimumSpacing = 7.5
Saturation = 0.42
Clumping = 0.72
ClumpScale = 44.0
MaxSlope = 0.4
HeightRange = Vector2(-9999, 34)
Tint = Color(0.78, 0.84, 0.90, 1)
TintVariation = 0.10
VisibilityRangeEnd = 155.0
VisibilityFadeMargin = 20.0
HlodShape = 1
HlodReduction = 4
HlodRangeBegin = 130.0
HlodRangeEnd = 320.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

; Living conifers below the tree line: a 10-20 m fir, snow-dusted by a cold tint. Open country
; only - the roosts and the hold keep their dead-wood profiles, where a wall of green would hand
; the player cover a dragon fight is designed not to offer.
[sub_resource type="Resource" id="Layer_frost_fir"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_pine_fir_a.glb"
Count = 30
MinimumScale = 0.7
MaximumScale = 1.4
MinimumSpacing = 10.0
Saturation = 0.6
Clumping = 0.72
ClumpScale = 44.0
MaxSlope = 0.4
HeightRange = Vector2(-9999, 34)
Tint = Color(0.9, 0.96, 1.0, 1)
TintVariation = 0.1
VisibilityRangeEnd = 155.0
VisibilityFadeMargin = 20.0
CastShadows = true
HlodShape = 1
HlodReduction = 3
HlodRangeBegin = 130.0
HlodRangeEnd = 320.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

; The tor: the boulder at 2.5-4, a 10-16 m frost-split mass, one per 100 x 100 m. No collision
; (scatter never has any), so it stays out of the roost, hold, heights and Stormcrown profiles.
[sub_resource type="Resource" id="Layer_frost_tor"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_rock_boulder_a.glb"
Count = 1
MinimumScale = 2.5
MaximumScale = 4.0
MinimumSpacing = 60.0
Saturation = 0.3
Clumping = 0.6
ClumpScale = 90.0
MaxSlope = 0.5
Tint = Color(0.72, 0.79, 0.86, 1)
TintVariation = 0.08
VisibilityRangeEnd = 220.0
VisibilityFadeMargin = 26.0
CastShadows = true
HlodShape = 1
HlodReduction = 2
HlodRangeBegin = 200.0
HlodRangeEnd = 420.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.1, 1.1, 1.1)

; Frost-shattered stone: the one boulder at a quarter to two thirds size, drained and tinted cold
; (Saturation is what makes a warm grey rock read as frozen; a Tint alone only darkens it).
; 24 of a 626-triangle mesh is under the triangle load of the 70 small rocks it replaces.
[sub_resource type="Resource" id="Layer_frost_rock"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_rock_boulder_a.glb"
Count = 24
MinimumScale = 0.25
MaximumScale = 0.7
MinimumSpacing = 6.0
Saturation = 0.3
Clumping = 0.52
ClumpScale = 28.0
MaxSlope = 1.0
Tint = Color(0.72, 0.79, 0.86, 1)
TintVariation = 0.12
VisibilityRangeEnd = 135.0
VisibilityFadeMargin = 18.0
HlodShape = 2
HlodReduction = 5
HlodRangeBegin = 112.0
HlodRangeEnd = 280.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

[sub_resource type="Resource" id="Layer_snow_tuft"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_grass_clump_a.glb"
Count = 420
MinimumScale = 0.4
MaximumScale = 0.7
MinimumSpacing = 2.6
Saturation = 0.35
Clumping = 0.4
ClumpScale = 20.0
MaxSlope = 0.55
Tint = Color(0.80, 0.86, 0.92, 1)
TintVariation = 0.14
VisibilityRangeEnd = 52.0
VisibilityFadeMargin = 10.0
CastShadows = false

[sub_resource type="Resource" id="Layer_frost_rock_b"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_rock_rubble_a.glb"
Count = 34
MinimumScale = 0.4
MaximumScale = 0.85
MinimumSpacing = 7.0
Saturation = 0.3
Clumping = 0.55
ClumpScale = 30.0
MaxSlope = 0.95
Tint = Color(0.73, 0.79, 0.86, 1)
TintVariation = 0.13
VisibilityRangeEnd = 135.0
VisibilityFadeMargin = 18.0
CastShadows = true

; Shed ice. There is no ice-block model in the set: this is the rubble pile, drained to grey by
; Saturation and pushed to a pale blue by a Tint ABOVE 1 (an instance colour is a multiply, and
; the rubble atlas is mid grey, so only an over-bright tint can lift it to ice). Low and squat, so
; it dresses the ground a glacier has ground over rather than competing with the authored ice
; masses. ⚠️ 8, not 55: the pile is 1,350 triangles where the old chunk was 30.
[sub_resource type="Resource" id="Layer_ice_chunk"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_rock_rubble_a.glb"
Count = 8
MinimumScale = 0.3
MaximumScale = 0.7
MinimumSpacing = 5.2
Saturation = 0.05
Clumping = 0.62
ClumpScale = 26.0
MaxSlope = 0.7
Tint = Color(1.15, 1.45, 1.6, 1)
TintVariation = 0.09
VisibilityRangeEnd = 78.0
VisibilityFadeMargin = 14.0
CastShadows = false

; ⚠️ THE SPIRE STANDS 3-6 m AND IT IS THE ONE THAT NEEDS A SLOPE GATE. Ice that has been shoved
; upright belongs on the flat of a snowfield, not canted out of a 40-degree corrie wall — which is
; exactly the failure the terrain gate was added for (see WorldBiomeScatter's MaxSlope comment).
[sub_resource type="Resource" id="Layer_ice_shard"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_ice_spire_a.glb"
Count = 6
MinimumScale = 0.7
MaximumScale = 1.6
MinimumSpacing = 13.0
Clumping = 0.66
ClumpScale = 40.0
MaxSlope = 0.32
Tint = Color(0.88, 0.93, 0.98, 1)
TintVariation = 0.07
VisibilityRangeEnd = 130.0
VisibilityFadeMargin = 18.0
CastShadows = true

; ⚠️ AN EXCLUSION FOLLOWS ITS NEST AND THE NESTS DID NOT MOVE WITHIN THEIR CELLS. Each roost names
; its own, centred on where its Nest node actually sits in cell-local metres.
[sub_resource type="Resource" id="Exclusion_dragon_roost"]
script = ExtResource("11_exclusion")
Center = Vector2(-14, -20)
Radius = 15.0

[sub_resource type="Resource" id="Exclusion_ash_roost"]
script = ExtResource("11_exclusion")
Center = Vector2(10, 6)
Radius = 16.0

; The ash roost causeway: a 34 m exposed approach, and a line of trees across it would hand the
; player cover the fight is designed not to offer.
[sub_resource type="Resource" id="Exclusion_ash_causeway"]
script = ExtResource("11_exclusion")
Center = Vector2(-32, 1)
Radius = 12.0

; Widened with the dragons (2026-10): the Ancient sweeps 12 m about its nest (22 m long, 17.7 m
; across the wings), the Ash 8.1 m and the Wild 6.7 m. Each clearing is about twice its sweep.
[sub_resource type="Resource" id="Exclusion_aerie"]
script = ExtResource("11_exclusion")
Center = Vector2(-6, -18)
Radius = 23.0

[sub_resource type="Resource" id="Exclusion_aerie_hoard"]
script = ExtResource("11_exclusion")
Center = Vector2(12, -12)
Radius = 7.0

[sub_resource type="Resource" id="Scatter_glacier"]
script = ExtResource("9_scatter")
Seed = 5205
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_frost_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_chunk"), SubResource("Layer_ice_shard"), SubResource("Layer_snow_tuft"), SubResource("Layer_frost_tor")])

[sub_resource type="Resource" id="Scatter_dragon_roost"]
script = ExtResource("9_scatter")
Seed = 5202
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_dead_pine"), SubResource("Layer_frost_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_chunk"), SubResource("Layer_snow_tuft")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_dragon_roost")])

[sub_resource type="Resource" id="Scatter_ash_roost"]
script = ExtResource("9_scatter")
Seed = 5203
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_dead_pine"), SubResource("Layer_frost_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_chunk")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_ash_roost"), SubResource("Exclusion_ash_causeway")])

[sub_resource type="Resource" id="Scatter_aerie"]
script = ExtResource("9_scatter")
Seed = 5204
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_dead_pine"), SubResource("Layer_frost_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_chunk")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_aerie"), SubResource("Exclusion_aerie_hoard")])

[sub_resource type="Resource" id="Layer_high_rock"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_rock_crag_a.glb"
Count = 16
MinimumScale = 0.5
MaximumScale = 1.3
MinimumSpacing = 8.0
Saturation = 0.28
Clumping = 0.58
ClumpScale = 32.0
MaxSlope = 1.15
Tint = Color(0.76, 0.81, 0.87, 1)
TintVariation = 0.14
VisibilityRangeEnd = 145.0
VisibilityFadeMargin = 20.0
HlodShape = 2
HlodReduction = 5
HlodRangeBegin = 120.0
HlodRangeEnd = 290.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

[sub_resource type="Resource" id="Layer_high_pine"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/world/prp_tree_dead_a.glb"
Count = 16
MinimumScale = 0.7
MaximumScale = 1.2
MinimumSpacing = 14.0
Saturation = 0.4
Clumping = 0.6
ClumpScale = 50.0
MaxSlope = 0.38
Tint = Color(0.80, 0.86, 0.92, 1)
TintVariation = 0.08
VisibilityRangeEnd = 150.0
VisibilityFadeMargin = 20.0

; ⚠️ ABOVE THE TREE LINE, AND THAT IS THE POINT. The shared roost profile put 230 dead pines on the
; Ancient's massif and buried the summit court, the crescent and three precipices in a forest — the
; one cell in the realm whose whole job is a reveal. Sixteen wind-killed trunks and bare rock.
[sub_resource type="Resource" id="Scatter_heights"]
script = ExtResource("9_scatter")
Seed = 5209
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_high_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_shard"), SubResource("Layer_high_pine")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_aerie"), SubResource("Exclusion_aerie_hoard")])

; The Storm Tyrant's duelling ground under the spire: bare, so the fight has no cover to hide in.
[sub_resource type="Resource" id="Exclusion_stormcrown_arena"]
script = ExtResource("11_exclusion")
Center = Vector2(20, 45)
Radius = 19.0

[sub_resource type="Resource" id="Scatter_stormcrown"]
script = ExtResource("9_scatter")
Seed = 5210
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_high_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_shard"), SubResource("Layer_high_pine")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_stormcrown_arena")])

[sub_resource type="Resource" id="Scatter_snowfield"]
script = ExtResource("9_scatter")
Seed = 5206
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_snow_tuft"), SubResource("Layer_frost_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_chunk"), SubResource("Layer_dead_pine"), SubResource("Layer_frost_fir"), SubResource("Layer_frost_tor")])

[sub_resource type="Resource" id="Scatter_march"]
script = ExtResource("9_scatter")
Seed = 5207
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_snow_tuft"), SubResource("Layer_dead_pine"), SubResource("Layer_frost_fir"), SubResource("Layer_frost_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_chunk"), SubResource("Layer_frost_tor")])

[sub_resource type="Resource" id="Scatter_hold"]
script = ExtResource("9_scatter")
Seed = 5208
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_snow_tuft"), SubResource("Layer_frost_rock"), SubResource("Layer_frost_rock_b"), SubResource("Layer_ice_chunk")])

'''

RESOURCE = '''[resource]
script = ExtResource("1_region")
Id = "region.frostfang_reach"
DisplayName = "Frostfang Reach"
Realm = 1

; The arrival is the southern gap in the fells, three hundred and fifty metres of vale road south of
; the Clan Hold; the portal back to the Ember Crown stands at the gap behind the player.
SpawnPoint = @WORLD(-60, 1.2, -1336)@
PortalPoint = @WORLD(-60, 0, -1316)@

; ⚠️ FROSTFANG IS NOT QUEST-GATED (maintainer direction, 2026-08-28). UnlockFlagId held
; "flag.frostfang.passage_open" — written by quest.warband.heart — and RegionSetup fed it to the
; portal's RequiredFlagId, so the door was hidden until that quest closed. It is EMPTY, and the
; portal is visible and usable from the first minute. The Crossway toll below is a separate thing
; and still fails closed: removing the quest gate made the crossing a price, not a prerequisite.
UnlockFlagId = ""
Cells = Array[ExtResource("2_cell")]([@CELLS@])
EnvironmentProfile = SubResource("Environment_frostfang")
GenerationProfile = ExtResource("13_generation")
PerformanceBudget = SubResource("Budget_frostfang")

; The lattice is x -460..500, z -2320..-1300, disjoint from the Ember Crown (x -520..520, z -720..440).
Bounds = @BOUNDS(20, -80, 220)@
SafeZoneCenter = @ORIGIN(clan_hold, 0, 0, 0)@
SafeZoneRadius = 40.0
WeavePotency = 0.5
DefaultWeatherId = "weather.clear"
DayPhaseBias = 2
Neighbours = Array[String](["region.ember_crown"])

; The Crossway toll, northbound (Phase 38M). The twin of the block in EmberCrown.tres — same gate,
; same road, same permit — because the toll is declared on the destination and a crossing has two.
TollGold = 25
TollPermitFlagId = "flag.crossway.permit"
TollPassFlagId = "flag.crossway.pass"
'''


FROST = "res://scenes/regions/frostfang_reach/"


def empty(key, center, size, seed, scatter, biome=None, note="", resolution=None, tint=None, tint_strength=0.0):
    """High country: ground, weather, ecology and at most a clan track — no gameplay beat."""
    if resolution is None:
        resolution = min(80, max(36, int(max(size) / 2.8)))
    return Cell(key=key, cell_id=f"frostfang_reach.{key}", scene=f"{FROST}{key}.tscn",
                center=center, size=size, resolution=resolution, seed=seed, scatter=scatter,
                biome=biome, note=note, tint=tint, tint_strength=tint_strength)


def lattice():
    out = {}
    for r, (top, bottom) in enumerate(ROWS):
        xs = [EXTENT_X[0], *COLUMNS[r], EXTENT_X[1]]
        for c in range(len(xs) - 1):
            out[(r, c)] = (((xs[c] + xs[c + 1]) / 2, (top + bottom) / 2), (xs[c + 1] - xs[c], bottom - top))
    return out


# Where each lair's scatter clearing sits in its OWN content frame; shifted with the content.
EXCLUSION_OWNERS = {
    "Exclusion_dragon_roost": "dragon_roost",
    "Exclusion_ash_roost": "ash_roost",
    "Exclusion_ash_causeway": "ash_roost",
    "Exclusion_aerie": "ancient_aerie",
    "Exclusion_aerie_hoard": "ancient_aerie",
    "Exclusion_stormcrown_arena": "stormcrown",
}


def cells() -> list[Cell]:
    L = lattice()

    def at(r, c):
        return {"center": L[(r, c)][0], "size": L[(r, c)][1]}

    return [
        # ================================================================== row 0 — the northern wall
        empty("aerie_west", **at(0, 0), seed=401, scatter="Scatter_heights", biome="Snowfield"),
        Cell(
            key="ancient_aerie", cell_id="frostfang_reach.ancient_aerie", scene=f"{FROST}ancient_aerie.tscn",
            **at(0, 1), origin=(-110.0, -2215.0), resolution=80, seed=204, tint=(0.67, 0.72, 0.82),
            tint_strength=0.16, scatter="Scatter_heights", biome="Snowfield",
            note="""
            THE ANCIENT AERIE — the highest court in the Reach, against the northern wall and nine
            hundred metres from the arrival. Two ways up: the glacier road through the pass and the
            snow saddle, or the hunters' ridge route from the dragon country in the west. The massif,
            the switchback procession, the standing-stone crescent and the hidden hoard are unchanged.
            """,
            yards=(
                Yard((-6, -16), (16, 14), 4.0, 0.62, elevation=0.0, name="Area_aerie_court"),
                Yard((12, -12), (5, 5), 2.0, 0.72, elevation=0.0, name="Area_aerie_hoard"),
            ),
            routes=(
                Route((0, 6), (-6, -16), 4.5, 3.0, name="Path_aerie_crescent"),
                Route((2, -6), (9, -10), 3.0, 1.0, name="Path_aerie_hoard"),
                Route((0, 55), (18, 42), 5.5, 3.0),
                Route((18, 42), (8, 30), 5.5, 3.0),
                Route((8, 30), (0, 20), 5.5, 3.0),
                Route((0, 20), (10, 13), 4.5, 2.0),
                Route((10, 13), (0, 6), 4.5, 2.0),
            ),
            landforms=(
                Mound(at=(0, -10), ext=(58, 54), h=18.0, fall=0.95),
                Mound(at=(-46, 40), ext=(27, 23), h=4.0, fall=0.9),
                Mound(at=(-6, -18), ext=(23, 19), h=20.0, fall=0.3, flat=1.0),
                Mound(at=(16, -10), ext=(9, 8), h=19.0, fall=0.3, flat=1.0),
                Mound(at=(-54, -30), ext=(23, 27), h=-14.0, fall=0.35),
                Mound(at=(56, -34), ext=(23, 27), h=-16.0, fall=0.35),
                Mound(at=(0, -50), ext=(62, 21), h=-18.0, fall=0.3),
            ),
        ),
        Cell(
            key="aerie_ascent", cell_id="frostfang_reach.aerie_ascent", scene=f"{FROST}aerie_ascent.tscn",
            **at(0, 2), resolution=70, seed=208, scatter="Scatter_heights", biome="Alpine",
            note="""
            THE AERIE ASCENT — the last climb from the head of the glacier to the massif, under the
            northern wall. High traverse with nothing on it.
            """,
        ),
        empty("stormfall", **at(0, 3), seed=404, scatter="Scatter_heights", biome="Snowfield"),
        Cell(
            key="stormcrown", cell_id="frostfang_reach.stormcrown",
            scene=f"{FROST}stormcrown.tscn", **at(0, 4), resolution=60, seed=405,
            scatter="Scatter_stormcrown", biome="Snowfield",
            note="""STORMCROWN — the blasted spire in the north-east high passes, where the Storm Tyrant
            waits. The track ends at a levelled duelling ground under the spire (the finish run's
            Act II beat); nothing else is built here.""",
            yards=(Yard((20, 45), (15, 13), 4.0, 0.7, elevation=0.0, name="Area_stormcrown_arena"),),
        ),

        # ================================================================== row 1 — the snow line
        Cell(
            key="north_snowfield", cell_id="frostfang_reach.north_snowfield",
            scene=f"{FROST}north_snowfield.tscn", **at(1, 0), resolution=64, seed=209,
            scatter="Scatter_snowfield", biome="Snowfield",
            note="""THE NORTH SNOWFIELD — open snow above the dragon country. The hunters' ridge route
            to the aerie crosses it. Nothing else.""",
        ),
        empty("high_traverse", **at(1, 1), seed=412, scatter="Scatter_heights", biome="Snowfield"),
        empty("glacier_head", **at(1, 2), seed=413, scatter="Scatter_glacier", biome="Glacier",
              tint=(0.70, 0.84, 0.92), tint_strength=0.25),
        empty("ice_shelf", **at(1, 3), seed=414, scatter="Scatter_glacier", biome="Glacier"),
        Cell(
            key="ash_approach", cell_id="frostfang_reach.ash_approach", scene=f"{FROST}ash_approach.tscn",
            **at(1, 4), resolution=64, seed=210, scatter="Scatter_ash_roost", biome="AshWaste",
            note="""THE ASH APPROACH — dead country north of the crater. Unroaded and empty.""",
        ),

        # ================================================================== row 2 — the glacier valley
        empty("roost_heights", **at(2, 0), seed=421, scatter="Scatter_dragon_roost", biome="Snowfield"),
        empty("snow_saddle", **at(2, 1), seed=422, scatter="Scatter_snowfield", biome="Snowfield"),
        Cell(
            key="glacier", cell_id="frostfang_reach.glacier", scene=f"{FROST}glacier.tscn", **at(2, 2),
            origin=(20.0, -1960.0), resolution=80, seed=205, tint=(0.70, 0.84, 0.92), tint_strength=0.30,
            scatter="Scatter_glacier", biome="Glacier",
            note="""
            GLACIER PASS — the ice pass north of the Clan Hold, between the valley walls, and the way to
            the head of the glacier and the aerie. Its walls, spurs, crevasses and pockets are unchanged.
            """,
            yards=(Yard((0, 0), (8, 6), 2.0, 0.45, elevation=-0.9, name="Area_glacier_saddle"),),
            routes=(
                Route((0, 10), (-4, 4), 7.0, 2.5, name="Path_glacier_entry"),
                Route((-4, 4), (0, 0), 7.0, 2.5, name="Path_glacier_chicane"),
                Route((0, 0), (-28, -2), 6.0, 2.0, name="Path_glacier_west"),
                Route((0, 0), (28, 2), 6.0, 2.0, name="Path_glacier_east"),
                Route((0, 0), (6, -20), 4.0, 2.5),
            ),
            landforms=(
                Ridge(a=(-60, 40), b=(-14, 42), half=16, h=26.0, fall=0.5),
                Ridge(a=(16, 43), b=(60, 44), half=16, h=26.0, fall=0.5),
                Ridge(a=(-60, -40), b=(-14, -42), half=16, h=26.0, fall=0.5),
                Ridge(a=(16, -43), b=(60, -44), half=16, h=26.0, fall=0.5),
                Mound(at=(0, -20), ext=(70, 42), h=6.0, fall=0.95),
                Mound(at=(-18, -18), ext=(25, 21), h=16.0, fall=0.45),
                Mound(at=(15, 25), ext=(28, 16), h=15.0, fall=0.6),
                Mound(at=(34, -20), ext=(21, 19), h=13.0, fall=0.45),
                Ridge(a=(-46, 10), b=(-30, 22), half=5.0, h=-7.0, fall=0.32, flat=1.0),
                Ridge(a=(14, -28), b=(26, -16), half=4.5, h=-8.0, fall=0.32, flat=1.0),
                Mound(at=(-34, -2), ext=(17, 15), h=-5.0, fall=0.55, flat=0.7),
                Mound(at=(32, 4), ext=(19, 16), h=-4.0, fall=0.55, flat=0.7),
                Mound(at=(0, 0), ext=(13, 11), h=-1.5, fall=0.8, flat=0.8),
            ),
        ),
        empty("east_crags", **at(2, 3), seed=424, scatter="Scatter_heights", biome="Alpine"),
        empty("ash_rim", **at(2, 4), seed=425, scatter="Scatter_ash_roost", biome="AshWaste",
              tint=(0.24, 0.17, 0.15), tint_strength=0.4),

        # ================================================================== row 3 — the lairs
        Cell(
            key="dragon_roost", cell_id="frostfang_reach.dragon_roost", scene=f"{FROST}dragon_roost.tscn",
            **at(3, 0), origin=(-330.0, -1830.0), resolution=80, seed=202,
            scatter="Scatter_dragon_roost", biome="Snowfield",
            note="""
            THE WILD DRAGON'S ROOST — the Splintered Shelf, at the head of its own side valley west of
            the Clan Hold beyond the roost ridge. The road leaves the hold's west gate, crosses the ridge
            by its one col and comes up the valley to the splinter field. The shelf, the narrows, the
            splinter ridges and the ice wall are unchanged.
            """,
            yards=(
                Yard((-14, -14), (18, 13), 5.0, 0.48, elevation=0.0, name="Area_dragon_bowl"),
                Yard((26, 0), (14, 12), 5.0, 0.30, elevation=-5.16, name="Area_dragon_splinter"),
            ),
            routes=(
                Route((45, 0), (14, 1), 6.0, 3.0, name="Path_dragon_approach"),
                Route((14, 1), (4, -4), 5.0, 2.0, name="Path_dragon_narrows"),
                Route((4, -4), (-14, -16), 6.0, 4.0, name="Path_dragon_shelf"),
            ),
            landforms=(
                Ridge(a=(-50, -40), b=(20, -42), half=15, h=20.0, fall=0.35),
                Mound(at=(-44, 0), ext=(21, 35), h=8.0, fall=0.9),
                Mound(at=(-18, 10), ext=(25, 19), h=-5.0, fall=0.5),
                Ridge(a=(14, -24), b=(30, 20), half=7, h=5.0, fall=0.45),
                Ridge(a=(34, -18), b=(44, 16), half=6, h=6.0, fall=0.45),
                Ridge(a=(14, -18), b=(18, -4), half=6, h=9.0, fall=0.4),
                Ridge(a=(2, 6), b=(8, 20), half=6, h=9.0, fall=0.4),
                Mound(at=(-14, -16), ext=(22, 19), h=10.0, fall=0.45, flat=1.0),
            ),
        ),
        empty("vale_head", **at(3, 1), seed=432, scatter="Scatter_snowfield", biome="Snowfield"),
        empty("hold_pass", **at(3, 2), seed=433, scatter="Scatter_heights", biome="Alpine", note="""
            HOLD PASS — the gap in the wall behind the Clan Hold, where the glacier road leaves."""),
        empty("burnt_col", **at(3, 3), seed=434, scatter="Scatter_ash_roost", biome="AshWaste", note="""
            THE BURNT COL — the gap in the eastern ridge where the snow turns to ash. Past it the ground
            is the Ash dragon's."""),
        Cell(
            key="ash_roost", cell_id="frostfang_reach.ash_roost", scene=f"{FROST}ash_roost.tscn",
            **at(3, 4), origin=(335.0, -1790.0), resolution=80, seed=203, tint=(0.20, 0.13, 0.11),
            tint_strength=0.68, scatter="Scatter_ash_roost", biome="AshWaste",
            note="""
            THE ASH ROOST — the corrupted crater beyond the burnt col, east of the Clan Hold. The rim,
            the bowl and the exposed causeway are unchanged; the approach is now a walk through ash
            country that tells you where you are going before the crater does.
            """,
            yards=(Yard((12, 5), (20, 17), 5.0, 0.68, elevation=0.0, name="Area_ash_bowl"),),
            routes=(
                Route((-50, 0), (-16, 2), 6.0, 4.0, name="Path_ash_causeway"),
                Route((-16, 2), (10, 6), 5.0, 3.0, name="Path_ash_bowl"),
                Route((10, 6), (26, -8), 3.5, 2.0, name="Path_ash_vent"),
            ),
            landforms=(
                Ridge(a=(30, -40), b=(52, 10), half=13, h=16.0, fall=0.5),
                Mound(at=(-34, -24), ext=(25, 19), h=-6.0, fall=0.6),
                Mound(at=(-34, 26), ext=(25, 19), h=-6.0, fall=0.6),
                Ridge(a=(-58, 0), b=(-14, 3), half=8, h=4.0, fall=0.5),
                Mound(at=(12, 5), ext=(35, 31), h=8.0, fall=0.45),
                Ridge(a=(24, -10), b=(40, -22), half=5, h=-3.0, fall=0.4),
                Mound(at=(12, 5), ext=(21, 18), h=-4.0, fall=0.3, flat=1.0),
            ),
        ),

        # ================================================================== row 4 — the hold
        empty("west_scree", **at(4, 0), seed=441, scatter="Scatter_dragon_roost", biome="Snowfield"),
        empty("roost_trail", **at(4, 1), seed=442, scatter="Scatter_march", biome="Alpine"),
        Cell(
            key="clan_hold", cell_id="frostfang_reach.clan_hold", scene=f"{FROST}clan_hold.tscn",
            **at(4, 2), origin=(-40.0, -1680.0), resolution=80, seed=201, safe_radius=30.0,
            scatter="Scatter_hold", biome="Alpine",
            note="""
            THE CLAN HOLD — the Stormbound's hold, on a bench at the head of the Stormbound Vale under the
            mountain wall, three hundred and fifty metres of vale road from the arrival. Roads leave it
            north for the glacier, west over the roost ridge and east through the burnt col. The moot
            ring, the work terrace and the beast runs are unchanged.
            """,
            yards=(
                Yard((-4, 2), (11, 9), 3.0, 0.70, elevation=0.0, name="Area_hold_moot"),
                Yard((15, -1), (7, 6), 1.5, 0.82, elevation=0.0, name="Area_hold_craft"),
                Yard((-23, 2), (5, 7), 2.0, 0.55, elevation=0.0, name="Area_hold_runs"),
                Yard(at=(-15.0, 10.1), ext=(4.5, 5.6), feather=3.0, blend=0.9),
            ),
            routes=(
                Route((-30, 0), (-14, 1), 5.5, 2.5, name="Path_hold_west"),
                Route((30, 0), (8, 0), 5.5, 2.5, name="Path_hold_east"),
                Route((0, -30), (12, -16), 5.0, 2.5, name="Path_hold_north"),
                Route((12, -16), (12, -5), 4.5, 2.0, name="Path_hold_ring"),
                Route((12, -5), (4, -4), 4.5, 2.0, name="Path_hold_moot_access"),
                Route((0, 20), (-2, 9), 4.0, 2.0, name="Path_hold_south"),
            ),
            landforms=(
                Ridge(a=(-60, -30), b=(-16, -33), half=13, h=22.0, fall=0.55),
                Ridge(a=(26, -34), b=(60, -36), half=13, h=22.0, fall=0.55),
                Mound(at=(0, 0), ext=(32, 26), h=0.0, fall=0.5, flat=0.85),
                Mound(at=(15, -1), ext=(9, 8), h=2.2, fall=0.35, flat=1.0),
                Mound(at=(-23, 2), ext=(8, 10), h=-1.6, fall=0.4, flat=1.0),
            ),
        ),
        empty("ravenspur", **at(4, 3), seed=444, scatter="Scatter_march", biome="Alpine", note="""
            RAVENSPUR — the spur east of the hold where the clan kept a watch on the vale. The old
            watchpost stands broken on the end of it."""),
        empty("eastern_marches", **at(4, 4), seed=445, scatter="Scatter_march", biome="Alpine"),

        # ================================================================== row 5 — the vale
        empty("western_fells", **at(5, 0), seed=451, scatter="Scatter_march", biome="Alpine"),
        empty("hunting_grounds", **at(5, 1), seed=452, scatter="Scatter_march", biome="Alpine", note="""
            THE HUNTING GROUNDS — open fell west of the vale. An abandoned hunting lodge stands on it,
            and the hunters' path to it leaves the vale road at the frozen tarn."""),
        empty("stormbound_vale", **at(5, 2), seed=453, scatter="Scatter_march", biome="Alpine", note="""
            THE STORMBOUND VALE — the long glacial valley from the arrival to the Clan Hold, and the
            only way into the Reach from the south."""),
        empty("stonewatch", **at(5, 3), seed=454, scatter="Scatter_march", biome="Alpine", note="""
            STONEWATCH — the clan's waystation on the vale road, half way between the arrival and the
            hold: a cairn, a fire, a shelter and a waystone."""),
        Cell(
            key="frost_march_e", cell_id="frostfang_reach.frost_march_e", scene=f"{FROST}frost_march_e.tscn",
            **at(5, 4), resolution=56, seed=207, scatter="Scatter_march",
            note="""THE EASTERN MARCH — empty fell east of the vale. Nothing here but the weather.""",
        ),
        empty("east_fells", **at(5, 5), seed=456, scatter="Scatter_march", biome="Alpine"),

        # ================================================================== row 6 — the arrival
        empty("south_fells_w", **at(6, 0), seed=461, scatter="Scatter_march", biome="Alpine"),
        Cell(
            key="frost_march_w", cell_id="frostfang_reach.frost_march_w", scene=f"{FROST}frost_march_w.tscn",
            **at(6, 1), resolution=64, seed=206, scatter="Scatter_march",
            note="""
            THE SOUTHERN MARCH — where the road from the Ember Crown comes out of the pass and the player
            arrives, with the vale opening north and the frozen tarn below the road to the west.
            """,
        ),
        empty("vale_foot", **at(6, 2), seed=463, scatter="Scatter_march", biome="Alpine"),
        empty("south_fells_e", **at(6, 3), seed=464, scatter="Scatter_march", biome="Alpine"),
        empty("southeast_fells", **at(6, 4), seed=465, scatter="Scatter_march", biome="Alpine"),
    ]


def roads() -> list[Road]:
    H = (-40.0, -1680.0)     # Clan Hold
    G = (20.0, -1960.0)      # Glacier Pass
    R = (-330.0, -1830.0)    # Wild roost
    A = (335.0, -1790.0)     # Ash roost
    Ae = (-110.0, -2215.0)   # Ancient Aerie

    def o(origin, local):
        return (origin[0] + local[0], origin[1] + local[1])

    return [
        # ---- the vale road: arrival -> Stonewatch -> Clan Hold
        Road(((-60, -1318), (-44, -1404), (18, -1470), (62, -1512), (20, -1580), o(H, (0, 20))),
             width=5.5, shoulder=2.5),
        # ---- the glacier road: hold north gate -> Hold Pass -> Glacier Pass -> snow saddle -> aerie
        Road((o(H, (0, -30)), (-30, -1788), (20, -1880), o(G, (0, 10))), width=5.0, shoulder=2.5),
        Road((o(G, (6, -20)), (4, -2046), (-44, -2112), (-96, -2146), o(Ae, (0, 55))), width=4.5, shoulder=2.5),
        # ---- west road over the roost ridge's col to the Splintered Shelf
        Road((o(H, (-30, 0)), (-150, -1712), (-212, -1752), (-252, -1808), o(R, (45, 0))), width=4.5, shoulder=2.5),
        # ---- east road through the burnt col to the ash crater's causeway
        Road((o(H, (30, 0)), (96, -1702), (196, -1756), (252, -1784), o(A, (-50, 0))), width=4.5, shoulder=2.5),
        # ---- the hunters' ridge route: roost road -> snowfield -> the aerie's west flank (the loop)
        Road(((-212, -1752), (-186, -1860), (-180, -1990), (-168, -2100), o(Ae, (0, 55))), width=3.0, shoulder=2.0),
        # ---- tertiary: hunters' path from the frozen tarn to the abandoned lodge
        Road(((-44, -1404), (-126, -1418), (-212, -1478), (-248, -1532)), width=2.5, shoulder=1.5),
        # ---- tertiary: the Ravenspur watch spur
        Road(((96, -1702), (150, -1672), (166, -1654)), width=2.5, shoulder=1.5),
        # ---- tertiary: Stormcrown track (reserved), from the glacier's east arm to the foot of the spire
        Road((o(G, (6, -20)), (4, -2046), (64, -2118), (150, -2134), (240, -2172), (318, -2166),
              (400, -2176)),
             width=3.0, shoulder=2.0),
    ]


def geography() -> list:
    vale = [(-60, -1300), (-40, -1420), (10, -1500), (-10, -1600)]
    forms = [
        # The northern wall behind the aerie and Stormcrown.
        # Gapped around the aerie: the massif is the Ancient's own mountain, and a wall laid over it
        # sank the summit court into its flank.
        Ridge(a=(-500, -2306), b=(-250, -2300), half=46, h=64.0, fall=0.8),
        Ridge(a=(20, -2304), b=(540, -2296), half=46, h=72.0, fall=0.8),
        # Stormcrown's blasted spire.
        Mound(at=(372, -2214), ext=(34, 34), h=58.0, fall=0.55),
        # The glacier valley's walls.
        Ridge(a=(-120, -1900), b=(-104, -2070), half=34, h=38.0, fall=0.8),
        Ridge(a=(182, -1890), b=(170, -2080), half=48, h=44.0, fall=0.8),
        # The roost ridge between the vale and the dragon country, with its col at the west road.
        Ridge(a=(-196, -1590), b=(-200, -1660), half=34, h=34.0, fall=0.8),
        Ridge(a=(-246, -1840), b=(-262, -1970), half=34, h=36.0, fall=0.8),
        # The eastern ridge, with the burnt col at the east road.
        Ridge(a=(236, -1560), b=(248, -1720), half=40, h=36.0, fall=0.8),
        Ridge(a=(266, -1840), b=(286, -1990), half=40, h=38.0, fall=0.8),
        # The fells that wall the vale.
        Ridge(a=(-340, -1330), b=(-300, -1560), half=50, h=30.0, fall=0.85),
        Ridge(a=(220, -1330), b=(250, -1520), half=50, h=32.0, fall=0.85),
        # The southern edge, gapped where the road comes in.
        Ridge(a=(-470, -1312), b=(-130, -1320), half=30, h=24.0, fall=0.85),
        Ridge(a=(12, -1322), b=(510, -1312), half=30, h=26.0, fall=0.85),
        # Ravenspur.
        Ridge(a=(90, -1640), b=(170, -1654), half=20, h=8.0, fall=0.9),
        # The frozen tarn: a shallow basin a player can wade (under WadeDepth), iced over.
        Mound(at=(-170, -1400), ext=(34, 26), h=-0.9, fall=0.6, flat=0.9),
        Water(at=(-170, -1400), ext=(44, 34), ident="FrozenTarn",
              shallow=(0.62, 0.72, 0.80), deep=(0.36, 0.48, 0.58), opaque=2.6),
    ]
    for a, b in zip(vale, vale[1:]):
        forms.append(Ridge(a=a, b=b, half=60, h=-7.0, fall=0.9))
    return forms


def district_pads() -> list:
    """Levelled pads for this realm's standalone structures (tools/district_layouts.py)."""
    import district_layouts
    return [Yard(at=(x, z), ext=(hx, hz), feather=2.5, blend=0.9)
            for x, z, hx, hz in district_layouts.pads(district_layouts.ITEMS)
            if EXTENT_X[0] < x < EXTENT_X[1] and ROWS[0][0] < z < ROWS[-1][1]]


def build_frostfang() -> tuple[str, list[str]]:
    spec = cells()
    issues = check_tiling("FrostfangReach", spec, ROWS, EXTENT_X)
    by_key = {c.key: c for c in spec}
    spec, _ = apply_origins(spec, [])
    spec = place_world(spec, geography() + district_pads())
    spec, road_issues = realize_roads(spec, roads())
    issues += [f"FrostfangReach: {issue}" for issue in road_issues]
    issues += check_envelopes("FrostfangReach", spec, {c.key: list(c.routes) for c in spec})

    # A lair's scatter clearing is authored in its content frame, so it moves with its content.
    def shift_exclusion(match):
        ident, x, z = match.group(1), float(match.group(2)), float(match.group(3))
        dx, dz = by_key[EXCLUSION_OWNERS[ident]].offset if ident in EXCLUSION_OWNERS else (0.0, 0.0)
        return (f'[sub_resource type="Resource" id="{ident}"]\nscript = ExtResource("11_exclusion")\n'
                f"Center = Vector2({round(x + dx, 3)}, {round(z + dz, 3)})")
    scatter = re.sub(r'\[sub_resource type="Resource" id="(Exclusion_[a-z_]+)"\]\n'
                     r'script = ExtResource\("11_exclusion"\)\nCenter = Vector2\(([-\d.]+), ([-\d.]+)\)',
                     shift_exclusion, SCATTER)
    # Trees and rocks stay out from under the monuments and the boss rings (gen_regions.py).
    from gen_regions import monument_exclusions
    spec, scatter = monument_exclusions(spec, scatter)
    return emit("frostfang_reach", HEADER, spec, [], ENVIRONMENT, BUDGET, RESOURCE, scatter, "Alpine"), issues
