#!/usr/bin/env python3
"""The hidden realm's macro layout, geography and approaches (finish plan, Act II). Consumed by
tools/gen_regions.py. Started from tools/region_spec_template.py.

⚠️ SECRECY. This realm is found by story, never advertised (docs/WORLD_ATLAS.md, tools/world_atlas.py).
Its region id and flags may appear anywhere; its NAME may not appear in player-visible text before
`flag.pale_concord_revealed`. The region's UnlockFlagId is that flag, which is what hides and disarms
the door to it (RegionSetup feeds a destination's UnlockFlagId to the portal's RequiredFlagId), and
every map location in here is RequiredFlagId-gated on it.
"""

from __future__ import annotations

from pathlib import Path

from gen_regions import (Cell, Mound, Ridge, Road, Route, Water, Yard, apply_origins,
                         check_envelopes, check_tiling, emit, place_world, realize_roads)

ROOT = Path(__file__).resolve().parent.parent

# --------------------------------------------------------------------------------------------------
# 1. MACRO GEOGRAPHY — the lattice. Inside the atlas band x -2600..-1500, z -400..900. Compact:
# twelve cells, three places (the landing, the city, the palace) and nine cells of still country.
# --------------------------------------------------------------------------------------------------
EXTENT_X = (-2360.0, -1760.0)
_ROW_BREAKS = [-160.0, 30.0, 200.0, 410.0, 640.0]
ROWS = list(zip(_ROW_BREAKS, _ROW_BREAKS[1:]))
# Irregular on purpose and chosen after the places.
COLUMNS = {
    0: [-2170.0, -1980.0],
    1: [-2200.0, -1960.0],
    2: [-2170.0, -1920.0],
    3: [-2140.0, -1950.0],
}

# The door out. Sunspire's library holds the story portal in; the way back goes there too. Until the
# Sunspire region exists on this branch, the door falls back to the Ember Crown so --validate never
# sees an unknown neighbour. Re-run tools/gen_regions.py after Sunspire lands and it switches itself.
RETURN_REGION = ("region.sunspire"
                 if any('Id = "region.sunspire"' in p.read_text(encoding="utf-8", errors="ignore")
                        for p in (ROOT / "data" / "regions").glob("*.tres"))
                 else "region.ember_crown")

HEADER = '''[gd_resource type="Resource" script_class="RegionResource" load_steps=12 format=3 uid="uid://crgnpaleconc0"]

[ext_resource type="Script" path="res://src/World/RegionResource.cs" id="1_region"]
[ext_resource type="Script" path="res://src/World/RegionCellResource.cs" id="2_cell"]
[ext_resource type="Script" path="res://src/World/WorldEnvironmentProfileResource.cs" id="3_environment"]
[ext_resource type="Script" path="res://src/World/WorldCellPresentationResource.cs" id="4_presentation"]
[ext_resource type="Script" path="res://src/World/WorldPerformanceBudgetResource.cs" id="5_budget"]
[ext_resource type="Script" path="res://src/World/WorldPathSegmentResource.cs" id="6_path"]
[ext_resource type="Script" path="res://src/World/WorldGroundAreaResource.cs" id="7_area"]
[ext_resource type="Script" path="res://src/World/WorldLandformResource.cs" id="8_landform"]
[ext_resource type="Script" path="res://src/World/WorldBiomeScatterResource.cs" id="9_scatter"]
[ext_resource type="Script" path="res://src/World/BiomeScatterLayerResource.cs" id="10_layer"]
[ext_resource type="Script" path="res://src/World/BiomeScatterExclusionResource.cs" id="11_exclusion"]
[ext_resource type="Script" path="res://src/World/WorldWaterResource.cs" id="12_water"]
[ext_resource type="Resource" path="res://data/world_gen/PaleConcord.tres" id="13_generation"]

; ⚠️ GENERATED BY tools/gen_regions.py FROM tools/region_spec_pale_concord.py. Edit the spec.
;
; THE HIDDEN REALM. A country the Hollow Queen hid from death and from history, held at dusk: still
; fields, straight canals, immaculate roads nobody walks, and one preserved city whose residents do
; not die. The landing is in the south, the city three hundred metres north of it, and her palace on
; its terrace three hundred metres further on at the end of the processional way.
'''

# --------------------------------------------------------------------------------------------------
# 6. BIOME, MATERIALS AND ATMOSPHERE. The dusk is pinned by FixedSkyHour: presentation only, the
# world clock keeps running (schedules, weather). Low warm sun, pale violet haze, drained colour.
# --------------------------------------------------------------------------------------------------
ENVIRONMENT = '''[sub_resource type="Resource" id="Environment_pale"]
script = ExtResource("3_environment")
SurfaceColor = Color(0.40, 0.39, 0.34, 1)
SecondaryColor = Color(0.52, 0.50, 0.43, 1)
DetailColor = Color(0.20, 0.19, 0.18, 1)
RoadColor = Color(0.62, 0.60, 0.55, 1)
BackdropColor = Color(0.30, 0.28, 0.32, 1)
Relief = 1.0
DetailScale = 2.5
BackdropRadius = 340.0
BackdropHeight = 60.0
TerrainSeed = 4400
SurfaceRoughness = 0.95
DetailRoughness = 0.88
RoadRoughness = 0.8
SlopeBlendStart = 0.24
SlopeBlendEnd = 0.62
HeightBlendStart = 7.0
HeightBlendEnd = 26.0
SunTint = Color(1.0, 0.80, 0.74, 1)
SunEnergyScale = 1.3
HazeColor = Color(0.66, 0.60, 0.70, 1)
HazeScale = 1.35
FixedSkyHour = 17.4

'''

BUDGET = '''[sub_resource type="Resource" id="Budget_pale"]
script = ExtResource("5_budget")
MaxAuthoredNodesPerCell = 400
MaxResidentAuthoredNodes = 3000
MaxResidentRuntimeNodes = 9000
MaxScatterInstancesPerCell = 5000
MaxResidentScatterInstances = 80000
MaxTerrainVerticesPerCell = 7000
MaxResidentTerrainVertices = 100000
MaxDrawCalls = 1800
MaxNodeCount = 20000
MaxStaticMemoryMb = 2048.0
MaxFrameMilliseconds = 16.67
ConsecutiveSamplesBeforeWarning = 5
BiomeCullDistance = 340.0
VisibilityUpdateInterval = 0.25
MaxConcurrentLoadRequests = 2
MaxCellInstantiationsPerFrame = 1
NearDistance = 95.0
MidDistance = 190.0
FarDistance = 420.0
BackdropDistance = 1100.0

'''

# 8. SCATTER. Drained colour: grass that never ripens, trees that never shed. Saturation under 1 is
# the only way to drain a shared asset.
SCATTER = '''[sub_resource type="Resource" id="Layer_still_grass"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_grass_tall.glb"
Count = 480
MinimumScale = 0.75
MaximumScale = 1.2
MinimumSpacing = 1.6
Saturation = 0.45
MaxSlope = 0.55
Clumping = 0.3
ClumpScale = 24.0
Tint = Color(0.86, 0.84, 0.70, 1)
TintVariation = 0.08
VisibilityRangeEnd = 62.0
VisibilityFadeMargin = 12.0
CastShadows = false

[sub_resource type="Resource" id="Layer_wheat"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_grass_wispy.glb"
Count = 360
MinimumScale = 0.8
MaximumScale = 1.1
MinimumSpacing = 1.8
Saturation = 0.5
MaxSlope = 0.35
Clumping = 0.7
ClumpScale = 40.0
Tint = Color(0.92, 0.86, 0.62, 1)
TintVariation = 0.05
VisibilityRangeEnd = 58.0
VisibilityFadeMargin = 10.0
CastShadows = false

[sub_resource type="Resource" id="Layer_pale_tree"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_tree_broadleaf.glb"
Count = 38
MinimumScale = 0.8
MaximumScale = 1.3
MinimumSpacing = 9.0
Saturation = 0.35
MaxSlope = 0.42
Clumping = 0.8
ClumpScale = 50.0
Tint = Color(0.82, 0.80, 0.74, 1)
TintVariation = 0.08
VisibilityRangeEnd = 150.0
VisibilityFadeMargin = 22.0
CastShadows = true
HlodShape = 1
HlodReduction = 3
HlodRangeBegin = 130.0
HlodRangeEnd = 320.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

[sub_resource type="Resource" id="Layer_stone"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_rock_cluster_a.glb"
Count = 10
MinimumScale = 0.3
MaximumScale = 0.6
MinimumSpacing = 12.0
Saturation = 0.3
MaxSlope = 0.9
Clumping = 0.5
ClumpScale = 30.0
Tint = Color(0.80, 0.78, 0.76, 1)
TintVariation = 0.08
VisibilityRangeEnd = 110.0
VisibilityFadeMargin = 16.0

[sub_resource type="Resource" id="Exclusion_arena"]
script = ExtResource("11_exclusion")
Center = Vector2(-35, 35)
Radius = 24.0

[sub_resource type="Resource" id="Scatter_fields"]
script = ExtResource("9_scatter")
Seed = 7301
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_still_grass"), SubResource("Layer_wheat"), SubResource("Layer_pale_tree"), SubResource("Layer_stone")])

[sub_resource type="Resource" id="Scatter_city"]
script = ExtResource("9_scatter")
Seed = 7302
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_still_grass"), SubResource("Layer_pale_tree")])

[sub_resource type="Resource" id="Scatter_palace"]
script = ExtResource("9_scatter")
Seed = 7303
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_still_grass"), SubResource("Layer_stone")])
Exclusions = Array[ExtResource("11_exclusion")]([SubResource("Exclusion_arena")])

'''

RESOURCE = '''[resource]
script = ExtResource("1_region")
Id = "region.pale_concord"
DisplayName = "The Pale Concord"
Realm = 5

; The landing: a stone quay beside the still canal in the south. The door home stands behind it.
SpawnPoint = @WORLD(-2090, 1.2, 600)@
PortalPoint = @WORLD(-2090, 0, 616)@

; ⚠️ THE SECRECY GATE. RegionSetup gives the door INTO this realm this flag as its RequiredFlagId, so
; the Sunspire library's portal stays hidden and inert until HiddenRealmReveal sets it.
UnlockFlagId = "flag.pale_concord_revealed"
Cells = Array[ExtResource("2_cell")]([@CELLS@])
EnvironmentProfile = SubResource("Environment_pale")
GenerationProfile = ExtResource("13_generation")
PerformanceBudget = SubResource("Budget_pale")
Bounds = @BOUNDS(20, -60, 160)@
SafeZoneCenter = @ORIGIN(city, 0, 0, 0)@
SafeZoneRadius = 45.0
WeavePotency = 0.35
DefaultWeatherId = "weather.clear"
DayPhaseBias = 2
; Sealed: only encounters naming this realm (the Queen's servants) roll here.
ScopedContentOnly = true
Neighbours = Array[String](["@RETURN@"])
'''

PALE = "res://scenes/regions/pale_concord/"


def empty(key, center, size, seed, scatter="Scatter_fields", biome=None, note=""):
    """Still country: ground, ecology and at most a road — no gameplay beat."""
    return Cell(key=key, cell_id=f"pale_concord.{key}", scene=f"{PALE}{key}.tscn",
                center=center, size=size, resolution=min(64, max(36, int(max(size) / 3.2))),
                seed=seed, scatter=scatter, biome=biome, note=note)


def lattice():
    out = {}
    for r, (top, bottom) in enumerate(ROWS):
        xs = [EXTENT_X[0], *COLUMNS[r], EXTENT_X[1]]
        for c in range(len(xs) - 1):
            out[(r, c)] = (((xs[c] + xs[c + 1]) / 2, (top + bottom) / 2), (xs[c + 1] - xs[c], bottom - top))
    return out


def cells() -> list[Cell]:
    L = lattice()

    def at(r, c):
        return {"center": L[(r, c)][0], "size": L[(r, c)][1]}

    return [
        # ================================================================== row 0 — the palace
        empty("west_mere", **at(0, 0), seed=801, biome="Wetland"),
        Cell(
            key="palace", cell_id="pale_concord.palace", scene=f"{PALE}palace.tscn",
            **at(0, 1), origin=(-2110.0, -40.0), resolution=72, seed=802,
            scatter="Scatter_palace", biome="TemperateLowland",
            note="""
            THE PALACE — the Hollow Queen's seat, on a raised terrace at the head of the processional
            way, three hundred metres north of the city. It is where the road ends because it is
            where everything in this country was decided. Her ring stands in the forecourt.
            """,
            landforms=(
                # The terrace the palace and its forecourt ring stand on: made, level and square.
                Mound(at=(0, -10), ext=(40, 42), h=2.5, fall=0.45, flat=1.0),
                # The rise behind it that closes the view.
                Ridge(a=(-70, -84), b=(60, -86), half=22, h=14.0, fall=0.8),
            ),
            yards=(
                Yard((0, 12), (16, 14), 3.0, 0.9, elevation=0.0, name="Area_palace_ring"),
                Yard((0, -30), (17, 15), 2.5, 0.9, elevation=0.0, name="Area_palace_hall"),
            ),
            routes=(Route((0, 28), (0, 6), 6.0, 2.5, name="Path_palace_forecourt"),),
        ),
        empty("north_fields", **at(0, 2), seed=803, biome="Pasture"),

        # ================================================================== row 1 — the processional
        empty("west_canal", **at(1, 0), seed=811, biome="Wetland"),
        empty("processional", **at(1, 1), seed=812, biome="Pasture", note="""
            THE PROCESSIONAL WAY — an immaculate road between the city and the palace, with nobody
            on it. The fields either side are sown and will never be cut."""),
        empty("east_orchard", **at(1, 2), seed=813, biome="Woodland"),

        # ================================================================== row 2 — the city
        empty("west_fields", **at(2, 0), seed=821, biome="Pasture"),
        Cell(
            key="city", cell_id="pale_concord.city", scene=f"{PALE}city.tscn",
            **at(2, 1), origin=(-2020.0, 268.0), resolution=72, seed=822, safe_radius=40.0,
            scatter="Scatter_city", biome="TemperateLowland",
            note="""
            THE PRESERVED CITY — the realm's one town, where the landing road and the processional
            way meet, on dry ground between the two canals. Every house is in perfect repair and the
            residents keep the same hours they kept on the day of the bargain.
            """,
            yards=(
                Yard((0, 0), (16, 14), 3.0, 0.85, elevation=0.0, name="Area_city_plaza"),
                Yard((-11, -11), (4, 5), 2.0, 0.9, elevation=0.0),
                Yard((11, -11), (6, 4), 2.0, 0.9, elevation=0.0),
                Yard((-11, 11), (6, 4), 2.0, 0.9, elevation=0.0),
                Yard((12, 11), (4, 5), 2.0, 0.9, elevation=0.0),
                Yard((-22, -2), (4, 4), 2.0, 0.9, elevation=0.0),
            ),
            routes=(
                Route((0, 22), (0, 0), 5.0, 2.0, name="Path_city_south"),
                Route((0, 0), (0, -24), 5.0, 2.0, name="Path_city_north"),
                Route((0, 0), (25, 0), 4.0, 2.0, name="Path_city_east"),
            ),
        ),
        empty("east_canal", **at(2, 2), seed=823, biome="Wetland", note="""
            THE EAST CANAL — a straight still cut. The city's east lane ends at its bank, looking
            at water that has not moved in four hundred years."""),

        # ================================================================== row 3 — the landing
        empty("southwest_fields", **at(3, 0), seed=831, biome="Pasture"),
        Cell(
            key="landing", cell_id="pale_concord.landing", scene=f"{PALE}landing.tscn",
            **at(3, 1), origin=(-2090.0, 590.0), resolution=56, seed=832,
            scatter="Scatter_fields", biome="Pasture",
            note="""
            THE LANDING — where the way from the Sunspire library lets out: a paved quay on the dry
            bank above the south fields, with the door home behind it and the city road ahead.
            """,
            yards=(Yard((0, 0), (10, 12), 3.0, 0.85, elevation=0.0, name="Area_landing_quay"),),
            routes=(Route((0, 26), (0, -12), 5.0, 2.0, name="Path_landing_quay"),),
        ),
        empty("south_fields", **at(3, 2), seed=833, biome="Pasture"),
    ]


def roads() -> list[Road]:
    return [
        # the landing road: quay -> city south gate
        Road(((-2090, 578), (-2078, 500), (-2066, 440), (-2040, 360), (-2020, 290)), width=5.0, shoulder=2.0),
        # the processional way: city north gate -> palace forecourt
        Road(((-2020, 244), (-2034, 190), (-2070, 100), (-2100, 20), (-2110, -12)), width=6.0, shoulder=2.5),
        # the east lane: city -> the canal bank (a dead end that pays out in a view)
        Road(((-1995, 268), (-1900, 280), (-1872, 318)), width=4.0, shoulder=1.5),
    ]


def geography() -> list:
    forms = [
        # The rise that walls the north and west: the realm's edge reads as country, not a line.
        Ridge(a=(-2380, -150), b=(-1740, -156), half=40, h=22.0, fall=0.85),
        Ridge(a=(-2350, -140), b=(-2346, 640), half=30, h=16.0, fall=0.85),
        Ridge(a=(-1770, -140), b=(-1774, 640), half=28, h=12.0, fall=0.85),
        # The west canal: a straight shallow cut (wadeable, under WadeDepth) with still water in it.
        Ridge(a=(-2250, 60), b=(-2250, 600), half=6, h=-0.8, fall=0.5, flat=1.0),
        Water(at=(-2250, 330), ext=(12, 290), ident="WestCanal",
              shallow=(0.46, 0.46, 0.52), deep=(0.24, 0.24, 0.30), opaque=2.4),
        # The east canal, the other side of the city.
        Ridge(a=(-1810, 120), b=(-1810, 600), half=6, h=-0.8, fall=0.5, flat=1.0),
        Water(at=(-1810, 360), ext=(12, 260), ident="EastCanal",
              shallow=(0.46, 0.46, 0.52), deep=(0.24, 0.24, 0.30), opaque=2.4),
        # The mere in the north-west: a still pond under the palace rise.
        Mound(at=(-2270, -60), ext=(40, 30), h=-0.9, fall=0.6, flat=0.9),
        Water(at=(-2270, -60), ext=(50, 40), ident="StillMere",
              shallow=(0.46, 0.46, 0.52), deep=(0.24, 0.24, 0.30), opaque=2.4),
        # Low swells in the fields so the country is not a table.
        Mound(at=(-1880, 520), ext=(60, 40), h=4.0, fall=0.95),
        Mound(at=(-2200, 180), ext=(50, 60), h=3.0, fall=0.95),
        Mound(at=(-1870, 60), ext=(55, 45), h=5.0, fall=0.95),
    ]
    return forms


def build_pale_concord() -> tuple[str, list[str]]:
    spec = cells()
    issues = check_tiling("PaleConcord", spec, ROWS, EXTENT_X)
    spec, _ = apply_origins(spec, [])
    spec = place_world(spec, geography())
    spec, road_issues = realize_roads(spec, roads())
    issues += [f"PaleConcord: {issue}" for issue in road_issues]
    issues += check_envelopes("PaleConcord", spec, {c.key: list(c.routes) for c in spec})
    resource = RESOURCE.replace("@RETURN@", RETURN_REGION)
    return emit("pale_concord", HEADER, spec, [], ENVIRONMENT, BUDGET, resource, SCATTER, "Pasture"), issues


if __name__ == "__main__":
    _text, _issues = build_pale_concord()
    for _issue in _issues:
        print(f"LATTICE ERROR: {_issue}")
    print("self-check: FAILED" if _issues else f"self-check: builds ({len(_text)} bytes)")
    raise SystemExit(1 if _issues else 0)
