#!/usr/bin/env python3
"""The Ember Crown's macro layout, geography and approaches. Consumed by tools/gen_regions.py."""

from __future__ import annotations

from gen_regions import (Cell, Mound, Ridge, Route, Seam, Water, Yard, check_envelopes,
                         check_seams, check_tiling, emit, local)

# The lattice. Row bands run the full width of the region and are split into columns, which is what
# makes a gap arithmetically impossible: a hole in the ground is a hole the player falls through and
# it is not visible from any file.
EXTENT_X = (-190.0, 140.0)
ROWS = [(-310.0, -220.0), (-220.0, -130.0), (-130.0, -60.0), (-60.0, 40.0), (40.0, 130.0)]

HEADER = '''[gd_resource type="Resource" script_class="RegionResource" load_steps=12 format=3 uid="uid://crgnembrcrown0"]

[ext_resource type="Script" path="res://src/World/RegionResource.cs" id="1_region"]
[ext_resource type="Script" path="res://src/World/RegionCellResource.cs" id="2_cell"]
[ext_resource type="Script" path="res://src/World/WorldEnvironmentProfileResource.cs" id="3_environment"]
[ext_resource type="Script" path="res://src/World/WorldCellPresentationResource.cs" id="4_presentation"]
[ext_resource type="Script" path="res://src/World/WorldPerformanceBudgetResource.cs" id="5_budget"]
[ext_resource type="Script" path="res://src/World/WorldPathSegmentResource.cs" id="6_path"]
[ext_resource type="Script" path="res://src/World/WorldGroundAreaResource.cs" id="7_area"]
[ext_resource type="Script" path="res://src/World/WorldLandformResource.cs" id="8_landform"]
[ext_resource type="Script" path="res://src/World/WorldBiomeScatterResource.cs" id="9_scatter"]
[ext_resource type="Script" path="res://src/World/BiomeScatterLayerResource.cs" id="10_layer"]
[ext_resource type="Script" path="res://src/World/BiomeScatterExclusionResource.cs" id="11_exclusion"]
[ext_resource type="Script" path="res://src/World/WorldWaterResource.cs" id="12_water"]
[ext_resource type="Resource" path="res://data/world_gen/EmberCrown.tres" id="13_generation"]

; ⚠️ GENERATED BY tools/gen_regions.py FROM tools/region_spec_ember.py. Edit the spec, not this file.
; The generator checks the lattice tiles exactly and that every seam route is authored from BOTH
; sides of the same world point before it writes a byte. Three shipped seam defects (NOW.md
; invariant 11) were all somebody doing that arithmetic in their head.
;
; ====================================================================================================
; THE EMBER CROWN AFTER THE 2026-08-29 GEOGRAPHY OVERHAUL
; ====================================================================================================
;
; WHAT CHANGED. The realm was ten cells packed edge to edge inside 210 x 250 metres, on flat 0.5 m
; slabs, under a 4 cm decorative wobble that faded to exactly zero at every boundary. Walking it read
; as cell -> POI -> cell -> POI: every location began the instant the last one ended, and the terrain
; drew the lattice on the ground in relief rather than hiding it. It is now 330 x 440 metres of
; CONTINUOUS ground — one region-wide heightfield with real elevation, real collision and real
; navigation, no seam fade anywhere — and six of the sixteen cells are transitional country with a
; road through them and almost nothing else in them, on purpose.
;
; WHAT DID NOT CHANGE, AND THIS IS DELIBERATE. Every location's interior circulation is the 2026-08-28
; layout rebuild's, lifted verbatim: the Kingsway's S, the Coilyard and the Crookway, the Crossway's
; dog-leg, Emberdeep's working loop, the Wilds North fork, Tarn's spit and neck, Hollowreach's spine
; between two flooded channels, the corrie throat, Ashfall's diagonal drive, the arena's south gate
; and asymmetric breach. Those were good and they were never the problem. What is new is the ground
; they stand on and the country between them.
;
; ⚠️ THE TOWN HUB DOES NOT MOVE, AND EVERY OTHER CELL MOVED AROUND IT. Its centre is still (0, 0, -10)
; because SpawnPoint, SafeZoneCenter and five raw-world NPC schedules all read off it — keeping it
; still turned a fourteen-file migration into a five-file one. It grew from 60 x 60 to 100 x 100
; instead, which is the same trick applied to the whole realm: a location keeps its own coordinates
; and gains outskirts.
;
;   ROW z -310..-220   frontier_waste (x -190..10)          arena (x 10..140)
;   ROW z -220..-130   north_moor (-190..-50)   wilds_north (-50..50)   ashen_reach (50..140)
;   ROW z -130..-60    west_downs (-190..-50)   crossway_post (-50..50) mine_road (50..140)
;   ROW z  -60..40     wilds_west (-190..-130)  tarn_landing (-130..-50)
;                      TOWN_HUB (-50..50)       emberdeep_mine (50..140)
;   ROW z   40..130    fen_edge (-190..-140)    hollowreach (-140..-50)
;                      embermarket (-50..50)    ashfall_homestead (50..140)
;
; DISTANCES THE PLAYER ACTUALLY WALKS, centre to centre (was -> is):
;   town -> market            56 -> 95      town -> mine        56 -> 95
;   town -> Tarn's Landing    56 -> 90      town -> Crossway     56 -> 85
;   market -> Ashfall         52 -> 95      market -> Hollowreach 52 -> 95
;   town square -> arena     150 -> 285, through the gate, the wilds AND an empty frontier
;
; ⚠️ SIX CELLS EXIST TO CONTAIN NOTHING. west_downs, mine_road, north_moor, ashen_reach,
; frontier_waste and fen_edge carry a road, weather, vegetation and landform and no gameplay beat at
; all. Two of them are dead ends. That is the feature: a realm where every thirty metres has a
; purpose is a realm that advertises on every step that it was designed. Do not fill them in.
'''

ENVIRONMENT = '''; ⚠️ Relief IS METRES NOW. It was 0.055 — five and a half centimetres of decorative wobble over a
; flat slab. 1.4 m is gentle countryside: enough that open ground is never a plane, small enough that
; it never fights an authored landform. HeightBlend moved with it (0.04/0.15 -> 7/26): the shader
; blends toward bare rock by real elevation, so hilltops and cut faces go stony on their own.
;
; ⚠️ RoadColor WENT FROM 0.31 TO 0.46 BECAUSE IT IS THE ONLY THING DRAWING A ROAD NOW. It used to be
; a tint under a 6 cm slab that was the visible carriageway; the slabs are deleted and the shader's
; path mask is the road, so a road colour three per cent off the surface colour is a road nobody can
; see. Trodden earth is paler and greyer than the field beside it.
[sub_resource type="Resource" id="Environment_ember_crown"]
script = ExtResource("3_environment")
SurfaceColor = Color(0.24, 0.20, 0.15, 1)
SecondaryColor = Color(0.34, 0.29, 0.20, 1)
DetailColor = Color(0.12, 0.105, 0.09, 1)
RoadColor = Color(0.46, 0.395, 0.29, 1)
BackdropColor = Color(0.19, 0.17, 0.15, 1)
Relief = 1.4
DetailScale = 2.75
BackdropCenter = Vector3(-25, 0, -90)
BackdropRadius = 340.0
BackdropHeight = 78.0
BackdropCount = 26
TerrainSeed = 3800
SurfaceRoughness = 0.96
DetailRoughness = 0.88
RoadRoughness = 0.82
SlopeBlendStart = 0.24
SlopeBlendEnd = 0.62
HeightBlendStart = 7.0
HeightBlendEnd = 26.0

; The Ember Crown keeps the realm's default light — ART_STYLE §2.1's "golden-hour amber, soft fog" —
; so its numbers are near-neutral. They are written out rather than defaulted so the contrast with
; Frostfang's block is legible in one diff, and so the next region has two worked examples.
SunTint = Color(1.0, 0.97, 0.92, 1)
SunEnergyScale = 1.0
HazeColor = Color(0.79, 0.77, 0.73, 1)
HazeScale = 1.0

'''

BUDGET = '''; ⚠️ THE TERRAIN BUDGET WENT UP AND THE MESH BUDGET WENT DOWN, AND THAT IS THE WHOLE PERFORMANCE
; STORY OF THIS OVERHAUL. Terrain vertices per cell rose 3000 -> 7000 because a 200 m transitional
; cell needs a grid, but a terrain cell is ONE draw call whatever its resolution — the realm's
; sixteen cells cost about 41k vertices and sixteen draws in total. In exchange roughly 1,100
; individual ground-cover Node3Ds across the Ember Crown became MultiMesh scatter layers, which is
; the lever NOW.md named and never pulled. Scatter INSTANCES are up an order of magnitude and scatter
; DRAWS are down by three figures: 8,500 instances across roughly forty MultiMeshInstance3Ds is forty
; draw calls, and the 1,277 authored Node3Ds they replaced were 1,277. ⚠️ READ THE INSTANCE BUDGET AS
; A MEMORY LIMIT, NOT A DRAW LIMIT — raising it is nearly free and raising MaxDrawCalls is not.
[sub_resource type="Resource" id="Budget_ember_crown"]
script = ExtResource("5_budget")
MaxAuthoredNodesPerCell = 700
MaxResidentAuthoredNodes = 4200
MaxResidentRuntimeNodes = 9000
MaxScatterInstancesPerCell = 2400
MaxResidentScatterInstances = 30000
MaxTerrainVerticesPerCell = 7000
MaxResidentTerrainVertices = 60000
MaxDrawCalls = 1800
MaxNodeCount = 14000
MaxStaticMemoryMb = 2048.0
MaxFrameMilliseconds = 25.0
ConsecutiveSamplesBeforeWarning = 5
BiomeCullDistance = 340.0
VisibilityUpdateInterval = 0.25
MaxConcurrentLoadRequests = 2
MaxCellInstantiationsPerFrame = 1

'''

# --------------------------------------------------------------------------------------------------
# Ecology. The Ember Crown authored NO biome scatter at all before this pass — every tuft of grass in
# the realm was a Node3D with its own draw call. These layers replace them.
# --------------------------------------------------------------------------------------------------

SCATTER = '''[sub_resource type="Resource" id="Layer_grass"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_grass_tall.glb"
Count = 620
MinimumScale = 0.7
MaximumScale = 1.35
MinimumSpacing = 1.6
Clumping = 0.32
ClumpScale = 22.0
MaxSlope = 0.55
Tint = Color(0.82, 0.84, 0.66, 1)
TintVariation = 0.22
VisibilityRangeEnd = 62.0
VisibilityFadeMargin = 12.0

[sub_resource type="Resource" id="Layer_grass_short"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_grass_short.glb"
Count = 520
MinimumScale = 0.75
MaximumScale = 1.3
MinimumSpacing = 1.4
MaxSlope = 0.6
Tint = Color(0.78, 0.80, 0.62, 1)
TintVariation = 0.20
VisibilityRangeEnd = 48.0
VisibilityFadeMargin = 10.0

[sub_resource type="Resource" id="Layer_clover"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_clover.glb"
Count = 240
MinimumScale = 0.7
MaximumScale = 1.15
MinimumSpacing = 2.4
Clumping = 0.45
ClumpScale = 18.0
MaxSlope = 0.5
Tint = Color(0.70, 0.78, 0.58, 1)
TintVariation = 0.18
VisibilityRangeEnd = 40.0
VisibilityFadeMargin = 8.0

[sub_resource type="Resource" id="Layer_bracken"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_fern.glb"
Count = 300
MinimumScale = 0.65
MaximumScale = 1.25
MinimumSpacing = 3.0
Clumping = 0.5
ClumpScale = 26.0
MaxSlope = 0.6
Tint = Color(0.62, 0.70, 0.52, 1)
TintVariation = 0.20
VisibilityRangeEnd = 70.0
VisibilityFadeMargin = 14.0

; ⚠️ THE REALM'S ENTIRE STONE COVER WAS ONE PEBBLE. `Layer_stone` scattered `prp_pebble_a` at 210
; instances per 100 x 100 m across FIVE of the six biome profiles, and a MultiMesh varies only yaw,
; uniform scale and tint — so every stone in the Ember Crown was the same 136-triangle silhouette
; seen from a different angle. That is the "obvious repetition" the visual-QA checklist names, and
; at 3.4 m spacing there is always another one of them in frame.
;
; ⚠️ THE FIX SPLITS THE EXISTING DENSITY, IT DOES NOT ADD TO IT. `MaxScatterInstancesPerCell` is
; 2400 and the seven layers already sat near it; four species at 90 + 70 + 26 + 5 = 191 is LESS
; ground cover than the 210 it replaces, and four distinct silhouettes instead of one. Read the
; instance budget as the memory limit it is (see BUDGET above) and the draw budget as the tight
; one: this is four MultiMeshInstance3Ds where there was one, which is three extra draws per cell.
[sub_resource type="Resource" id="Layer_stone"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_pebble_a.glb"
Count = 90
MinimumScale = 0.8
MaximumScale = 1.9
MinimumSpacing = 3.4
Clumping = 0.4
ClumpScale = 24.0
MaxSlope = 1.1
Tint = Color(0.68, 0.65, 0.60, 1)
TintVariation = 0.16
VisibilityRangeEnd = 55.0
VisibilityFadeMargin = 12.0

[sub_resource type="Resource" id="Layer_stone_b"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_pebble_c.glb"
Count = 70
MinimumScale = 0.85
MaximumScale = 2.05
MinimumSpacing = 3.1
Clumping = 0.46
ClumpScale = 21.0
MaxSlope = 1.1
Tint = Color(0.66, 0.64, 0.61, 1)
TintVariation = 0.18
VisibilityRangeEnd = 55.0
VisibilityFadeMargin = 12.0

; The knee-to-waist tier the realm had nothing in: `prp_pebble_a` tops out around 0.9 m even at
; MaximumScale, and the next thing up was an authored boulder placed by hand. Sparse and widely
; spaced, so it reads as an outcrop breaking the turf rather than as litter.
[sub_resource type="Resource" id="Layer_rock_medium"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_rock_medium.glb"
Count = 26
MinimumScale = 0.42
MaximumScale = 0.86
MinimumSpacing = 9.5
Clumping = 0.58
ClumpScale = 34.0
MaxSlope = 0.85
Tint = Color(0.70, 0.67, 0.62, 1)
TintVariation = 0.14
VisibilityRangeEnd = 120.0
VisibilityFadeMargin = 18.0
CastShadows = true

; ⚠️ A BOULDER LAYER IS AN HLOD LAYER FOR THE SAME REASON A TREE LAYER IS, and it needs one more
; than a tree does: at five per 100 x 100 m the detailed tier is nearly free, but a 5.6 m mass
; that pops out of existence at its visibility range is the most obvious cull in the realm.
[sub_resource type="Resource" id="Layer_boulder"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_boulder_large.glb"
Count = 5
MinimumScale = 0.55
MaximumScale = 1.05
MinimumSpacing = 26.0
Clumping = 0.5
ClumpScale = 60.0
MaxSlope = 0.6
Tint = Color(0.71, 0.68, 0.63, 1)
TintVariation = 0.12
VisibilityRangeEnd = 165.0
VisibilityFadeMargin = 22.0
CastShadows = true
HlodShape = 1
HlodReduction = 2
HlodRangeBegin = 145.0
HlodRangeEnd = 340.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.1, 1.1, 1.1)

; ⚠️ A TREE LAYER IS AN HLOD LAYER OR IT IS A DRAW CALL STORM AT DISTANCE. The proxy cone carries the
; silhouette past 130 m; the detailed instance fades out before it.
[sub_resource type="Resource" id="Layer_pine"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_tree_broadleaf.glb"
Count = 260
MinimumScale = 0.75
MaximumScale = 1.6
MinimumSpacing = 6.5
Clumping = 0.78
ClumpScale = 46.0
MaxSlope = 0.42
Tint = Color(0.72, 0.78, 0.66, 1)
TintVariation = 0.18
VisibilityRangeEnd = 150.0
VisibilityFadeMargin = 22.0
CastShadows = true
HlodShape = 1
HlodReduction = 3
HlodRangeBegin = 130.0
HlodRangeEnd = 320.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

[sub_resource type="Resource" id="Layer_scrub"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_bush_flowering.glb"
Count = 200
MinimumScale = 0.7
MaximumScale = 1.5
MinimumSpacing = 5.0
Clumping = 0.55
ClumpScale = 30.0
MaxSlope = 0.62
Tint = Color(0.66, 0.70, 0.56, 1)
TintVariation = 0.20
VisibilityRangeEnd = 105.0
VisibilityFadeMargin = 18.0
HlodShape = 2
HlodReduction = 4
HlodRangeBegin = 92.0
HlodRangeEnd = 230.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

; Settlement ecology: the verges and back lots of an inhabited place, and nothing tall enough to hide
; a doorway. EdgePadding 1 because a settlement's outskirts should thin INTO the next cell's country,
; not stop at a line 3 m short of the seam.
[sub_resource type="Resource" id="Scatter_settled"]
script = ExtResource("9_scatter")
Seed = 5101
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_grass_short"), SubResource("Layer_clover"), SubResource("Layer_stone"), SubResource("Layer_stone_b")])

[sub_resource type="Resource" id="Scatter_pasture"]
script = ExtResource("9_scatter")
Seed = 5102
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_grass"), SubResource("Layer_grass_short"), SubResource("Layer_clover"), SubResource("Layer_scrub")])

[sub_resource type="Resource" id="Scatter_wilds"]
script = ExtResource("9_scatter")
Seed = 5103
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_grass"), SubResource("Layer_bracken"), SubResource("Layer_pine"), SubResource("Layer_scrub"), SubResource("Layer_stone"), SubResource("Layer_stone_b"), SubResource("Layer_rock_medium")])

[sub_resource type="Resource" id="Scatter_upland"]
script = ExtResource("9_scatter")
Seed = 5104
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_grass"), SubResource("Layer_bracken"), SubResource("Layer_stone"), SubResource("Layer_stone_b"), SubResource("Layer_rock_medium"), SubResource("Layer_boulder"), SubResource("Layer_scrub")])

[sub_resource type="Resource" id="Scatter_waste"]
script = ExtResource("9_scatter")
Seed = 5105
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_stone"), SubResource("Layer_stone_b"), SubResource("Layer_rock_medium"), SubResource("Layer_boulder"), SubResource("Layer_bracken"), SubResource("Layer_grass_short"), SubResource("Layer_scrub")])

[sub_resource type="Resource" id="Scatter_shore"]
script = ExtResource("9_scatter")
Seed = 5106
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_grass_short"), SubResource("Layer_stone"), SubResource("Layer_stone_b"), SubResource("Layer_scrub")])

'''

RESOURCE = '''[resource]
script = ExtResource("1_region")
Id = "region.ember_crown"
DisplayName = "The Ember Crown"
Realm = 0
SpawnPoint = Vector3(0, 1.2, 5)

; ⚠️ THE PORTAL MOVED WITH THE CROSSWAY, NOT WITH THE PLAYER. The gate cell went from (0, 0, -66) to
; (0, 0, -95) when the lattice grew, so the portal that stood at world z = -72 — cell-local z = -6,
; the gap between the two palisades — is world z = -101 now. Read the local offset, never the old
; world number: that is the 37C placement bug and it is completely silent.
PortalPoint = Vector3(0, 0, -101)
Cells = Array[ExtResource("2_cell")]([@CELLS@])
EnvironmentProfile = SubResource("Environment_ember_crown")
GenerationProfile = ExtResource("13_generation")
PerformanceBudget = SubResource("Budget_ember_crown")

; The lattice is x -190..140, z -310..130. Bounds are that plus a margin, and the Y range is real
; now: the Emberdeep pit floor is 6 m down and the frontier ridges are 25 m up.
Bounds = AABB(-210, -80, -330, 370, 200, 480)
SafeZoneCenter = Vector3(0, 0, -10)
SafeZoneRadius = 34.0
WeavePotency = 1.0
DefaultWeatherId = "weather.cloudy"
DayPhaseBias = 2
Neighbours = Array[String](["region.frostfang_reach"])

; The Crossway toll (Phase 38M). Authored on BOTH regions rather than on one, because there is one
; gate on one road and the wardens do not care which way a cart is pointing. 25 gold sits under
; TravelFee.CrossRegionFee (40) on purpose: walking must stay the cheap way across, or the toll is a
; tax on the only option and the map screen quietly becomes the sensible one.
TollGold = 25
TollPermitFlagId = "flag.crossway.permit"
TollPassFlagId = "flag.crossway.pass"
'''


def cells() -> list[Cell]:
    return [
        # ------------------------------------------------------------------ row z 40..130 (the south)
        Cell(
            key="fen_edge", cell_id="ember_crown.fen_edge",
            scene="res://scenes/regions/ember_crown/fen_edge.tscn",
            center=(-165.0, 85.0), size=(50.0, 90.0), resolution=28, seed=116,
            scatter="Scatter_shore",
            biome="Wetland",
            note="""
            THE FEN EDGE — sodden dead ground west of the wharf, and one of the six cells that exist
            to contain nothing. A causeway comes in over the wilds_west seam, crosses the marsh and
            stops. There is no loot here, no encounter marker, no NPC and no map pin: it is the
            far side of Hollowreach's water, seen from the far side of Hollowreach's water.
            """,
            landforms=(
                Mound(at=(0, 0), ext=(30, 42), h=-2.6, fall=0.9),
                Mound(at=(-15, -30), ext=(19, 17), h=4.5, fall=0.9),
                Ridge(a=(-24, 36), b=(24, 30), half=9, h=3.0, fall=0.85),
            ),
            routes=(Route((-2, -16), (-8, 8), 3.0, 2.5),),
        ),
        Cell(
            key="hollowreach", cell_id="ember_crown.hollowreach",
            scene="res://scenes/regions/ember_crown/hollowreach.tscn",
            center=(-95.0, 85.0), size=(90.0, 90.0), resolution=60, seed=107,
            tint=(0.38, 0.42, 0.38), tint_strength=0.12, scatter="Scatter_shore",
            biome="Wetland",
            note="""
            HOLLOWREACH — the drowned district, and now actually drowned. The channels were two
            translucent boxes laid on a flat floor; they are CUT into the ground: sheer little
            retaining faces (Falloff 0.2 across a 7 m half-width is a 3:1 wall), 3.2 m of water in
            them, and the spine standing 0.9 m proud between the two of them. The open water west is
            4.5 m deep behind a drop-off steeper than 45 degrees, so a player cannot casually walk
            out into it — there is no swimming in this game and there is now no need for an
            invisible wall either, because the LAND says no. The whole district sits 1.2 m below the
            country around it, so the approach from the market descends into it.
            """,
            legacy_paths=("Path_hollowreach_east", "Path_hollowreach_turn", "Path_hollowreach_spine"),
            legacy_areas=("Area_hollowreach_hollow", "Area_hollowreach_street", "Area_hollowreach_spine"),
            area_elevation={"Area_hollowreach_hollow": 0.62, "Area_hollowreach_street": 1.16,
                            "Area_hollowreach_spine": 0.61},
            # 42B: the Ledger House stands on this. Area_hollowreach_street is 8 m of road plus 2 m
            # of shoulder in an 8 m deep pad — the pad is the street — so the counting house sits on
            # a bench cut north of it, at the street's own 1.4 rather than at the district's 0.9:
            # the point of the Syndicate's house is that it is the dry building above the channels.
            yards=(Yard(at=(20.0, 23.0), ext=(5.0, 5.0), feather=2.5, blend=0.8, elevation=1.17),),
            landforms=(
                # ⚠️ THE DISTRICT STANDS JUST ABOVE THE WATERLINE AND THE CHANNELS ARE CUT BELOW
                # IT. It used to sit 1.2 m UNDER it, which meant every water surface had to stop
                # exactly at its own carved edge or it flooded the streets — and a surface that
                # stops at its own edge is a rectangle of water lying on the ground, which is
                # the artefact this whole overhaul exists to remove. At +0.8 the declared bodies
                # are drawn generously larger than the wet ground and their borders are buried in
                # the banks, so what the player sees is the terrain's own contour.
                Mound(at=(0, 0), ext=(48, 46), h=0.8, fall=0.8),
                Mound(at=(34, -30), ext=(30, 24), h=5.0, fall=0.85),
                Mound(at=(2, 34), ext=(34, 14), h=2.2, fall=0.9),
                # The open water west, out past the cell edge and under the fen's eastern margin —
                # which is how the fen reads as the far shore rather than the next room. A 0.6 m
                # margin first so there is a wadeable rim, then the 4.5 m basin behind a 53 degree
                # face nothing walks down.
                Mound(at=(-46, 0), ext=(38, 50), h=-0.6, fall=0.25, flat=0.9),
                Mound(at=(-46, 0), ext=(34, 46), h=-4.5, fall=0.10, flat=1.0),
                # The two flooded streets, cut to the footprint of their declared water bodies. Falloff
                # 0.2 across a 5 m half-width is a 3:1 retaining face: these are channels carved
                # into a district, not decals laid on top of one.
                Ridge(a=(-31, -10), b=(10, -10), half=5.5, h=-3.2, fall=0.2, flat=1.0),
                Ridge(a=(-31, 13), b=(-2, 13), half=6.5, h=-3.2, fall=0.2, flat=1.0),
            ),
            routes=(Route((33, -14), (27, 12), 4.0, 2.0),),
            # ⚠️ DRAWN LARGER THAN THE BASINS, ON PURPOSE. The surfaces used to be BoxMeshes hand-
            # sized to sit INSIDE the carved ellipse so their straight edges would not lie on dry
            # land, which left a rectangle of water short of its own shore. WorldCellWater takes the
            # shoreline from the terrain instead, so a body that overhangs the bank renders nothing
            # there and the coastline is the ground's own contour.
            waters=(
                Water(at=(-50, 0), ext=(42, 52), ident="OpenWater",
                      shallow=(0.20, 0.31, 0.31), deep=(0.04, 0.11, 0.15), opaque=1.6),
                Water(at=(-10, -10), ext=(26, 11), ident="ChannelNorth"),
                Water(at=(-12, 13), ext=(24, 12), ident="ChannelSouth"),
            ),
        ),
        Cell(
            key="embermarket", cell_id="ember_crown.embermarket",
            scene="res://scenes/regions/ember_crown/embermarket.tscn",
            center=(0.0, 85.0), size=(100.0, 90.0), resolution=64, seed=102,
            safe_radius=32.0, scatter="Scatter_settled",
            biome="Pasture",
            note="""
            THE EMBERMARKET — still the town's second district and still connected to it, but the two
            no longer share a property line. Ninety-five metres of walled fields, a knoll and a
            bending road now sit between the square and the market gate, so the settlement reads as
            a place with districts rather than two squares glued together. The market keeps its exact
            x alignment with the town hub, which is why the Kingsway and the Gate Lane still meet.
            The Salt Steps became a real 0.45 m terrace instead of a 15 cm slab (0.5 m is
            StepUp.MaxHeight, so anything taller is a wall), and the ground falls
            away west toward Hollowreach and rises south into pasture.
            """,
            legacy_paths=("Path_market_gate", "Path_market_crook", "Path_market_caravan",
                          "Path_market_dock", "Path_market_alley", "Path_market_sump"),
            # The salt steps colonnade spreads 16 m and the south wall runs across the
            # market slope; both came out over half a metre off their own ground.
            # ⚠️ NO PAD UNDER THE SALT STEPS. Its colonnade straddles the market's own roads, and a
            # yard there makes the ground range WORSE rather than better: the pad levels everything
            # the road does not cover while the road holds its own grade, so the two meet in a step
            # across the footprint. Road beats yard by design (NOW.md invariant 21) and this is what
            # that rule looks like from the other side - a structure on a road wants moving, not
            # levelling. Measured: 0.77 m without a pad, 0.77 m with one.
            yards=(Yard(at=(-2.0, 22.5), ext=(5.0, 5.0), feather=3.0, blend=0.9),
                   Yard(at=(-2.5, 16.6), ext=(4.5, 5.6), feather=3.0, blend=0.9)),
            legacy_areas=("Area_market_yard", "Area_market_terrace", "Area_market_timber",
                          "Area_market_sump"),
            area_elevation={"Area_market_terrace": 0.0},
            landforms=(
                Mound(at=(0, -4), ext=(36, 34), h=0.0, fall=0.5, flat=0.92),
                Mound(at=(16, 14), ext=(9.5, 8.5), h=0.45, fall=0.35, flat=1.0),
                Mound(at=(-10, 38), ext=(42, 18), h=4.0, fall=0.9),
                Ridge(a=(44, -40), b=(40, 34), half=8, h=3.5, fall=0.85),
                Mound(at=(-48, -2), ext=(22, 36), h=-3.5, fall=0.85),
            ),
        ),
        Cell(
            key="ashfall_homestead", cell_id="ember_crown.ashfall_homestead",
            scene="res://scenes/regions/ember_crown/ashfall_homestead.tscn",
            center=(95.0, 85.0), size=(90.0, 90.0), resolution=52, seed=109,
            safe_radius=26.0, scatter="Scatter_pasture",
            biome="Pasture",
            note="""
            THE ASHFALL HOMESTEAD — the player's holding, moved out of the market's back pocket. It
            used to begin twenty-six metres from the last market stall; the plot's gate is now
            ninety-five metres of pasture, field bank and hedge from it, up a lane that bends round a
            hollow. The plot itself is a pad so the cottage stands level, and the boundary dissolves
            into rough grazing rather than stopping at a floor edge. Nothing inside the hexagon moved.
            ⚠️ PropertyResource.PlacementCenter moved with the cell: local (0, 5) is world (95, 0, 90).
            """,
            legacy_paths=("Path_homestead_lane", "Path_homestead_gate", "Path_homestead_drive",
                          "Path_homestead_door", "Path_homestead_entry"),
            legacy_areas=("Area_homestead_yard", "Area_homestead_garden", "Area_homestead_workshop"),
            landforms=(
                Mound(at=(0, 0), ext=(26, 24), h=0.0, fall=0.55, flat=0.85),
                Mound(at=(-32, 26), ext=(21, 19), h=3.5, fall=0.95),
                Mound(at=(30, 30), ext=(23, 21), h=-2.0, fall=0.95),
                Ridge(a=(-40, 34), b=(40, 30), half=6, h=2.2, fall=0.8),
                Mound(at=(38, -34), ext=(31, 23), h=7.0, fall=0.9),
            ),
        ),

        # ------------------------------------------------------------------ row z -60..40 (the town belt)
        Cell(
            key="wilds_west", cell_id="ember_crown.wilds_west",
            scene="res://scenes/regions/ember_crown/wilds_west.tscn",
            center=(-160.0, -10.0), size=(60.0, 100.0), resolution=40, seed=108,
            scatter="Scatter_wilds",
            biome="Woodland",
            note="""
            THE WESTERN WILDS — the bandit corrie, and the corrie is LAND now. It was a horseshoe of
            scaled prp_rock_cluster props standing on a floor; it is four ridge landforms 13-16 m
            high with a Falloff of 0.35 (a 2:1 face, comfortably past the 45 degree floor limit, so
            the walls are walls without a single collider) and a five-metre throat left between the
            two east ridges. The camp floor is dished 1.5 m below the apron. The scramble over the
            north lip survives as a narrow path that notches the ridge. Rock props still dress those
            faces; they no longer ARE those faces.
            """,
            # Path_wilds_west_scramble is re-cut below. The layout rebuild's 10 m notch over the
            # northern lip was a 47 degree climb once that lip became a twelve-metre ridge instead
            # of a row of rocks; the same scramble over 23 m is 28 degrees, which is a scramble
            # rather than a wall with a road painted on it.
            legacy_paths=("Path_wilds_west_track", "Path_wilds_west_throat"),
            legacy_areas=("Area_wilds_west_camp", "Area_wilds_west_apron"),
            area_elevation={"Area_wilds_west_camp": 0.0, "Area_wilds_west_apron": -2.33},
            landforms=(
                Mound(at=(0, -42), ext=(38, 18), h=8.0, fall=0.85),
                Mound(at=(0, 42), ext=(38, 18), h=6.0, fall=0.85),
                Mound(at=(20, -2), ext=(24, 32), h=3.0, fall=0.95),
                Ridge(a=(-26, -18), b=(-26, 15), half=10, h=14.0, fall=0.35),
                Ridge(a=(-26, -18), b=(-6, -20), half=10, h=12.0, fall=0.35),
                Ridge(a=(-26, 15), b=(-8, 16), half=10, h=12.0, fall=0.35),
                Ridge(a=(-4, -18), b=(-4, -6), half=8, h=12.0, fall=0.4),
                Ridge(a=(-4, 6), b=(-4, 15), half=8, h=12.0, fall=0.4),
                Mound(at=(-14, -1), ext=(12, 13), h=-1.5, fall=0.5, flat=0.9),
            ),
            routes=(Route((4, -26), (-10, -8), 2.5, 1.5),
                    Route((2, -1), (16, 12), 3.0, 2.0)),
        ),
        Cell(
            key="tarn_landing", cell_id="ember_crown.tarn_landing",
            scene="res://scenes/regions/ember_crown/tarn_landing.tscn",
            center=(-90.0, -10.0), size=(80.0, 100.0), resolution=56, seed=106,
            safe_radius=22.0, scatter="Scatter_shore",
            surplus=("fish",), demand=("ore", "metal", "fuel"), shocks=("fish", "ore"),
            biome="Wetland",
            note="""
            TARN'S LANDING — the spit and the bay survive; the water stopped being a decal over flat
            ground. The land DESCENDS to the shore: a wadeable shelf at -0.7 m runs out from the
            beach, and beyond it the bed drops to -4.5 m over three and a half metres, which is a 53
            degree face. CharacterBody3D's floor limit is 45, so the player slides off it rather than
            strolling out across visually deep water — no swimming was added and no invisible wall
            was needed. The spit stands 0.8 m proud, the docks reach out over the shelf, and the land
            rises east toward the town road.
            ⚠️ The tarn is a DECLARED WorldWaterResource (see waters= below), not a mesh in the .tscn.
            Its SurfaceY is a real lake level rather than a clearance, WorldCellWater fades it out
            where the ground rises through it, and declaring it is what puts the deep lobes under
            WorldWater's non-swimming recovery contract.
            """,
            legacy_paths=("Path_tarn_road_east", "Path_tarn_road_shore", "Path_tarn_neck"),
            legacy_areas=("Area_tarn_spit", "Area_tarn_yard"),
            area_elevation={"Area_tarn_spit": -0.31, "Area_tarn_yard": 0.81},
            landforms=(
                Mound(at=(26, -6), ext=(23, 44), h=4.0, fall=0.9),
                Mound(at=(6, -36), ext=(27, 17), h=3.0, fall=0.9),
                Mound(at=(-2, 40), ext=(30, 14), h=2.0, fall=0.9),
                # ⚠️ A SHORELINE IS WHERE THE LAND CROSSES THE WATER LEVEL, NOT WHERE THE WATER MESH
                # ENDS. Two rounds of this cell were spent shrinking water boxes to fit carved
                # basins, and both read as a rectangle of sea lying on flat ground — because the
                # visible edge was still the mesh's own edge. WorldCellWater bakes the depth at every
                # surface vertex and fades the water out where the ground crosses the waterline, so
                # the declared body is deliberately LARGER than the wet ground and what the player
                # sees is the terrain's own contour, which is a coastline.
                #
                # A low bank around the bay, so the land visibly falls toward the water.
                Mound(at=(-14, 16), ext=(32, 30), h=2.2, fall=0.9),
                # The wadeable shelf: 70 cm over a gentle slope. The player may paddle here, and it
                # stops three metres short of the shore road at z = -2 — a basin that reaches the
                # road floods the only way into the district.
                Mound(at=(-16, 17), ext=(17, 15), h=-0.7, fall=0.7, flat=0.85),
                # ...and the two deep lobes. Falloff 0.2 across a 7 m half-extent is past
                # CharacterBody3D's 45 degree floor limit, so the player slides off the edge of the
                # shelf instead of strolling out over four metres of open water. No swimming was
                # added and no invisible wall was needed: the LAND says no.
                Mound(at=(-21, 15), ext=(7, 15), h=-4.2, fall=0.2, flat=1.0),
                Mound(at=(-7, 20), ext=(13, 9), h=-4.2, fall=0.2, flat=1.0),
            ),
            routes=(Route((10, -8), (20, 18), 4.0, 2.0),),
            # One body, not two. The old TarnSouth box lay entirely inside the main one and existed
            # only to reach a lobe the big rectangle could not cover without spilling onto dry land;
            # a terrain-derived shoreline makes both the split and the careful sizing unnecessary.
            waters=(Water(at=(-14, 17), ext=(30, 27), ident="Tarn",
                          shallow=(0.21, 0.33, 0.34), deep=(0.05, 0.13, 0.18), opaque=1.5),),
        ),
        Cell(
            key="town_hub", cell_id="ember_crown.town_hub",
            scene="res://scenes/regions/ember_crown/town_hub.tscn",
            center=(0.0, -10.0), size=(100.0, 100.0), resolution=64, seed=101,
            scatter="Scatter_settled",
            note="""
            THE TOWN HUB — the anchor, and the one centre in the realm that did not move. What moved
            is its edge: 60 x 60 became 100 x 100, so the square, the two yards and the Long Green
            now sit in the middle of twenty metres of thinning outskirts on every side instead of
            ending at a floor edge. The settlement core is levelled to y = 0 by a pad, which is why
            SpawnPoint (0, 1.2, 5) and every one of the five raw-world town schedules is still
            correct to the centimetre. Around that pad the ground moves: a knoll south-west that the
            market road bends round, a wooded bank north-east, a hollow east, and a rise north so the
            walk to the Crossway gate is a climb.
            """,
            legacy_paths=("Path_town_kingsway_s", "Path_town_kingsway_m", "Path_town_kingsway_n",
                          "Path_town_west", "Path_town_east", "Path_town_green"),
            # Two houses on the town's own slope, 0.87 m and 0.75 m out across their
            # footprints. The square, craft yard and green already have pads; these two sit
            # outside all three.
            yards=(Yard(at=(-20.0, 22.0), ext=(6.0, 6.0), feather=3.0, blend=0.9),
                   Yard(at=(25.0, 6.0), ext=(6.0, 7.0), feather=3.0, blend=0.9),
                   Yard(at=(-22.0, 11.1), ext=(4.5, 4.6), feather=3.0, blend=0.9)),
            legacy_areas=("Area_town_square", "Area_town_craft", "Area_town_green"),
            landforms=(
                Mound(at=(-4, -6), ext=(40, 36), h=0.0, fall=0.55, flat=0.9),
                Mound(at=(-40, 36), ext=(19, 17), h=5.5, fall=0.85),
                Ridge(a=(16, -48), b=(48, -20), half=10, h=6.0, fall=0.8),
                Mound(at=(44, 14), ext=(16, 14), h=-3.0, fall=0.9),
                Mound(at=(-6, -46), ext=(32, 17), h=3.0, fall=0.9),
            ),
        ),
        Cell(
            key="emberdeep_mine", cell_id="ember_crown.emberdeep_mine",
            scene="res://scenes/regions/ember_crown/emberdeep_mine.tscn",
            center=(95.0, -10.0), size=(90.0, 100.0), resolution=64, seed=104,
            tint=(0.58, 0.45, 0.33), tint_strength=0.15, safe_radius=24.0,
            scatter="Scatter_upland",
            surplus=("ore", "metal", "fuel"), demand=("food", "fish", "textile"),
            shocks=("ore", "food"),
            biome="Excavated",
            note="""
            THE EMBERDEEP MINE — the biggest single change in the realm, and the one the brief asked
            for by name: the earth has been excavated instead of having mining props stood on it.
            The working loop is unchanged (defile -> Weighing Yard -> haul road -> the Cut -> Pit
            Head -> spoil track -> back to the yard) and every one of those is now geography:
              the defile      a 6 m trench cut through a spur, walls at 3:1
              the yard        a level bench at y = 0 with the hill standing over it
              the Cut         the haul road grades from about +1 down to the pit floor over 18 m,
                              which is a 21 degree descent — a road a cart could actually use
              the Pit Head    a 3.5 m deep floor inside a raised 3 m rim - six and a half
                              metres of relief whose inner faces are far past the walkable
                              limit, so the pit is a pit and the Cut is the only graded way in
              the spoil bank  a 6 m ridge of thrown waste along the east of the spoil track
            The big hill sits on the EAST half of the north edge on purpose: the mine road out to the
            Crossway runs up the west side of it, so leaving is a walk under the workings rather than
            over them.
            """,
            legacy_paths=("Path_mine_defile", "Path_mine_haul", "Path_mine_link"),
            legacy_areas=("Area_mine_yard", "Area_mine_pithead", "Area_mine_rest"),
            area_elevation={"Area_mine_yard": 0.0, "Area_mine_pithead": 0.0, "Area_mine_rest": 0.0},
            landforms=(
                Ridge(a=(2, -42), b=(44, -34), half=26, h=16.0, fall=0.75),
                Ridge(a=(-32, -14), b=(-8, -16), half=13, h=8.0, fall=0.7),
                Ridge(a=(-36, -2), b=(-10, -2), half=5.5, h=-6.0, fall=0.3, flat=1.0),
                Mound(at=(-8, 9.5), ext=(14, 14), h=0.0, fall=0.4, flat=1.0),
                Mound(at=(21, -12), ext=(30, 30), h=2.0, fall=0.85),
                Mound(at=(21, -12), ext=(13, 13.5), h=-3.5, fall=0.42, flat=1.0),
                Ridge(a=(23, -2), b=(23, 24), half=7, h=6.0, fall=0.55),
                Mound(at=(-40, -4), ext=(16, 28), h=-2.0, fall=0.9),
                Mound(at=(6, 40), ext=(34, 16), h=2.5, fall=0.9),
            ),
            # The Cut, re-authored longer than the 12 m the layout rebuild gave it so the descent
            # into the pit head is a 21 degree grade rather than a 45 degree one.
            # The Cut, re-authored longer than the 12 m the layout rebuild gave it AND started
            # further back up the haul road, so the descent to the pit floor is a 20 degree grade a
            # cart could use rather than the 45 degree one a 12 m run produced.
            # A spiral haul ramp round the pit ran straight into the spoil bank, which is where a
            # spoil bank belongs. The pit is 3.5 m deep inside a 3 m rim instead of 6 inside 4:
            # six and a half metres of relief with sheer inner walls still reads as an excavation
            # from the yard, and the Cut is one 20 degree ramp again.
            # ⚠️ THE CUT OVERLAPS THE HAUL ROAD RATHER THAN BUTTING ONTO IT. A segment's target is
            # held constant past its own ends for as far as its width reaches, so two routes that
            # meet at a corner with very different gradients blend into a kink a metre or two long —
            # which is what ValidateRouteGrades kept calling at 48 degrees on a ramp whose average
            # is 9. Starting the Cut back on the haul road makes the two nearly collinear over the
            # overlap, so their targets agree where they are blended.
            routes=(Route((0, 3), (18, -8), 6.0, 2.5),
                    Route((14, -6), (14, 19), 6.0, 2.0),
                    Route((-8, 6), (-6, -26), 4.5, 2.0)),
        ),

        # ------------------------------------------------------------------ row z -130..-60
        Cell(
            key="west_downs", cell_id="ember_crown.west_downs",
            scene="res://scenes/regions/ember_crown/west_downs.tscn",
            center=(-120.0, -95.0), size=(140.0, 70.0), resolution=40, seed=111,
            scatter="Scatter_pasture",
            note="""
            THE WEST DOWNS — a hundred and forty metres of empty rolling grazing between the tarn
            country and the Crossway. A drovers' track comes off the warden compound, crosses two
            rises and stops in the middle of a field. Nothing here. That is the point.
            """,
            landforms=(
                Mound(at=(-30, -6), ext=(42, 28), h=8.0, fall=0.95),
                Mound(at=(34, 10), ext=(36, 24), h=-3.0, fall=0.95),
                Ridge(a=(-64, 20), b=(10, 26), half=13, h=5.0, fall=0.9),
                Mound(at=(52, -20), ext=(29, 21), h=6.0, fall=0.9),
            ),
            routes=(Route((40, 4), (14, 8), 3.0, 2.5),),
        ),
        Cell(
            key="crossway_post", cell_id="ember_crown.crossway_post",
            scene="res://scenes/regions/ember_crown/crossway_post.tscn",
            center=(0.0, -95.0), size=(100.0, 70.0), resolution=56, seed=103,
            safe_radius=26.0, scatter="Scatter_upland",
            note="""
            THE CROSSWAY POST — the gate now stands where a gate would stand. Two nine-metre spurs
            run in from the east and west edges and stop short of each other, and the palisade closes
            the neck between them: the toll is charged at the one place in forty metres of ridge that
            a road can get through, which is an argument the geography makes rather than the .tres.
            North of the post the ground falls away toward the wilds, so the frontier is visibly
            downhill of the last safe ground.
            """,
            legacy_paths=("Path_crossway_south", "Path_crossway_turn", "Path_crossway_gate",
                          "Path_crossway_dogleg", "Path_crossway_north", "Path_crossway_compound"),
            legacy_areas=("Area_crossway_hold", "Area_crossway_compound", "Area_crossway_gate"),
            area_elevation={"Area_crossway_hold": 0.0, "Area_crossway_compound": 0.0,
                            "Area_crossway_gate": 0.0},
            # 42B: the Wardens' Watch stands on this. ⚠️ IT IS NOT INSIDE THE COMPOUND, AND IT
            # CANNOT BE: Path_crossway_compound runs east-west along z = 14 with a 4 m road and a
            # 1.5 m shoulder, so the compound pad IS the track for all but three metres of its
            # depth. The keep went there first and the traversal probe found what that means — two
            # authored routes with no navigation path through them. This apron sits south of the
            # track, between it and the palisade, and is levelled to the compound's own 0.0.
            yards=(Yard(at=(-19.5, 6.5), ext=(6.0, 5.0), feather=2.5, blend=0.8, elevation=0.0),),
            landforms=(
                Mound(at=(0, 4), ext=(32, 26), h=0.0, fall=0.5, flat=0.9),
                # THE NECK IS NORTH OF THE POST, NOT ACROSS IT. Drawn east-west through the
                # compound the two spurs sat on the road out to the mine and on the drovers' track
                # west, and ValidateRouteGrades reported a 68 degree climb on both. They close the
                # NORTHERN road instead - which is the road the toll is charged on - and stop 14 m
                # either side of it, so the gate fills a 28 m gap in 100 m of ridge.
                Ridge(a=(-50, -16), b=(-14, -19), half=10, h=9.0, fall=0.55),
                Ridge(a=(14, -19), b=(50, -16), half=10, h=9.0, fall=0.55),
                Mound(at=(0, -32), ext=(30, 12), h=-2.0, fall=0.95),
            ),
            routes=(Route((6, 9), (18, 12), 4.5, 2.0),),
        ),
        Cell(
            key="mine_road", cell_id="ember_crown.mine_road",
            scene="res://scenes/regions/ember_crown/mine_road.tscn",
            center=(95.0, -95.0), size=(90.0, 70.0), resolution=36, seed=112,
            scatter="Scatter_upland",
            note="""
            THE MINE ROAD — hill country and a three-way junction: the Crossway west, the Emberdeep
            south, the burnt heath north. No buildings, no encounter marker, no pin. A crossroads
            that is only a crossroads is what makes the two places it joins feel like they are in the
            same country.
            """,
            landforms=(
                Ridge(a=(-40, 20), b=(40, 10), half=17, h=8.0, fall=0.85),
                Mound(at=(-10, -20), ext=(31, 21), h=5.0, fall=0.9),
                Mound(at=(30, -8), ext=(21, 19), h=-3.0, fall=0.9),
            ),
            routes=(Route((-20, 12), (0, 18), 4.5, 2.0),
                    Route((0, 18), (4, 0), 3.5, 2.0)),
        ),

        # ------------------------------------------------------------------ row z -220..-130
        Cell(
            key="north_moor", cell_id="ember_crown.north_moor",
            scene="res://scenes/regions/ember_crown/north_moor.tscn",
            center=(-120.0, -175.0), size=(140.0, 90.0), resolution=40, seed=113,
            scatter="Scatter_wilds",
            note="""
            THE NORTH MOOR — high open ground west of the wilds road, with an eleven-metre swell in
            the middle of it that hides everything behind it. A sheep track comes over from the
            encounter bowl and dies. Empty on purpose.
            """,
            landforms=(
                Mound(at=(-40, 0), ext=(48, 36), h=11.0, fall=0.95),
                Mound(at=(30, -20), ext=(31, 25), h=-4.0, fall=0.9),
                Ridge(a=(-70, 34), b=(60, 26), half=15, h=6.0, fall=0.9),
                Mound(at=(56, 18), ext=(23, 21), h=7.0, fall=0.85),
            ),
            routes=(Route((44, 2), (20, 6), 2.5, 2.5),),
        ),
        Cell(
            key="wilds_north", cell_id="ember_crown.wilds_north",
            scene="res://scenes/regions/ember_crown/wilds_north.tscn",
            center=(0.0, -175.0), size=(100.0, 90.0), resolution=48, seed=105,
            scatter="Scatter_wilds",
            biome="Woodland",
            note="""
            THE NORTHERN WILDS — the fork survives; what changed is that you can no longer see the
            whole cell from the fork. The encounter bowl is a real 3.5 m hollow, the ruin sits two
            metres DOWN in dead ground behind a scarp instead of twenty metres from everything, the
            deadfall is under that scarp, and Cairn Rise is a seven-metre rise you can see the road
            from. The cell doubled in area and none of the new ground has anything on it: the two
            branches of the fork now run through quiet forest for thirty metres before they reach
            anything authored.
            """,
            legacy_paths=("Path_wn_stem", "Path_wn_west_a", "Path_wn_west_b", "Path_wn_west_c",
                          "Path_wn_east_a", "Path_wn_east_b", "Path_wn_east_c"),
            legacy_areas=("Area_wilds_north_ruin", "Area_wn_bowl", "Area_wn_deadfall"),
            # ⚠️ The deadfall hollow was a 5.4 m cut, and the Deadfall Lodge stands on its
            # LIP - 2.8 m from Path_wilds_north_ap2 as well, so a building pad there is
            # cancelled by the road (road beats yard, deliberately). With real relief the
            # hollow's own edge put 2.6 m of slope across the lodge's footprint. Two metres
            # is still a deadfall and leaves the lodge somewhere to stand.
            area_elevation={"Area_wilds_north_ruin": -0.3, "Area_wn_bowl": 0.61,
                            "Area_wn_deadfall": -5.39},
            # ⚠️ The Deadfall Lodge is placed ON this pad by design ("the Ash Hunters' hub, on the
            # deadfall pad under the scarp"), and the pad was authored at a blend of 0.22 — which
            # levelled almost nothing, so the lodge stood on 4.96 m of variation and its lower storey
            # disappeared into the hillside. A pad a building sits on has to actually be a floor.
            area_blend={"Area_wn_deadfall": 0.9},
            # ⚠️ AND THE SUPPLEMENTARY PAD SHARES THE HOLLOW'S ELEVATION, WHICH IS THE WHOLE TRICK.
            # Area_wn_deadfall reaches most of the lodge but not its eastern side. A yard added there
            # at elevation 0 made things WORSE - 4.96 m became 5.68 - because two pads at different
            # heights over one footprint meet in a step, and strongest-mask-wins picks a side. Giving
            # this one the hollow's own offset makes the two agree instead of compete.
            yards=(Yard(at=(21.5, -15.0), ext=(5.5, 6.5), feather=3.0, blend=0.9,
                        elevation=-5.39),),
            landforms=(
                Mound(at=(0, -38), ext=(62, 27), h=9.0, fall=0.9),
                Mound(at=(-17, 8), ext=(15, 16), h=-3.5, fall=0.7),
                Ridge(a=(10, -22), b=(30, -4), half=8, h=5.0, fall=0.5),
                Mound(at=(0, -5), ext=(17, 17), h=-2.0, fall=0.65),
                Mound(at=(24, 18), ext=(13, 13), h=7.0, fall=0.7),
                Mound(at=(-34, 26), ext=(21, 19), h=-2.0, fall=0.95),
                Mound(at=(-40, -30), ext=(20, 18), h=6.0, fall=0.9),
            ),
        ),
        Cell(
            key="ashen_reach", cell_id="ember_crown.ashen_reach",
            scene="res://scenes/regions/ember_crown/ashen_reach.tscn",
            center=(95.0, -175.0), size=(90.0, 90.0), resolution=36, seed=114,
            tint=(0.42, 0.36, 0.31), tint_strength=0.18, scatter="Scatter_waste",
            biome="BurnedHeath",
            note="""
            THE ASHEN REACH — burnt heath under a long scarp, joining the mine road to the eastern
            branch of the wilds fork. Stone, bracken and dead ground. Nothing to find.
            """,
            landforms=(
                Ridge(a=(-40, -30), b=(40, -20), half=19, h=14.0, fall=0.7),
                Mound(at=(-6, 16), ext=(31, 23), h=-3.0, fall=0.9),
                Mound(at=(34, 8), ext=(21, 21), h=6.0, fall=0.85),
            ),
            routes=(Route((-4, 20), (-16, -2), 3.0, 2.0),),
        ),

        # ------------------------------------------------------------------ row z -310..-220 (frontier)
        Cell(
            key="frontier_waste", cell_id="ember_crown.frontier_waste",
            scene="res://scenes/regions/ember_crown/frontier_waste.tscn",
            center=(-90.0, -265.0), size=(200.0, 90.0), resolution=44, seed=115,
            scatter="Scatter_waste",
            biome="BurnedHeath",
            note="""
            THE FRONTIER WASTE — two hundred metres of nothing at the top of the realm, and the last
            thing between the wilds and the arena. The road crosses one corner of it and leaves; the
            other hundred and eighty metres are a ridge, two swells and a hollow that the player can
            see from the road and has no reason to walk to. This is the cell that makes the arena
            feel far away.
            """,
            landforms=(
                Mound(at=(-60, 10), ext=(62, 36), h=14.0, fall=0.95),
                Mound(at=(20, -16), ext=(52, 32), h=10.0, fall=0.9),
                Ridge(a=(-96, -30), b=(96, -34), half=17, h=9.0, fall=0.85),
                Mound(at=(60, 24), ext=(35, 23), h=-4.0, fall=0.9),
            ),
        ),
        Cell(
            key="arena", cell_id="ember_crown.arena",
            scene="res://scenes/regions/ember_crown/arena.tscn",
            center=(75.0, -265.0), size=(130.0, 90.0), resolution=48, seed=110,
            tint=(0.36, 0.24, 0.20), tint_strength=0.16, scatter="Scatter_waste",
            biome="BurnedHeath",
            note="""
            THE ARENA — a boss arena at the end of a road, which is what it always should have been.
            It was sixty-five metres from the town square in one revision and directly behind the
            wilds in the next; it is two hundred and eighty-five metres and four cells from the
            square now, reached by a road that enters this cell at its far west edge and takes
            sixty-five metres of climbing, bending approach to arrive at the south gate. The ring
            stands on a levelled 3 m shelf, there are crags behind it to the east, and the ground
            drops six metres beyond the breach in the north wall, so the second way out is a way DOWN.
            The corrected south entrance and the asymmetric breach are unchanged.
            """,
            legacy_paths=("Path_arena_gate", "Path_arena_breach"),
            legacy_areas=("Area_arena_ring", "Area_arena_breach"),
            area_elevation={"Area_arena_ring": 0.0, "Area_arena_breach": 0.0},
            landforms=(
                Mound(at=(0, 0), ext=(32, 30), h=3.0, fall=0.35, flat=1.0),
                Mound(at=(-50, 4), ext=(32, 36), h=-3.0, fall=0.9),
                Ridge(a=(30, -30), b=(58, 20), half=15, h=18.0, fall=0.5),
                Mound(at=(6, -38), ext=(42, 17), h=-6.0, fall=0.6),
            ),
            routes=(Route((-40, 30), (-16, 27), 5.0, 2.5),
                    Route((-16, 27), (0, 18), 5.0, 2.0)),
        ),
    ]


def seams() -> list[Seam]:
    return [
        Seam("town_hub", "embermarket", (-8, 40), (-11, 30), (-11, -26), 4.5, 2.0),
        Seam("town_hub", "crossway_post", (-4, -60), (-6, -24), (-6, 18), 6.0, 2.5),
        Seam("town_hub", "tarn_landing", (-50, -8), (-30, -4), (26, -8), 5.5, 2.0),
        Seam("town_hub", "emberdeep_mine", (50, -14), (30, -2), (-26, -2), 5.5, 2.0),
        Seam("embermarket", "hollowreach", (-50, 98), (-26, 12), (26, 12), 4.0, 2.0),
        Seam("embermarket", "ashfall_homestead", (50, 88), (26, 3.5), (-26, 3.5), 5.0, 2.0),
        Seam("tarn_landing", "wilds_west", (-130, -12), (-26, -1), (25, 0), 4.0, 2.0),
        Seam("tarn_landing", "hollowreach", (-70, 40), (20, 18), (33, -14), 4.0, 2.0),
        Seam("wilds_west", "fen_edge", (-165, 40), (16, 12), (-2, -16), 3.0, 2.5),
        Seam("crossway_post", "west_downs", (-50, -86), (-20, 14), (40, 4), 4.0, 2.0),
        Seam("crossway_post", "wilds_north", (-2, -130), (0, -26), (0, 25), 6.0, 2.5),
        Seam("crossway_post", "mine_road", (50, -88), (18, 12), (-20, 12), 4.5, 2.0),
        Seam("emberdeep_mine", "mine_road", (95, -60), (-6, -26), (0, 18), 4.5, 2.0),
        Seam("mine_road", "ashen_reach", (95, -130), (4, 0), (-4, 20), 3.5, 2.0),
        Seam("wilds_north", "north_moor", (-50, -168), (-17, 8), (44, 2), 2.5, 2.5),
        Seam("wilds_north", "ashen_reach", (50, -182), (13, -6), (-16, -2), 3.0, 2.5),
        Seam("wilds_north", "frontier_waste", (0, -220), (0, -25), (94, 30), 5.0, 2.5),
        Seam("frontier_waste", "arena", (10, -240), (94, 30), (-40, 30), 5.0, 2.5),
    ]


def build_ember(legacy: dict[str, str]) -> tuple[str, list[str]]:
    spec = cells()
    by_key = {c.key: c for c in spec}
    link = seams()

    issues = check_tiling("EmberCrown", spec, ROWS, EXTENT_X)
    issues += check_seams("EmberCrown", by_key, link)

    routed = {c.key: list(c.routes) for c in spec}
    for seam in link:
        routed[seam.a].append(Route(seam.reach_a, local(by_key[seam.a], seam.at)))
        routed[seam.b].append(Route(local(by_key[seam.b], seam.at), seam.reach_b))
    issues += check_envelopes("EmberCrown", spec, routed)

    return emit("ember_crown", HEADER, spec, link, legacy,
                ENVIRONMENT, BUDGET, RESOURCE, SCATTER, "TemperateLowland"), issues
