#!/usr/bin/env python3
"""The Ember Crown's macro layout, geography and approaches. Consumed by tools/gen_regions.py."""

from __future__ import annotations

from gen_regions import (Cell, Mound, Ridge, Road, Route, Water, Yard, apply_origins,
                         check_envelopes, check_tiling, emit, place_world, realize_roads)

# The lattice. Row bands run the full width of the region and are split into columns, which is what
# makes a gap arithmetically impossible: a hole in the ground is a hole the player falls through and
# it is not visible from any file.
EXTENT_X = (-520.0, 520.0)
_ROW_BREAKS = [-720.0, -610.0, -500.0, -350.0, -250.0, -95.0, 20.0, 160.0, 280.0, 440.0]
ROWS = list(zip(_ROW_BREAKS, _ROW_BREAKS[1:]))
# Interior column breaks per row. ⚠️ THEY ARE IRREGULAR ON PURPOSE and chosen AFTER the places:
# every settlement, dungeon and landmark was put where the country wants it, and the breaks were then
# moved until none of them sat near a cell centre or across a cell edge. A cell is a streaming
# partition; tools/check_world_composition.py fails the region if the places start lining up with it.
COLUMNS = {
    0: [-290.0, -40.0, 190.0, 370.0],
    1: [-290.0, -40.0, 120.0, 270.0, 420.0],
    2: [-420.0, -170.0, 40.0, 280.0],
    3: [-330.0, -150.0, 60.0, 280.0],
    4: [-330.0, -150.0, 20.0, 200.0, 350.0],
    5: [-400.0, -220.0, -90.0, 110.0, 300.0],
    6: [-420.0, -230.0, -110.0, 80.0, 240.0, 390.0],
    7: [-400.0, -240.0, -60.0, 140.0, 380.0],
    8: [-400.0, -200.0, 0.0, 200.0, 380.0],
}

HEADER = '''[gd_resource type="Resource" script_class="RegionResource" load_steps=12 format=3 uid="uid://crgnembrcrown0"]

[ext_resource type="Script" path="res://src/World/RegionResource.cs" id="1_region"]
[ext_resource type="Script" path="res://src/World/RegionCellResource.cs" id="2_cell"]
[ext_resource type="Script" path="res://src/World/WorldEnvironmentProfileResource.cs" id="3_environment"]
[ext_resource type="Script" path="res://src/World/WorldCellPresentationResource.cs" id="4_presentation"]
[ext_resource type="Script" path="res://src/World/WorldPerformanceBudgetResource.cs" id="5_budget"]
[ext_resource type="Script" path="res://src/World/WorldPathSegmentResource.cs" id="6_path"]
[ext_resource type="Script" path="res://src/World/WorldGroundAreaResource.cs" id="7_area"]
[ext_resource type="Script" path="res://src/World/WorldLandformResource.cs" id="8_landform"]
[ext_resource type="Script" path="res://src/World/WorldBiomeScatterResource.cs" id="9_scatter"]
[ext_resource type="Script" path="res://src/World/BiomeScatterLayerResource.cs" id="10_layer"]
[ext_resource type="Script" path="res://src/World/BiomeScatterExclusionResource.cs" id="11_exclusion"]
[ext_resource type="Script" path="res://src/World/WorldWaterResource.cs" id="12_water"]
[ext_resource type="Resource" path="res://data/world_gen/EmberCrown.tres" id="13_generation"]

; ⚠️ GENERATED BY tools/gen_regions.py FROM tools/region_spec_ember.py. Edit the spec, not this file.
; The generator checks the lattice tiles exactly and that every seam route is authored from BOTH
; sides of the same world point before it writes a byte. Three shipped seam defects (NOW.md
; invariant 11) were all somebody doing that arithmetic in their head.
;
; ====================================================================================================
; THE EMBER CROWN AFTER THE 2026-09 WORLD REBUILD
; ====================================================================================================
;
; WHAT CHANGED. The realm was 330 x 440 m: every settlement sat on its own cell centre ninety metres
; from the next, the capital was thirteen houses on a green, and the boss arena was a four-minute walk
; from the inn. It is now 1040 x 1160 m, laid out geography first: the Crown Range walls the north
; with one pass, and the Crossway holds the pass; the Emberwash comes off the range, runs down its
; valley past the capital's west side under Kingsbridge and into the Tarn; the fens and Hollowreach
; spread below the lake; Emberdeep is dug into the eastern hills; the farm belt and the ash flats run
; south to the border hills. The capital stands where the roads meet, on the spur the Iron Citadel
; crowns, and the arena is at the far end of the realm under the Emberspire, reached by the short
; road across the frontier waste or the long one up from Emberdeep.
;
; CELLS ARE STREAMING PARTITIONS, NOT PLACES. Fifty-two of them in irregular rows and columns, chosen
; after the places. Settlement content is placed at a world ORIGIN inside its cell (Cell.origin), the
; realm's landforms and roads are authored as world geometry (geography() and roads() in the spec) and
; split across whichever cells they cross. Interior circulation — the Crookway, the Coilyard, the
; Kingsway's S, Emberdeep's working loop, Tarn's spit, Hollowreach's channels, the corrie, the arena's
; gate and breach — is unchanged.
;
; DISTANCES, content origin to content origin (was -> is):
;   Crown Square -> Embermarket      95 -> 138     Crown Square -> Tarn's Landing   90 -> 348
;   Crown Square -> Emberdeep         95 -> 392     Crown Square -> Crossway         85 -> 547
;   Embermarket -> Hollowreach        95 -> 396     Embermarket -> Ashfall           95 -> 371
;   Crown Square -> arena            285 -> 614 (and further by either road)
;
; ⚠️ MOST OF THE REALM CONTAINS NOTHING. Thirty-six of the fifty-two cells carry ground, weather,
; ecology and at most a road. That is the feature. Do not fill them in.
'''

ENVIRONMENT = '''; ⚠️ Relief IS METRES NOW. It was 0.055 — five and a half centimetres of decorative wobble over a
; flat slab. 1.4 m is gentle countryside: enough that open ground is never a plane, small enough that
; it never fights an authored landform. HeightBlend moved with it (0.04/0.15 -> 7/26): the shader
; blends toward bare rock by real elevation, so hilltops and cut faces go stony on their own.
;
; ⚠️ RoadColor WENT FROM 0.31 TO 0.46 BECAUSE IT IS THE ONLY THING DRAWING A ROAD NOW. It used to be
; a tint under a 6 cm slab that was the visible carriageway; the slabs are deleted and the shader's
; path mask is the road, so a road colour three per cent off the surface colour is a road nobody can
; see. Trodden earth is paler and greyer than the field beside it.
[sub_resource type="Resource" id="Environment_ember_crown"]
script = ExtResource("3_environment")
SurfaceColor = Color(0.24, 0.20, 0.15, 1)
SecondaryColor = Color(0.34, 0.29, 0.20, 1)
DetailColor = Color(0.12, 0.105, 0.09, 1)
RoadColor = Color(0.46, 0.395, 0.29, 1)
BackdropColor = Color(0.19, 0.17, 0.15, 1)
Relief = 1.4
DetailScale = 2.75
BackdropCenter = Vector3(-25, 0, -90)
BackdropRadius = 340.0
BackdropHeight = 78.0
BackdropCount = 26
TerrainSeed = 3800
SurfaceRoughness = 0.96
DetailRoughness = 0.88
RoadRoughness = 0.82
SlopeBlendStart = 0.24
SlopeBlendEnd = 0.62
HeightBlendStart = 7.0
HeightBlendEnd = 26.0

; The Ember Crown keeps the realm's default light — ART_STYLE §2.1's "golden-hour amber, soft fog" —
; so its numbers are near-neutral. They are written out rather than defaulted so the contrast with
; Frostfang's block is legible in one diff, and so the next region has two worked examples.
SunTint = Color(1.0, 0.97, 0.92, 1)
SunEnergyScale = 1.0
HazeColor = Color(0.79, 0.77, 0.73, 1)
HazeScale = 1.0

'''

BUDGET = '''; ⚠️ THE TERRAIN BUDGET WENT UP AND THE MESH BUDGET WENT DOWN, AND THAT IS THE WHOLE PERFORMANCE
; STORY OF THIS OVERHAUL. Terrain vertices per cell rose 3000 -> 7000 because a 200 m transitional
; cell needs a grid, but a terrain cell is ONE draw call whatever its resolution — the realm's
; sixteen cells cost about 41k vertices and sixteen draws in total. In exchange roughly 1,100
; individual ground-cover Node3Ds across the Ember Crown became MultiMesh scatter layers, which is
; the lever NOW.md named and never pulled. Scatter INSTANCES are up an order of magnitude and scatter
; DRAWS are down by three figures: 8,500 instances across roughly forty MultiMeshInstance3Ds is forty
; draw calls, and the 1,277 authored Node3Ds they replaced were 1,277. ⚠️ READ THE INSTANCE BUDGET AS
; A MEMORY LIMIT, NOT A DRAW LIMIT — raising it is nearly free and raising MaxDrawCalls is not.
; ⚠️ 2400 -> 7000 PER CELL (2026-09 world rebuild): count is a DENSITY scaled by footprint, and cells
; went from ~1 ha to up to ~4 ha. The density per hectare did not change; the cells did.
[sub_resource type="Resource" id="Budget_ember_crown"]
script = ExtResource("5_budget")
MaxAuthoredNodesPerCell = 700
MaxResidentAuthoredNodes = 12000
MaxResidentRuntimeNodes = 24000
MaxScatterInstancesPerCell = 7000
MaxResidentScatterInstances = 240000
MaxTerrainVerticesPerCell = 7000
MaxResidentTerrainVertices = 380000
MaxDrawCalls = 1800
MaxNodeCount = 40000
MaxStaticMemoryMb = 2048.0
MaxFrameMilliseconds = 16.67
ConsecutiveSamplesBeforeWarning = 5
BiomeCullDistance = 420.0
VisibilityUpdateInterval = 0.25
MaxConcurrentLoadRequests = 2
MaxCellInstantiationsPerFrame = 1

; ⚠️ STREAMING RADII FOR A KILOMETRE REALM (2026-09 world rebuild). The defaults (85/170/300/460)
; were never authored because the old realm fit inside the backdrop radius from anywhere in it. This
; one does not: the backdrop mesh leaves a hole over the whole lattice, so a cell that unloads is a
; hole in the ground. BackdropDistance therefore covers the realm's diagonal and every cell stays
; resident at least as terrain + HLOD + landmarks, which is also what lets the citadel and the
; Emberspire be seen from the far side of the realm. Far is widened so settlements read as places,
; not as terrain, from a village away.
NearDistance = 95.0
MidDistance = 190.0
FarDistance = 420.0
BackdropDistance = 1700.0

'''

# --------------------------------------------------------------------------------------------------
# Ecology. The Ember Crown authored NO biome scatter at all before this pass — every tuft of grass in
# the realm was a Node3D with its own draw call. These layers replace them.
# --------------------------------------------------------------------------------------------------

SCATTER = '''[sub_resource type="Resource" id="Layer_grass"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_grass_tall.glb"
Count = 620
MinimumScale = 0.7
MaximumScale = 1.35
MinimumSpacing = 1.6
Clumping = 0.32
ClumpScale = 22.0
MaxSlope = 0.55
Tint = Color(0.82, 0.84, 0.66, 1)
TintVariation = 0.22
VisibilityRangeEnd = 62.0
VisibilityFadeMargin = 12.0
CastShadows = false

[sub_resource type="Resource" id="Layer_grass_short"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_grass_short.glb"
Count = 430
MinimumScale = 0.75
MaximumScale = 1.3
MinimumSpacing = 1.4
MaxSlope = 0.6
Tint = Color(0.78, 0.80, 0.62, 1)
TintVariation = 0.20
VisibilityRangeEnd = 48.0
VisibilityFadeMargin = 10.0
CastShadows = false

[sub_resource type="Resource" id="Layer_clover"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_clover.glb"
Count = 150
MinimumScale = 0.7
MaximumScale = 1.15
MinimumSpacing = 2.4
Clumping = 0.45
ClumpScale = 18.0
MaxSlope = 0.5
Tint = Color(0.70, 0.78, 0.58, 1)
TintVariation = 0.18
VisibilityRangeEnd = 40.0
VisibilityFadeMargin = 8.0
CastShadows = false

; ⚠️ FLOWERS ARE THE ONE LAYER THAT MUST STAY SPARSE. `prp_flowers_a` and `prp_flowers_b` were
; adopted and never scattered, and the reflex on finding that is to give them a clover-sized count —
; which turns a dying realm's pasture into a meadow postcard. Fifty-odd per 100 x 100 m, heavily
; clumped, reads as flowers having come up where the ground was left alone. `Layer_clover` gives up
; 90 of its 240 to pay for both, so the settled and pasture profiles carry no more instances than
; they did (docs/ART_STYLE.md: worn, lived-in, restrained).
[sub_resource type="Resource" id="Layer_flowers"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_flowers_a.glb"
Count = 52
MinimumScale = 0.72
MaximumScale = 1.2
MinimumSpacing = 3.6
Clumping = 0.72
ClumpScale = 14.0
MaxSlope = 0.45
Tint = Color(0.80, 0.78, 0.66, 1)
TintVariation = 0.22
VisibilityRangeEnd = 38.0
VisibilityFadeMargin = 8.0
CastShadows = false

[sub_resource type="Resource" id="Layer_flowers_b"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_flowers_b.glb"
Count = 40
MinimumScale = 0.7
MaximumScale = 1.15
MinimumSpacing = 3.9
Clumping = 0.76
ClumpScale = 12.0
MaxSlope = 0.45
Tint = Color(0.78, 0.76, 0.64, 1)
TintVariation = 0.24
VisibilityRangeEnd = 38.0
VisibilityFadeMargin = 8.0
CastShadows = false

; Forest floor, and the most heavily clumped layer in the realm on purpose: mushrooms grow in rings
; and drifts against deadfall, never evenly. Wilds only — a mushroom in a pasture or on a shore is
; the kind of detail that reads as scatter having been switched on rather than authored.
; `Layer_bracken` gives up 15 of its 300 to pay for it.
[sub_resource type="Resource" id="Layer_mushrooms"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_mushrooms.glb"
Count = 18
MinimumScale = 0.65
MaximumScale = 1.25
MinimumSpacing = 5.5
Clumping = 0.85
ClumpScale = 9.0
MaxSlope = 0.5
Tint = Color(0.72, 0.68, 0.60, 1)
TintVariation = 0.20
VisibilityRangeEnd = 34.0
VisibilityFadeMargin = 8.0
CastShadows = false

; The thin, dry grass of a shore and a waste, where the short turf has no business growing. It
; splits `Layer_grass_short` (520 -> 430) rather than thickening the ground: those two profiles are
; meant to read as sparse, and the point of this layer is a second silhouette in the sparseness, not
; more of it.
[sub_resource type="Resource" id="Layer_grass_wispy"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_grass_wispy.glb"
Count = 90
MinimumScale = 0.7
MaximumScale = 1.4
MinimumSpacing = 2.2
Clumping = 0.55
ClumpScale = 20.0
MaxSlope = 0.7
Tint = Color(0.76, 0.75, 0.62, 1)
TintVariation = 0.22
VisibilityRangeEnd = 46.0
VisibilityFadeMargin = 10.0
CastShadows = false

[sub_resource type="Resource" id="Layer_bracken"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_fern.glb"
Count = 285
MinimumScale = 0.65
MaximumScale = 1.25
MinimumSpacing = 3.0
Clumping = 0.5
ClumpScale = 26.0
MaxSlope = 0.6
Tint = Color(0.62, 0.70, 0.52, 1)
TintVariation = 0.20
VisibilityRangeEnd = 70.0
VisibilityFadeMargin = 14.0
CastShadows = false

; ⚠️ THE REALM'S ENTIRE STONE COVER WAS ONE PEBBLE. `Layer_stone` scattered `prp_pebble_a` at 210
; instances per 100 x 100 m across FIVE of the six biome profiles, and a MultiMesh varies only yaw,
; uniform scale and tint — so every stone in the Ember Crown was the same 136-triangle silhouette
; seen from a different angle. That is the "obvious repetition" the visual-QA checklist names, and
; at 3.4 m spacing there is always another one of them in frame.
;
; ⚠️ THE FIX SPLITS THE EXISTING DENSITY, IT DOES NOT ADD TO IT. `MaxScatterInstancesPerCell` is
; 2400 and the seven layers already sat near it; four species at 90 + 70 + 26 + 5 = 191 is LESS
; ground cover than the 210 it replaces, and four distinct silhouettes instead of one. Read the
; instance budget as the memory limit it is (see BUDGET above) and the draw budget as the tight
; one: this is four MultiMeshInstance3Ds where there was one, which is three extra draws per cell.
[sub_resource type="Resource" id="Layer_stone"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_pebble_a.glb"
Count = 60
MinimumScale = 0.8
MaximumScale = 1.9
MinimumSpacing = 3.4
Clumping = 0.4
ClumpScale = 24.0
MaxSlope = 1.1
Tint = Color(0.68, 0.65, 0.60, 1)
TintVariation = 0.16
VisibilityRangeEnd = 55.0
VisibilityFadeMargin = 12.0
CastShadows = false

[sub_resource type="Resource" id="Layer_stone_b"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_pebble_c.glb"
Count = 52
MinimumScale = 0.85
MaximumScale = 2.05
MinimumSpacing = 3.1
Clumping = 0.46
ClumpScale = 21.0
MaxSlope = 1.1
Tint = Color(0.66, 0.64, 0.61, 1)
TintVariation = 0.18
VisibilityRangeEnd = 55.0
VisibilityFadeMargin = 12.0
CastShadows = false

; ⚠️ THE THIRD PEBBLE SPECIES, AND IT SPLITS THE DENSITY RATHER THAN ADDING TO IT — the same rule
; the two-species fix above was made under. `prp_pebble_b` was adopted with the rest of the nature
; set and then scattered nowhere: it sat in `assets/models/props` sharing the nature atlas, costing
; disk and carrying zero instances, while the ground cover it belongs to ran on two silhouettes.
; 90 + 70 becomes 60 + 52 + 48 — the same 160 stones per 100 x 100 m, one more outline in the mix.
[sub_resource type="Resource" id="Layer_stone_c"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_pebble_b.glb"
Count = 48
MinimumScale = 0.82
MaximumScale = 1.95
MinimumSpacing = 3.2
Clumping = 0.43
ClumpScale = 23.0
MaxSlope = 1.1
Tint = Color(0.67, 0.65, 0.61, 1)
TintVariation = 0.17
VisibilityRangeEnd = 55.0
VisibilityFadeMargin = 12.0
CastShadows = false

; The knee-to-waist tier the realm had nothing in: `prp_pebble_a` tops out around 0.9 m even at
; MaximumScale, and the next thing up was an authored boulder placed by hand. Sparse and widely
; spaced, so it reads as an outcrop breaking the turf rather than as litter.
[sub_resource type="Resource" id="Layer_rock_medium"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_rock_medium.glb"
Count = 26
MinimumScale = 0.42
MaximumScale = 0.86
MinimumSpacing = 9.5
Clumping = 0.58
ClumpScale = 34.0
MaxSlope = 0.85
Tint = Color(0.70, 0.67, 0.62, 1)
TintVariation = 0.14
VisibilityRangeEnd = 120.0
VisibilityFadeMargin = 18.0
CastShadows = true

; ⚠️ A BOULDER LAYER IS AN HLOD LAYER FOR THE SAME REASON A TREE LAYER IS, and it needs one more
; than a tree does: at five per 100 x 100 m the detailed tier is nearly free, but a 5.6 m mass
; that pops out of existence at its visibility range is the most obvious cull in the realm.
[sub_resource type="Resource" id="Layer_boulder"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_boulder_large.glb"
Count = 5
MinimumScale = 0.55
MaximumScale = 1.05
MinimumSpacing = 26.0
Clumping = 0.5
ClumpScale = 60.0
MaxSlope = 0.6
Tint = Color(0.71, 0.68, 0.63, 1)
TintVariation = 0.12
VisibilityRangeEnd = 165.0
VisibilityFadeMargin = 22.0
CastShadows = true
HlodShape = 1
HlodReduction = 2
HlodRangeBegin = 145.0
HlodRangeEnd = 340.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.1, 1.1, 1.1)

; ⚠️ A TREE LAYER IS AN HLOD LAYER OR IT IS A DRAW CALL STORM AT DISTANCE. The proxy cone carries the
; silhouette past 130 m; the detailed instance fades out before it.
[sub_resource type="Resource" id="Layer_pine"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_tree_broadleaf.glb"
Count = 260
MinimumScale = 0.75
MaximumScale = 1.6
MinimumSpacing = 6.5
Clumping = 0.78
ClumpScale = 46.0
MaxSlope = 0.42
Tint = Color(0.72, 0.78, 0.66, 1)
TintVariation = 0.18
VisibilityRangeEnd = 150.0
VisibilityFadeMargin = 22.0
CastShadows = true
HlodShape = 1
HlodReduction = 3
HlodRangeBegin = 130.0
HlodRangeEnd = 320.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

[sub_resource type="Resource" id="Layer_scrub"]
script = ExtResource("10_layer")
ScenePath = "res://assets/models/props/prp_bush_flowering.glb"
Count = 200
MinimumScale = 0.7
MaximumScale = 1.5
MinimumSpacing = 5.0
Clumping = 0.55
ClumpScale = 30.0
MaxSlope = 0.62
Tint = Color(0.66, 0.70, 0.56, 1)
TintVariation = 0.20
VisibilityRangeEnd = 105.0
VisibilityFadeMargin = 18.0
HlodShape = 2
HlodReduction = 4
HlodRangeBegin = 92.0
HlodRangeEnd = 230.0
HlodColor = Color(0.88, 0.9, 0.92, 1)
HlodScale = Vector3(1.15, 1.15, 1.15)

; Settlement ecology: the verges and back lots of an inhabited place, and nothing tall enough to hide
; a doorway. EdgePadding 1 because a settlement's outskirts should thin INTO the next cell's country,
; not stop at a line 3 m short of the seam.
[sub_resource type="Resource" id="Scatter_settled"]
script = ExtResource("9_scatter")
Seed = 5101
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_grass_short"), SubResource("Layer_clover"), SubResource("Layer_stone"), SubResource("Layer_stone_b"), SubResource("Layer_flowers"), SubResource("Layer_flowers_b"), SubResource("Layer_stone_c")])

[sub_resource type="Resource" id="Scatter_pasture"]
script = ExtResource("9_scatter")
Seed = 5102
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_grass"), SubResource("Layer_grass_short"), SubResource("Layer_clover"), SubResource("Layer_scrub"), SubResource("Layer_flowers"), SubResource("Layer_flowers_b")])

[sub_resource type="Resource" id="Scatter_wilds"]
script = ExtResource("9_scatter")
Seed = 5103
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_grass"), SubResource("Layer_bracken"), SubResource("Layer_pine"), SubResource("Layer_scrub"), SubResource("Layer_stone"), SubResource("Layer_stone_b"), SubResource("Layer_rock_medium"), SubResource("Layer_mushrooms"), SubResource("Layer_stone_c")])

[sub_resource type="Resource" id="Scatter_upland"]
script = ExtResource("9_scatter")
Seed = 5104
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_grass"), SubResource("Layer_bracken"), SubResource("Layer_stone"), SubResource("Layer_stone_b"), SubResource("Layer_rock_medium"), SubResource("Layer_boulder"), SubResource("Layer_scrub"), SubResource("Layer_stone_c")])

[sub_resource type="Resource" id="Scatter_waste"]
script = ExtResource("9_scatter")
Seed = 5105
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_stone"), SubResource("Layer_stone_b"), SubResource("Layer_rock_medium"), SubResource("Layer_boulder"), SubResource("Layer_bracken"), SubResource("Layer_grass_short"), SubResource("Layer_scrub"), SubResource("Layer_stone_c"), SubResource("Layer_grass_wispy")])

[sub_resource type="Resource" id="Scatter_shore"]
script = ExtResource("9_scatter")
Seed = 5106
EdgePadding = 1.0
Layers = Array[ExtResource("10_layer")]([SubResource("Layer_grass_short"), SubResource("Layer_stone"), SubResource("Layer_stone_b"), SubResource("Layer_scrub"), SubResource("Layer_stone_c"), SubResource("Layer_grass_wispy")])

'''

RESOURCE = '''[resource]
script = ExtResource("1_region")
Id = "region.ember_crown"
DisplayName = "The Ember Crown"
Realm = 0
SpawnPoint = @ORIGIN(town_hub, 0, 1.2, 15)@

; ⚠️ THE PORTAL MOVED WITH THE CROSSWAY, NOT WITH THE PLAYER. The gate cell went from (0, 0, -66) to
; (0, 0, -95) when the lattice grew, so the portal that stood at world z = -72 — cell-local z = -6,
; the gap between the two palisades — is world z = -101 now. Read the local offset, never the old
; world number: that is the 37C placement bug and it is completely silent.
PortalPoint = @WORLD(-150, 0, -652)@
Cells = Array[ExtResource("2_cell")]([@CELLS@])
EnvironmentProfile = SubResource("Environment_ember_crown")
GenerationProfile = ExtResource("13_generation")
PerformanceBudget = SubResource("Budget_ember_crown")

; The lattice is x -190..140, z -310..130. Bounds are that plus a margin, and the Y range is real
; now: the Emberdeep pit floor is 6 m down and the frontier ridges are 25 m up.
Bounds = @BOUNDS(20, -80, 200)@
SafeZoneCenter = @WORLD(20, 0, -40)@
SafeZoneRadius = 120.0
WeavePotency = 1.0
DefaultWeatherId = "weather.cloudy"
DayPhaseBias = 2
Neighbours = Array[String](["region.frostfang_reach", "region.ashen_wilds", "region.sunspire"])

; One door per neighbour (the Ashen Wilds and Sunspire, 2026-09). Frostfang's stays at the Crown Pass
; (PortalPoint); the Wilds' stands at the end of the burnt track in the Ashen Breach and Sunspire's in
; the Southmarch Gate, and a traveller coming back through either is put down beside it.
NeighbourPortalPoints = Array[Vector3]([Vector3(0, 0, 0), @WORLD(492, 0, -282)@, @WORLD(72, 0, 402)@])
NeighbourArrivalPoints = Array[Vector3]([Vector3(0, 0, 0), @WORLD(484, 1.2, -283)@, @WORLD(72, 1.2, 394)@])

; The Crossway toll (Phase 38M). Authored on BOTH regions rather than on one, because there is one
; gate on one road and the wardens do not care which way a cart is pointing. 25 gold sits under
; TravelFee.CrossRegionFee (40) on purpose: walking must stay the cheap way across, or the toll is a
; tax on the only option and the map screen quietly becomes the sensible one.
TollGold = 25
TollPermitFlagId = "flag.crossway.permit"
TollPassFlagId = "flag.crossway.pass"
; The Crossway wardens stand on the Frostfang road only; the Ashen Breach is not tolled.
TollFromRegionIds = Array[String](["region.frostfang_reach"])
'''


EMBER = "res://scenes/regions/ember_crown/"


def empty(key, center, size, seed, scatter, biome=None, note="", resolution=None, tint=None, tint_strength=0.0):
    """A transitional cell: ground, weather, ecology and whatever roads cross it — no gameplay beat."""
    if resolution is None:
        # ~2.8 m a vertex across open country, capped by the 7000-vertex terrain budget (res 82).
        resolution = min(80, max(36, int(max(size) / 2.8)))
    return Cell(key=key, cell_id=f"ember_crown.{key}", scene=f"{EMBER}{key}.tscn",
                center=center, size=size, resolution=resolution, seed=seed, scatter=scatter,
                biome=biome, note=note, tint=tint, tint_strength=tint_strength)


def lattice() -> dict[tuple[int, int], tuple[tuple[float, float], tuple[float, float]]]:
    """(row, column) -> (centre, size) for the whole realm."""
    out = {}
    for r, (top, bottom) in enumerate(ROWS):
        xs = [EXTENT_X[0], *COLUMNS[r], EXTENT_X[1]]
        for c in range(len(xs) - 1):
            out[(r, c)] = (((xs[c] + xs[c + 1]) / 2, (top + bottom) / 2), (xs[c + 1] - xs[c], bottom - top))
    return out


def cells() -> list[Cell]:
    L = lattice()

    def at(r, c):
        return {"center": L[(r, c)][0], "size": L[(r, c)][1]}

    return [
        # ================================================================== row 0 — the Crown Range
        empty("range_west", **at(0, 0), seed=301, scatter="Scatter_upland", biome="BurnedHeath", note="""
            THE WESTERN CROWN RANGE. The realm's northern wall, fifty-five metres of ridge with no road
            over it. It is what every northward view in the west of the realm ends on."""),
        empty("crown_pass", **at(0, 1), seed=302, scatter="Scatter_waste", biome="BurnedHeath", note="""
            THE CROWN PASS. The one saddle in the range. The road climbs out of the Crossway's mouth to
            the portal on the saddle; the ridges stand either side of it. The only way north is here,
            which is why the Crossway exists."""),
        empty("range_mid", **at(0, 2), seed=303, scatter="Scatter_upland", biome="BurnedHeath", note="""
            THE CENTRAL RANGE. Sixty metres of ridge behind the frontier heath. Empty high ground."""),
        empty("range_east", **at(0, 3), seed=304, scatter="Scatter_waste", biome="BurnedHeath"),
        empty("emberspire", **at(0, 4), seed=305, scatter="Scatter_waste", biome="BurnedHeath", note="""
            THE EMBERSPIRE MASSIF. The highest ground in the realm, seventy-five metres, standing over
            the Iron King's arena. Seen from the capital it is the north-east horizon."""),

        # ================================================================== row 1 — the frontier
        empty("pass_foot_west", **at(1, 0), seed=311, scatter="Scatter_wilds", biome="Woodland"),
        Cell(
            key="crossway_post", cell_id="ember_crown.crossway_post",
            scene=f"{EMBER}crossway_post.tscn", **at(1, 1), origin=(-135.0, -550.0),
            resolution=80, seed=103, safe_radius=26.0, scatter="Scatter_upland",
            note="""
            THE CROSSWAY POST — the toll gate at the mouth of the Crown Pass, the only road through the
            range. Five hundred and fifty metres north of the capital up the Kingsway, with the pass
            saddle and the portal a hundred metres further up the road behind it. The two spurs either
            side of the palisade are the pass's own shoulders.
            """,
            yards=(
                Yard((6, 9), (9, 5.5), 2.5, 0.82, elevation=0.0, name="Area_crossway_hold"),
                Yard((-17, 13), (7, 6), 2.0, 0.68, elevation=0.0, name="Area_crossway_compound"),
                Yard((7.5, 2), (5, 4), 1.5, 0.9, elevation=0.0, name="Area_crossway_gate"),
                # 42B: the Wardens' Watch apron, south of the compound track (NOW.md invariant 21).
                Yard(at=(-19.5, 6.5), ext=(6.0, 5.0), feather=2.5, blend=0.8, elevation=0.0),
            ),
            routes=(
                Route((-6, 26), (-6, 14), 7.0, 2.0, name="Path_crossway_south"),
                Route((-6, 14), (3, 9), 7.0, 2.0, name="Path_crossway_turn"),
                Route((3, 9), (7.5, 0), 7.0, 2.0, name="Path_crossway_gate"),
                Route((7.5, 0), (0, -8), 7.0, 2.0, name="Path_crossway_dogleg"),
                Route((0, -8), (0, -26), 7.0, 2.0, name="Path_crossway_north"),
                Route((-10, 14), (-20, 14), 4.0, 1.5, name="Path_crossway_compound"),
                Route((6, 9), (18, 12), 4.5, 2.0),
            ),
            landforms=(
                Mound(at=(0, 4), ext=(32, 26), h=0.0, fall=0.5, flat=0.9),
                Ridge(a=(-50, -16), b=(-14, -19), half=10, h=9.0, fall=0.55),
                Ridge(a=(14, -19), b=(50, -16), half=10, h=9.0, fall=0.55),
            ),
        ),
        empty("frontier_waste", **at(1, 2), seed=115, scatter="Scatter_waste", biome="BurnedHeath", note="""
            THE FRONTIER WASTE — burnt heath under the range, crossed by the frontier road from the
            Crossway to the arena. The dangerous short way east. Nothing on it but the road and the
            weather."""),
        empty("ashen_reach", **at(1, 3), seed=114, scatter="Scatter_waste", biome="BurnedHeath",
              tint=(0.42, 0.36, 0.31), tint_strength=0.18, note="""
            THE ASHEN REACH — the frontier road's last stretch before the arena, under the massif."""),
        Cell(
            key="arena", cell_id="ember_crown.arena", scene=f"{EMBER}arena.tscn", **at(1, 4),
            origin=(365.0, -565.0), resolution=64, seed=110, tint=(0.36, 0.24, 0.20), tint_strength=0.16,
            scatter="Scatter_waste", biome="BurnedHeath",
            note="""
            THE EMBER ARENA — the Iron King's ring, at the far north-east of the realm under the
            Emberspire. Six hundred metres from the capital as the crow flies and further by either
            road: the frontier road across the waste from the Crossway, or the long east road up from
            Emberdeep. The ring stands on its levelled shelf with the massif's crags behind it, and the
            breach in the north wall is still the way down.
            """,
            yards=(
                Yard((0, -1), (15, 14), 1.5, 0.95, elevation=0.0, name="Area_arena_ring"),
                Yard((9, -16), (4, 3), 2.0, 0.55, elevation=0.0, name="Area_arena_breach"),
            ),
            routes=(
                Route((0, 18), (0, 9), 5.0, 1.5, name="Path_arena_gate"),
                Route((9, -18), (7, -8), 4.0, 2.5, name="Path_arena_breach"),
                Route((-40, 30), (-16, 27), 5.0, 2.5),
                Route((-16, 27), (0, 18), 5.0, 2.0),
            ),
            landforms=(
                Mound(at=(0, 0), ext=(32, 30), h=3.0, fall=0.35, flat=1.0),
                Ridge(a=(30, -30), b=(58, 20), half=15, h=18.0, fall=0.5),
                Mound(at=(6, -38), ext=(42, 17), h=-6.0, fall=0.6),
            ),
        ),
        empty("range_foot_east", **at(1, 5), seed=316, scatter="Scatter_waste", biome="BurnedHeath"),

        # ================================================================== row 2 — the northern uplands
        empty("wildwood_west", **at(2, 0), seed=321, scatter="Scatter_wilds", biome="Woodland"),
        Cell(
            key="wilds_north", cell_id="ember_crown.wilds_north", scene=f"{EMBER}wilds_north.tscn",
            **at(2, 1), origin=(-285.0, -390.0), resolution=80, seed=105,
            scatter="Scatter_wilds", biome="Woodland",
            note="""
            THE NORTHERN WILDS — goblin country in the forested upland west of the Kingsway, and the
            Ash Hunters' Deadfall Lodge in its hollow. A branch trail leaves the Kingsway below the
            watch ridge; a second comes down from the Crossway, so the wilds are a loop rather than a
            dead end. The fork, the bowl, the ruin in dead ground and Cairn Rise are unchanged.
            """,
            yards=(
                Yard((0, -5), (7, 7), 3.5, 0.42, elevation=-0.3, name="Area_wilds_north_ruin"),
                Yard((-17, 8), (6, 7), 4.0, 0.3, elevation=0.61, name="Area_wn_bowl"),
                Yard((18, -12), (6, 7), 4.5, 0.9, elevation=-5.39, name="Area_wn_deadfall"),
                Yard(at=(21.5, -15.0), ext=(5.5, 6.5), feather=3.0, blend=0.9, elevation=-5.39),
            ),
            routes=(
                Route((0, 25), (0, 16), 5.0, 2.5, name="Path_wn_stem"),
                Route((0, 16), (-11, 4), 4.0, 2.5, name="Path_wn_west_a"),
                Route((-11, 4), (-12, -10), 4.0, 2.5, name="Path_wn_west_b"),
                Route((-12, -10), (0, -25), 4.0, 2.5, name="Path_wn_west_c"),
                Route((0, 16), (11, 6), 3.5, 2.0, name="Path_wn_east_a"),
                Route((11, 6), (13, -6), 3.5, 2.0, name="Path_wn_east_b"),
                Route((13, -6), (0, -25), 3.5, 2.0, name="Path_wn_east_c"),
            ),
            landforms=(
                Mound(at=(-17, 8), ext=(15, 16), h=-3.5, fall=0.7),
                Ridge(a=(10, -22), b=(30, -4), half=8, h=5.0, fall=0.5),
                Mound(at=(0, -5), ext=(17, 17), h=-2.0, fall=0.65),
                Mound(at=(24, 18), ext=(13, 13), h=7.0, fall=0.7),
            ),
        ),
        empty("emberwash_head", **at(2, 2), seed=323, scatter="Scatter_wilds", biome="Woodland", note="""
            THE EMBERWASH HEAD — where the river comes down off the range into its valley, beside the
            Kingsway's climb to the Crossway."""),
        empty("heath_south", **at(2, 3), seed=324, scatter="Scatter_upland", biome="BurnedHeath"),
        empty("east_uplands", **at(2, 4), seed=325, scatter="Scatter_upland", biome="BurnedHeath", note="""
            THE EAST UPLANDS — the long east road climbs through here from Emberdeep to the arena. The
            safe long way north-east."""),

        # ================================================================== row 3 — the watch ridge
        empty("western_ridge", **at(3, 0), seed=331, scatter="Scatter_upland"),
        empty("wildwood_edge", **at(3, 1), seed=332, scatter="Scatter_wilds", biome="Woodland"),
        Cell(
            key="north_moor", cell_id="ember_crown.north_moor", scene=f"{EMBER}north_moor.tscn",
            **at(3, 2), origin=(-20.0, -310.0), resolution=60, seed=113, scatter="Scatter_upland",
            note="""
            THE NORTH MOOR — the watch ridge north of the capital. The old Kingsway watchtower stands
            ruined on its crest: the first landmark on the road north, visible from the city's north
            gate and from the Crossway, and the place from which the capital's citadel is seen whole.
            """,
        ),
        empty("crown_fields_north", **at(3, 3), seed=334, scatter="Scatter_pasture", biome="Pasture"),
        empty("ashen_breach", **at(3, 4), seed=335, scatter="Scatter_waste", biome="BurnedHeath",
              tint=(0.40, 0.34, 0.30), tint_strength=0.16, note="""
            THE ASHEN BREACH — a scorched cut through the eastern border hills where the old road to the
            Ashen Wilds went. Reserved for Phase 44 (location.ashen.station lies beyond it); today the
            track ends at the burnt gap looking out over dead country."""),

        # ================================================================== row 4 — citadel row
        Cell(
            key="wilds_west", cell_id="ember_crown.wilds_west", scene=f"{EMBER}wilds_west.tscn",
            **at(4, 0), origin=(-455.0, -205.0), resolution=64, seed=108,
            scatter="Scatter_wilds", biome="Woodland",
            note="""
            THE WESTERN WILDS — the bandit corrie in the western ridge above the Tarn, reached by a
            shore trail north from Tarn's Landing that fords the Emberwash. The corrie's four ridges,
            its throat and its dished camp floor are unchanged.
            """,
            yards=(
                Yard((-14, -1), (7, 8), 3.5, 0.38, elevation=0.0, name="Area_wilds_west_camp"),
                Yard((10, -1), (9, 6), 4.0, 0.2, elevation=-2.33, name="Area_wilds_west_apron"),
            ),
            routes=(
                Route((25, 0), (2, -1), 3.5, 2.5, name="Path_wilds_west_track"),
                Route((2, -1), (-8, 0), 5.0, 1.5, name="Path_wilds_west_throat"),
            ),
            landforms=(
                Ridge(a=(-26, -18), b=(-26, 15), half=10, h=14.0, fall=0.35),
                Ridge(a=(-26, -18), b=(-6, -20), half=10, h=12.0, fall=0.35),
                Ridge(a=(-26, 15), b=(-8, 16), half=10, h=12.0, fall=0.35),
                Ridge(a=(-4, -18), b=(-4, -6), half=8, h=12.0, fall=0.4),
                Ridge(a=(-4, 6), b=(-4, 15), half=8, h=12.0, fall=0.4),
                Mound(at=(-14, -1), ext=(12, 13), h=-1.5, fall=0.5, flat=0.9),
            ),
        ),
        empty("emberwash_valley", **at(4, 1), seed=342, scatter="Scatter_wilds", biome="Woodland"),
        empty("kings_approach", **at(4, 2), seed=343, scatter="Scatter_pasture", biome="Pasture", note="""
            THE KING'S APPROACH — the Kingsway leaves the capital's north gate and climbs toward the
            watch ridge. Kingsbridge carries the west road over the Emberwash at its south-west corner."""),
        Cell(
            key="citadel", cell_id="ember_crown.citadel", scene=f"{EMBER}citadel.tscn",
            **at(4, 3), origin=(100.0, -150.0), resolution=80, seed=344, scatter="Scatter_settled",
            note="""
            THE IRON CITADEL — the seat of the realm. The Iron King's keep on the spur above the capital:
            the skyline every road in the Ember Crown is composed toward.
            """,
        ),
        Cell(
            key="mine_road", cell_id="ember_crown.mine_road", scene=f"{EMBER}mine_road.tscn",
            **at(4, 4), resolution=60, seed=112, scatter="Scatter_upland",
            note="""
            THE MINE ROAD — hill country on the east road between the capital and Emberdeep, where the
            long road to the arena branches north. A crossroads that is only a crossroads.
            """,
        ),
        Cell(
            key="emberdeep_mine", cell_id="ember_crown.emberdeep_mine", scene=f"{EMBER}emberdeep_mine.tscn",
            **at(4, 5), origin=(405.0, -160.0), resolution=80, seed=104,
            tint=(0.58, 0.45, 0.33), tint_strength=0.15, safe_radius=24.0, scatter="Scatter_upland",
            surplus=("ore", "metal", "fuel"), demand=("food", "fish", "textile"), shocks=("ore", "food"),
            biome="Excavated",
            note="""
            THE EMBERDEEP MINE — cut into the eastern hills four hundred metres from the capital along the
            east road. The working loop (defile, Weighing Yard, haul road, the Cut, Pit Head, spoil
            track) is unchanged and is still geography: the pit, the spoil bank and the hill it is dug
            into. The long east road to the arena leaves from its north side.
            """,
            yards=(
                Yard((-8, 9.5), (9, 9.5), 3.0, 0.92, elevation=0.0, name="Area_mine_yard"),
                Yard((18, -9), (8, 9), 3.5, 0.88, elevation=0.0, name="Area_mine_pithead"),
                Yard((-19, 15), (4, 5), 1.5, 0.6, elevation=0.0, name="Area_mine_rest"),
            ),
            routes=(
                Route((-26, -2), (-14, -2), 6.0, 2.0, name="Path_mine_defile"),
                Route((-4, 8), (8, -4), 6.0, 2.0, name="Path_mine_haul"),
                Route((11, 17), (-1, 17), 5.0, 1.5, name="Path_mine_link"),
                Route((0, 3), (18, -8), 6.0, 2.5),
                Route((14, -6), (14, 19), 6.0, 2.0),
                Route((-8, 6), (-6, -26), 4.5, 2.0),
            ),
            landforms=(
                Ridge(a=(2, -42), b=(44, -34), half=26, h=16.0, fall=0.75),
                Ridge(a=(-32, -14), b=(-8, -16), half=13, h=8.0, fall=0.7),
                Ridge(a=(-36, -2), b=(-10, -2), half=5.5, h=-6.0, fall=0.3, flat=1.0),
                Mound(at=(-8, 9.5), ext=(14, 14), h=0.0, fall=0.4, flat=1.0),
                Mound(at=(21, -12), ext=(30, 30), h=2.0, fall=0.85),
                Mound(at=(21, -12), ext=(13, 13.5), h=-3.5, fall=0.42, flat=1.0),
                Ridge(a=(23, -2), b=(23, 24), half=7, h=6.0, fall=0.55),
            ),
        ),

        # ================================================================== row 5 — the capital
        empty("tarn_north", **at(5, 0), seed=351, scatter="Scatter_wilds", biome="Woodland"),
        empty("tarn_road", **at(5, 1), seed=352, scatter="Scatter_pasture", biome="Pasture", note="""
            THE TARN ROAD — the west road runs down the Emberwash from Kingsbridge to Tarn's Landing,
            the river on the right hand and the lake opening ahead."""),
        empty("bridgeward", **at(5, 2), seed=353, scatter="Scatter_settled", biome="Pasture", note="""
            BRIDGEWARD — the capital's western outskirts between the city and Kingsbridge."""),
        Cell(
            key="town_hub", cell_id="ember_crown.town_hub", scene=f"{EMBER}town_hub.tscn",
            **at(5, 3), origin=(35.0, -30.0), resolution=80, seed=101, scatter="Scatter_settled",
            note="""
            THE CROWN SQUARE — the capital's upper town: the square, the Ember Rest, the smithy, the
            craft yard and the Long Green, under the citadel's spur. The Kingsway leaves its north side
            for the Crossway, the west road for Kingsbridge and the Tarn, the east road for Emberdeep,
            and the market lane runs down to the Embermarket.
            """,
            yards=(
                Yard((-14, -2), (9, 10), 3.0, 0.85, elevation=None, name="Area_town_square"),
                Yard((16, 1), (8, 8), 2.5, 0.78, elevation=None, name="Area_town_craft"),
                Yard((6, -21), (11, 5), 3.0, 0.35, elevation=None, name="Area_town_green"),
                Yard(at=(-20.0, 22.0), ext=(6.0, 6.0), feather=3.0, blend=0.9),
                Yard(at=(25.0, 6.0), ext=(6.0, 7.0), feather=3.0, blend=0.9),
                Yard(at=(-22.0, 11.1), ext=(4.5, 4.6), feather=3.0, blend=0.9),
                # HouseSouthB, 1.42 m out across its footprint on the rebuilt ground.
                Yard(at=(17.2, 27.2), ext=(2.7, 2.7), feather=2.5, blend=0.9),
            ),
            routes=(
                Route((-11, 30), (1, 14), 4.5, 1.5, name="Path_town_kingsway_s"),
                Route((1, 14), (2, -8), 5.0, 1.5, name="Path_town_kingsway_m"),
                Route((2, -8), (-6, -30), 4.5, 1.5, name="Path_town_kingsway_n"),
                Route((-30, -4), (-18, -4), 5.0, 2.0, name="Path_town_west"),
                Route((30, -2), (18, -2), 5.0, 2.0, name="Path_town_east"),
                Route((-4, -20), (16, -20), 3.5, 1.25, name="Path_town_green"),
            ),
            landforms=(
                Mound(at=(-4, -6), ext=(40, 36), h=0.0, fall=0.55, flat=0.9),
            ),
        ),
        empty("east_gate", **at(5, 4), seed=355, scatter="Scatter_settled", biome="Pasture", note="""
            EASTGATE — the capital's working quarter along the east road."""),
        empty("emberdeep_slopes", **at(5, 5), seed=356, scatter="Scatter_upland"),

        # ================================================================== row 6 — lake and market
        empty("tarn_west", **at(6, 0), seed=361, scatter="Scatter_shore", biome="Wetland"),
        Cell(
            key="tarn_landing", cell_id="ember_crown.tarn_landing", scene=f"{EMBER}tarn_landing.tscn",
            **at(6, 1), origin=(-300.0, 65.0), resolution=80, seed=106, safe_radius=22.0,
            scatter="Scatter_shore", surplus=("fish",), demand=("ore", "metal", "fuel"), shocks=("fish", "ore"),
            biome="Wetland",
            note="""
            TARN'S LANDING — the fishing village on the Tarn's north-east shore, where the Emberwash
            comes into the lake. The spit, the bay, the docks and the neck are unchanged; the bay is now
            the corner of a real lake rather than a pond, and the shore trail north to the corrie starts
            at the end of its shore road.
            """,
            yards=(
                Yard((-7, 8), (8, 6), 2.5, 0.74, elevation=-0.31, name="Area_tarn_spit"),
                Yard((11, -14), (7, 6), 2.0, 0.66, elevation=0.81, name="Area_tarn_yard"),
            ),
            routes=(
                Route((26, -8), (6, -7), 6.0, 2.0, name="Path_tarn_road_east"),
                Route((6, -3), (-26, -1), 7.0, 2.0, name="Path_tarn_road_shore"),
                Route((-6, -2), (-6, 4), 6.0, 1.5, name="Path_tarn_neck"),
            ),
            landforms=(
                Mound(at=(-16, 17), ext=(17, 15), h=-0.7, fall=0.7, flat=0.85),
                Mound(at=(-21, 15), ext=(7, 15), h=-4.2, fall=0.2, flat=1.0),
                Mound(at=(-7, 20), ext=(13, 9), h=-4.2, fall=0.2, flat=1.0),
            ),
        ),
        empty("lakeshore_east", **at(6, 2), seed=363, scatter="Scatter_pasture", biome="Pasture"),
        Cell(
            key="embermarket", cell_id="ember_crown.embermarket", scene=f"{EMBER}embermarket.tscn",
            **at(6, 3), origin=(-60.0, 70.0), resolution=80, seed=102, safe_radius=32.0,
            scatter="Scatter_settled", biome="Pasture",
            note="""
            THE EMBERMARKET — the capital's lower town, below the Crown Square on the market lane and
            beside the river road. Its south gate opens on the Hollowreach road and the caravan road to
            the southern border. The Crookway, the Coilyard, the Salt Steps and the Gate Lane are
            unchanged.
            """,
            yards=(
                Yard((7, 2), (11, 10), 3.0, 0.9, elevation=None, name="Area_market_yard"),
                Yard((16, 14), (5.5, 5), 1.5, 0.88, elevation=0.0, name="Area_market_terrace"),
                Yard((3, 16.5), (7, 4.5), 2.0, 0.6, elevation=None, name="Area_market_timber"),
                Yard((-11.5, 17), (4.5, 4), 1.5, 0.55, elevation=None, name="Area_market_sump"),
                Yard(at=(-2.0, 22.5), ext=(5.0, 5.0), feather=3.0, blend=0.9),
                Yard(at=(-2.5, 16.6), ext=(4.5, 5.6), feather=3.0, blend=0.9),
            ),
            routes=(
                Route((-11, -26), (-11, -13), 4.5, 1.0, name="Path_market_gate"),
                Route((-11, -13), (2, -7.5), 5.0, 1.5, name="Path_market_crook"),
                Route((26, 3.5), (16, 3.5), 7.0, 2.0, name="Path_market_caravan"),
                Route((-26, 12), (-18, 12), 3.5, 1.5, name="Path_market_dock"),
                Route((-18, -15), (-18, 15), 3.2, 1.0, name="Path_market_alley"),
                Route((-16, 17), (-9, 17), 3.0, 1.0, name="Path_market_sump"),
            ),
            landforms=(
                Mound(at=(0, -4), ext=(36, 34), h=0.0, fall=0.5, flat=0.92),
                Mound(at=(16, 14), ext=(9.5, 8.5), h=0.45, fall=0.35, flat=1.0),
            ),
        ),
        empty("south_fields", **at(6, 4), seed=365, scatter="Scatter_pasture", biome="Pasture"),
        empty("ashfall_lane", **at(6, 5), seed=366, scatter="Scatter_pasture", biome="Pasture"),
        empty("eastern_downs", **at(6, 6), seed=367, scatter="Scatter_pasture", biome="Pasture"),

        # ================================================================== row 7 — the southern country
        empty("outflow", **at(7, 0), seed=371, scatter="Scatter_shore", biome="Wetland"),
        empty("reach_road", **at(7, 1), seed=372, scatter="Scatter_shore", biome="Wetland"),
        Cell(
            key="west_downs", cell_id="ember_crown.west_downs", scene=f"{EMBER}west_downs.tscn",
            **at(7, 2), origin=(-175.0, 205.0), resolution=60, seed=111, scatter="Scatter_pasture",
            note="""
            THE WEST DOWNS — rolling grazing between the market and the fens. A drovers' track leaves the
            Hollowreach road and ends at a collapsed sheepfold on the highest ground. Nothing here.
            """,
            routes=(Route((40, 4), (14, 8), 3.0, 2.5),),
        ),
        empty("caravan_road", **at(7, 3), seed=374, scatter="Scatter_pasture", biome="Pasture", note="""
            THE CARAVAN ROAD — the old trade road south toward the Sunspire border, through the realm's
            farm belt."""),
        Cell(
            key="ashfall_homestead", cell_id="ember_crown.ashfall_homestead",
            scene=f"{EMBER}ashfall_homestead.tscn", **at(7, 4), origin=(290.0, 240.0), resolution=80,
            seed=109, safe_radius=26.0, scatter="Scatter_pasture", biome="Pasture",
            note="""
            THE ASHFALL HOMESTEAD — the player's holding, out on the ash flats south-east of the capital
            at the end of the farm lane, nearly four hundred metres from the market gate. Nothing inside
            the plot moved.
            """,
            yards=(
                Yard((0, 5), (8, 7), 3.0, 0.58, elevation=None, name="Area_homestead_yard"),
                Yard((-13, 4), (5, 7), 1.5, 0.35, elevation=None, name="Area_homestead_garden"),
                Yard((13.5, -6), (3.5, 6), 1.5, 0.72, elevation=None, name="Area_homestead_workshop"),
            ),
            routes=(
                Route((-26, 3.5), (-21, -5.5), 4.5, 2.0, name="Path_homestead_lane"),
                Route((-21, -5.5), (-13, -10), 4.5, 2.0, name="Path_homestead_gate"),
                Route((-13, -10), (-3, -3.6), 3.5, 1.5, name="Path_homestead_drive"),
                Route((-3, -3.6), (7, 2), 3.5, 1.25, name="Path_homestead_door"),
                Route((7, 2), (7, 0), 3.5, 1.25, name="Path_homestead_entry"),
            ),
            landforms=(
                Mound(at=(0, 0), ext=(26, 24), h=0.0, fall=0.55, flat=0.85),
            ),
        ),
        empty("ash_flats", **at(7, 5), seed=376, scatter="Scatter_waste", biome="BurnedHeath"),

        # ================================================================== row 8 — fens and border
        Cell(
            key="fen_edge", cell_id="ember_crown.fen_edge", scene=f"{EMBER}fen_edge.tscn",
            **at(8, 0), origin=(-470.0, 370.0), resolution=48, seed=116,
            scatter="Scatter_shore", biome="Wetland",
            note="""
            THE FEN EDGE — the drowned margin west of Hollowreach where the Emberwash leaves the realm. A
            causeway crosses the marsh and stops at two drowned pillars looking back at the wharf. No
            loot, no encounter, no pin.
            """,
            routes=(Route((-2, -16), (-8, 8), 3.0, 2.5),),
        ),
        Cell(
            key="hollowreach", cell_id="ember_crown.hollowreach", scene=f"{EMBER}hollowreach.tscn",
            **at(8, 1), origin=(-340.0, 350.0), resolution=80, seed=107,
            tint=(0.38, 0.42, 0.38), tint_strength=0.12, scatter="Scatter_shore", biome="Wetland",
            note="""
            HOLLOWREACH — the drowned district in the Emberwash fens below the Tarn, where the river
            spreads out before it leaves the realm. The spine between two flooded channels, the open
            water behind its drop-off and the dry Ledger House above them are unchanged; the district now
            sits in a real delta with the old town's drowned towers standing in the water beyond it.
            """,
            yards=(
                Yard((-9, 1), (5, 5), 1.5, 0.85, elevation=0.62, name="Area_hollowreach_hollow"),
                Yard((16, 12), (10, 4), 2.5, 0.72, elevation=1.16, name="Area_hollowreach_street"),
                Yard((-5, 1), (11, 7), 2.5, 0.78, elevation=0.61, name="Area_hollowreach_spine"),
                # 42B: the Ledger House bench, north of the street pad at the street's own offset.
                Yard(at=(20.0, 23.0), ext=(5.0, 5.0), feather=2.5, blend=0.8, elevation=1.17),
            ),
            routes=(
                Route((26, 12), (6, 12), 8.0, 2.0, name="Path_hollowreach_east"),
                Route((6, 12), (6, 2), 8.0, 2.0, name="Path_hollowreach_turn"),
                Route((6, 1), (-7, 1), 12.0, 2.0, name="Path_hollowreach_spine"),
                Route((33, -14), (27, 12), 4.0, 2.0),
            ),
            landforms=(
                Mound(at=(0, 0), ext=(48, 46), h=0.8, fall=0.8),
                Mound(at=(-46, 0), ext=(38, 50), h=-0.6, fall=0.25, flat=0.9),
                Mound(at=(-46, 0), ext=(34, 46), h=-4.5, fall=0.10, flat=1.0),
                Ridge(a=(-31, -10), b=(10, -10), half=5.5, h=-3.2, fall=0.2, flat=1.0),
                Ridge(a=(-31, 13), b=(-2, 13), half=6.5, h=-3.2, fall=0.2, flat=1.0),
            ),
            waters=(
                Water(at=(-50, 0), ext=(42, 52), ident="OpenWater",
                      shallow=(0.20, 0.31, 0.31), deep=(0.04, 0.11, 0.15), opaque=1.6),
                Water(at=(-10, -10), ext=(26, 11), ident="ChannelNorth"),
                Water(at=(-12, 13), ext=(24, 12), ident="ChannelSouth"),
            ),
        ),
        empty("southern_fens", **at(8, 2), seed=383, scatter="Scatter_shore", biome="Wetland"),
        empty("south_gate", **at(8, 3), seed=384, scatter="Scatter_pasture", biome="Pasture", note="""
            THE SOUTHMARCH GATE — the caravan road ends at the realm's southern border, where the old
            gate to the Sunspire road stands broken in its gap in the border hills. Its portal to the
            Sunspire Dominion opens when the Iron King falls (NeighbourPortalPoints)."""),
        empty("border_hills", **at(8, 4), seed=385, scatter="Scatter_upland"),
        empty("border_east", **at(8, 5), seed=386, scatter="Scatter_upland"),
    ]


# The realm's roads, authored as WORLD polylines (gen_regions.Road). Every vertex is a place a road
# turns because the ground or a destination makes it turn. A road that starts or ends at a settlement
# starts or ends at that settlement's own street end (content origin + the street's local endpoint),
# which is how the old interior circulation joins the new country.
def roads() -> list[Road]:
    T = (35.0, -30.0)       # Crown Square content origin
    M = (-60.0, 70.0)       # Embermarket
    C = (-135.0, -550.0)    # Crossway
    E = (405.0, -160.0)     # Emberdeep
    Lt = (-300.0, 65.0)     # Tarn's Landing
    H = (-340.0, 350.0)     # Hollowreach
    A = (290.0, 240.0)      # Ashfall
    Ww = (-455.0, -205.0)   # corrie
    Wn = (-285.0, -390.0)   # northern wilds
    Ar = (365.0, -565.0)    # arena
    F = (-470.0, 370.0)     # fen edge
    D = (-175.0, 205.0)     # west downs

    def o(origin, local):
        return (origin[0] + local[0], origin[1] + local[1])

    return [
        # ---- primary: the Kingsway, capital north gate -> watch ridge -> Emberwash head -> Crossway -> pass
        Road((o(T, (-6, -30)), (30, -104), (-8, -180), (-62, -262), (-98, -364), (-118, -436),
              o(C, (-6, 26))), width=6.0, shoulder=2.5),
        Road((o(C, (0, -26)), (-142, -618), (-150, -652)), width=6.0, shoulder=2.5),
        # ---- primary: west road, capital -> Kingsbridge -> down the Emberwash -> Tarn's Landing
        Road((o(T, (-30, -4)), (-62, -48), (-138, -76), (-205, -70), (-248, -12), o(Lt, (26, -8))),
             width=5.5, shoulder=2.0),
        # ---- primary: market lane, Crown Square -> Embermarket
        Road((o(T, (-11, 30)), (4, 14), (-48, 30), o(M, (-11, -26))), width=4.5, shoulder=1.5),
        # ---- primary: east road, capital -> Eastgate -> mine road -> Emberdeep
        Road((o(T, (30, -2)), (142, -52), (232, -104), (318, -152), o(E, (-26, -2))), width=5.5, shoulder=2.0),
        # ---- primary: Hollowreach road, market -> West Downs -> fens -> Hollowreach
        Road((o(M, (-26, 12)), (-146, 132), (-208, 186), (-266, 262), (-292, 334), o(H, (26, 12))),
             width=5.0, shoulder=2.0),
        # ---- primary: farm lane, market -> southern fields -> Ashfall
        Road((o(M, (26, 3.5)), (38, 112), (132, 172), (214, 226), o(A, (-26, 3.5))), width=5.0, shoulder=2.0),
        # ---- primary: caravan road south to the Southmarch Gate (reserved border)
        Road(((38, 112), (58, 218), (74, 322), (72, 402)), width=5.5, shoulder=2.0),
        # ---- primary: the long east road, Emberdeep north -> uplands -> arena (safe, long)
        Road((o(E, (-6, -26)), (392, -262), (384, -372), (352, -468), o(Ar, (-40, 30))), width=5.0, shoulder=2.0),
        # ---- secondary: the frontier road across the waste, Crossway -> arena (short, dangerous)
        Road((o(C, (18, 12)), (-44, -512), (68, -488), (182, -508), (262, -528), o(Ar, (-40, 30))),
             width=4.0, shoulder=2.0),
        # ---- secondary: lakeshore road, Tarn's Landing -> outflow -> Hollowreach
        Road(((-318, 104), (-350, 176), (-352, 262), o(H, (33, -14))), width=4.0, shoulder=2.0),
        # ---- secondary: wilds trail off the Kingsway below the watch ridge
        Road(((-98, -364), (-172, -330), (-248, -356), o(Wn, (0, 25))), width=3.5, shoulder=2.0),
        # ---- secondary: the Crossway's west track down into the wilds (the loop)
        Road(((-129.5, -480), (-212, -474), o(Wn, (0, -25))), width=3.0, shoulder=2.0),
        # ---- secondary: shore trail north to the corrie, fording the Emberwash
        Road((o(Lt, (-26, -1)), (-362, 28), (-412, -44), (-438, -124), o(Ww, (25, 0))), width=3.0, shoulder=2.0),
        # ---- secondary: the watch-ridge spur to the ruined tower
        Road(((-62, -262), (-38, -290)), width=2.5, shoulder=1.5),
        # ---- secondary: the citadel ramp, from the Kingsway up the spur
        Road(((30, -104), (60, -118), (84, -138)), width=5.0, shoulder=2.0),
        # ---- tertiary: drovers' track to the sheepfold
        Road(((-146, 132), o(D, (40, 4))), width=3.0, shoulder=2.0),
        # ---- tertiary: fen causeway toward the drowned pillars
        Road(((-352, 262), (-420, 300), o(F, (-2, -16))), width=3.0, shoulder=2.0),
        # ---- tertiary: the burnt track to the Ashen Breach (reserved), ending at the gap
        Road(((392, -262), (452, -286), (496, -282)), width=3.0, shoulder=2.0),
    ]


# The realm's macro geography, authored as WORLD landforms (see gen_regions.place_world).
def geography() -> list:
    valley = [(-112, -600), (-138, -470), (-160, -350), (-172, -230), (-198, -110), (-262, -40),
              (-330, 30), (-362, 90)]
    outflow = [(-392, 200), (-386, 270), (-414, 350), (-490, 420)]
    forms = [
        # The Crown Range: a wall across the north with one saddle, at the Crossway.
        Ridge(a=(-560, -690), b=(-240, -700), half=70, h=52.0, fall=0.8),
        Ridge(a=(-60, -706), b=(180, -690), half=70, h=58.0, fall=0.8),
        Ridge(a=(200, -688), b=(520, -650), half=80, h=74.0, fall=0.8),
        Mound(at=(-150, -700), ext=(70, 40), h=16.0, fall=0.9),
        Ridge(a=(-280, -628), b=(-196, -612), half=26, h=28.0, fall=0.75),
        Ridge(a=(-96, -612), b=(0, -636), half=26, h=30.0, fall=0.75),
        # Frontier foothills and the north-west forest upland.
        Mound(at=(90, -560), ext=(90, 45), h=12.0, fall=0.9),
        Mound(at=(-440, -470), ext=(90, 70), h=16.0, fall=0.95),
        Mound(at=(-330, -430), ext=(110, 60), h=9.0, fall=0.95),
        # The watch ridge north of the capital; the Kingsway rounds its western tip.
        Ridge(a=(-60, -318), b=(70, -296), half=32, h=15.0, fall=0.85),
        # The western ridge behind the corrie.
        Ridge(a=(-505, -420), b=(-495, -60), half=45, h=26.0, fall=0.85),
        # The capital's citadel spur and the eastern hills around Emberdeep.
        Mound(at=(112, -170), ext=(84, 66), h=16.0, fall=0.75),
        # The citadel's court: the spur's crown levelled at the spur's own height (relative to the
        # generated ground under it, so 14 of the spur's 16 m) for the keep, towers and halls. Its
        # level core (72% of the extent) holds the curtain towers too: they stood on the falloff ring
        # with up to 4 m of fall under them.
        Mound(at=(106, -162), ext=(60, 54), h=14.0, fall=0.28, flat=1.0),
        Mound(at=(470, -110), ext=(80, 110), h=22.0, fall=0.9),
        Mound(at=(300, -262), ext=(80, 60), h=11.0, fall=0.9),
        Mound(at=(440, -420), ext=(70, 80), h=14.0, fall=0.9),
        # The Tarn: a wadeable shelf, then a deep basin behind a real drop (NOW.md invariant 24).
        Mound(at=(-372, 132), ext=(96, 78), h=-0.7, fall=0.45, flat=0.85),
        Mound(at=(-384, 138), ext=(74, 58), h=-5.0, fall=0.25, flat=1.0),
        # The fens and the delta below the Tarn.
        Mound(at=(-420, 372), ext=(110, 64), h=-2.4, fall=0.9),
        # The southern farm belt and the ash flats.
        Mound(at=(150, 300), ext=(130, 80), h=5.0, fall=0.95),
        Mound(at=(360, 300), ext=(90, 70), h=-3.0, fall=0.95),
        # The border hills, gapped at the Southmarch Gate and at the Ashen Breach.
        Ridge(a=(-200, 432), b=(24, 428), half=28, h=14.0, fall=0.85),
        Ridge(a=(122, 424), b=(520, 406), half=30, h=16.0, fall=0.85),
        Ridge(a=(512, -600), b=(508, -330), half=28, h=26.0, fall=0.85),
        Ridge(a=(508, -236), b=(512, 60), half=28, h=20.0, fall=0.85),
    ]
    for a, b in zip(valley, valley[1:]):
        forms.append(Ridge(a=a, b=b, half=38, h=-6.0, fall=0.9))
    for a, b in zip(outflow, outflow[1:]):
        forms.append(Ridge(a=a, b=b, half=30, h=-4.0, fall=0.9))
    forms.append(Water(at=(-384, 136), ext=(120, 100), ident="Tarn",
                       shallow=(0.21, 0.33, 0.34), deep=(0.05, 0.13, 0.18), opaque=1.5))
    return forms


def district_terraces() -> list:
    """The levelled strips the capital's frontages stand on (tools/district_layouts.py): a flat ridge
    along each street, at the country's own height, so a terrace follows its lane instead of being an
    axis-aligned pad dropped across it."""
    import district_layouts
    return [Ridge(a=a, b=b, half=half, h=0.0, fall=0.55, flat=0.95)
            for a, b, half in district_layouts.TERRACES
            if EXTENT_X[0] < a[0] < EXTENT_X[1] and ROWS[0][0] < a[1] < ROWS[-1][1]]


def district_pads() -> list:
    """Levelled pads for this realm's standalone structures (tools/district_layouts.py)."""
    import district_layouts
    return [Yard(at=(x, z), ext=(hx, hz), feather=2.5, blend=0.9)
            for x, z, hx, hz in district_layouts.pads(district_layouts.ITEMS)
            if EXTENT_X[0] < x < EXTENT_X[1] and ROWS[0][0] < z < ROWS[-1][1]]


def build_ember() -> tuple[str, list[str]]:
    spec = cells()
    issues = check_tiling("EmberCrown", spec, ROWS, EXTENT_X)
    spec, _ = apply_origins(spec, [])
    spec = place_world(spec, geography() + district_terraces() + district_pads())
    spec, road_issues = realize_roads(spec, roads())
    issues += [f"EmberCrown: {issue}" for issue in road_issues]
    issues += check_envelopes("EmberCrown", spec, {c.key: list(c.routes) for c in spec})
    return emit("ember_crown", HEADER, spec, [], ENVIRONMENT, BUDGET, RESOURCE, SCATTER,
                "TemperateLowland"), issues
