#!/usr/bin/env python3
"""Unit tests for the generator-lane tools. No engine, no network, no credits.

    python -m unittest discover -s tools -p "test_*.py"
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import time
import unittest
import unittest.mock
from pathlib import Path
from types import SimpleNamespace

sys.path.insert(0, str(Path(__file__).resolve().parent))

import check_world_static  # noqa: E402
import content  # noqa: E402
import meshy_batch  # noqa: E402
import regen  # noqa: E402
import tres_reader  # noqa: E402
import world_bake  # noqa: E402
from tres_reader import Raw, Ref  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent

ENEMY = '''[gd_resource type="Resource" script_class="EnemyArchetypeResource" load_steps=3 format=3 uid="uid://x"]

[ext_resource type="Script" path="res://src/Enemies/EnemyArchetypeResource.cs" id="1_archetype"]

; A comment with "quotes" and a [bracket that must be ignored.
[sub_resource type="Resource" id="Zone_head"]
script = ExtResource("1_archetype")
Id = "head"
Offset = Vector3(0, 9, -8.2)

[resource]
script = ExtResource("1_archetype")
Id = "enemy.bandit"
NameKey = "enemy.bandit.name"
LootTablePath = "res://data/loot/BanditLoot.tres"
KnownSpellIds = Array[String](["spell.a", "spell.b, with comma"])
HitZones = Array[Resource]([SubResource("Zone_head")])
Levels = PackedInt32Array(10, 20)
IsBoss = true
MaxPoise = 35.0
XpValue = 30
Description = "line one
line two with \\"escaped\\" quotes"
'''


class TresReaderTests(unittest.TestCase):
    def test_typed_values(self):
        doc = tres_reader.parse(ENEMY)
        root = doc.root
        self.assertEqual(doc.script_class, "EnemyArchetypeResource")
        self.assertEqual(root.get("Id"), "enemy.bandit")
        self.assertIs(root.get("IsBoss"), True)
        self.assertEqual(root.get("MaxPoise"), 35.0)
        self.assertEqual(root.get("XpValue"), 30)
        self.assertEqual(root.get("KnownSpellIds"), ["spell.a", "spell.b, with comma"])
        self.assertEqual(root.get("Levels"), [10, 20])
        self.assertEqual(root.get("HitZones"), [Ref("sub", "Zone_head")])
        self.assertEqual(root.get("Description"), 'line one\nline two with "escaped" quotes')

    def test_sections_refs_and_raw(self):
        doc = tres_reader.parse(ENEMY.replace("\n", "\r\n"))
        self.assertEqual([s.kind for s in doc.sections], ["gd_resource", "ext_resource", "sub_resource", "resource"])
        self.assertEqual(doc.ext, {"1_archetype": "res://src/Enemies/EnemyArchetypeResource.cs"})
        zone = doc.resolve(doc.root.get("HitZones"))[0]
        self.assertEqual(zone.get("Id"), "head")
        self.assertIsInstance(zone.get("Offset"), Raw)
        self.assertEqual(doc.resolve(zone.get("script")), "res://src/Enemies/EnemyArchetypeResource.cs")

    def test_typed_array_of_ext_resource_type(self):
        doc = tres_reader.parse('[resource]\nAttacks = Array[ExtResource("2_action")]([SubResource("Bite"), SubResource("Tail")])\n')
        self.assertEqual(doc.root.get("Attacks"), [Ref("sub", "Bite"), Ref("sub", "Tail")])

    def test_scene_nodes_have_paths(self):
        doc = tres_reader.parse(
            '[gd_scene format=3]\n[ext_resource type="PackedScene" path="res://a.tscn" id="1"]\n'
            '[node name="Root" type="Node3D"]\n[node name="Nav" type="Node3D" parent="."]\n'
            '[node name="Smith" parent="Nav" instance=ExtResource("1")]\nShopId = "shop.smith"\n')
        self.assertEqual([n.path for n in doc.nodes], [".", "Nav", "Nav/Smith"])
        self.assertEqual(doc.nodes[2].attrs["instance"], Ref("ext", "1"))
        self.assertIn(("Nav/Smith", "ShopId", "shop.smith"),
                      [(s.label, k, v) for s, k, v in doc.strings()])

    def test_every_repo_resource_parses_to_its_section_count(self):
        import re
        for folder in ("data/enemies", "data/loot", "data/shops"):
            for path in sorted((ROOT / folder).glob("*.tres")):
                text = path.read_text(encoding="utf-8", errors="replace")
                want = len(re.findall(r"^\[(?:gd_resource|ext_resource|sub_resource|resource)\b", text, re.M))
                self.assertEqual(len(tres_reader.parse(text).sections), want, path.name)


def make_tree(root: Path) -> None:
    files = {
        "data/items/Scrap.tres": '[gd_resource script_class="ItemResource"]\n; Generated by tools/gen_items.py from x\n'
                                 '[resource]\nId = "item.scrap"\nValue = 4\nWorldModelPath = "res://assets/models/scrap.glb"\n',
        "data/items/Orphan.tres": '[gd_resource script_class="ItemResource"]\n[resource]\nId = "item.orphan"\nValue = 9\n',
        "data/loot/Bandit.tres": '[gd_resource script_class="LootTable"]\n[sub_resource type="Resource" id="Entry_a"]\n'
                                 'ItemId = "item.scrap"\nDropChance = 0.5\nMinQuantity = 2\nMaxQuantity = 4\n'
                                 '[sub_resource type="Resource" id="Entry_b"]\nItemId = "item.ghost"\n'
                                 '[resource]\nEntries = Array[Resource]([SubResource("Entry_a"), SubResource("Entry_b")])\n'
                                 'GoldChance = 1.0\nGoldMin = 10\nGoldMax = 20\n',
        "data/enemies/Bandit.tres": '[gd_resource script_class="EnemyArchetypeResource"]\n[resource]\nId = "enemy.bandit"\n'
                                    'NameKey = "enemy.bandit.name"\nLootTablePath = "res://data/loot/Bandit.tres"\n'
                                    'ModelPath = "res://assets/models/missing.glb"\n',
        "scenes/regions/ember/camp.tscn": '[gd_scene format=3]\n[node name="Camp" type="Node3D"]\n'
                                          '[node name="Spawn" type="Node3D" parent="."]\nTemplateId = "enemy.bandit"\n',
        "data/locale/strings.csv": "keys,en\n# comment\nenemy.bandit.name,Bandit\n",
        "src/Core/GameIds.cs": 'public const string Scrap = "item.scrap";\n',
        "assets/models/scrap.glb": "x",
    }
    for rel, text in files.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")


class ContentIndexTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        make_tree(self.root)
        self.index = content.build_index(self.root)

    def tearDown(self):
        self.temp.cleanup()

    def test_refs_lists_definition_and_every_kind_of_use(self):
        result = content.refs(self.index, "item.scrap")
        self.assertEqual([d["path"] for d in result["defs"]], ["data/items/Scrap.tres"])
        self.assertEqual(result["defs"][0]["generated"], "tools/gen_items.py")
        self.assertEqual({(u["kind"], u["where"]) for u in result["uses"]},
                         {("loot", "Entry_a.ItemId"), ("code", "line 1")})

    def test_refs_follows_the_defining_file_path_and_model_stems(self):
        loot = content.refs(self.index, "res://data/loot/Bandit.tres")
        self.assertEqual([(u["kind"], u["where"]) for u in loot["uses"]], [("enemies", "resource.LootTablePath")])
        model = content.refs(self.index, "scrap")
        self.assertEqual([u["via"] for u in model["uses"]], ["res://assets/models/scrap.glb"])
        scene = content.refs(self.index, "enemy.bandit")
        self.assertIn(("scenes", "Spawn.TemplateId"), [(u["kind"], u["where"]) for u in scene["uses"]])
        self.assertEqual(scene["locale_keys"], ["enemy.bandit.name"])

    def test_refs_lists_a_use_in_json_under_data(self):
        graph = self.root / "data/story/campaign_graph.json"
        graph.parent.mkdir(parents=True)
        graph.write_text('{"nodes": [\n {"boss": "enemy.bandit", "drop": "item.not_defined"}]}', encoding="utf-8")
        bake = self.root / "data/world_bake/manifest.json"
        bake.parent.mkdir(parents=True)
        bake.write_text('{"x": "enemy.bandit"}', encoding="utf-8")
        index = content.build_index(self.root)
        uses = [(u["kind"], u["path"], u["where"]) for u in content.refs(index, "enemy.bandit")["uses"]]
        self.assertIn(("json", "data/story/campaign_graph.json", "line 2"), uses)
        self.assertNotIn("data/world_bake/manifest.json", [path for _, path, _ in uses])
        # Like code, JSON is searched for uses but is not a source of dangling rows.
        self.assertNotIn("item.not_defined", [row["token"] for row in content.dangling(index)])

    def test_unknown_id_has_no_defs_and_no_uses(self):
        result = content.refs(self.index, "item.nothing")
        self.assertFalse(result["defs"] or result["uses"])

    def test_unused_and_dangling(self):
        self.assertEqual([d.id for d in content.unused(self.index, "items")], ["item.orphan"])
        found = {row["token"]: row["why"] for row in content.dangling(self.index)}
        self.assertEqual(found, {"item.ghost": "undefined id", "res://assets/models/missing.glb": "missing file"})

    def test_locale_keys_are_not_dangling_ids(self):
        self.assertNotIn("enemy.bandit.name", [row["token"] for row in content.dangling(self.index)])

    def test_cache_reuses_unchanged_files_and_sees_edits(self):
        cache = self.root / "artifacts" / "index.json"
        first = content.build_index(self.root, cache=cache)
        self.assertTrue(cache.is_file())
        stamp = cache.stat().st_mtime_ns
        again = content.build_index(self.root, cache=cache)
        self.assertEqual(cache.stat().st_mtime_ns, stamp, "an unchanged tree must not rewrite the cache")
        self.assertEqual(sorted(first.defs), sorted(again.defs))
        target = self.root / "data/items/Orphan.tres"
        target.write_text(target.read_text(encoding="utf-8").replace("item.orphan", "item.renamed_now"), encoding="utf-8")
        self.assertIn("item.renamed_now", content.build_index(self.root, cache=cache).defs)

    def test_census_counts_generated_and_hand_files(self):
        result = content.census(self.root)
        self.assertEqual(result["kinds"]["items"], {"files": 2, "generated": 1, "hand": 1})
        self.assertEqual(result["scenes"], 1)
        self.assertEqual(result["locale_rows"], 2)

    def test_loot_value_expects_drop_chance_quantity_and_gold(self):
        values = content.item_values(self.root)
        value = content.table_value(self.root, self.root / "data/loot/Bandit.tres", values, tier=1)
        self.assertAlmostEqual(value, 15 + 0.5 * 3 * 4)  # gold 15 + half the time three scrap at 4


class ContentDiffTests(unittest.TestCase):
    def test_field_level_diff_names_root_and_sub_resource_fields(self):
        old = '[sub_resource type="Resource" id="Entry_a"]\nDropChance = 0.5\n[resource]\nId = "x.y"\nHealth = 80.0\nGone = 1\n'
        new = '[sub_resource type="Resource" id="Entry_a"]\nDropChance = 0.7\n[resource]\nId = "x.y"\nHealth = 95.0\nAdded = "v"\n'
        fields = {f["field"]: (f["old"], f["new"]) for f in content.diff_documents(old, new)["fields"]}
        self.assertEqual(fields, {"Health": ("80", "95"), "Entry_a.DropChance": ("0.5", "0.7"),
                                  "Gone": ("1", None), "Added": (None, "v")})

    def test_comment_and_line_ending_changes_are_not_content_changes(self):
        old = '[resource]\nId = "x.y"\n'
        self.assertEqual(content.diff_documents(old, "; note\r\n" + old.replace("\n", "\r\n"))["fields"], [])

    def test_locale_diff_counts_keys(self):
        self.assertEqual(content.diff_locale("a,1\nb,2\n# c\n", "a,1\nb,3\nd,4\n"),
                         {"added": 1, "removed": 0, "changed": 1})

    def test_fact_lines_collapse_wide_changes(self):
        fact = {"status": "~", "kind": "enemies", "path": "p", "id": "enemy.x",
                "fields": [{"field": f"Zone_{i}.Radius", "old": "1", "new": "2"} for i in range(8)]}
        self.assertEqual(content.fact_line(fact, False),
                         "~ enemy.x (enemies) 8 fields in 8 section(s): Zone_0, Zone_1, Zone_2 ...")
        self.assertIn("Zone_7.Radius 1 -> 2", content.fact_line(fact, True))
        self.assertEqual(content.summary_line({"items": {"+": 2, "~": 1}, "quests": {"-": 1}}),
                         "summary items +2 ~1 | quests -1")

    def test_diff_against_head_runs_on_this_repo(self):
        result = content.content_diff("HEAD", "HEAD")
        self.assertEqual(result["facts"], [])


class BalanceTests(unittest.TestCase):
    def test_formulas_match_combat_math(self):
        self.assertEqual(content.combat_math_drift(), [], "CombatMath.cs changed: update the mirror in content.py")
        self.assertAlmostEqual(content.armor_multiplier(100), 0.5)
        self.assertAlmostEqual(content.armor_multiplier(-20), 1.0)
        self.assertAlmostEqual(content.scale_damage(10, 14), 17.0)
        self.assertAlmostEqual(content.hits_to_kill(80, 10, 20, 0), 4.0)
        self.assertEqual(content.xp_to_leave(4, 100, 1.5, 50), 800)
        self.assertEqual(content.xp_to_leave(50, 100, 1.5, 50), 0)

    def test_flags_mark_outliers_against_tier_peers(self):
        def row(name, ttk, ttd=10.0, hp=100.0, boss=False, xp_per_hp=0.5):
            return {"id": name, "boss": boss, "tiers": [1], "band_known": True, "hp": hp,
                    "ttk_lo": ttk, "ttd_lo": ttd, "xp_per_hp": xp_per_hp}
        rows = [row("a", 3), row("b", 3), row("c", 3), row("tank", 12), row("glass", 0.5),
                row("killer", 3, ttd=1.5), row("rich", 3, xp_per_hp=5.0),
                row("weak_boss", 3, hp=50, boss=True)]
        content.flag_enemies(rows)
        flags = {r["id"]: r["flags"] for r in rows}
        self.assertEqual(flags["a"], [])
        self.assertEqual(flags["tank"], ["tanky"])
        self.assertEqual(flags["glass"], ["fragile"])
        self.assertEqual(flags["killer"], ["one-shots-at-entry"])
        self.assertEqual(flags["rich"], ["xp-outlier"])
        self.assertEqual(flags["weak_boss"], ["boss-weaker-than-trash"])

    def test_moved_reports_only_rows_past_the_threshold(self):
        before = [{"id": "a", "hp": 100, "boss": False}, {"id": "b", "hp": 100}, {"id": "gone", "hp": 1}]
        after = [{"id": "a", "hp": 110, "boss": True}, {"id": "b", "hp": 130}, {"id": "new", "hp": 1}]
        changes = {r["id"]: r["change"] for r in content.moved(after, before, 0.15)}
        self.assertEqual(changes, {"b": "hp 100 -> 130", "new": "new", "gone": "removed"})

    def test_enemy_table_covers_every_enemy_in_the_repo(self):
        rows = content.balance_enemies()
        self.assertEqual(len(rows), len(list((ROOT / "data" / "enemies").glob("*.tres"))))
        bandit = next(r for r in rows if r["id"] == "enemy.bandit")
        self.assertGreater(bandit["ttk_lo"], 0)
        self.assertGreater(bandit["ttd_lo"], 0)
        self.assertTrue(all(r["tiers"] for r in rows))


def process(returncode=0, output="", timed_out=False):
    return SimpleNamespace(returncode=returncode, output=output, timed_out=timed_out)


class RegenTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        (self.root / "out").mkdir()
        (self.root / "gen.py").write_text("# generator\n", encoding="utf-8")
        (self.root / "out" / "a.txt").write_text("old\n", encoding="utf-8")
        self.state = self.root / "artifacts" / "regen"
        self.entry = regen.Entry("gen", "test", ("gen.py", "--check"), ("gen.py",), ("gen.py", "out/*.txt"))
        regen._GLOBS.clear()

    def tearDown(self):
        self.temp.cleanup()

    def test_registry_keeps_the_catalogue_chain_in_order(self):
        names = [entry.name for entry in regen.REGISTRY]
        self.assertEqual(len(names), len(set(names)))
        chain = [names.index(n) for n in ("catalogue", "gen_items", "gen_recipes", "gen_loot")]
        self.assertEqual(chain, sorted(chain))
        for entry in regen.REGISTRY:
            for command in (entry.check, entry.write):
                if command:
                    self.assertTrue((ROOT / command[0]).is_file(), f"{entry.name}: {command[0]} does not exist")
            if entry.check is None:
                self.assertTrue(entry.owns, f"{entry.name} has no --check, so it must name the files it owns")
            self.assertTrue(regen.files_for(ROOT, entry.watch), f"{entry.name} watches nothing that exists")

    def test_classify(self):
        self.assertEqual(regen.classify(0, "", False, False), "ok")
        self.assertEqual(regen.classify(1, "WOULD CHANGE x", False, False), "DRIFT")
        self.assertEqual(regen.classify(2, "lattice error", False, False), "FAIL")
        self.assertEqual(regen.classify(1, "selftest: 10/11", False, True), "FAIL")
        self.assertEqual(regen.classify(1, "Traceback (most recent call last):\n", False, False), "ERROR")
        self.assertEqual(regen.classify(124, "", True, False), "ERROR")
        self.assertEqual(regen.first_reason("warning: differs a bit\n27 quests\nDRIFT: data/x: differs\ndone"),
                         "DRIFT: data/x: differs")

    def test_select_keeps_registry_order_and_rejects_unknown_names(self):
        self.assertEqual([e.name for e in regen.select(["gen_loot", "gen_items"])], ["gen_items", "gen_loot"])
        with self.assertRaises(SystemExit):
            regen.select(["nope"])

    def test_passing_check_is_cached_until_a_watched_file_changes(self):
        calls = []

        def run(root, arguments, timeout):
            calls.append(arguments)
            return process()
        first = regen.regen("check", [self.entry], self.root, self.state, run=run)
        second = regen.regen("check", [self.entry], self.root, self.state, run=run)
        self.assertEqual((first["exit_code"], second["cached"], len(calls)), (0, 1, 1))
        (self.root / "out" / "a.txt").write_text("hand edited\n", encoding="utf-8")
        regen._GLOBS.clear()
        self.assertEqual(regen.regen("stale", [self.entry], self.root, self.state, run=run)["drift"], ["gen"])
        regen.regen("check", [self.entry], self.root, self.state, run=run)
        self.assertEqual(len(calls), 2)
        regen.regen("check", [self.entry], self.root, self.state, use_cache=False, run=run)
        self.assertEqual(len(calls), 3)

    def test_line_endings_do_not_change_a_signature(self):
        before = regen.signature(self.root, self.entry)
        (self.root / "out" / "a.txt").write_bytes(b"old\r\n")
        regen._GLOBS.clear()
        self.assertEqual(regen.signature(self.root, self.entry), before)

    def test_drift_is_exit_1_and_a_crash_is_exit_2(self):
        drift = regen.regen("check", [self.entry], self.root, self.state,
                            run=lambda *a: process(1, "WOULD CHANGE out/a.txt"))
        self.assertEqual((drift["exit_code"], drift["drift"]), (1, ["gen"]))
        self.assertEqual((self.state / "gen.log").read_text(encoding="utf-8"), "WOULD CHANGE out/a.txt")
        crash = regen.regen("check", [self.entry], self.root, self.state,
                            run=lambda *a: process(1, "Traceback (most recent call last):\nboom"))
        self.assertEqual((crash["exit_code"], crash["errors"]), (2, ["gen"]))

    def test_fix_writes_what_drifted_then_proves_a_fixed_point(self):
        target = self.root / "out" / "a.txt"

        def run(root, arguments, timeout):
            if "--check" in arguments:
                return process(0 if target.read_text(encoding="utf-8") == "new\n" else 1, "WOULD CHANGE out/a.txt")
            target.write_text("new\n", encoding="utf-8")
            return process()
        result = regen.regen("fix", [self.entry], self.root, self.state, run=run)
        self.assertEqual((result["exit_code"], result["fixed"]), (0, ["gen"]))
        self.assertEqual(result["entries"][0]["changed"], ["out/a.txt"])

    def test_fix_reports_a_writer_that_never_settles(self):
        def run(root, arguments, timeout):
            if "--check" in arguments:
                return process(1, "WOULD CHANGE out/a.txt")
            (self.root / "out" / "a.txt").write_text(str(time.monotonic_ns()), encoding="utf-8")
            return process()
        result = regen.regen("fix", [self.entry], self.root, self.state, run=run)
        self.assertEqual((result["exit_code"], result["not_idempotent"]), (1, ["gen"]))
        self.assertEqual(result["entries"][0]["status"], "NOT-IDEMPOTENT")

    def test_writer_without_check_runs_on_a_copy_and_never_writes_the_tree(self):
        entry = regen.Entry("plain", "test", None, ("gen.py",), ("gen.py", "out/*.txt"), owns=("out/*.txt",),
                            reads=("in/*.txt",))
        (self.root / "in").mkdir()
        (self.root / "in" / "source.txt").write_text("input\n", encoding="utf-8")
        seen = {}

        def run(root, arguments, timeout):
            self.assertNotEqual(root, self.root)
            # The copy holds the script, what it reads and what it owns, at the same relative paths.
            seen["files"] = sorted(path.relative_to(root).as_posix() for path in root.rglob("*") if path.is_file())
            (root / "out" / "a.txt").write_text("regenerated\n", encoding="utf-8")
            (root / "out" / "b.txt").write_text("brand new\n", encoding="utf-8")
            # A run killed here leaves the real tree exactly as it was.
            self.assertEqual((self.root / "out" / "a.txt").read_text(encoding="utf-8"), "old\n")
            self.assertFalse((self.root / "out" / "b.txt").exists())
            return process()
        row = regen.run_check(self.root, entry, run)
        self.assertEqual(seen["files"], ["gen.py", "in/source.txt", "out/a.txt"])
        self.assertEqual((row["status"], row["changed"]), ("DRIFT", ["out/a.txt", "out/b.txt"]))
        self.assertEqual((self.root / "out" / "a.txt").read_text(encoding="utf-8"), "old\n")
        self.assertFalse((self.root / "out" / "b.txt").exists())
        self.assertEqual(regen.run_check(self.root, entry, lambda *a: process())["status"], "ok")

    def test_every_check_less_writer_finds_its_root_from_its_own_file(self):
        # run_in_copy relies on it: a writer that used the working directory or a fixed path
        # would write the real tree from inside the copy.
        for entry in regen.REGISTRY:
            if entry.check is None:
                text = (regen.ROOT / entry.write[0]).read_text(encoding="utf-8")
                self.assertIn("os.path.dirname(os.path.dirname(os.path.abspath(__file__)))", text, entry.name)
                for pattern in (*entry.owns, *entry.reads):
                    self.assertTrue(regen.files_for(regen.ROOT, (pattern,)), f"{entry.name}: {pattern} matches nothing")

    def test_an_imported_helper_invalidates_the_cache(self):
        (self.root / "tools").mkdir()
        (self.root / "tools" / "helper.py").write_text("X = 1\n", encoding="utf-8")
        (self.root / "tools" / "deep.py").write_text("Y = 1\n", encoding="utf-8")
        (self.root / "gen.py").write_text("import os\nfrom helper import X\n", encoding="utf-8")
        (self.root / "tools" / "helper.py").write_text("import deep\nX = 1\n", encoding="utf-8")
        self.assertEqual(regen.local_imports(self.root, "gen.py"), ("tools/deep.py", "tools/helper.py"))
        before = regen.signature(self.root, self.entry)
        (self.root / "tools" / "deep.py").write_text("Y = 22\n", encoding="utf-8")
        regen._GLOBS.clear()
        self.assertNotEqual(regen.signature(self.root, self.entry), before)

    def test_missing_dependency_skips_a_full_run_and_fails_a_named_one(self):
        entry = regen.Entry("needs", "test", ("gen.py",), None, ("gen.py",), needs=("no_such_module_xyz",))
        result = regen.regen("check", [entry], self.root, self.state, run=lambda *a: self.fail("must not run"))
        self.assertEqual((result["exit_code"], result["skipped"]), (0, ["needs"]))
        named = regen.regen("check", [entry], self.root, self.state, run=lambda *a: self.fail("must not run"),
                            required=True)
        self.assertEqual((named["ok"], named["exit_code"], named["errors"]), (False, 2, ["needs"]))
        self.assertIn("missing no_such_module_xyz", named["entries"][0]["reason"])

    def test_lock_is_exclusive_until_its_owner_is_gone(self):
        first, second = regen.Lock(self.state / ".lock"), regen.Lock(self.state / ".lock")
        self.assertTrue(first.acquire())
        self.assertFalse(second.acquire())
        # Age alone never frees it: a long --fix is still running.
        old = time.time() - regen.LOCK_STALE_SECONDS - 5
        os.utime(self.state / ".lock", (old, old))
        self.assertFalse(second.acquire())
        gone = subprocess.Popen([sys.executable, "-c", "pass"])
        gone.wait()
        (self.state / ".lock" / "pid").write_text(str(gone.pid), encoding="utf-8")
        self.assertTrue(second.acquire())
        second.release()
        self.assertFalse((self.state / ".lock").exists())


class RegenPngCompareTests(unittest.TestCase):
    def test_a_png_is_compared_by_pixels_not_by_encoded_bytes(self):
        try:
            from PIL import Image
        except ImportError:
            self.skipTest("Pillow is not installed")
        import io

        def png(colour, level):
            buffer = io.BytesIO()
            Image.new("RGB", (4, 4), colour).save(buffer, "PNG", compress_level=level)
            return buffer.getvalue()

        loose, tight = png((10, 20, 30), 0), png((10, 20, 30), 9)
        self.assertNotEqual(loose, tight)
        self.assertTrue(regen.same_content("mask.png", loose, tight))
        self.assertFalse(regen.same_content("mask.png", loose, png((10, 20, 31), 0)))
        self.assertFalse(regen.same_content("mask.png", loose, None))
        self.assertFalse(regen.same_content("data.tres", b"a", b"b"))


class WorldBakeTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)

    def tearDown(self):
        self.temp.cleanup()

    def outputs(self, region: str, cells: int) -> set[Path]:
        folder = self.root / "cells" / region
        folder.mkdir(parents=True, exist_ok=True)
        (self.root / "regions").mkdir(exist_ok=True)
        return {self.root / "regions" / f"{region}.res"} | {folder / f"cell{i}.scn" for i in range(cells)}

    def test_progress_counts_only_files_written_since_the_bake_started(self):
        expected = {"region.a": self.outputs("a", 3), "region.b": self.outputs("b", 2)}
        started = time.time()
        stale = self.root / "cells" / "a" / "cell0.scn"
        stale.write_text("old")
        os.utime(stale, (started - 500, started - 500))
        for name, age in (("cell1.scn", 0), ("cell2.scn", 3)):
            path = self.root / "cells" / "a" / name
            path.write_text("new")
            os.utime(path, (started + age, started + age))
        snapshot = world_bake.progress(expected, started, started + 10, fallback_rate=2.0)
        self.assertEqual((snapshot["done"], snapshot["total"]), (2, 7))
        self.assertEqual((snapshot["region"], snapshot["artifact"]), ("region.a", "cell2"))
        self.assertEqual(snapshot["regions_done"], [])
        self.assertEqual(snapshot["eta_seconds"], 25)  # 5 s per artifact so far, 5 left
        nothing = world_bake.progress(expected, started + 100, started + 100, fallback_rate=2.0)
        self.assertEqual((nothing["done"], nothing["eta_seconds"]), (0, 14))

    def test_a_region_is_done_when_its_resource_is_written(self):
        expected = {"region.a": self.outputs("a", 1)}
        started = time.time() - 5
        for path in expected["region.a"]:
            path.write_text("x")
        snapshot = world_bake.progress(expected, started, time.time())
        self.assertEqual((snapshot["done"], snapshot["regions_done"]), (2, ["region.a"]))

    def test_status_line_and_exit_codes(self):
        now = 1000.0
        self.assertEqual(world_bake.status_line({}, now)[1:], ("none", 2))
        running = {"state": "running", "done": 87, "total": 151, "region": "region.ember_crown",
                   "artifact": "ember_crown_tarn_east", "elapsed_seconds": 212, "eta_seconds": 156, "updated": now - 3}
        self.assertEqual(world_bake.status_line(running, now),
                         ("bake running 87/151 region.ember_crown ember_crown_tarn_east elapsed 212s eta 156s",
                          "running", 3))
        dead = world_bake.status_line({**running, "updated": now - 300}, now)
        self.assertEqual(dead[1:], ("interrupted", 1))
        self.assertIn("--bake --resume", dead[0])
        self.assertEqual(world_bake.status_line({"state": "preparing", "updated": now - 300}, now)[1:], ("preparing", 3))
        self.assertEqual(world_bake.status_line({"state": "done", "done": 151, "total": 151}, now)[2], 0)
        failed = world_bake.status_line({"state": "failed", "error": "engine exited 1"}, now)
        self.assertEqual((failed[2], failed[0].endswith("engine exited 1")), (1, True))

    def test_watcher_journals_a_settled_region_only_while_the_engine_is_alive(self):
        expected = {"region.a": self.outputs("a", 2)}
        for path in expected["region.a"]:
            path.write_bytes(b"half")
        journal = {"regions": {}}
        with unittest.mock.patch.object(world_bake, "ROOT", self.root), \
                unittest.mock.patch.object(world_bake, "JOURNAL", self.root / "journal.json"), \
                unittest.mock.patch.object(world_bake, "STATUS", self.root / "status.json"):
            watcher = world_bake.Watcher(expected, {"region.a": "sig"}, time.time() - 5, {}, 2.0, journal)
            # The engine was killed mid-save: its files stop changing, which is not "finished".
            watcher.tick(journal=False)
            watcher.tick(journal=False)
            self.assertEqual(journal["regions"], {})
            watcher.tick()
            watcher.tick()
            self.assertEqual(list(journal["regions"]), ["region.a"])

    def test_resumable_needs_same_signature_and_same_bytes(self):
        original = world_bake.ROOT
        world_bake.ROOT = self.root
        try:
            outputs = self.outputs("a", 2)
            for path in outputs:
                path.write_text(path.name)
            journal: dict = {}
            world_bake.journal_region(journal, "region.a", "sig1", outputs)
            self.assertEqual(world_bake.resumable(journal, {"region.a": "sig1"}), {"region.a"})
            self.assertEqual(world_bake.resumable(journal, {"region.a": "sig2"}), set(), "inputs changed")
            (self.root / "cells" / "a" / "cell0.scn").write_text("rewritten")
            self.assertEqual(world_bake.resumable(journal, {"region.a": "sig1"}), set(), "an output changed")
            self.assertEqual(world_bake.resumable({}, {"region.a": "sig1"}), set())
        finally:
            world_bake.ROOT = original

    def test_capped_groups_by_kind_and_directory(self):
        lines = [f"changed source requires bake: assets/models/world/m{i}.glb" for i in range(14)]
        lines += ["changed source requires bake: src/World/A.cs", "source signature does not match current inputs"]
        out = world_bake.capped(lines, limit=10)
        self.assertEqual(len(out), 13)
        self.assertIn("changed source requires bake: ... 4 more under assets/models/world", out)
        self.assertEqual(out[-1], "source signature does not match current inputs")

    def test_plan_and_signatures_agree_with_the_committed_manifest(self):
        sources = world_bake.source_hashes()
        result = world_bake.plan(world_bake.read_json(world_bake.MANIFEST), sources)
        self.assertEqual(len(result["regions"]), 6)
        self.assertEqual(sum(r["artifacts"] for r in result["regions"]), len(world_bake.expected_outputs()))
        stale = set(world_bake.stale_regions(world_bake.read_json(world_bake.MANIFEST),
                                             world_bake.region_signatures(sources)))
        self.assertEqual(set(result["to_bake"]), stale)
        self.assertEqual(result["eta_seconds"], sum(r["eta_seconds"] for r in result["regions"]))

    def test_plan_names_a_changed_region_input_and_estimates_its_cost(self):
        sources = world_bake.source_hashes()
        manifest = world_bake.read_json(world_bake.MANIFEST)
        _, own = world_bake.region_inputs(sources)
        scene = next(name for name in sorted(own["region.pale_concord"]) if name.endswith(".tscn"))
        edited = {**sources, scene: "0" * 64}
        result = world_bake.plan(manifest, edited, rate=2.0)
        row = next(r for r in result["regions"] if r["region"] == "region.pale_concord")
        self.assertEqual((row["state"], row["own_changed"], row["eta_seconds"]),
                         ("stale", [scene], row["artifacts"] * 2))
        self.assertIn("region.pale_concord", result["to_bake"])
        # Editing one region's own scene adds nothing to the shared inputs, whatever the tree's
        # bake state is (a branch that touched src/World already lists that file here).
        # Compared with the unedited plan, not with []: the committed bake may itself be stale.
        self.assertEqual(result["shared_changed"], world_bake.plan(manifest, sources, rate=2.0)["shared_changed"])


PLAN = [{"id": "tree", "prompt": "an oak", "targetPolycount": 5000},
        {"id": "wolf", "prompt": "a wolf", "targetPolycount": 8000, "rig": True}]


class MeshyBatchTests(unittest.TestCase):
    """No test here reaches the network: create/poll/fetch are always fakes."""

    def fakes(self, statuses=None):
        calls = {"create": [], "poll": [], "fetch": [], "sleep": 0}
        statuses = statuses or {}

        def create(stage, item, st):
            calls["create"].append((item["id"], stage))
            return f"task-{item['id']}-{stage}"

        def poll(stage, task):
            calls["poll"].append(task)
            return {"status": statuses.get(task, "SUCCEEDED"), "model_urls": {"glb": "u"},
                    "result": {"rigged_character_glb_url": "u"}, "thumbnail_url": "t"}

        def fetch(url, dest):
            calls["fetch"].append(os.path.basename(dest))

        def sleep(seconds):
            calls["sleep"] += 1
        return calls, {"create": create, "poll": poll, "fetch": fetch, "sleep": sleep, "say": lambda *_: None}

    def test_wanted_stages_rig_only_when_asked(self):
        self.assertEqual(meshy_batch.wanted(PLAN[0], 2), ["preview", "refine"])
        self.assertEqual(meshy_batch.wanted(PLAN[1], 2), ["preview", "refine", "rig"])
        self.assertEqual(meshy_batch.wanted(PLAN[1], 0), ["preview"])

    def test_cost_preview_counts_remaining_stages_and_respects_the_cap(self):
        state = {"tree": {"preview": {"task": "t1", "status": "SUCCEEDED"}}}
        preview = meshy_batch.cost_preview(PLAN, state, 2, cap=1300)
        self.assertEqual((preview["spent"], preview["needed"], preview["would_spend"]), (5, 30, 30))
        self.assertEqual(preview["would_start"], ["tree:refine", "wolf:preview", "wolf:refine", "wolf:rig"])
        tight = meshy_batch.cost_preview(PLAN, state, 2, cap=20)
        self.assertEqual((tight["would_spend"], tight["headroom"]), (15, 15))
        self.assertEqual(tight["blocked_by_cap"], ["wolf:refine", "wolf:rig"])

    def test_cost_preview_never_recreates_a_failed_stage(self):
        state = {"tree": {"preview": {"task": "t1", "status": "FAILED"}}}
        self.assertEqual(meshy_batch.cost_preview(PLAN[:1], state, 2, cap=100)["needed"], 0)

    def test_status_rows_and_exit_codes(self):
        state = {"tree": {"preview": {"task": "a", "status": "SUCCEEDED"}, "refine": {"task": "b", "status": "SUCCEEDED"}},
                 "wolf": {"preview": {"task": "c", "status": "IN_PROGRESS"}}}
        rows = meshy_batch.status_rows(PLAN, state, 2)
        self.assertEqual([(r["id"], r["state"], r["credits"]) for r in rows], [("tree", "done", 15), ("wolf", "pending", 5)])
        self.assertEqual(rows[1]["stages"], {"preview": "IN_PROGRESS", "refine": "-", "rig": "-"})
        self.assertEqual(meshy_batch.status_exit(rows), 3)
        state["wolf"]["preview"]["status"] = "FAILED"
        self.assertEqual(meshy_batch.status_exit(meshy_batch.status_rows(PLAN, state, 2)), 1)
        self.assertEqual(meshy_batch.status_exit(meshy_batch.status_rows(PLAN[:1], state, 2)), 0)

    def test_run_walks_every_stage_once_and_downloads(self):
        calls, fakes = self.fakes()
        state: dict = {}
        outcome = meshy_batch.run(PLAN, state, lambda: None, 2, 1300, "out", 60, **fakes)
        self.assertEqual(outcome, "done")
        self.assertEqual(calls["create"], [("tree", "preview"), ("tree", "refine"),
                                           ("wolf", "preview"), ("wolf", "refine"), ("wolf", "rig")])
        self.assertEqual(meshy_batch.spent(state), 35)
        self.assertIn("wolf.rig.glb", calls["fetch"])
        again, fakes = self.fakes()
        meshy_batch.run(PLAN, state, lambda: None, 2, 1300, "out", 60, **fakes)
        self.assertEqual(again["create"], [], "a re-run must never create a task that already has an id")

    def test_run_stops_at_the_cap_before_paying(self):
        calls, fakes = self.fakes()
        state: dict = {}
        meshy_batch.run(PLAN, state, lambda: None, 2, 12, "out", 60, **fakes)
        self.assertEqual(calls["create"], [("tree", "preview"), ("wolf", "preview")])
        self.assertLessEqual(meshy_batch.spent(state), 12)

    def test_run_returns_budget_when_tasks_outlive_the_wall_clock(self):
        calls, fakes = self.fakes({"task-tree-preview": "IN_PROGRESS"})
        ticks = iter(range(0, 10_000, 200))
        state: dict = {}
        outcome = meshy_batch.run(PLAN[:1], state, lambda: None, 2, 1300, "out", 540,
                                  clock=lambda: next(ticks), **fakes)
        self.assertEqual(outcome, "budget")
        self.assertEqual(state["tree"]["preview"], {"task": "task-tree-preview", "status": "IN_PROGRESS"})
        self.assertEqual(calls["create"], [("tree", "preview")])
        self.assertGreaterEqual(calls["sleep"], 1)

    def test_ledger_rows_follow_the_file_wording_and_skip_known_tasks(self):
        state: dict = {}
        _, fakes = self.fakes()
        meshy_batch.run(PLAN, state, lambda: None, 2, 1300, "out", 60, **fakes)
        rows = meshy_batch.ledger_rows(PLAN, state, 2, "", "2026-10-07")
        self.assertEqual([r["entity"] for r in rows], ["tree", "wolf"])
        self.assertEqual(rows[0]["meshy_task_id"], "preview task-tree-preview; refine task-tree-refine")
        self.assertEqual((rows[0]["rig_task_id"], rows[1]["rig_task_id"]), ("none (static)", "task-wolf-rig"))
        self.assertEqual(rows[0]["status"], "generated")
        self.assertIn("15 credits", rows[0]["notes"])
        known = "x,preview task-tree-preview; refine task-tree-refine,y"
        self.assertEqual([r["entity"] for r in meshy_batch.ledger_rows(PLAN, state, 2, known, "d")], ["wolf"])
        state["wolf"]["rig"]["status"] = "IN_PROGRESS"
        self.assertEqual([r["entity"] for r in meshy_batch.ledger_rows(PLAN, state, 2, "", "d")], ["tree"])

    def test_append_ledger_keeps_existing_bytes_and_line_endings(self):
        with tempfile.TemporaryDirectory() as folder:
            path = os.path.join(folder, "manifest.csv")
            head = (",".join(meshy_batch.LEDGER_COLUMNS) + "\r\nold,row\r\n").encode("utf-8")
            with open(path, "wb") as handle:
                handle.write(head)
            row = {column: "v" for column in meshy_batch.LEDGER_COLUMNS}
            row["prompt"] = 'a "quoted", prompt'
            self.assertEqual(meshy_batch.append_ledger(path, [row]), 1)
            with open(path, "rb") as handle:
                data = handle.read()
            self.assertTrue(data.startswith(head))
            self.assertTrue(data.endswith(b"\r\n"))
            self.assertIn(b'"a ""quoted"", prompt"', data)
            self.assertEqual(meshy_batch.append_ledger(path, []), 0)

    def test_the_real_ledger_has_the_columns_this_tool_writes(self):
        with open(meshy_batch.LEDGER, encoding="utf-8", newline="") as handle:
            self.assertEqual(handle.readline().strip().split(","), meshy_batch.LEDGER_COLUMNS)

    def test_status_and_dry_run_need_no_key_and_no_network(self):
        with tempfile.TemporaryDirectory() as folder:
            plan = os.path.join(folder, "plan.json")
            with open(plan, "w", encoding="utf-8") as handle:
                json.dump({"generations": PLAN}, handle)
            saved = os.environ.pop("MESHY_API_KEY", None)
            original = meshy_batch.call
            meshy_batch.call = lambda *a, **k: self.fail("no API call is allowed here")
            import contextlib
            import io
            try:
                with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
                    self.assertEqual(meshy_batch.main([plan, folder, "--status", "--json"]), 3)
                    self.assertEqual(meshy_batch.main([plan, folder, "--dry-run", "--json"]), 0)
                    self.assertEqual(meshy_batch.main([plan, folder]), 2, "a real run without a key must refuse")
            finally:
                meshy_batch.call = original
                if saved is not None:
                    os.environ["MESHY_API_KEY"] = saved


class WorldStaticTests(unittest.TestCase):
    def test_failures_are_explained_and_passes_stay_quiet(self):
        def noisy(path):
            print("  SEAM_OK a <-> b")
            print(f"  OPEN_EDGE {path.stem} reaches north with no abutting cell")
            return 1 if path.stem == "Bad" else 0
        result = check_world_static.run([Path("Good.tres"), Path("Bad.tres")], ["seams"], logs=None,
                                        checks={"seams": noisy})
        self.assertEqual((result["passed"], result["failed"], result["exit_code"]), (1, 1, 1))
        self.assertEqual(result["failures"][0]["lines"], ["  OPEN_EDGE Bad reaches north with no abutting cell"])

    def test_a_crashing_check_is_a_failure_with_its_reason(self):
        def boom(path):
            raise ValueError("bad region")
        result = check_world_static.run([Path("X.tres")], ["layout"], logs=None, checks={"layout": boom})
        self.assertEqual(result["failures"][0]["lines"], ["ERROR ValueError: bad region"])

    def test_region_filter_accepts_slugs_stems_and_ids(self):
        stems = [p.stem for p in check_world_static.regions(wanted=["ember_crown", "region.pale_concord", "Sunspire"])]
        self.assertEqual(stems, ["EmberCrown", "PaleConcord", "Sunspire"])
        self.assertEqual(len(check_world_static.regions()), 6)
        with self.assertRaises(SystemExit):
            check_world_static.regions(wanted=["atlantis"])


class ProbeBaseTests(unittest.TestCase):
    """The engine cannot run here, so these only pin what a migration must not get wrong."""

    MIGRATED = ("cell_mesh_census.gd", "magic_lifetime_probe.gd", "region_transition_probe.gd")

    def test_base_is_a_scene_tree_with_a_uid_sidecar(self):
        base = (ROOT / "tools" / "probe_base.gd").read_text(encoding="utf-8")
        self.assertIn("\nextends SceneTree\n", base)
        self.assertRegex((ROOT / "tools" / "probe_base.gd.uid").read_text(encoding="utf-8"),
                         r"^uid://[a-y0-8]{12,13}\n$")
        for function in ("boot", "arg", "wants", "regions", "check", "fail", "metric", "finish"):
            self.assertIn(f"\nfunc {function}(", base)

    def test_migrated_probes_extend_the_base_and_keep_no_private_epilogue(self):
        for name in self.MIGRATED:
            text = (ROOT / "tools" / name).read_text(encoding="utf-8")
            self.assertIn('\nextends "res://tools/probe_base.gd"\n', text, name)
            self.assertNotIn("_failures", text, f"{name} would shadow the base's failure list")
            self.assertEqual(text.count("quit("), 0, f"{name} must end through finish()")
            self.assertEqual(text.count("\tfinish("), 1, name)
            self.assertFalse([line for line in text.splitlines() if line.startswith(" ")],
                             f"{name} mixes spaces into tab indentation")


if __name__ == "__main__":
    unittest.main()
