using Embervale.Loot;
using Embervale.World;
using Xunit;

namespace Embervale.Tests;

/// <summary>
/// The realm-tier rules loot is generated by: which tier a realm drops, the level band of a tier,
/// and the level one drop rolls at. The bands are the ones <c>tools/items/catalogue.py</c> uses.
/// </summary>
public class LootTiersTests
{
    [Theory]
    [InlineData(Realm.EmberCrown, 1)]
    [InlineData(Realm.FrostfangReach, 2)]
    [InlineData(Realm.AshenWilds, 3)]
    [InlineData(Realm.SunspireDominion, 4)]
    [InlineData(Realm.PaleConcord, 5)]
    [InlineData(Realm.CelestialRealm, 6)]
    public void EveryRealmHasItsOwnTier(Realm realm, int tier)
    {
        Assert.Equal(tier, LootTiers.TierOfRealm(realm));
    }

    [Theory]
    [InlineData(1, 1, 10, 5)]
    [InlineData(2, 8, 20, 14)]
    [InlineData(3, 18, 30, 24)]
    [InlineData(4, 28, 40, 34)]
    [InlineData(5, 36, 46, 41)]
    [InlineData(6, 44, 50, 47)]
    public void BandsMatchTheCatalogue(int tier, int low, int high, int typical)
    {
        Assert.Equal((low, high), LootTiers.LevelBand(tier));
        Assert.Equal(typical, LootTiers.TypicalItemLevel(tier));
        Assert.InRange(typical, low, high);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(7)]
    [InlineData(-1)]
    public void AnUnknownTierIsLevelLess(int tier)
    {
        Assert.False(LootTiers.IsTier(tier));
        Assert.Equal((0, 0), LootTiers.LevelBand(tier));
        Assert.Equal(0, LootTiers.TypicalItemLevel(tier));
        Assert.Equal(0, LootTiers.RollItemLevel(tier, 20, 0.5f));
    }

    [Fact]
    public void ARollNeverLeavesItsBand()
    {
        for (int tier = LootTiers.MinTier; tier <= LootTiers.MaxTier; tier++)
        {
            (int low, int high) = LootTiers.LevelBand(tier);
            foreach (int finder in new[] { 0, 1, 12, 25, 50, 99 })
            {
                for (int i = 0; i <= 100; i++)
                {
                    Assert.InRange(LootTiers.RollItemLevel(tier, finder, i / 100f), low, high);
                }
            }
        }
    }

    [Fact]
    public void WithNoFinderTheRollCoversTheWholeBand()
    {
        Assert.Equal(8, LootTiers.RollItemLevel(2, 0, 0f));
        Assert.Equal(20, LootTiers.RollItemLevel(2, 0, 1f));
    }

    [Fact]
    public void WithAFinderTheRollStaysNearTheirLevel()
    {
        for (int i = 0; i <= 100; i++)
        {
            int level = LootTiers.RollItemLevel(2, 14, i / 100f);
            Assert.InRange(level, 14 - LootTiers.LevelSpread, 14 + LootTiers.LevelSpread);
        }

        Assert.Equal(12, LootTiers.RollItemLevel(2, 14, 0f));
        Assert.Equal(16, LootTiers.RollItemLevel(2, 14, 1f));
    }

    [Fact]
    public void AnOverLevelledFinderIsHeldToTheBandCeiling()
    {
        Assert.Equal(10, LootTiers.RollItemLevel(1, 40, 0f));
        Assert.Equal(10, LootTiers.RollItemLevel(1, 40, 1f));
        Assert.Equal(10, LootTiers.ReferenceLevel(1, 40));
    }

    [Fact]
    public void TheReferenceLevelFallsBackToTheTiersTypicalLevel()
    {
        Assert.Equal(24, LootTiers.ReferenceLevel(3, 0));
        Assert.Equal(22, LootTiers.ReferenceLevel(3, 22));
        Assert.Equal(0, LootTiers.ReferenceLevel(0, 0));
    }

    [Fact]
    public void ARolledLevelIsHeldInsideTheItemsOwnTier()
    {
        Assert.Equal(10, LootTiers.ClampToItemTier(27, 1));
        Assert.Equal(27, LootTiers.ClampToItemTier(27, 3));
        Assert.Equal(27, LootTiers.ClampToItemTier(27, 0));
        Assert.Equal(0, LootTiers.ClampToItemTier(0, 3));
    }

    [Fact]
    public void TheTierTokenIsFilledAndOtherPathsAreLeftAlone()
    {
        Assert.Equal("res://data/loot/tiers/Tier4Gear.tres", LootTiers.ResolvePath("res://data/loot/tiers/Tier{tier}Gear.tres", 4));
        Assert.Equal("res://data/loot/tiers/Tier1Gear.tres", LootTiers.ResolvePath("res://data/loot/tiers/Tier{tier}Gear.tres", 0));
        Assert.Equal("res://data/loot/ChestLoot.tres", LootTiers.ResolvePath("res://data/loot/ChestLoot.tres", 4));
        Assert.Equal(string.Empty, LootTiers.ResolvePath(string.Empty, 4));
    }
}
